// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockInternalWatchdog creates a new instance of MockInternalWatchdog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInternalWatchdog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInternalWatchdog {
	mock := &MockInternalWatchdog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInternalWatchdog is an autogenerated mock type for the InternalWatchdog type
type MockInternalWatchdog struct {
	mock.Mock
}

type MockInternalWatchdog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInternalWatchdog) EXPECT() *MockInternalWatchdog_Expecter {
	return &MockInternalWatchdog_Expecter{mock: &_m.Mock}
}

// RegisterProcessPIDWithWatchdog provides a mock function for the type MockInternalWatchdog
func (_mock *MockInternalWatchdog) RegisterProcessPIDWithWatchdog(pid int) error {
	ret := _mock.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for RegisterProcessPIDWithWatchdog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(pid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalWatchdog_RegisterProcessPIDWithWatchdog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterProcessPIDWithWatchdog'
type MockInternalWatchdog_RegisterProcessPIDWithWatchdog_Call struct {
	*mock.Call
}

// RegisterProcessPIDWithWatchdog is a helper method to define mock.On call
//   - pid int
func (_e *MockInternalWatchdog_Expecter) RegisterProcessPIDWithWatchdog(pid interface{}) *MockInternalWatchdog_RegisterProcessPIDWithWatchdog_Call {
	return &MockInternalWatchdog_RegisterProcessPIDWithWatchdog_Call{Call: _e.mock.On("RegisterProcessPIDWithWatchdog", pid)}
}

func (_c *MockInternalWatchdog_RegisterProcessPIDWithWatchdog_Call) Run(run func(pid int)) *MockInternalWatchdog_RegisterProcessPIDWithWatchdog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalWatchdog_RegisterProcessPIDWithWatchdog_Call) Return(err error) *MockInternalWatchdog_RegisterProcessPIDWithWatchdog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalWatchdog_RegisterProcessPIDWithWatchdog_Call) RunAndReturn(run func(pid int) error) *MockInternalWatchdog_RegisterProcessPIDWithWatchdog_Call {
	_c.Call.Return(run)
	return _c
}
