within MoSimQuadrotorModel.Controllers.GraphicalMIL.ClassicRobust;
model MoSim_Classic_NDI_MIL
  extends ModelWorkspace;
  import SysplorerEmbeddedCoder.Types.*;
  import BaseWorkspace.*;
  annotation(__MWORKS(version="26.3.0",modelType=Control,BlockSystem(blockKind=BlockKind.userModel,SampleTime(auto=true,group="")=0.01,OutputInterval=0.01),SysblockVersion="1.0"),experiment(DoublePrecision=true,Algorithm=Euler,IntegratorStep=0.01,Interval=0.01,StartTime=0,StopTime=0.2,StoreEventValue=0),Diagram(coordinateSystem(extent={{-620,-480},{620,480}},grid={2,2})));
  MoSim_Classic_CFunction_Sysblock controller annotation(Placement(transformation(origin={0,0},extent={{-110,-440},{110,440}})));
  SysplorerEmbeddedCoder.Sources.Constant controller_id_source(k=3.0) annotation(Placement(transformation(origin={{-500,420}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant dt_source(k=0.01) annotation(Placement(transformation(origin={{-500,376}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant position_x_source(k=0.1) annotation(Placement(transformation(origin={{-500,332}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant position_y_source(k=-0.05) annotation(Placement(transformation(origin={{-500,288}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant position_z_source(k=0.8) annotation(Placement(transformation(origin={{-500,244}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant velocity_x_source(k=0.02) annotation(Placement(transformation(origin={{-500,200}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant velocity_y_source(k=-0.01) annotation(Placement(transformation(origin={{-500,156}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant velocity_z_source(k=0.01) annotation(Placement(transformation(origin={{-500,112}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_position_x_source(k=0.25) annotation(Placement(transformation(origin={{-500,68}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_position_y_source(k=0.1) annotation(Placement(transformation(origin={{-500,24}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_position_z_source(k=1.0) annotation(Placement(transformation(origin={{-500,-20}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_velocity_x_source(k=0.0) annotation(Placement(transformation(origin={{-500,-64}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_velocity_y_source(k=0.0) annotation(Placement(transformation(origin={{-500,-108}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_velocity_z_source(k=0.0) annotation(Placement(transformation(origin={{-500,-152}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_acceleration_x_source(k=0.01) annotation(Placement(transformation(origin={{-500,-196}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_acceleration_y_source(k=-0.02) annotation(Placement(transformation(origin={{-500,-240}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_acceleration_z_source(k=0.0) annotation(Placement(transformation(origin={{-500,-284}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_yaw_source(k=0.15) annotation(Placement(transformation(origin={{-500,-328}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant enable_source(k=1.0) annotation(Placement(transformation(origin={{-500,-372}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Sources.Constant reset_source(k=0.0) annotation(Placement(transformation(origin={{-500,-416}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport desired_acceleration_x annotation(Placement(transformation(origin={{500,420}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport desired_acceleration_y annotation(Placement(transformation(origin={{500,396}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport desired_acceleration_z annotation(Placement(transformation(origin={{500,372}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport desired_attitude_w annotation(Placement(transformation(origin={{500,348}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport desired_attitude_x annotation(Placement(transformation(origin={{500,324}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport desired_attitude_y annotation(Placement(transformation(origin={{500,300}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport desired_attitude_z annotation(Placement(transformation(origin={{500,276}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport observer_position_x annotation(Placement(transformation(origin={{500,252}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport observer_position_y annotation(Placement(transformation(origin={{500,228}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport observer_position_z annotation(Placement(transformation(origin={{500,204}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport observer_velocity_x annotation(Placement(transformation(origin={{500,180}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport observer_velocity_y annotation(Placement(transformation(origin={{500,156}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport observer_velocity_z annotation(Placement(transformation(origin={{500,132}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport reference_model_position_x annotation(Placement(transformation(origin={{500,108}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport reference_model_position_y annotation(Placement(transformation(origin={{500,84}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport reference_model_position_z annotation(Placement(transformation(origin={{500,60}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport reference_model_velocity_x annotation(Placement(transformation(origin={{500,36}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport reference_model_velocity_y annotation(Placement(transformation(origin={{500,12}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport reference_model_velocity_z annotation(Placement(transformation(origin={{500,-12}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport adaptive_position_delta_x annotation(Placement(transformation(origin={{500,-36}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport adaptive_position_delta_y annotation(Placement(transformation(origin={{500,-60}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport adaptive_position_delta_z annotation(Placement(transformation(origin={{500,-84}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport adaptive_velocity_delta_x annotation(Placement(transformation(origin={{500,-108}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport adaptive_velocity_delta_y annotation(Placement(transformation(origin={{500,-132}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport adaptive_velocity_delta_z annotation(Placement(transformation(origin={{500,-156}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport fractional_integral_x annotation(Placement(transformation(origin={{500,-180}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport fractional_integral_y annotation(Placement(transformation(origin={{500,-204}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport fractional_integral_z annotation(Placement(transformation(origin={{500,-228}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport fractional_derivative_x annotation(Placement(transformation(origin={{500,-252}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport fractional_derivative_y annotation(Placement(transformation(origin={{500,-276}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport fractional_derivative_z annotation(Placement(transformation(origin={{500,-300}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport normalized_thrust annotation(Placement(transformation(origin={{500,-324}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport collective_thrust_n annotation(Placement(transformation(origin={{500,-348}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport saturated annotation(Placement(transformation(origin={{500,-372}},extent={{-10,-10},{10,10}})));
  SysplorerEmbeddedCoder.Port.Outport status_code annotation(Placement(transformation(origin={{500,-396}},extent={{-10,-10},{10,10}})));
  model ModelWorkspace
    annotation(__MWORKS(hide=true,BlockSystem(blockKind=BlockKind.modelWorkspace)));
  end ModelWorkspace;
equation
  connect(controller_id_source.y, controller.controller_id_in);
  connect(dt_source.y, controller.dt_in);
  connect(position_x_source.y, controller.position_x_in);
  connect(position_y_source.y, controller.position_y_in);
  connect(position_z_source.y, controller.position_z_in);
  connect(velocity_x_source.y, controller.velocity_x_in);
  connect(velocity_y_source.y, controller.velocity_y_in);
  connect(velocity_z_source.y, controller.velocity_z_in);
  connect(reference_position_x_source.y, controller.reference_position_x_in);
  connect(reference_position_y_source.y, controller.reference_position_y_in);
  connect(reference_position_z_source.y, controller.reference_position_z_in);
  connect(reference_velocity_x_source.y, controller.reference_velocity_x_in);
  connect(reference_velocity_y_source.y, controller.reference_velocity_y_in);
  connect(reference_velocity_z_source.y, controller.reference_velocity_z_in);
  connect(reference_acceleration_x_source.y, controller.reference_acceleration_x_in);
  connect(reference_acceleration_y_source.y, controller.reference_acceleration_y_in);
  connect(reference_acceleration_z_source.y, controller.reference_acceleration_z_in);
  connect(reference_yaw_source.y, controller.reference_yaw_in);
  connect(enable_source.y, controller.enable_in);
  connect(reset_source.y, controller.reset_in);
  connect(controller.desired_acceleration_x_out, desired_acceleration_x);
  connect(controller.desired_acceleration_y_out, desired_acceleration_y);
  connect(controller.desired_acceleration_z_out, desired_acceleration_z);
  connect(controller.desired_attitude_w_out, desired_attitude_w);
  connect(controller.desired_attitude_x_out, desired_attitude_x);
  connect(controller.desired_attitude_y_out, desired_attitude_y);
  connect(controller.desired_attitude_z_out, desired_attitude_z);
  connect(controller.observer_position_x_out, observer_position_x);
  connect(controller.observer_position_y_out, observer_position_y);
  connect(controller.observer_position_z_out, observer_position_z);
  connect(controller.observer_velocity_x_out, observer_velocity_x);
  connect(controller.observer_velocity_y_out, observer_velocity_y);
  connect(controller.observer_velocity_z_out, observer_velocity_z);
  connect(controller.reference_model_position_x_out, reference_model_position_x);
  connect(controller.reference_model_position_y_out, reference_model_position_y);
  connect(controller.reference_model_position_z_out, reference_model_position_z);
  connect(controller.reference_model_velocity_x_out, reference_model_velocity_x);
  connect(controller.reference_model_velocity_y_out, reference_model_velocity_y);
  connect(controller.reference_model_velocity_z_out, reference_model_velocity_z);
  connect(controller.adaptive_position_delta_x_out, adaptive_position_delta_x);
  connect(controller.adaptive_position_delta_y_out, adaptive_position_delta_y);
  connect(controller.adaptive_position_delta_z_out, adaptive_position_delta_z);
  connect(controller.adaptive_velocity_delta_x_out, adaptive_velocity_delta_x);
  connect(controller.adaptive_velocity_delta_y_out, adaptive_velocity_delta_y);
  connect(controller.adaptive_velocity_delta_z_out, adaptive_velocity_delta_z);
  connect(controller.fractional_integral_x_out, fractional_integral_x);
  connect(controller.fractional_integral_y_out, fractional_integral_y);
  connect(controller.fractional_integral_z_out, fractional_integral_z);
  connect(controller.fractional_derivative_x_out, fractional_derivative_x);
  connect(controller.fractional_derivative_y_out, fractional_derivative_y);
  connect(controller.fractional_derivative_z_out, fractional_derivative_z);
  connect(controller.normalized_thrust_out, normalized_thrust);
  connect(controller.collective_thrust_n_out, collective_thrust_n);
  connect(controller.saturated_out, saturated);
  connect(controller.status_code_out, status_code);
end MoSim_Classic_NDI_MIL;