within MoSimQuadrotorModel.Controllers.GraphicalMIL.ClassicRobust;

model MoSim_WaveA_LQR_MIL
  extends ModelWorkspace;
  import SysplorerEmbeddedCoder.Types.*;
  import BaseWorkspace.*;
  annotation(__MWORKS(version="26.3.0",modelType=Control,BlockSystem(blockKind=BlockKind.userModel,SampleTime(auto=true,group="")=0.01,OutputInterval=0.01),SysblockVersion="1.0"),experiment(DoublePrecision=true,Algorithm=Euler,IntegratorStep=0.01,Interval=0.01,StartTime=0,StopTime=0.03,StoreEventValue=0),Diagram(coordinateSystem(extent={{-320,-180},{320,300}},grid={2,2})));
  MoSim_WaveA_CFunction_Sysblock controller annotation(Placement(transformation(origin={0,40},extent={{-25,-25},{25,25}})));
  SysplorerEmbeddedCoder.Sources.Constant controller_id_source(k=1.0) annotation(Placement(transformation(origin={-260,260},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant dt_source(k=0.01) annotation(Placement(transformation(origin={-260,248},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant position_x_source(k=0.1) annotation(Placement(transformation(origin={-260,236},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant position_y_source(k=-0.2) annotation(Placement(transformation(origin={-260,224},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant position_z_source(k=0.3) annotation(Placement(transformation(origin={-260,212},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant velocity_x_source(k=0.05) annotation(Placement(transformation(origin={-260,200},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant velocity_y_source(k=-0.04) annotation(Placement(transformation(origin={-260,188},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant velocity_z_source(k=0.02) annotation(Placement(transformation(origin={-260,176},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant attitude_w_source(k=1.0) annotation(Placement(transformation(origin={-260,164},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant attitude_x_source(k=0.0) annotation(Placement(transformation(origin={-260,152},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant attitude_y_source(k=0.0) annotation(Placement(transformation(origin={-260,140},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant attitude_z_source(k=0.0) annotation(Placement(transformation(origin={-260,128},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_position_x_source(k=1.0) annotation(Placement(transformation(origin={-260,116},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_position_y_source(k=-0.5) annotation(Placement(transformation(origin={-260,104},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_position_z_source(k=1.2) annotation(Placement(transformation(origin={-260,92},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_velocity_x_source(k=0.1) annotation(Placement(transformation(origin={-260,80},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_velocity_y_source(k=0.0) annotation(Placement(transformation(origin={-260,68},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_velocity_z_source(k=0.05) annotation(Placement(transformation(origin={-260,56},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_acceleration_x_source(k=0.0) annotation(Placement(transformation(origin={-260,44},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_acceleration_y_source(k=0.0) annotation(Placement(transformation(origin={-260,32},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_acceleration_z_source(k=0.0) annotation(Placement(transformation(origin={-260,20},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_attitude_w_source(k=0.995004165278) annotation(Placement(transformation(origin={-260,8},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_attitude_x_source(k=0.0) annotation(Placement(transformation(origin={-260,-4},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_attitude_y_source(k=0.0) annotation(Placement(transformation(origin={-260,-16},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_attitude_z_source(k=0.099833416647) annotation(Placement(transformation(origin={-260,-28},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_body_rate_x_source(k=0.1) annotation(Placement(transformation(origin={-260,-40},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_body_rate_y_source(k=-0.2) annotation(Placement(transformation(origin={-260,-52},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_body_rate_z_source(k=0.05) annotation(Placement(transformation(origin={-260,-64},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reference_yaw_source(k=0.2) annotation(Placement(transformation(origin={-260,-76},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant collective_thrust_n_source(k=6.57) annotation(Placement(transformation(origin={-260,-88},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant enable_source(k=1.0) annotation(Placement(transformation(origin={-260,-100},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Sources.Constant reset_source(k=0.0) annotation(Placement(transformation(origin={-260,-112},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport desired_attitude_w annotation(Placement(transformation(origin={260,180},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport desired_attitude_x annotation(Placement(transformation(origin={260,162},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport desired_attitude_y annotation(Placement(transformation(origin={260,144},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport desired_attitude_z annotation(Placement(transformation(origin={260,126},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport desired_body_rate_x annotation(Placement(transformation(origin={260,108},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport desired_body_rate_y annotation(Placement(transformation(origin={260,90},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport desired_body_rate_z annotation(Placement(transformation(origin={260,72},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport desired_acceleration_x annotation(Placement(transformation(origin={260,54},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport desired_acceleration_y annotation(Placement(transformation(origin={260,36},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport desired_acceleration_z annotation(Placement(transformation(origin={260,18},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport normalized_thrust annotation(Placement(transformation(origin={260,0},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport commanded_collective_thrust_n annotation(Placement(transformation(origin={260,-18},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport command_variant annotation(Placement(transformation(origin={260,-36},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport saturated annotation(Placement(transformation(origin={260,-54},extent={{-8,-8},{8,8}})));
  SysplorerEmbeddedCoder.Port.Outport status_code annotation(Placement(transformation(origin={260,-72},extent={{-8,-8},{8,8}})));
  model ModelWorkspace
    annotation(__MWORKS(hide=true,BlockSystem(blockKind=BlockKind.modelWorkspace)));
  end ModelWorkspace;
equation
  connect(controller_id_source.y, controller.controller_id_in);
  connect(dt_source.y, controller.dt_in);
  connect(position_x_source.y, controller.position_x_in);
  connect(position_y_source.y, controller.position_y_in);
  connect(position_z_source.y, controller.position_z_in);
  connect(velocity_x_source.y, controller.velocity_x_in);
  connect(velocity_y_source.y, controller.velocity_y_in);
  connect(velocity_z_source.y, controller.velocity_z_in);
  connect(attitude_w_source.y, controller.attitude_w_in);
  connect(attitude_x_source.y, controller.attitude_x_in);
  connect(attitude_y_source.y, controller.attitude_y_in);
  connect(attitude_z_source.y, controller.attitude_z_in);
  connect(reference_position_x_source.y, controller.reference_position_x_in);
  connect(reference_position_y_source.y, controller.reference_position_y_in);
  connect(reference_position_z_source.y, controller.reference_position_z_in);
  connect(reference_velocity_x_source.y, controller.reference_velocity_x_in);
  connect(reference_velocity_y_source.y, controller.reference_velocity_y_in);
  connect(reference_velocity_z_source.y, controller.reference_velocity_z_in);
  connect(reference_acceleration_x_source.y, controller.reference_acceleration_x_in);
  connect(reference_acceleration_y_source.y, controller.reference_acceleration_y_in);
  connect(reference_acceleration_z_source.y, controller.reference_acceleration_z_in);
  connect(reference_attitude_w_source.y, controller.reference_attitude_w_in);
  connect(reference_attitude_x_source.y, controller.reference_attitude_x_in);
  connect(reference_attitude_y_source.y, controller.reference_attitude_y_in);
  connect(reference_attitude_z_source.y, controller.reference_attitude_z_in);
  connect(reference_body_rate_x_source.y, controller.reference_body_rate_x_in);
  connect(reference_body_rate_y_source.y, controller.reference_body_rate_y_in);
  connect(reference_body_rate_z_source.y, controller.reference_body_rate_z_in);
  connect(reference_yaw_source.y, controller.reference_yaw_in);
  connect(collective_thrust_n_source.y, controller.collective_thrust_n_in);
  connect(enable_source.y, controller.enable_in);
  connect(reset_source.y, controller.reset_in);
  connect(controller.desired_attitude_w_out, desired_attitude_w);
  connect(controller.desired_attitude_x_out, desired_attitude_x);
  connect(controller.desired_attitude_y_out, desired_attitude_y);
  connect(controller.desired_attitude_z_out, desired_attitude_z);
  connect(controller.desired_body_rate_x_out, desired_body_rate_x);
  connect(controller.desired_body_rate_y_out, desired_body_rate_y);
  connect(controller.desired_body_rate_z_out, desired_body_rate_z);
  connect(controller.desired_acceleration_x_out, desired_acceleration_x);
  connect(controller.desired_acceleration_y_out, desired_acceleration_y);
  connect(controller.desired_acceleration_z_out, desired_acceleration_z);
  connect(controller.normalized_thrust_out, normalized_thrust);
  connect(controller.commanded_collective_thrust_n_out, commanded_collective_thrust_n);
  connect(controller.command_variant_out, command_variant);
  connect(controller.saturated_out, saturated);
  connect(controller.status_code_out, status_code);
end MoSim_WaveA_LQR_MIL;
