// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// GOOS provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) GOOS() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GOOS")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOSLayer_GOOS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GOOS'
type MockOSLayer_GOOS_Call struct {
	*mock.Call
}

// GOOS is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) GOOS() *MockOSLayer_GOOS_Call {
	return &MockOSLayer_GOOS_Call{Call: _e.mock.On("GOOS")}
}

func (_c *MockOSLayer_GOOS_Call) Run(run func()) *MockOSLayer_GOOS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_GOOS_Call) Return(s string) *MockOSLayer_GOOS_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOSLayer_GOOS_Call) RunAndReturn(run func() string) *MockOSLayer_GOOS_Call {
	_c.Call.Return(run)
	return _c
}

// IsAbs provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) IsAbs(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsAbs")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockOSLayer_IsAbs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAbs'
type MockOSLayer_IsAbs_Call struct {
	*mock.Call
}

// IsAbs is a helper method to define mock.On call
//   - path string
func (_e *MockOSLayer_Expecter) IsAbs(path interface{}) *MockOSLayer_IsAbs_Call {
	return &MockOSLayer_IsAbs_Call{Call: _e.mock.On("IsAbs", path)}
}

func (_c *MockOSLayer_IsAbs_Call) Run(run func(path string)) *MockOSLayer_IsAbs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_IsAbs_Call) Return(b bool) *MockOSLayer_IsAbs_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockOSLayer_IsAbs_Call) RunAndReturn(run func(path string) bool) *MockOSLayer_IsAbs_Call {
	_c.Call.Return(run)
	return _c
}
