import * as fs from "node:fs";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  applyCursorRules,
  generateClaudeRules,
  mergeRulesIndexForVendor,
  readRules,
} from "./rules.js";

vi.mock("node:fs", () => ({
  existsSync: vi.fn(),
  mkdirSync: vi.fn(),
  readFileSync: vi.fn(),
  readdirSync: vi.fn(),
  writeFileSync: vi.fn(),
  cpSync: vi.fn(),
}));

const mockTargetDir = "/tmp/test-project";

describe("readRules", () => {
  beforeEach(() => vi.clearAllMocks());
  afterEach(() => vi.restoreAllMocks());

  it("should return empty array when rules dir does not exist", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      false,
    );
    expect(readRules(mockTargetDir)).toEqual([]);
  });

  it("should parse frontmatter fields from rule files", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      true,
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      '---\ndescription: Frontend standards\nglobs: "**/*.tsx"\nalwaysApply: false\n---\n\n# Frontend',
    );

    const rules = readRules(mockTargetDir);
    expect(rules).toHaveLength(1);
    expect(rules[0]?.name).toBe("frontend");
    expect(rules[0]?.description).toBe("Frontend standards");
    expect(rules[0]?.globs).toBe("**/*.tsx");
    expect(rules[0]?.alwaysApply).toBe(false);
    expect(rules[0]?.body).toContain("# Frontend");
  });

  it("should filter non-.md files", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      true,
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      ".gitkeep",
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    expect(readRules(mockTargetDir)).toHaveLength(1);
  });
});

describe("applyCursorRules", () => {
  beforeEach(() => vi.clearAllMocks());
  afterEach(() => vi.restoreAllMocks());

  it("should return empty array when no rules exist", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      false,
    );
    expect(applyCursorRules(mockTargetDir)).toEqual([]);
  });

  it("should generate .mdc files with Cursor frontmatter", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      true,
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      '---\ndescription: Frontend standards\nglobs: "**/*.{tsx,jsx}"\nalwaysApply: false\n---\n\n# Frontend\n\n1. Use React',
    );

    const result = applyCursorRules(mockTargetDir);
    expect(result).toEqual(["frontend"]);

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith(".mdc"),
    );

    expect(writeCall).toBeDefined();
    const content = writeCall?.[1] as string;
    expect(content).toContain('description: "Frontend standards"');
    expect(content).toContain('globs: "**/*.{tsx,jsx}"');
    expect(content).toContain("alwaysApply: false");
    expect(content).toContain("# Frontend");
    expect(content).toContain("<!-- Generated by oh-my-agent");
  });

  it("should respect alwaysApply: true", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      true,
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "i18n.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: i18n\nalwaysApply: true\n---\n\n# i18n",
    );

    applyCursorRules(mockTargetDir);

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith(".mdc"),
    );

    expect(writeCall?.[1] as string).toContain("alwaysApply: true");
  });
});

describe("generateClaudeRules", () => {
  beforeEach(() => vi.clearAllMocks());
  afterEach(() => vi.restoreAllMocks());

  it("should return empty array when no rules exist", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      false,
    );
    expect(generateClaudeRules(mockTargetDir)).toEqual([]);
  });

  it("should generate .md files with paths frontmatter for scoped rules", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      true,
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      '---\ndescription: Frontend standards\nglobs: "**/*.{tsx,jsx}"\nalwaysApply: false\n---\n\n# Frontend',
    );

    const result = generateClaudeRules(mockTargetDir);
    expect(result).toEqual(["frontend"]);

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith("frontend.md"),
    );

    expect(writeCall).toBeDefined();
    const content = writeCall?.[1] as string;
    expect(content).toContain("description:");
    expect(content).toContain("paths: ");
    expect(content).toContain("**/*.{tsx,jsx}");
    expect(content).toContain("# Frontend");
  });

  it("should omit paths for alwaysApply rules", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      true,
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "i18n.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: i18n\nalwaysApply: true\n---\n\n# i18n",
    );

    generateClaudeRules(mockTargetDir);

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith("i18n.md"),
    );

    const content = writeCall?.[1] as string;
    expect(content).not.toContain("paths:");
  });
});

describe("mergeRulesIndexForVendor", () => {
  beforeEach(() => vi.clearAllMocks());
  afterEach(() => vi.restoreAllMocks());

  it("should return false for unsupported vendor", () => {
    expect(mergeRulesIndexForVendor(mockTargetDir, "unknown-vendor")).toBe(
      false,
    );
  });

  it("should still generate usage guide even without rules", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("GEMINI.md")) return false;
        if (typeof p === "string" && p.includes(".agents/rules")) return false;
        return false;
      },
    );

    const result = mergeRulesIndexForVendor(mockTargetDir, "gemini");
    expect(result).toBe(true);

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith("GEMINI.md"),
    );
    expect(writeCall).toBeDefined();
    const content = writeCall?.[1] as string;
    expect(content).toContain("# oh-my-agent");
    expect(content).toContain("## Workflows");
    expect(content).not.toContain("## Project Rules");
  });

  it("should create GEMINI.md with usage guide and rules index", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        const norm = typeof p === "string" ? p.replace(/\\/g, "/") : "";
        if (norm.endsWith("GEMINI.md")) return false;
        return norm.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
      "backend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      '---\ndescription: test\nglobs: "**/*.tsx"\n---\n\n# Test',
    );

    const result = mergeRulesIndexForVendor(mockTargetDir, "gemini");
    expect(result).toBe(true);

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith("GEMINI.md"),
    );
    expect(writeCall).toBeDefined();
    const content = writeCall?.[1] as string;
    expect(content).toContain("<!-- OMA:START");
    expect(content).toContain("<!-- OMA:END -->");
    expect(content).toContain("# oh-my-agent");
    expect(content).toContain("## Workflows");
    expect(content).toContain("| frontend |");
    expect(content).toContain("| backend |");
    expect(content).toContain(".agents/rules/");
  });

  it("should create AGENTS.md for codex vendor", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("AGENTS.md")) return false;
        return p.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    mergeRulesIndexForVendor(mockTargetDir, "codex");

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith("AGENTS.md"),
    );
    expect(writeCall).toBeDefined();
  });

  it("should write CLAUDE.md for claude vendor", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("CLAUDE.md")) return false;
        return p.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    mergeRulesIndexForVendor(mockTargetDir, "claude");

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith("CLAUDE.md"),
    );
    expect(writeCall).toBeDefined();
  });

  it("should write AGENTS.md for qwen vendor (shared with codex)", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("AGENTS.md")) return false;
        return p.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    mergeRulesIndexForVendor(mockTargetDir, "qwen");

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith("AGENTS.md"),
    );
    expect(writeCall).toBeDefined();
  });

  it("should write AGENTS.md for cursor vendor", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("AGENTS.md")) return false;
        return p.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    mergeRulesIndexForVendor(mockTargetDir, "cursor");

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith("AGENTS.md"),
    );
    expect(writeCall).toBeDefined();
  });

  it("should replace existing OMA block on update", () => {
    const omaStart = "<!-- OMA:START";
    const omaEnd = "<!-- OMA:END -->";
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      true,
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("AGENTS.md")) {
          return `# My Project\n\nCustom content\n\n${omaStart} -->\nold block\n${omaEnd}\n\nMore user content`;
        }
        return "---\ndescription: test\n---\n\n# Test";
      },
    );

    mergeRulesIndexForVendor(mockTargetDir, "codex");

    const writeCall = (
      fs.writeFileSync as unknown as ReturnType<typeof vi.fn>
    ).mock.calls.find(
      (call: string[]) =>
        typeof call[0] === "string" && call[0].endsWith("AGENTS.md"),
    );
    const content = writeCall?.[1] as string;
    expect(content).toContain("# My Project");
    expect(content).toContain("Custom content");
    expect(content).toContain("More user content");
    expect(content).toContain(omaStart);
    expect(content).not.toContain("old block");
    expect(content).toContain("# oh-my-agent");
  });
});
