set(QGC_APP_NAME "MoSim Flight Console" CACHE STRING "App Name" FORCE)
set(QGC_DISABLE_APM_MAVLINK ON CACHE BOOL "Disable APM dialect" FORCE)
set(QGC_DISABLE_APM_PLUGIN ON CACHE BOOL "Disable APM plugin" FORCE)
set(QGC_DISABLE_APM_PLUGIN_FACTORY ON CACHE BOOL "Disable APM plugin factory" FORCE)
