// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// Command provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Command(name string, arg ...string) osfacade.Cmd {
	var tmpRet mock.Arguments
	if len(arg) > 0 {
		tmpRet = _mock.Called(name, arg)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Command")
	}

	var r0 osfacade.Cmd
	if returnFunc, ok := ret.Get(0).(func(string, ...string) osfacade.Cmd); ok {
		r0 = returnFunc(name, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.Cmd)
		}
	}
	return r0
}

// MockOSLayer_Command_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Command'
type MockOSLayer_Command_Call struct {
	*mock.Call
}

// Command is a helper method to define mock.On call
//   - name string
//   - arg ...string
func (_e *MockOSLayer_Expecter) Command(name interface{}, arg ...interface{}) *MockOSLayer_Command_Call {
	return &MockOSLayer_Command_Call{Call: _e.mock.On("Command",
		append([]interface{}{name}, arg...)...)}
}

func (_c *MockOSLayer_Command_Call) Run(run func(name string, arg ...string)) *MockOSLayer_Command_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockOSLayer_Command_Call) Return(cmd osfacade.Cmd) *MockOSLayer_Command_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockOSLayer_Command_Call) RunAndReturn(run func(name string, arg ...string) osfacade.Cmd) *MockOSLayer_Command_Call {
	_c.Call.Return(run)
	return _c
}

// Executable provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Executable() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Executable")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOSLayer_Executable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Executable'
type MockOSLayer_Executable_Call struct {
	*mock.Call
}

// Executable is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) Executable() *MockOSLayer_Executable_Call {
	return &MockOSLayer_Executable_Call{Call: _e.mock.On("Executable")}
}

func (_c *MockOSLayer_Executable_Call) Run(run func()) *MockOSLayer_Executable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_Executable_Call) Return(s string, err error) *MockOSLayer_Executable_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOSLayer_Executable_Call) RunAndReturn(run func() (string, error)) *MockOSLayer_Executable_Call {
	_c.Call.Return(run)
	return _c
}
