// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOSSignaler creates a new instance of MockOSSignaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSSignaler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSSignaler {
	mock := &MockOSSignaler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSSignaler is an autogenerated mock type for the OSSignaler type
type MockOSSignaler struct {
	mock.Mock
}

type MockOSSignaler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSSignaler) EXPECT() *MockOSSignaler_Expecter {
	return &MockOSSignaler_Expecter{mock: &_m.Mock}
}

// InterruptSignalChan provides a mock function for the type MockOSSignaler
func (_mock *MockOSSignaler) InterruptSignalChan() <-chan os.Signal {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InterruptSignalChan")
	}

	var r0 <-chan os.Signal
	if returnFunc, ok := ret.Get(0).(func() <-chan os.Signal); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan os.Signal)
		}
	}
	return r0
}

// MockOSSignaler_InterruptSignalChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InterruptSignalChan'
type MockOSSignaler_InterruptSignalChan_Call struct {
	*mock.Call
}

// InterruptSignalChan is a helper method to define mock.On call
func (_e *MockOSSignaler_Expecter) InterruptSignalChan() *MockOSSignaler_InterruptSignalChan_Call {
	return &MockOSSignaler_InterruptSignalChan_Call{Call: _e.mock.On("InterruptSignalChan")}
}

func (_c *MockOSSignaler_InterruptSignalChan_Call) Run(run func()) *MockOSSignaler_InterruptSignalChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSSignaler_InterruptSignalChan_Call) Return(signalCh <-chan os.Signal) *MockOSSignaler_InterruptSignalChan_Call {
	_c.Call.Return(signalCh)
	return _c
}

func (_c *MockOSSignaler_InterruptSignalChan_Call) RunAndReturn(run func() <-chan os.Signal) *MockOSSignaler_InterruptSignalChan_Call {
	_c.Call.Return(run)
	return _c
}
