#!/usr/bin/env python3
"""Generate Factory L2 indoor lawnmower waypoints for same-flight coverage."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ENVELOPE = ROOT / "Config/gazebo/scene_profiles/factory_l2_exploration_envelope.json"


def repo_path(value: str | Path) -> Path:
    path = Path(value)
    candidate = path if path.is_absolute() else ROOT / path
    resolved = candidate.resolve()
    root = ROOT.resolve()
    if not (resolved == root or root in resolved.parents):
        raise SystemExit(f"path outside MoSim workspace: {value}")
    return resolved


def as_float(value: Any, default: float = 0.0) -> float:
    try:
        out = float(value)
    except (TypeError, ValueError):
        return default
    return out if math.isfinite(out) else default


def load_boundary(envelope_path: Path) -> dict[str, float]:
    envelope = json.loads(envelope_path.read_text(encoding="utf-8"))
    raw = envelope.get("exploration_boundary") or {}
    boundary = {
        "min_x_m": as_float(raw.get("min_x_m")),
        "max_x_m": as_float(raw.get("max_x_m")),
        "min_y_m": as_float(raw.get("min_y_m")),
        "max_y_m": as_float(raw.get("max_y_m")),
        "center_x_m": as_float(raw.get("center_x_m"), (as_float(raw.get("min_x_m")) + as_float(raw.get("max_x_m"))) * 0.5),
        "center_y_m": as_float(raw.get("center_y_m"), (as_float(raw.get("min_y_m")) + as_float(raw.get("max_y_m"))) * 0.5),
    }
    if boundary["max_x_m"] <= boundary["min_x_m"] or boundary["max_y_m"] <= boundary["min_y_m"]:
        raise SystemExit(f"invalid exploration boundary in {envelope_path}")
    return boundary


def row_order(min_y: float, max_y: float, center_y: float, strip_spacing: float) -> list[float]:
    rows: list[float] = []
    y = min_y
    while y <= max_y + 1e-6:
        rows.append(round(min(y, max_y), 6))
        y += strip_spacing
    if rows and rows[-1] < max_y - 1e-6:
        rows.append(round(max_y, 6))
    return sorted(rows, key=lambda value: abs(value - center_y))


def generate_waypoints(boundary: dict[str, float], args: argparse.Namespace) -> list[tuple[float, float, float]]:
    min_x = boundary["min_x_m"] + args.margin_m
    max_x = boundary["max_x_m"] - args.margin_m
    min_y = boundary["min_y_m"] + args.margin_m
    max_y = boundary["max_y_m"] - args.margin_m
    if max_x <= min_x or max_y <= min_y:
        raise SystemExit("margin leaves no valid coverage area")

    rows = row_order(min_y, max_y, boundary["center_y_m"], args.strip_spacing_m)
    waypoints: list[tuple[float, float, float]] = []
    direction = 1
    if args.include_center_start:
        waypoints.append((round(boundary["center_x_m"], 6), round(boundary["center_y_m"], 6), args.z_m))
    for y in rows:
        endpoints = [(min_x, y), (max_x, y)] if direction > 0 else [(max_x, y), (min_x, y)]
        for x, yy in endpoints:
            point = (round(x, 6), round(yy, 6), args.z_m)
            if not waypoints or math.dist(waypoints[-1], point) > 1e-6:
                waypoints.append(point)
        direction *= -1
    return densify_waypoints(waypoints, args.segment_length_m, args.max_waypoints)


def densify_waypoints(
    waypoints: list[tuple[float, float, float]], max_segment_m: float, max_waypoints: int
) -> list[tuple[float, float, float]]:
    if not waypoints or max_segment_m <= 0.0:
        return waypoints[:max_waypoints] if max_waypoints > 0 else waypoints
    dense: list[tuple[float, float, float]] = [waypoints[0]]
    for start, end in zip(waypoints, waypoints[1:]):
        distance = math.dist(start, end)
        steps = max(1, math.ceil(distance / max_segment_m))
        for step in range(1, steps + 1):
            ratio = step / steps
            point = (
                round(start[0] + (end[0] - start[0]) * ratio, 6),
                round(start[1] + (end[1] - start[1]) * ratio, 6),
                round(start[2] + (end[2] - start[2]) * ratio, 6),
            )
            if math.dist(dense[-1], point) > 1e-6:
                dense.append(point)
            if max_waypoints > 0 and len(dense) >= max_waypoints:
                return dense
    return dense


def write_yaml(path: Path, section: str, waypoints: list[tuple[float, float, float]]) -> None:
    lines = [
        "# Generated by Scripts/sunray/generate_factory_l2_lawnmower_waypoints.py",
        "# Mode 1: x y z. Diff-Planner multipoint only reads fixed keys such as test1/test_back.",
        f"{section}:",
    ]
    for x, y, z in waypoints:
        lines.append(f"  - [{x:.6f}, {y:.6f}, {z:.6f}]")
    if section != "test_back":
        start_x, start_y, start_z = waypoints[0]
        lines.extend(
            [
                "",
                "test_back:",
                f"  - [{start_x:.6f}, {start_y:.6f}, {start_z:.6f}]",
            ]
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def planned_sensor_proxy(waypoints: list[tuple[float, float, float]], boundary: dict[str, float], resolution: float, sensor_radius: float) -> dict[str, Any]:
    nx = max(1, math.ceil((boundary["max_x_m"] - boundary["min_x_m"]) / resolution))
    ny = max(1, math.ceil((boundary["max_y_m"] - boundary["min_y_m"]) / resolution))
    cells: set[tuple[int, int]] = set()
    if len(waypoints) < 2:
        samples = waypoints
    else:
        samples: list[tuple[float, float, float]] = []
        step = max(resolution, sensor_radius * 0.25)
        for a, b in zip(waypoints, waypoints[1:]):
            dist = math.hypot(b[0] - a[0], b[1] - a[1])
            count = max(1, math.ceil(dist / step))
            for i in range(count + 1):
                t = i / count
                samples.append((a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t, a[2] + (b[2] - a[2]) * t))
    radius_cells = max(0, math.ceil(sensor_radius / resolution))
    for x, y, _z in samples:
        cx = int((x - boundary["min_x_m"]) / resolution)
        cy = int((y - boundary["min_y_m"]) / resolution)
        for ix in range(cx - radius_cells, cx + radius_cells + 1):
            if ix < 0 or ix >= nx:
                continue
            px = boundary["min_x_m"] + (ix + 0.5) * resolution
            for iy in range(cy - radius_cells, cy + radius_cells + 1):
                if iy < 0 or iy >= ny:
                    continue
                py = boundary["min_y_m"] + (iy + 0.5) * resolution
                if math.hypot(px - x, py - y) <= sensor_radius:
                    cells.add((ix, iy))
    return {
        "grid_resolution_m": resolution,
        "sensor_radius_m": sensor_radius,
        "grid_shape": [nx, ny],
        "grid_cell_count": nx * ny,
        "planned_sensor_footprint_cells": len(cells),
        "planned_sensor_footprint_coverage_ratio": len(cells) / (nx * ny),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--envelope", default=str(DEFAULT_ENVELOPE))
    parser.add_argument("--output-yaml", required=True)
    parser.add_argument("--output-json", required=True)
    parser.add_argument("--section", default="test1")
    parser.add_argument("--z-m", type=float, default=1.2)
    parser.add_argument("--margin-m", type=float, default=8.0)
    parser.add_argument("--strip-spacing-m", type=float, default=12.0)
    parser.add_argument("--segment-length-m", type=float, default=5.0)
    parser.add_argument("--max-waypoints", type=int, default=0)
    parser.add_argument("--coverage-resolution-m", type=float, default=2.0)
    parser.add_argument("--sensor-radius-m", type=float, default=8.0)
    parser.add_argument("--include-center-start", action="store_true")
    args = parser.parse_args()

    envelope = repo_path(args.envelope)
    output_yaml = repo_path(args.output_yaml)
    output_json = repo_path(args.output_json)
    boundary = load_boundary(envelope)
    waypoints = generate_waypoints(boundary, args)
    if not waypoints:
        raise SystemExit("no waypoints generated")
    write_yaml(output_yaml, args.section, waypoints)
    packet = {
        "schema": "mosim.factory_l2_lawnmower_waypoints.v1",
        "status": "planned",
        "envelope": str(envelope),
        "output_yaml": str(output_yaml),
        "section": args.section,
        "boundary": boundary,
        "parameters": {
            "z_m": args.z_m,
            "margin_m": args.margin_m,
            "strip_spacing_m": args.strip_spacing_m,
            "segment_length_m": args.segment_length_m,
            "max_waypoints": args.max_waypoints,
            "include_center_start": args.include_center_start,
        },
        "waypoint_count": len(waypoints),
        "first_waypoint": list(waypoints[0]),
        "last_waypoint": list(waypoints[-1]),
        "waypoints": [list(point) for point in waypoints],
        "planned_coverage_proxy": planned_sensor_proxy(waypoints, boundary, args.coverage_resolution_m, args.sensor_radius_m),
        "claim_boundary": [
            "This is a planned same-flight coverage route, not proof that the runtime planner reached every waypoint.",
            "Acceptance still requires ROS1/Sunray/PX4/MAVROS/px4ctrl runtime metrics and FACTORY_L2_INDOOR_COVERAGE_PACKET.json.",
        ],
    }
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(packet, indent=2), encoding="utf-8")
    print(output_yaml)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
