#!/usr/bin/env bash
# Reproduce the accepted Factory L2 RACER + three independent FAST-LIO profile.

set -eo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-/mnt/c/Users/HP/Desktop/MoSim}"
: "${RUN_ID:?RUN_ID is required}"
RESULT_DIR="${RESULT_DIR:-${PROJECT_ROOT}/Results/sunray_ros1/${RUN_ID}}"
RACER_D3_EXPLORATION_DURATION_S="${RACER_D3_EXPLORATION_DURATION_S:-30}"
TOTAL_TIMEOUT_S="${TOTAL_TIMEOUT_S:-840}"

exec env \
  RUN_ID="${RUN_ID}" \
  RESULT_DIR="${RESULT_DIR}" \
  PLANNER_VARIANT=racer UAV_NUM=3 \
  RACER_SENSOR_SOURCE=fastlio RACER_INPUT_GATE_ONLY=false \
  GUI=false OPEN_RVIZ=false KEEP_ALIVE=false \
  WORLD_FILE="${PROJECT_ROOT}/Config/gazebo/worlds/factoryenvironmentcollect_l2_static_review_clean.sdf" \
  FACTORY_MODEL_PATH="${PROJECT_ROOT}/Config/gazebo/models" \
  SUNRAY_GAZEBO_LAUNCH_FILE="${PROJECT_ROOT}/Scripts/sunray/factory_l2_sunray_px4_gazebo.launch" \
  SUNRAY_STRIP_PX4_MODEL_PATH=true \
  SUNRAY_MID360_PLUGIN_DOWNSAMPLE=4 \
  SUNRAY_LIVOX_PLUGIN_FILENAME="${PROJECT_ROOT}/Results/sunray_ros1/workspaces/sunray_livox_plugin_ws/devel/lib/liblivox_laser_simulation.so" \
  SUNRAY_MID360_CSV_FILE_NAME=mid360-real-centr.csv \
  SUNRAY_MID360_GOAL5_CSV_STRIDE=4 \
  START1_X=-10.575025 START1_Y=-19.36313 \
  START2_X=-11.0 START2_Y=-15.0 \
  START3_X=-14.5 START3_Y=-17.5 \
  MAVROS_READY_TIMEOUT_S=120 TOTAL_TIMEOUT_S="${TOTAL_TIMEOUT_S}" \
  GOAL5_STARTUP_ATTEMPTS=1 \
  SEQUENTIAL_SPAWN=false STAGGERED_SPAWN=true STAGGERED_SPAWN_INTERVAL_S=12 \
  RACER_FRAME_BRIDGE_ENABLED=true \
  RACER_FRAME_OFFSET_X=-10.575025 RACER_FRAME_OFFSET_Y=-19.36313 RACER_FRAME_OFFSET_Z=0.0 \
  RACER_FASTLIO_SCAN_RATE_HZ=20.0 \
  RACER_FASTLIO_FILTER_SIZE_SURF=0.5 RACER_FASTLIO_FILTER_SIZE_MAP=0.5 \
  RACER_FASTLIO_ALIGNMENT_Z_SOURCE=truth RACER_FASTLIO_ALIGNMENT_REFERENCE=config \
  POINTCLOUD_MIN_WORLD_Z_M=0.2 POINTCLOUD_MAX_WORLD_Z_M=4.0 \
  POINTCLOUD_MAX_SENSOR_RANGE_M=80.0 POINTCLOUD_MAX_ABS_ODOM_XY_M=200.0 \
  RACER_D3_EXPLORATION_DURATION_S="${RACER_D3_EXPLORATION_DURATION_S}" \
  RACER_D3_MAP_SIZE_X=180.0 RACER_D3_MAP_SIZE_Y=70.0 RACER_D3_MAP_SIZE_Z=2.2 \
  RACER_D3_BOX_MIN_X=-90.0 RACER_D3_BOX_MIN_Y=-35.0 \
  RACER_D3_BOX_MAX_X=90.0 RACER_D3_BOX_MAX_Y=35.0 \
  RACER_D3_BOX_MIN_Z=0.90 RACER_D3_BOX_MAX_Z=1.35 \
  RACER_D3_GROUND_HEIGHT=0.0 RACER_D3_VIRTUAL_CEIL_HEIGHT=1.30 \
  RACER_D3_VISUALIZATION_TRUNCATE_HEIGHT=1.50 RACER_D3_VISUALIZATION_TRUNCATE_LOW=0.50 \
  RACER_D3_SWARM_SAFE_DIST=3.5 EGO_GATE_MIN_INTER_UAV_DISTANCE=1.5 \
  RACER_D3_OBSTACLES_INFLATION=0.35 \
  RACER_D3_ASTAR_START_CLEARANCE_RADIUS=0.70 RACER_D3_ASTAR_MAX_SEARCH_TIME=0.005 \
  RACER_D3_DISABLE_PAIR_OPT="${RACER_D3_DISABLE_PAIR_OPT:-true}" \
  RACER_D3_ALLOW_PAIR_OPT_FACTORY="${RACER_D3_ALLOW_PAIR_OPT_FACTORY:-false}" \
  RACER_D3_PAIR_OPT_AFTER_TRIGGER_ONLY=true \
  RACER_D3_ROUND_ROBIN_INIT=true \
  RACER_D3_MIN_UNKNOWN=500 RACER_D3_MIN_FREE=1200 RACER_D3_GRID_SIZE=4.0 \
  RACER_D3_ATTEMPT_INTERVAL=0.4 RACER_D3_PAIR_OPT_INTERVAL=2.0 \
  RACER_D3_FRONTIER_MIN_VISIB_NUM=10 RACER_D3_MIN_SWARM_TRAJ_COUNT=1 \
  EGO_MAX_VEL=0.8 EGO_MAX_ACC=0.8 EGO_MAX_JERK=4.0 \
  EGO_CMD_SAFETY_MIN_Z=0.90 EGO_CMD_SAFETY_MAX_Z=1.35 \
  EGO_CMD_SAFETY_SMOOTHING_ENABLE=true EGO_CMD_SAFETY_SMOOTHING_MAX_SPEED_MPS=1.5 \
  EGO_CMD_SAFETY_SMOOTHING_ZERO_DYNAMICS=true EGO_CMD_SAFETY_ZERO_ALL_DYNAMICS=false \
  EGO_CMD_SAFETY_MOTION_TIME_BASIS=ros_sim_time \
  EGO_CMD_SAFETY_RECOMPUTE_VELOCITY_FROM_POSITION=true \
  EGO_CMD_SAFETY_MAX_VELOCITY_MPS=2.0 \
  EGO_CMD_SAFETY_MAX_ACCELERATION_MPS2=1.2 \
  EGO_CMD_SAFETY_MAX_LATERAL_ACCELERATION_MPS2=1.2 \
  EGO_CMD_SAFETY_MAX_JERK_MPS3=6.0 \
  EGO_CMD_SAFETY_MAX_TARGET_DISTANCE_FROM_ODOM_M=0.75 \
  EGO_CMD_SAFETY_MAX_XY_TARGET_DISTANCE_FROM_ODOM_M=0.60 \
  EGO_GATE_EXECUTE_TIMEOUT_S=150 EGO_GATE_LAND_TIMEOUT_S=35 \
  PX4CTRL_CORE_PROFILE=l1_awff \
  bash "${PROJECT_ROOT}/Scripts/sunray/run_px4ctrl_ego_swarm_gate.sh"
