#!/usr/bin/env bash
# Short Factory L2 indoor uav_frontier single-UAV runtime gate.

set -eo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-/mnt/c/Users/HP/Desktop/MoSim}"
RESULT_ROOT="${RESULT_ROOT:-${PROJECT_ROOT}/Results/sunray_ros1}"
STAMP="$(date +%Y%m%d_%H%M%S)"
RESULT_DIR="${RESULT_DIR:-${RESULT_ROOT}/factory_l2_indoor_uav_frontier_single_uff3_${STAMP}}"

export PROJECT_ROOT
export MOSIM_ROOT="${MOSIM_ROOT:-${PROJECT_ROOT}}"
export RESULT_DIR
export PLANNER_VARIANT="${PLANNER_VARIANT:-uav_frontier}"
export GUI="${GUI:-false}"
export OPEN_RVIZ="${OPEN_RVIZ:-false}"
export KEEP_ALIVE="${KEEP_ALIVE:-false}"
export USE_SIM_TIME="${USE_SIM_TIME:-false}"
export TOTAL_TIMEOUT_S="${TOTAL_TIMEOUT_S:-300}"
export MAVROS_READY_TIMEOUT_S="${MAVROS_READY_TIMEOUT_S:-180}"
export GOAL4_EGO_TAKEOVER_TIMEOUT_S="${GOAL4_EGO_TAKEOVER_TIMEOUT_S:-90}"
export GOAL4_TAKEOFF_TIMEOUT_S="${GOAL4_TAKEOFF_TIMEOUT_S:-90}"
export PX4CTRL_CORE_PROFILE="${PX4CTRL_CORE_PROFILE:-l1_awff}"

export WORLD_FILE="${WORLD_FILE:-${PROJECT_ROOT}/Config/gazebo/worlds/factoryenvironmentcollect_l2_static_review_clean.sdf}"
export FACTORY_MODEL_PATH="${FACTORY_MODEL_PATH:-${PROJECT_ROOT}/Config/gazebo/models}"
export SUNRAY_GAZEBO_LAUNCH_FILE="${SUNRAY_GAZEBO_LAUNCH_FILE:-${PROJECT_ROOT}/Scripts/sunray/factory_l2_sunray_px4_gazebo.launch}"

export SUNRAY_UAV_INIT_X="${SUNRAY_UAV_INIT_X:--10.575025}"
export SUNRAY_UAV_INIT_Y="${SUNRAY_UAV_INIT_Y:--19.36313}"
export SUNRAY_UAV_INIT_Z="${SUNRAY_UAV_INIT_Z:-0.2}"
export SUNRAY_STRIP_PX4_MODEL_PATH="${SUNRAY_STRIP_PX4_MODEL_PATH:-true}"
export TARGET_X="${TARGET_X:--10.575025}"
export TARGET_Y="${TARGET_Y:--19.36313}"
export TARGET_Z="${TARGET_Z:-1.2}"
export GOAL4_TAKEOFF_HEIGHT="${GOAL4_TAKEOFF_HEIGHT:-1.2}"
export PX4CTRL_AUTO_TAKEOFF_HEIGHT="${PX4CTRL_AUTO_TAKEOFF_HEIGHT:-0.95}"
export DIFF_PUBLISH_HOVER_DURING_TAKEOFF="${DIFF_PUBLISH_HOVER_DURING_TAKEOFF:-true}"

export GOAL4_UAV_FRONTIER_WS="${GOAL4_UAV_FRONTIER_WS:-${PROJECT_ROOT}/Results/sunray_ros1/uav_frontier_f0_f1_source_build_audit_20260703_235018/ws}"
export UAV_FRONTIER_EXPLORATION_EXECUTE_S="${UAV_FRONTIER_EXPLORATION_EXECUTE_S:-60.0}"
export UAV_FRONTIER_CONFIG_FILE="${UAV_FRONTIER_CONFIG_FILE:-${PROJECT_ROOT}/Config/planners/uav_frontier_factory_l2_indoor.yaml}"
export UAV_FRONTIER_CMD_MIN_Z="${UAV_FRONTIER_CMD_MIN_Z:-0.90}"
export UAV_FRONTIER_CMD_MAX_Z="${UAV_FRONTIER_CMD_MAX_Z:-1.60}"
export UAV_FRONTIER_FIXED_Z="${UAV_FRONTIER_FIXED_Z:-1.2}"
export PLANNER_CMD_FIXED_Z="${PLANNER_CMD_FIXED_Z:-${UAV_FRONTIER_FIXED_Z}}"
export PLANNER_CMD_ADAPTER_INITIAL_ENABLED="${PLANNER_CMD_ADAPTER_INITIAL_ENABLED:-false}"
export PLANNER_CMD_ODOM_TARGET_GUARD_ENABLE="${PLANNER_CMD_ODOM_TARGET_GUARD_ENABLE:-true}"
export PLANNER_CMD_MAX_XY_TARGET_DISTANCE_FROM_ODOM_M="${PLANNER_CMD_MAX_XY_TARGET_DISTANCE_FROM_ODOM_M:-1.50}"
export PLANNER_CMD_MAX_TARGET_DISTANCE_FROM_ODOM_M="${PLANNER_CMD_MAX_TARGET_DISTANCE_FROM_ODOM_M:-1.80}"
export PLANNER_CMD_SEED_FROM_ODOM_ON_ENABLE="${PLANNER_CMD_SEED_FROM_ODOM_ON_ENABLE:-true}"
export UAV_FRONTIER_CMD_SMOOTH_MAX_SPEED_MPS="${UAV_FRONTIER_CMD_SMOOTH_MAX_SPEED_MPS:-0.8}"
export UAV_FRONTIER_CMD_SMOOTH_MAX_STEP_M="${UAV_FRONTIER_CMD_SMOOTH_MAX_STEP_M:-0.03}"
export UAV_FRONTIER_RAW_CMD_MAX_POSITION_JUMP_M="${UAV_FRONTIER_RAW_CMD_MAX_POSITION_JUMP_M:-0.8}"
export UAV_FRONTIER_RAW_CMD_MAX_POSITION_JUMP_SPEED_MPS="${UAV_FRONTIER_RAW_CMD_MAX_POSITION_JUMP_SPEED_MPS:-0}"

export DIFF_CMD_MIN_Z="${DIFF_CMD_MIN_Z:-${UAV_FRONTIER_CMD_MIN_Z}}"
export DIFF_CMD_MAX_Z="${DIFF_CMD_MAX_Z:-${UAV_FRONTIER_CMD_MAX_Z}}"
export DIFF_CMD_SAFETY_MAX_POSITION_JUMP_M="${DIFF_CMD_SAFETY_MAX_POSITION_JUMP_M:-${UAV_FRONTIER_RAW_CMD_MAX_POSITION_JUMP_M}}"
export DIFF_CMD_SAFETY_MAX_POSITION_JUMP_SPEED_MPS="${DIFF_CMD_SAFETY_MAX_POSITION_JUMP_SPEED_MPS:-${UAV_FRONTIER_RAW_CMD_MAX_POSITION_JUMP_SPEED_MPS}}"

export SUNRAY_MID360_PLUGIN_DOWNSAMPLE="${SUNRAY_MID360_PLUGIN_DOWNSAMPLE:-4}"
export SUNRAY_LIVOX_PLUGIN_FILENAME="${SUNRAY_LIVOX_PLUGIN_FILENAME:-${PROJECT_ROOT}/Results/sunray_ros1/workspaces/sunray_livox_plugin_ws/devel/lib/liblivox_laser_simulation.so}"
export SUNRAY_MID360_CSV_FILE_NAME="${SUNRAY_MID360_CSV_FILE_NAME:-mid360-real-centr.csv}"
export SUNRAY_MID360_GOAL5_CSV_STRIDE="${SUNRAY_MID360_GOAL5_CSV_STRIDE:-4}"
export FASTLIO_SCAN_RATE_HZ="${FASTLIO_SCAN_RATE_HZ:-20.0}"
export FASTLIO_FILTER_SIZE_SURF="${FASTLIO_FILTER_SIZE_SURF:-0.02}"
export FASTLIO_FILTER_SIZE_MAP="${FASTLIO_FILTER_SIZE_MAP:-0.02}"
export POINTCLOUD_MIN_WORLD_Z_M="${POINTCLOUD_MIN_WORLD_Z_M:-0.2}"
export POINTCLOUD_MAX_WORLD_Z_M="${POINTCLOUD_MAX_WORLD_Z_M:-4.0}"
export POINTCLOUD_MAX_SENSOR_RANGE_M="${POINTCLOUD_MAX_SENSOR_RANGE_M:-80.0}"
export POINTCLOUD_ODOM_SYNC_MODE="${POINTCLOUD_ODOM_SYNC_MODE:-auto_mixed_time}"
export POINTCLOUD_OUTPUT_STAMP_MODE="${POINTCLOUD_OUTPUT_STAMP_MODE:-now}"
export POINTCLOUD_REVIEW_VOXEL_SIZE_M="${POINTCLOUD_REVIEW_VOXEL_SIZE_M:-0.08}"
export POINTCLOUD_REVIEW_MIN_WORLD_Z_M="${POINTCLOUD_REVIEW_MIN_WORLD_Z_M:-0.2}"
export POINTCLOUD_REVIEW_MAX_WORLD_Z_M="${POINTCLOUD_REVIEW_MAX_WORLD_Z_M:-4.0}"
export POINTCLOUD_REVIEW_MAX_ACCUMULATED_POINTS="${POINTCLOUD_REVIEW_MAX_ACCUMULATED_POINTS:-0}"
export OCCUPANCY_REVIEW_MAX_ACCUMULATED_POINTS="${OCCUPANCY_REVIEW_MAX_ACCUMULATED_POINTS:-0}"
export ENABLE_OCCUPANCY_REVIEW_ACCUMULATION="${ENABLE_OCCUPANCY_REVIEW_ACCUMULATION:-true}"
export GOAL4_RECORD_HZ="${GOAL4_RECORD_HZ:-100}"
export GOAL4_RECORD_CMD_HZ="${GOAL4_RECORD_CMD_HZ:-100}"
export GOAL4_MAX_PATH_POINTS="${GOAL4_MAX_PATH_POINTS:-0}"
export EGO_ALLOW_EMPTY_FINAL_OCCUPANCY="${EGO_ALLOW_EMPTY_FINAL_OCCUPANCY:-true}"

mkdir -p "${RESULT_DIR}"
cat > "${RESULT_DIR}/FACTORY_L2_UAV_FRONTIER_SINGLE_RUNTIME_GATE_REQUEST.json" <<JSON
{
  "schema": "mosim.factory_l2_uav_frontier_single_runtime_gate_request.v1",
  "result_dir": "${RESULT_DIR}",
  "planner_variant": "${PLANNER_VARIANT}",
  "world_file": "${WORLD_FILE}",
  "factory_model_path": "${FACTORY_MODEL_PATH}",
  "workspace": "${GOAL4_UAV_FRONTIER_WS}",
  "config_file": "${UAV_FRONTIER_CONFIG_FILE}",
  "start_xyz": [${SUNRAY_UAV_INIT_X}, ${SUNRAY_UAV_INIT_Y}, ${SUNRAY_UAV_INIT_Z}],
  "target_xyz_placeholder": [${TARGET_X}, ${TARGET_Y}, ${TARGET_Z}],
  "exploration_execute_s": ${UAV_FRONTIER_EXPLORATION_EXECUTE_S},
  "z_band_m": [${UAV_FRONTIER_CMD_MIN_Z}, ${UAV_FRONTIER_CMD_MAX_Z}],
  "fixed_z_m": ${UAV_FRONTIER_FIXED_Z},
  "note": "Short UF-F3 gate proves uav_frontier startup, frontier goal production, bridge command production, and safe execution plumbing. It is not the full indoor coverage gate."
}
JSON

exec "${PROJECT_ROOT}/Scripts/sunray/run_px4ctrl_ego_single_gate.sh"
