#!/usr/bin/env bash
# Run a bounded Factory L2 indoor RACER three-UAV coverage gate and build an
# offline coverage packet from the completed run.

set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-/mnt/c/Users/HP/Desktop/MoSim}"
cd "${PROJECT_ROOT}"

STAMP="$(date +%Y%m%d_%H%M%S)"
RUN_ID="${RUN_ID:-factory_l2_indoor_racer_swarm_coverage_${STAMP}}"
RESULT_DIR="${RESULT_DIR:-${PROJECT_ROOT}/Results/sunray_ros1/${RUN_ID}}"
mkdir -p "${RESULT_DIR}"

EXPLORATION_DURATION_S="${EXPLORATION_DURATION_S:-120}"
MIN_EXPECTED_RTF="${MIN_EXPECTED_RTF:-0.08}"
if [[ -z "${TOTAL_TIMEOUT_S:-}" ]]; then
  TOTAL_TIMEOUT_S="$(awk -v duration="${EXPLORATION_DURATION_S}" -v rtf="${MIN_EXPECTED_RTF}" 'BEGIN { printf "%d", (duration / rtf) + 240.999 }')"
fi
WALL_TIMEOUT_S="${WALL_TIMEOUT_S:-$((TOTAL_TIMEOUT_S + 600))}"
EXECUTE_TIMEOUT_S="${EXECUTE_TIMEOUT_S:-150}"
MIN_SENSOR_COVERAGE_RATIO="${MIN_SENSOR_COVERAGE_RATIO:-0.80}"

echo "${RUN_ID}" > "${RESULT_DIR}/RUN_ID.txt"
date --iso-8601=seconds > "${RESULT_DIR}/start_time.txt"

set +e
RUN_ID="${RUN_ID}" \
RESULT_DIR="${RESULT_DIR}" \
PLANNER_VARIANT=racer \
RACER_SENSOR_SOURCE=fastlio \
RACER_INPUT_GATE_ONLY=false \
RACER_FASTLIO_SCAN_RATE_HZ="${RACER_FASTLIO_SCAN_RATE_HZ:-20.0}" \
RACER_FASTLIO_FILTER_SIZE_SURF="${RACER_FASTLIO_FILTER_SIZE_SURF:-0.5}" \
RACER_FASTLIO_FILTER_SIZE_MAP="${RACER_FASTLIO_FILTER_SIZE_MAP:-0.5}" \
RACER_FASTLIO_ALIGNMENT_Z_SOURCE="${RACER_FASTLIO_ALIGNMENT_Z_SOURCE:-truth}" \
RACER_FASTLIO_ALIGNMENT_REFERENCE="${RACER_FASTLIO_ALIGNMENT_REFERENCE:-config}" \
PX4CTRL_CORE_PROFILE="${PX4CTRL_CORE_PROFILE:-l1_awff}" \
GUI="${GUI:-false}" \
OPEN_RVIZ=false \
KEEP_ALIVE=false \
WORLD_FILE="${WORLD_FILE:-${PROJECT_ROOT}/Results/unreal_scene_mapping/factory_l2_static_import/gazebo_review_clean/worlds/factoryenvironmentcollect_l2_static_review_clean.sdf}" \
FACTORY_MODEL_PATH="${FACTORY_MODEL_PATH:-${PROJECT_ROOT}/Results/unreal_scene_mapping/factory_l2_static_import/gazebo_review_clean/models}" \
SUNRAY_GAZEBO_LAUNCH_FILE="${SUNRAY_GAZEBO_LAUNCH_FILE:-${PROJECT_ROOT}/Scripts/sunray/factory_l2_sunray_px4_gazebo.launch}" \
SUNRAY_STRIP_PX4_MODEL_PATH=true \
SUNRAY_MID360_PLUGIN_DOWNSAMPLE="${SUNRAY_MID360_PLUGIN_DOWNSAMPLE:-4}" \
SUNRAY_LIVOX_PLUGIN_FILENAME="${SUNRAY_LIVOX_PLUGIN_FILENAME:-${PROJECT_ROOT}/Results/sunray_ros1/workspaces/sunray_livox_plugin_ws/devel/lib/liblivox_laser_simulation.so}" \
SUNRAY_MID360_CSV_FILE_NAME="${SUNRAY_MID360_CSV_FILE_NAME:-mid360-real-centr.csv}" \
SUNRAY_MID360_GOAL5_CSV_STRIDE="${SUNRAY_MID360_GOAL5_CSV_STRIDE:-4}" \
START1_X="${START1_X:--10.575025}" \
START1_Y="${START1_Y:--19.36313}" \
START2_X="${START2_X:--8.575025}" \
START2_Y="${START2_Y:--19.36313}" \
START3_X="${START3_X:--10.575025}" \
START3_Y="${START3_Y:--17.36313}" \
MAVROS_READY_TIMEOUT_S="${MAVROS_READY_TIMEOUT_S:-120}" \
TOTAL_TIMEOUT_S="${TOTAL_TIMEOUT_S}" \
GOAL5_STARTUP_ATTEMPTS=1 \
SEQUENTIAL_SPAWN="${SEQUENTIAL_SPAWN:-false}" \
STAGGERED_SPAWN="${STAGGERED_SPAWN:-true}" \
STAGGERED_SPAWN_INTERVAL_S="${STAGGERED_SPAWN_INTERVAL_S:-12}" \
RACER_D3_EXPLORATION_DURATION_S="${EXPLORATION_DURATION_S}" \
RACER_D3_EXPLORATION_MAX_TRAJECTORY_STALE_S="${RACER_D3_EXPLORATION_MAX_TRAJECTORY_STALE_S:-10.0}" \
EGO_GATE_EXECUTE_TIMEOUT_S="${EXECUTE_TIMEOUT_S}" \
EGO_GATE_LAND_TIMEOUT_S="${EGO_GATE_LAND_TIMEOUT_S:-35}" \
RACER_D3_MAP_SIZE_X="${RACER_D3_MAP_SIZE_X:-180.0}" \
RACER_D3_MAP_SIZE_Y="${RACER_D3_MAP_SIZE_Y:-70.0}" \
RACER_D3_MAP_SIZE_Z="${RACER_D3_MAP_SIZE_Z:-2.2}" \
RACER_D3_MIN_UNKNOWN="${RACER_D3_MIN_UNKNOWN:-500}" \
RACER_D3_MIN_FREE="${RACER_D3_MIN_FREE:-1200}" \
RACER_D3_GRID_SIZE="${RACER_D3_GRID_SIZE:-4.0}" \
RACER_D3_FRONTIER_MIN_VISIB_NUM="${RACER_D3_FRONTIER_MIN_VISIB_NUM:-10}" \
RACER_D3_DISABLE_PAIR_OPT="${RACER_D3_DISABLE_PAIR_OPT:-true}" \
RACER_D3_ALLOW_PAIR_OPT_FACTORY="${RACER_D3_ALLOW_PAIR_OPT_FACTORY:-false}" \
RACER_D3_PAIR_OPT_AFTER_TRIGGER_ONLY="${RACER_D3_PAIR_OPT_AFTER_TRIGGER_ONLY:-true}" \
RACER_D3_ROUND_ROBIN_INIT="${RACER_D3_ROUND_ROBIN_INIT:-true}" \
RACER_D3_BOX_MIN_Z="${RACER_D3_BOX_MIN_Z:-0.90}" \
RACER_D3_BOX_MAX_Z="${RACER_D3_BOX_MAX_Z:-1.35}" \
RACER_D3_VIRTUAL_CEIL_HEIGHT="${RACER_D3_VIRTUAL_CEIL_HEIGHT:-1.30}" \
RACER_D3_VISUALIZATION_TRUNCATE_HEIGHT="${RACER_D3_VISUALIZATION_TRUNCATE_HEIGHT:-1.50}" \
RACER_D3_VISUALIZATION_TRUNCATE_LOW="${RACER_D3_VISUALIZATION_TRUNCATE_LOW:-0.50}" \
RACER_D3_SWARM_SAFE_DIST="${RACER_D3_SWARM_SAFE_DIST:-1.5}" \
RACER_D3_ASTAR_START_CLEARANCE_RADIUS="${RACER_D3_ASTAR_START_CLEARANCE_RADIUS:-0.70}" \
RACER_D3_ASTAR_MAX_SEARCH_TIME="${RACER_D3_ASTAR_MAX_SEARCH_TIME:-0.005}" \
RACER_FRAME_BRIDGE_ENABLED=true \
RACER_FRAME_OFFSET_X="${RACER_FRAME_OFFSET_X:--10.575025}" \
RACER_FRAME_OFFSET_Y="${RACER_FRAME_OFFSET_Y:--19.36313}" \
RACER_FRAME_OFFSET_Z="${RACER_FRAME_OFFSET_Z:-0.0}" \
EGO_CMD_SAFETY_MIN_Z="${EGO_CMD_SAFETY_MIN_Z:-0.90}" \
EGO_CMD_SAFETY_MAX_Z="${EGO_CMD_SAFETY_MAX_Z:-1.35}" \
EGO_CMD_SAFETY_SMOOTHING_ENABLE=true \
EGO_CMD_SAFETY_SMOOTHING_MAX_SPEED_MPS="${EGO_CMD_SAFETY_SMOOTHING_MAX_SPEED_MPS:-0.8}" \
EGO_CMD_SAFETY_ZERO_ALL_DYNAMICS=true \
EGO_CMD_SAFETY_MAX_POSITION_JUMP_M="${EGO_CMD_SAFETY_MAX_POSITION_JUMP_M:-0.8}" \
POINTCLOUD_MAX_SENSOR_RANGE_M="${POINTCLOUD_MAX_SENSOR_RANGE_M:-80.0}" \
POINTCLOUD_MIN_WORLD_Z_M="${POINTCLOUD_MIN_WORLD_Z_M:-0.2}" \
POINTCLOUD_MAX_WORLD_Z_M="${POINTCLOUD_MAX_WORLD_Z_M:-4.0}" \
POINTCLOUD_MAX_ABS_ODOM_XY_M="${POINTCLOUD_MAX_ABS_ODOM_XY_M:-200.0}" \
MAVROS_STREAM_RATE_HZ="${MAVROS_STREAM_RATE_HZ:-100}" \
timeout --kill-after=15s "${WALL_TIMEOUT_S}s" bash Scripts/sunray/run_px4ctrl_ego_swarm_gate.sh \
  > "${RESULT_DIR}/factory_l2_indoor_racer_swarm_coverage_gate.log" 2>&1
RUN_EXIT=$?
set -e
echo "${RUN_EXIT}" > "${RESULT_DIR}/run_exit_code.txt"

set +e
python3 Scripts/sunray/build_factory_l2_indoor_coverage_packet.py \
  --run "${RESULT_DIR}" \
  --output-dir "${RESULT_DIR}/coverage_packet" \
  --grid-resolution-m "${COVERAGE_GRID_RESOLUTION_M:-2.0}" \
  --sensor-radius-m "${COVERAGE_SENSOR_RADIUS_M:-8.0}" \
  --min-sensor-coverage-ratio "${MIN_SENSOR_COVERAGE_RATIO}" \
  > "${RESULT_DIR}/coverage_packet_builder.log" 2>&1
COVERAGE_EXIT=$?
set -e
echo "${COVERAGE_EXIT}" > "${RESULT_DIR}/coverage_packet_exit_code.txt"
date --iso-8601=seconds > "${RESULT_DIR}/end_time.txt"

echo "${RESULT_DIR}"
if [[ "${RUN_EXIT}" != "0" ]]; then
  exit "${RUN_EXIT}"
fi
exit "${COVERAGE_EXIT}"
