#!/usr/bin/env bash
# Short Factory L2 indoor FALCON runtime gate.

set -eo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-/mnt/c/Users/HP/Desktop/MoSim}"
RESULT_ROOT="${RESULT_ROOT:-${PROJECT_ROOT}/Results/sunray_ros1}"
STAMP="$(date +%Y%m%d_%H%M%S)"
RESULT_DIR="${RESULT_DIR:-${RESULT_ROOT}/factory_l2_indoor_falcon_single_f3_${STAMP}}"

export PROJECT_ROOT
export MOSIM_ROOT="${MOSIM_ROOT:-${PROJECT_ROOT}}"
export RESULT_DIR
export PLANNER_VARIANT="${PLANNER_VARIANT:-falcon}"
export GUI="${GUI:-false}"
export OPEN_RVIZ="${OPEN_RVIZ:-false}"
export KEEP_ALIVE="${KEEP_ALIVE:-false}"
export USE_SIM_TIME="${USE_SIM_TIME:-false}"
export TOTAL_TIMEOUT_S="${TOTAL_TIMEOUT_S:-300}"
export MAVROS_READY_TIMEOUT_S="${MAVROS_READY_TIMEOUT_S:-120}"
export GOAL4_EGO_TAKEOVER_TIMEOUT_S="${GOAL4_EGO_TAKEOVER_TIMEOUT_S:-90}"
export GOAL4_TAKEOFF_TIMEOUT_S="${GOAL4_TAKEOFF_TIMEOUT_S:-90}"
export PX4CTRL_CORE_PROFILE="${PX4CTRL_CORE_PROFILE:-l1_awff}"

export WORLD_FILE="${WORLD_FILE:-${PROJECT_ROOT}/Results/unreal_scene_mapping/factory_l2_static_import/gazebo_review_clean/worlds/factoryenvironmentcollect_l2_static_review_clean.sdf}"
export FACTORY_MODEL_PATH="${FACTORY_MODEL_PATH:-${PROJECT_ROOT}/Results/unreal_scene_mapping/factory_l2_static_import/gazebo_review_clean/models}"
export SUNRAY_GAZEBO_LAUNCH_FILE="${SUNRAY_GAZEBO_LAUNCH_FILE:-${PROJECT_ROOT}/Scripts/sunray/factory_l2_sunray_px4_gazebo.launch}"

export SUNRAY_UAV_INIT_X="${SUNRAY_UAV_INIT_X:--10.575025}"
export SUNRAY_UAV_INIT_Y="${SUNRAY_UAV_INIT_Y:--19.36313}"
export SUNRAY_STRIP_PX4_MODEL_PATH="${SUNRAY_STRIP_PX4_MODEL_PATH:-true}"
export SUNRAY_UAV_INIT_Z="${SUNRAY_UAV_INIT_Z:-0.2}"
export TARGET_X="${TARGET_X:--10.575025}"
export TARGET_Y="${TARGET_Y:--19.36313}"
export TARGET_Z="${TARGET_Z:-1.2}"
export GOAL4_TAKEOFF_HEIGHT="${GOAL4_TAKEOFF_HEIGHT:-1.2}"
export PX4CTRL_AUTO_TAKEOFF_HEIGHT="${PX4CTRL_AUTO_TAKEOFF_HEIGHT:-0.95}"
export DIFF_PUBLISH_HOVER_DURING_TAKEOFF="${DIFF_PUBLISH_HOVER_DURING_TAKEOFF:-true}"

export FALCON_EXPLORATION_EXECUTE_S="${FALCON_EXPLORATION_EXECUTE_S:-20.0}"
export FALCON_CMD_MIN_Z="${FALCON_CMD_MIN_Z:-0.90}"
export FALCON_CMD_MAX_Z="${FALCON_CMD_MAX_Z:-1.60}"
export PLANNER_CMD_FIXED_Z="${PLANNER_CMD_FIXED_Z:-1.2}"
export PLANNER_CMD_ADAPTER_INITIAL_ENABLED="${PLANNER_CMD_ADAPTER_INITIAL_ENABLED:-false}"
export PLANNER_CMD_ODOM_TARGET_GUARD_ENABLE="${PLANNER_CMD_ODOM_TARGET_GUARD_ENABLE:-true}"
export PLANNER_CMD_MAX_XY_TARGET_DISTANCE_FROM_ODOM_M="${PLANNER_CMD_MAX_XY_TARGET_DISTANCE_FROM_ODOM_M:-0.35}"
export PLANNER_CMD_MAX_TARGET_DISTANCE_FROM_ODOM_M="${PLANNER_CMD_MAX_TARGET_DISTANCE_FROM_ODOM_M:-0.45}"
export FALCON_CMD_SMOOTH_MAX_SPEED_MPS="${FALCON_CMD_SMOOTH_MAX_SPEED_MPS:-0.6}"
export FALCON_CMD_SMOOTH_MAX_STEP_M="${FALCON_CMD_SMOOTH_MAX_STEP_M:-0.02}"
export FALCON_RAW_CMD_MAX_POSITION_JUMP_M="${FALCON_RAW_CMD_MAX_POSITION_JUMP_M:-0.8}"
export FALCON_RAW_CMD_MAX_POSITION_JUMP_SPEED_MPS="${FALCON_RAW_CMD_MAX_POSITION_JUMP_SPEED_MPS:-0}"
export FALCON_HGRID_CELL_SIZE_MAX="${FALCON_HGRID_CELL_SIZE_MAX:-40.0}"
export FALCON_EXPLORATION_TOP_VIEW_NUM="${FALCON_EXPLORATION_TOP_VIEW_NUM:-3}"
export FALCON_EXPLORATION_REFINED_NUM="${FALCON_EXPLORATION_REFINED_NUM:-2}"

export DIFF_CMD_MIN_Z="${DIFF_CMD_MIN_Z:-${FALCON_CMD_MIN_Z}}"
export DIFF_CMD_MAX_Z="${DIFF_CMD_MAX_Z:-${FALCON_CMD_MAX_Z}}"
export DIFF_CMD_SAFETY_MAX_POSITION_JUMP_M="${DIFF_CMD_SAFETY_MAX_POSITION_JUMP_M:-${FALCON_RAW_CMD_MAX_POSITION_JUMP_M}}"
export DIFF_CMD_SAFETY_MAX_POSITION_JUMP_SPEED_MPS="${DIFF_CMD_SAFETY_MAX_POSITION_JUMP_SPEED_MPS:-${FALCON_RAW_CMD_MAX_POSITION_JUMP_SPEED_MPS}}"

export SUNRAY_MID360_PLUGIN_DOWNSAMPLE="${SUNRAY_MID360_PLUGIN_DOWNSAMPLE:-4}"
export SUNRAY_LIVOX_PLUGIN_FILENAME="${SUNRAY_LIVOX_PLUGIN_FILENAME:-${PROJECT_ROOT}/Results/sunray_ros1/workspaces/sunray_livox_plugin_ws/devel/lib/liblivox_laser_simulation.so}"
export SUNRAY_MID360_CSV_FILE_NAME="${SUNRAY_MID360_CSV_FILE_NAME:-mid360-real-centr.csv}"
export SUNRAY_MID360_GOAL5_CSV_STRIDE="${SUNRAY_MID360_GOAL5_CSV_STRIDE:-4}"
export FASTLIO_SCAN_RATE_HZ="${FASTLIO_SCAN_RATE_HZ:-20.0}"
export FASTLIO_FILTER_SIZE_SURF="${FASTLIO_FILTER_SIZE_SURF:-0.02}"
export FASTLIO_FILTER_SIZE_MAP="${FASTLIO_FILTER_SIZE_MAP:-0.02}"
export POINTCLOUD_MIN_WORLD_Z_M="${POINTCLOUD_MIN_WORLD_Z_M:-0.2}"
export POINTCLOUD_MAX_WORLD_Z_M="${POINTCLOUD_MAX_WORLD_Z_M:-4.0}"
export POINTCLOUD_MAX_SENSOR_RANGE_M="${POINTCLOUD_MAX_SENSOR_RANGE_M:-80.0}"
export POINTCLOUD_ODOM_SYNC_MODE="${POINTCLOUD_ODOM_SYNC_MODE:-auto_mixed_time}"
export POINTCLOUD_OUTPUT_STAMP_MODE="${POINTCLOUD_OUTPUT_STAMP_MODE:-now}"
export FALCON_BRIDGE_RESTAMP="${FALCON_BRIDGE_RESTAMP:-now}"
export POINTCLOUD_REVIEW_VOXEL_SIZE_M="${POINTCLOUD_REVIEW_VOXEL_SIZE_M:-0.08}"
export POINTCLOUD_REVIEW_MIN_WORLD_Z_M="${POINTCLOUD_REVIEW_MIN_WORLD_Z_M:-0.2}"
export POINTCLOUD_REVIEW_MAX_WORLD_Z_M="${POINTCLOUD_REVIEW_MAX_WORLD_Z_M:-4.0}"
export POINTCLOUD_REVIEW_MAX_ACCUMULATED_POINTS="${POINTCLOUD_REVIEW_MAX_ACCUMULATED_POINTS:-0}"
export OCCUPANCY_REVIEW_MAX_ACCUMULATED_POINTS="${OCCUPANCY_REVIEW_MAX_ACCUMULATED_POINTS:-0}"
export ENABLE_OCCUPANCY_REVIEW_ACCUMULATION="${ENABLE_OCCUPANCY_REVIEW_ACCUMULATION:-true}"
export GOAL4_RECORD_HZ="${GOAL4_RECORD_HZ:-100}"
export GOAL4_RECORD_CMD_HZ="${GOAL4_RECORD_CMD_HZ:-100}"
export GOAL4_MAX_PATH_POINTS="${GOAL4_MAX_PATH_POINTS:-0}"

mkdir -p "${RESULT_DIR}"
cat > "${RESULT_DIR}/FACTORY_L2_FALCON_SINGLE_RUNTIME_GATE_REQUEST.json" <<JSON
{
  "schema": "mosim.factory_l2_falcon_single_runtime_gate_request.v1",
  "result_dir": "${RESULT_DIR}",
  "planner_variant": "${PLANNER_VARIANT}",
  "world_file": "${WORLD_FILE}",
  "factory_model_path": "${FACTORY_MODEL_PATH}",
  "start_xyz": [${SUNRAY_UAV_INIT_X}, ${SUNRAY_UAV_INIT_Y}, ${SUNRAY_UAV_INIT_Z}],
  "target_xyz": [${TARGET_X}, ${TARGET_Y}, ${TARGET_Z}],
  "exploration_execute_s": ${FALCON_EXPLORATION_EXECUTE_S},
  "z_band_m": [${FALCON_CMD_MIN_Z}, ${FALCON_CMD_MAX_Z}],
  "falcon_sop_scale": {
    "hgrid_cell_size_max": ${FALCON_HGRID_CELL_SIZE_MAX},
    "top_view_num": ${FALCON_EXPLORATION_TOP_VIEW_NUM},
    "refined_num": ${FALCON_EXPLORATION_REFINED_NUM},
    "reason": "Factory indoor FALCON uses reduced SOP candidate scale because 20/6/4 repeatedly exceeded the upstream 1s SOP timeout and produced no executable bspline in 60s coverage."
  },
  "note": "Short F3 gate only proves runtime startup and nonempty planner/map/command topics, not full indoor coverage."
}
JSON

exec "${PROJECT_ROOT}/Scripts/sunray/run_px4ctrl_ego_single_gate.sh"
