#!/usr/bin/env bash
# Run a bounded Factory L2 indoor FALCON single-UAV coverage gate and build an
# offline coverage packet from the completed run.

set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-/mnt/c/Users/HP/Desktop/MoSim}"
cd "${PROJECT_ROOT}"

STAMP="$(date +%Y%m%d_%H%M%S)"
RUN_ID="${RUN_ID:-factory_l2_indoor_falcon_single_coverage_${STAMP}}"
RESULT_DIR="${RESULT_DIR:-${PROJECT_ROOT}/Results/sunray_ros1/${RUN_ID}}"
mkdir -p "${RESULT_DIR}"

EXPLORATION_DURATION_S="${EXPLORATION_DURATION_S:-60}"
TOTAL_TIMEOUT_S="${TOTAL_TIMEOUT_S:-360}"
MIN_SENSOR_COVERAGE_RATIO="${MIN_SENSOR_COVERAGE_RATIO:-0.80}"

echo "${RUN_ID}" > "${RESULT_DIR}/RUN_ID.txt"
date --iso-8601=seconds > "${RESULT_DIR}/start_time.txt"

set +e
RUN_ID="${RUN_ID}" \
RESULT_DIR="${RESULT_DIR}" \
PLANNER_VARIANT=falcon \
PX4CTRL_CORE_PROFILE="${PX4CTRL_CORE_PROFILE:-l1_awff}" \
GUI="${GUI:-false}" \
OPEN_RVIZ=false \
KEEP_ALIVE=false \
WORLD_FILE="${WORLD_FILE:-${PROJECT_ROOT}/Results/unreal_scene_mapping/factory_l2_static_import/gazebo_review_clean/worlds/factoryenvironmentcollect_l2_static_review_clean.sdf}" \
FACTORY_MODEL_PATH="${FACTORY_MODEL_PATH:-${PROJECT_ROOT}/Results/unreal_scene_mapping/factory_l2_static_import/gazebo_review_clean/models}" \
SUNRAY_GAZEBO_LAUNCH_FILE="${SUNRAY_GAZEBO_LAUNCH_FILE:-${PROJECT_ROOT}/Scripts/sunray/factory_l2_sunray_px4_gazebo.launch}" \
SUNRAY_UAV_INIT_X="${SUNRAY_UAV_INIT_X:--10.575025}" \
SUNRAY_UAV_INIT_Y="${SUNRAY_UAV_INIT_Y:--19.36313}" \
SUNRAY_UAV_INIT_Z="${SUNRAY_UAV_INIT_Z:-0.2}" \
TARGET_X="${TARGET_X:--10.575025}" \
TARGET_Y="${TARGET_Y:--19.36313}" \
TARGET_Z="${TARGET_Z:-1.2}" \
GOAL4_TAKEOFF_HEIGHT="${GOAL4_TAKEOFF_HEIGHT:-1.2}" \
PX4CTRL_AUTO_TAKEOFF_HEIGHT="${PX4CTRL_AUTO_TAKEOFF_HEIGHT:-0.95}" \
DIFF_PUBLISH_HOVER_DURING_TAKEOFF="${DIFF_PUBLISH_HOVER_DURING_TAKEOFF:-true}" \
FALCON_EXPLORATION_EXECUTE_S="${EXPLORATION_DURATION_S}" \
FALCON_CMD_MIN_Z="${FALCON_CMD_MIN_Z:-0.90}" \
FALCON_CMD_MAX_Z="${FALCON_CMD_MAX_Z:-1.60}" \
PLANNER_CMD_FIXED_Z="${PLANNER_CMD_FIXED_Z:-1.2}" \
PLANNER_CMD_ADAPTER_INITIAL_ENABLED="${PLANNER_CMD_ADAPTER_INITIAL_ENABLED:-false}" \
PLANNER_CMD_ODOM_TARGET_GUARD_ENABLE="${PLANNER_CMD_ODOM_TARGET_GUARD_ENABLE:-true}" \
PLANNER_CMD_MAX_XY_TARGET_DISTANCE_FROM_ODOM_M="${PLANNER_CMD_MAX_XY_TARGET_DISTANCE_FROM_ODOM_M:-0.35}" \
PLANNER_CMD_MAX_TARGET_DISTANCE_FROM_ODOM_M="${PLANNER_CMD_MAX_TARGET_DISTANCE_FROM_ODOM_M:-0.45}" \
FALCON_CMD_SMOOTH_MAX_SPEED_MPS="${FALCON_CMD_SMOOTH_MAX_SPEED_MPS:-0.6}" \
FALCON_CMD_SMOOTH_MAX_STEP_M="${FALCON_CMD_SMOOTH_MAX_STEP_M:-0.02}" \
FALCON_RAW_CMD_MAX_POSITION_JUMP_M="${FALCON_RAW_CMD_MAX_POSITION_JUMP_M:-0.8}" \
FALCON_RAW_CMD_MAX_POSITION_JUMP_SPEED_MPS="${FALCON_RAW_CMD_MAX_POSITION_JUMP_SPEED_MPS:-0}" \
FALCON_HGRID_CELL_SIZE_MAX="${FALCON_HGRID_CELL_SIZE_MAX:-40.0}" \
FALCON_EXPLORATION_TOP_VIEW_NUM="${FALCON_EXPLORATION_TOP_VIEW_NUM:-3}" \
FALCON_EXPLORATION_REFINED_NUM="${FALCON_EXPLORATION_REFINED_NUM:-2}" \
DIFF_EXECUTE_MAX_ROLL_PITCH_DEG="${DIFF_EXECUTE_MAX_ROLL_PITCH_DEG:-30.0}" \
SUNRAY_STRIP_PX4_MODEL_PATH=true \
SUNRAY_MID360_PLUGIN_DOWNSAMPLE="${SUNRAY_MID360_PLUGIN_DOWNSAMPLE:-4}" \
SUNRAY_LIVOX_PLUGIN_FILENAME="${SUNRAY_LIVOX_PLUGIN_FILENAME:-${PROJECT_ROOT}/Results/sunray_ros1/workspaces/sunray_livox_plugin_ws/devel/lib/liblivox_laser_simulation.so}" \
SUNRAY_MID360_CSV_FILE_NAME="${SUNRAY_MID360_CSV_FILE_NAME:-mid360-real-centr.csv}" \
SUNRAY_MID360_GOAL5_CSV_STRIDE="${SUNRAY_MID360_GOAL5_CSV_STRIDE:-4}" \
POINTCLOUD_MIN_WORLD_Z_M="${POINTCLOUD_MIN_WORLD_Z_M:-0.2}" \
POINTCLOUD_MAX_WORLD_Z_M="${POINTCLOUD_MAX_WORLD_Z_M:-4.0}" \
POINTCLOUD_MAX_SENSOR_RANGE_M="${POINTCLOUD_MAX_SENSOR_RANGE_M:-80.0}" \
POINTCLOUD_REVIEW_VOXEL_SIZE_M="${POINTCLOUD_REVIEW_VOXEL_SIZE_M:-0.08}" \
POINTCLOUD_REVIEW_MAX_ACCUMULATED_POINTS="${POINTCLOUD_REVIEW_MAX_ACCUMULATED_POINTS:-0}" \
OCCUPANCY_REVIEW_MAX_ACCUMULATED_POINTS="${OCCUPANCY_REVIEW_MAX_ACCUMULATED_POINTS:-0}" \
ENABLE_OCCUPANCY_REVIEW_ACCUMULATION=true \
GOAL4_RECORD_HZ="${GOAL4_RECORD_HZ:-100}" \
GOAL4_RECORD_CMD_HZ="${GOAL4_RECORD_CMD_HZ:-100}" \
GOAL4_MAX_PATH_POINTS="${GOAL4_MAX_PATH_POINTS:-0}" \
timeout "$((TOTAL_TIMEOUT_S + 30))s" bash Scripts/sunray/run_factory_l2_indoor_falcon_single_runtime_gate.sh \
  > "${RESULT_DIR}/factory_l2_indoor_falcon_single_coverage_gate.log" 2>&1
RUN_EXIT=$?
set -e
echo "${RUN_EXIT}" > "${RESULT_DIR}/run_exit_code.txt"

set +e
python3 Scripts/sunray/build_factory_l2_indoor_coverage_packet.py \
  --run "${RESULT_DIR}" \
  --output-dir "${RESULT_DIR}/coverage_packet" \
  --grid-resolution-m "${COVERAGE_GRID_RESOLUTION_M:-2.0}" \
  --sensor-radius-m "${COVERAGE_SENSOR_RADIUS_M:-8.0}" \
  --min-sensor-coverage-ratio "${MIN_SENSOR_COVERAGE_RATIO}" \
  > "${RESULT_DIR}/coverage_packet_builder.log" 2>&1
COVERAGE_EXIT=$?
set -e
echo "${COVERAGE_EXIT}" > "${RESULT_DIR}/coverage_packet_exit_code.txt"
date --iso-8601=seconds > "${RESULT_DIR}/end_time.txt"

echo "${RESULT_DIR}"
if [[ "${RUN_EXIT}" != "0" ]]; then
  exit "${RUN_EXIT}"
fi
exit "${COVERAGE_EXIT}"
