#!/usr/bin/env python3
"""Slice a Factory L2 waypoint packet for targeted corridor probes."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def load_packet(path: Path) -> dict[str, Any]:
    packet = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(packet, dict):
        raise SystemExit(f"packet root must be an object: {path}")
    waypoints = packet.get("waypoints")
    if not isinstance(waypoints, list):
        raise SystemExit(f"packet has no waypoints list: {path}")
    return packet


def write_yaml(path: Path, section: str, waypoints: list[list[float]]) -> None:
    lines = [
        "# Generated by Scripts/sunray/slice_factory_route_waypoints.py",
        "# Mode 1: x y z. Diff-Planner multipoint only reads fixed keys such as test1/test_back.",
        f"{section}:",
    ]
    for x, y, z in waypoints:
        lines.append(f"  - [{x:.6f}, {y:.6f}, {z:.6f}]")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-json", required=True)
    parser.add_argument("--output-json", required=True)
    parser.add_argument("--output-yaml", required=True)
    parser.add_argument("--section", default="test1")
    parser.add_argument("--start-index", type=int, required=True, help="1-based route index")
    parser.add_argument("--count", type=int, default=0, help="0 means through the end")
    args = parser.parse_args()

    input_json = Path(args.input_json)
    output_json = Path(args.output_json)
    output_yaml = Path(args.output_yaml)
    packet = load_packet(input_json)
    waypoints = packet["waypoints"]
    start = max(1, args.start_index) - 1
    stop = len(waypoints) if args.count <= 0 else min(len(waypoints), start + args.count)
    if start >= len(waypoints) or stop <= start:
        raise SystemExit(
            f"empty slice: start_index={args.start_index}, count={args.count}, waypoint_count={len(waypoints)}"
        )

    sliced = [[float(item[0]), float(item[1]), float(item[2])] for item in waypoints[start:stop]]
    packet["source_waypoint_count"] = len(waypoints)
    packet["source_waypoint_packet"] = str(input_json)
    packet["route_slice"] = {
        "enabled": True,
        "start_index_1based": start + 1,
        "end_index_1based": stop,
        "requested_count": args.count,
        "sliced_waypoint_count": len(sliced),
    }
    packet["waypoints"] = sliced
    packet["waypoint_count"] = len(sliced)
    packet["first_waypoint"] = sliced[0]
    packet["last_waypoint"] = sliced[-1]
    packet["output_yaml"] = str(output_yaml)
    output_json.write_text(json.dumps(packet, indent=2), encoding="utf-8")
    write_yaml(output_yaml, args.section, sliced)
    print(output_json)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
