// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnnotationProvider creates a new instance of MockAnnotationProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnnotationProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnnotationProvider {
	mock := &MockAnnotationProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnnotationProvider is an autogenerated mock type for the AnnotationProvider type
type MockAnnotationProvider struct {
	mock.Mock
}

type MockAnnotationProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnnotationProvider) EXPECT() *MockAnnotationProvider_Expecter {
	return &MockAnnotationProvider_Expecter{mock: &_m.Mock}
}

// ToToolAnnotations provides a mock function for the type MockAnnotationProvider
func (_mock *MockAnnotationProvider) ToToolAnnotations() *mcp.ToolAnnotations {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToToolAnnotations")
	}

	var r0 *mcp.ToolAnnotations
	if returnFunc, ok := ret.Get(0).(func() *mcp.ToolAnnotations); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.ToolAnnotations)
		}
	}
	return r0
}

// MockAnnotationProvider_ToToolAnnotations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToToolAnnotations'
type MockAnnotationProvider_ToToolAnnotations_Call struct {
	*mock.Call
}

// ToToolAnnotations is a helper method to define mock.On call
func (_e *MockAnnotationProvider_Expecter) ToToolAnnotations() *MockAnnotationProvider_ToToolAnnotations_Call {
	return &MockAnnotationProvider_ToToolAnnotations_Call{Call: _e.mock.On("ToToolAnnotations")}
}

func (_c *MockAnnotationProvider_ToToolAnnotations_Call) Run(run func()) *MockAnnotationProvider_ToToolAnnotations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnnotationProvider_ToToolAnnotations_Call) Return(toolAnnotations *mcp.ToolAnnotations) *MockAnnotationProvider_ToToolAnnotations_Call {
	_c.Call.Return(toolAnnotations)
	return _c
}

func (_c *MockAnnotationProvider_ToToolAnnotations_Call) RunAndReturn(run func() *mcp.ToolAnnotations) *MockAnnotationProvider_ToToolAnnotations_Call {
	_c.Call.Return(run)
	return _c
}
