// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolAdder creates a new instance of MockToolAdder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolAdder[ToolInput any, ToolOutput any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolAdder[ToolInput, ToolOutput] {
	mock := &MockToolAdder[ToolInput, ToolOutput]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolAdder is an autogenerated mock type for the ToolAdder type
type MockToolAdder[ToolInput any, ToolOutput any] struct {
	mock.Mock
}

type MockToolAdder_Expecter[ToolInput any, ToolOutput any] struct {
	mock *mock.Mock
}

func (_m *MockToolAdder[ToolInput, ToolOutput]) EXPECT() *MockToolAdder_Expecter[ToolInput, ToolOutput] {
	return &MockToolAdder_Expecter[ToolInput, ToolOutput]{mock: &_m.Mock}
}

// AddTool provides a mock function for the type MockToolAdder
func (_mock *MockToolAdder[ToolInput, ToolOutput]) AddTool(server *mcp.Server, tool *mcp.Tool, handler mcp.ToolHandlerFor[ToolInput, ToolOutput]) {
	_mock.Called(server, tool, handler)
	return
}

// MockToolAdder_AddTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTool'
type MockToolAdder_AddTool_Call[ToolInput any, ToolOutput any] struct {
	*mock.Call
}

// AddTool is a helper method to define mock.On call
//   - server *mcp.Server
//   - tool *mcp.Tool
//   - handler mcp.ToolHandlerFor[ToolInput, ToolOutput]
func (_e *MockToolAdder_Expecter[ToolInput, ToolOutput]) AddTool(server interface{}, tool interface{}, handler interface{}) *MockToolAdder_AddTool_Call[ToolInput, ToolOutput] {
	return &MockToolAdder_AddTool_Call[ToolInput, ToolOutput]{Call: _e.mock.On("AddTool", server, tool, handler)}
}

func (_c *MockToolAdder_AddTool_Call[ToolInput, ToolOutput]) Run(run func(server *mcp.Server, tool *mcp.Tool, handler mcp.ToolHandlerFor[ToolInput, ToolOutput])) *MockToolAdder_AddTool_Call[ToolInput, ToolOutput] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mcp.Server
		if args[0] != nil {
			arg0 = args[0].(*mcp.Server)
		}
		var arg1 *mcp.Tool
		if args[1] != nil {
			arg1 = args[1].(*mcp.Tool)
		}
		var arg2 mcp.ToolHandlerFor[ToolInput, ToolOutput]
		if args[2] != nil {
			arg2 = args[2].(mcp.ToolHandlerFor[ToolInput, ToolOutput])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockToolAdder_AddTool_Call[ToolInput, ToolOutput]) Return() *MockToolAdder_AddTool_Call[ToolInput, ToolOutput] {
	_c.Call.Return()
	return _c
}

func (_c *MockToolAdder_AddTool_Call[ToolInput, ToolOutput]) RunAndReturn(run func(server *mcp.Server, tool *mcp.Tool, handler mcp.ToolHandlerFor[ToolInput, ToolOutput])) *MockToolAdder_AddTool_Call[ToolInput, ToolOutput] {
	_c.Run(run)
	return _c
}
