// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSVersionProvider creates a new instance of MockOSVersionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSVersionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSVersionProvider {
	mock := &MockOSVersionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSVersionProvider is an autogenerated mock type for the OSVersionProvider type
type MockOSVersionProvider struct {
	mock.Mock
}

type MockOSVersionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSVersionProvider) EXPECT() *MockOSVersionProvider_Expecter {
	return &MockOSVersionProvider_Expecter{mock: &_m.Mock}
}

// Version provides a mock function for the type MockOSVersionProvider
func (_mock *MockOSVersionProvider) Version() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOSVersionProvider_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockOSVersionProvider_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockOSVersionProvider_Expecter) Version() *MockOSVersionProvider_Version_Call {
	return &MockOSVersionProvider_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockOSVersionProvider_Version_Call) Run(run func()) *MockOSVersionProvider_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSVersionProvider_Version_Call) Return(s string, err error) *MockOSVersionProvider_Version_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOSVersionProvider_Version_Call) RunAndReturn(run func() (string, error)) *MockOSVersionProvider_Version_Call {
	_c.Call.Return(run)
	return _c
}
