import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";

export const blueprintTool: ToolDef = categoryTool(
  "blueprint",
  "Blueprint reading, authoring, and compilation. Covers variables, functions, graphs, nodes, components, interfaces, and event dispatchers.",
  {
    read:              bp("Read BP structure incl. SCS components AND inherited native components from the CDO (CharacterMesh0, CharMoveComp, etc.). Params: assetPath, includeComponentProperties? (dump UPROPERTY name/type/value per component template; off by default) (#353/#370)", "read_blueprint", (p) => ({ path: p.assetPath, includeComponentProperties: p.includeComponentProperties })),
    list_variables:    bp("List variables. Params: assetPath", "list_blueprint_variables", (p) => ({ path: p.assetPath })),
    list_functions:    bp("List functions/graphs. Params: assetPath", "list_blueprint_functions", (p) => ({ path: p.assetPath })),
    read_graph:        bp("Read graph nodes. Params: assetPath, graphName", "read_blueprint_graph", (p) => ({ path: p.assetPath, graphName: p.graphName })),
    read_graph_summary: bp("Lightweight graph summary (nodes+edges only, ~10KB). Params: assetPath, graphName?", "read_blueprint_graph_summary", (p) => ({ path: p.assetPath, graphName: p.graphName })),
    get_execution_flow: bp("Trace exec pins from an entry point. Params: assetPath, graphName?, entryPoint?", "get_blueprint_execution_flow", (p) => ({ path: p.assetPath, graphName: p.graphName, entryPoint: p.entryPoint })),
    get_dependencies:   bp("Forward (classes/functions/assets) or reverse (referencers) deps. Params: assetPath, reverse?", "get_blueprint_dependencies", (p) => ({ path: p.assetPath, reverse: p.reverse })),
    create:            bp("Create Blueprint. Params: assetPath, parentClass?", "create_blueprint", (p) => ({ path: p.assetPath, parentClass: p.parentClass })),
    add_variable:      bp("Add variable. Params: assetPath, name, varType", "add_variable", (p) => ({ path: p.assetPath, name: p.name, type: p.varType })),
    set_variable_properties: bp("Edit variable properties. Params: assetPath, name, instanceEditable?, blueprintReadOnly?, category?, tooltip?, replicationType?, exposeOnSpawn?", "set_variable_properties", (p) => ({ path: p.assetPath, name: p.name, instanceEditable: p.instanceEditable, blueprintReadOnly: p.blueprintReadOnly, category: p.category, tooltip: p.tooltip, replicationType: p.replicationType, exposeOnSpawn: p.exposeOnSpawn })),
    create_function:   bp("Create function. Params: assetPath, functionName", "create_function", (p) => ({ path: p.assetPath, functionName: p.functionName })),
    delete_function:   bp("Delete function. Params: assetPath, functionName", "delete_function", (p) => ({ path: p.assetPath, functionName: p.functionName })),
    rename_function:   bp("Rename function. Params: assetPath, oldName, newName", "rename_function", (p) => ({ path: p.assetPath, oldName: p.oldName, newName: p.newName })),
    add_node:          bp("Add graph node. Params: assetPath, graphName?, nodeClass, nodeParams?", "add_node", (p) => ({ path: p.assetPath, graphName: p.graphName ?? "EventGraph", nodeClass: p.nodeClass, nodeParams: p.nodeParams })),
    delete_node:       bp("Delete node. Params: assetPath, graphName, nodeName", "delete_node", (p) => ({ path: p.assetPath, graphName: p.graphName, nodeName: p.nodeName })),
    set_node_property: bp("Set node pin default or struct property. Params: assetPath, graphName, nodeName, propertyName, value", "set_node_property", (p) => ({ path: p.assetPath, graphName: p.graphName, nodeName: p.nodeName, propertyName: p.propertyName, value: p.value })),
    connect_pins:      bp("Wire nodes. Params: sourceNode, sourcePin, targetNode, targetPin, assetPath, graphName?", "connect_pins"),
    add_component:     bp("Add BP component. Params: assetPath, componentClass, componentName?, parentComponent? (SCS parent for hierarchy — #115)", "add_component", (p) => ({ path: p.assetPath, componentClass: p.componentClass, componentName: p.componentName ?? p.componentClass, parentComponent: p.parentComponent })),
    remove_component:  bp("Remove SCS component. Params: assetPath, componentName", "remove_component", (p) => ({ path: p.assetPath, componentName: p.componentName })),
    set_component_property: bp("Set property on SCS or inherited component. Inherited components go through the child BP's InheritableComponentHandler override template so the parent stays untouched. Pass value=null to clear a TObjectPtr/SoftObject/WeakObject/UClass/Interface reference (e.g. clear AnimClass on CharacterMesh0) (#420). Params: assetPath, componentName, propertyName, value", "set_blueprint_component_property", (p) => ({ path: p.assetPath, componentName: p.componentName, propertyName: p.propertyName, value: p.value })),
    set_capsule_size: bp("Call UCapsuleComponent::SetCapsuleSize on a CapsuleComponent template (CharacterMovement-friendly path; raw property writes leave the visualizer stale). Pass either or both of halfHeight/radius. Returns the new + previous values. Params: assetPath, componentName, halfHeight?, radius? (#419)", "set_capsule_size", (p) => ({ path: p.assetPath, componentName: p.componentName, halfHeight: p.halfHeight, radius: p.radius })),
    get_component_property: bp("Read a single property value from an SCS or inherited component template. Returns the ICH override value for child BPs if one exists. Params: assetPath, componentName, propertyName", "get_blueprint_component_property", (p) => ({ path: p.assetPath, componentName: p.componentName, propertyName: p.propertyName })),
    set_class_default: bp("Set UPROPERTY on Blueprint CDO. Pass value=null to clear an object/class/interface reference (#420). Params: assetPath, propertyName, value", "set_class_default", (p) => ({ path: p.assetPath, propertyName: p.propertyName, value: p.value })),
    delete_variable:   bp("Delete a member variable. Params: assetPath, name", "delete_variable", (p) => ({ path: p.assetPath, name: p.name })),
    add_function_parameter: bp("Add input or output parameter to a function. Params: assetPath, functionName, parameterName, parameterType?, isOutput?", "add_function_parameter", (p) => ({ path: p.assetPath, functionName: p.functionName, parameterName: p.parameterName, parameterType: p.parameterType, isOutput: p.isOutput })),
    set_variable_default: bp("Set default value on a BP variable. Params: assetPath, name, value", "set_variable_default", (p) => ({ path: p.assetPath, name: p.name, value: p.value })),
    compile:           bp("Compile Blueprint. Params: assetPath", "compile_blueprint", (p) => ({ path: p.assetPath })),
    list_node_types:   bp("List node types. Params: category?, includeFunctions?", "list_node_types"),
    search_node_types: bp("Search nodes. Params: query", "search_node_types"),
    create_interface:  bp("Create BP Interface. Params: assetPath", "create_blueprint_interface", (p) => ({ path: p.assetPath })),
    add_interface:     bp("Implement interface. Params: blueprintPath, interfacePath", "add_blueprint_interface"),
    list_graphs:       bp("List all graphs in a blueprint. Params: assetPath", "list_blueprint_graphs", (p) => ({ path: p.assetPath })),
    add_event_dispatcher: bp("Add event dispatcher (multicast delegate variable + signature graph + UFunction). Without parameters, broadcasters fire void(). With parameters, the signature graph gets typed user pins so K2Node_CallDelegate compiles cleanly (#276). Params: blueprintPath, name, parameters?: [{name, type}] where type is bool/int/float/string/name/text/vector/rotator/transform/object:/Script/Module.Class/struct:/Script/Module.Struct", "add_event_dispatcher"),
    duplicate:         bp("Duplicate blueprint asset. Params: sourcePath, destinationPath", "duplicate_blueprint"),
    add_local_variable: bp("Add function-scope local variable. Params: assetPath, functionName, name, varType?", "add_local_variable"),
    list_local_variables: bp("List local variables in a function. Params: assetPath, functionName", "list_local_variables"),
    validate:          bp("Validate blueprint without saving (compile + collect diagnostics). Params: assetPath", "validate_blueprint"),
    read_component_properties: bp("Dump ALL UPROPERTYs on a BP component template incl. array contents (#105). Params: assetPath, componentName", "read_component_properties", (p) => ({ path: p.assetPath, componentName: p.componentName })),
    read_node_property: bp("Read a node pin default OR a reflected node property for verification (#102). Params: assetPath, graphName?, nodeName, propertyName", "read_node_property", (p) => ({ path: p.assetPath, graphName: p.graphName, nodeName: p.nodeName, propertyName: p.propertyName })),
    reparent_component: bp("Reparent an SCS component under a new parent (#115). Params: assetPath, componentName, newParent", "reparent_component", (p) => ({ path: p.assetPath, componentName: p.componentName, newParent: p.newParent })),
    reparent: bp("Change a Blueprint's ParentClass and recompile (#138). Params: assetPath, parentClass (short name or full path).", "reparent_blueprint", (p) => ({ path: p.assetPath, parentClass: p.parentClass })),
    set_actor_tick_settings: bp("Set actor CDO tick settings (#116). Params: assetPath, bCanEverTick?, bStartWithTickEnabled?, TickInterval?", "set_actor_tick_settings", (p) => ({ path: p.assetPath, bCanEverTick: p.bCanEverTick, bStartWithTickEnabled: p.bStartWithTickEnabled, TickInterval: p.TickInterval })),
    export_nodes_t3d:  bp("Export graph nodes as T3D text (Ctrl+C equivalent) for bulk round-trip (#130). Params: assetPath, graphName?, nodeIds? (omit = whole graph)", "export_nodes_t3d", (p) => ({ path: p.assetPath, graphName: p.graphName ?? "EventGraph", nodeIds: p.nodeIds })),
    import_nodes_t3d:  bp("Paste a T3D node blob into a graph (Ctrl+V equivalent) for bulk authoring (#130). Params: assetPath, graphName?, t3d, posX?, posY?", "import_nodes_t3d", (p) => ({ path: p.assetPath, graphName: p.graphName ?? "EventGraph", t3d: p.t3d, posX: p.posX, posY: p.posY })),
    set_cdo_property:  bp("Set UPROPERTY on any C++ class CDO (not just Blueprints). Params: className, propertyName, value (#182/#183)", "set_cdo_property"),
    get_cdo_properties: bp("Read UPROPERTY values from any C++ class CDO. Params: className, propertyNames? (#183)", "get_cdo_properties"),
    run_construction_script: bp("Spawn temp actor, run construction script, return generated components and transforms. Params: assetPath, location? (#195)", "run_construction_script", (p) => ({ path: p.assetPath, location: p.location })),
    compile_all: bp("Batch compile + save Blueprints. Params: assetPaths[], save? (default true). Returns per-path status (compiled/failed/not_found) (#284)", "compile_blueprints", (p) => ({ assetPaths: p.assetPaths, save: p.save })),
    cleanup_graph: bp("Remove orphan/corrupted nodes (no class, blank title+no pins, missing target UFunction). Params: assetPath, graphName? (default: every graph) (#285)", "cleanup_graph", (p) => ({ assetPath: p.assetPath, graphName: p.graphName })),
    connect_pins_batch: bp("Apply many pin connections in one call (single compile + save). Params: assetPath, graphName?, connections[]: [{sourceNode, sourcePin, targetNode, targetPin}] (#267)", "connect_pins_batch", (p) => ({ assetPath: p.assetPath, graphName: p.graphName, connections: p.connections })),
    set_node_position: bp("Move a graph node to (posX, posY). Params: assetPath, graphName?, nodeId, posX, posY (#277)", "set_node_position", (p) => ({ assetPath: p.assetPath, graphName: p.graphName, nodeId: p.nodeId, posX: p.posX, posY: p.posY })),
    auto_layout: bp("Topological layered layout for a graph. Eliminates the (0,0) stack from programmatic add_node. Params: assetPath, graphName?, columnGap? (default 360), rowGap? (default 200) (#277)", "auto_layout_graph", (p) => ({ assetPath: p.assetPath, graphName: p.graphName, columnGap: p.columnGap, rowGap: p.rowGap })),
  },
  undefined,
  {
    assetPath: z.string().optional().describe("Blueprint asset path"),
    graphName: z.string().optional(), functionName: z.string().optional(),
    name: z.string().optional(), varType: z.string().optional().describe("Variable type"),
    parentClass: z.string().optional(),
    instanceEditable: z.boolean().optional(), blueprintReadOnly: z.boolean().optional(),
    category: z.string().optional(), tooltip: z.string().optional(),
    replicationType: z.string().optional(),
    exposeOnSpawn: z.boolean().optional().describe("Toggle ExposeOnSpawn flag on a variable"),
    oldName: z.string().optional(), newName: z.string().optional(),
    nodeClass: z.string().optional(), nodeParams: z.record(z.unknown()).optional(),
    nodeName: z.string().optional(), propertyName: z.string().optional(),
    value: z.unknown().optional(),
    sourceNode: z.string().optional(), sourcePin: z.string().optional(),
    targetNode: z.string().optional(), targetPin: z.string().optional(),
    componentClass: z.string().optional(), componentName: z.string().optional(),
    halfHeight: z.number().optional().describe("set_capsule_size: capsule half height (unscaled)"),
    radius: z.number().optional().describe("set_capsule_size: capsule radius (unscaled)"),
    parentComponent: z.string().optional().describe("Parent SCS component for add_component hierarchy (#115)"),
    newParent: z.string().optional().describe("New parent component name for reparent_component"),
    bCanEverTick: z.boolean().optional(),
    bStartWithTickEnabled: z.boolean().optional(),
    TickInterval: z.number().optional(),
    parameterName: z.string().optional(), parameterType: z.string().optional(),
    isOutput: z.boolean().optional(),
    query: z.string().optional(),
    includeFunctions: z.boolean().optional(),
    blueprintPath: z.string().optional(), interfacePath: z.string().optional(),
    entryPoint: z.string().optional().describe("Event/function name to start exec-flow trace"),
    reverse: z.boolean().optional().describe("get_dependencies: true → referencers of this asset"),
    includeComponentProperties: z.boolean().optional().describe("read: dump UPROPERTY name/type/value per component template (#353/#370)"),
    sourcePath: z.string().optional(), destinationPath: z.string().optional(),
    nodeIds: z.array(z.string()).optional().describe("Node guids/names to export (omit = whole graph)"),
    t3d: z.string().optional().describe("T3D blob from export_nodes_t3d (or copied from the BP graph editor)"),
    className: z.string().optional().describe("C++ class name or path for set_cdo_property / get_cdo_properties"),
    propertyNames: z.array(z.string()).optional().describe("Property names to read for get_cdo_properties (omit = all)"),
    posX: z.number().optional().describe("Re-center pasted nodes around this X (with posY)"),
    posY: z.number().optional().describe("Re-center pasted nodes around this Y (with posX)"),
    parameters: z.array(z.object({
      name: z.string(),
      type: z.string().optional(),
    })).optional().describe("add_event_dispatcher: typed signature parameters [{name, type}]. type is bool/int/float/string/name/text/vector/rotator/transform/object:/Script/Module.Class/struct:/Script/Module.Struct"),
    assetPaths: z.array(z.string()).optional().describe("Asset paths for compile_all"),
    save: z.boolean().optional().describe("compile_all: persist on success (default true)"),
    nodeId: z.string().optional().describe("Node guid or name (set_node_position)"),
    columnGap: z.number().optional().describe("auto_layout: horizontal spacing between columns (default 360)"),
    rowGap: z.number().optional().describe("auto_layout: vertical spacing between rows (default 200)"),
    connections: z.array(z.object({
      sourceNode: z.string(), sourcePin: z.string(),
      targetNode: z.string(), targetPin: z.string(),
    })).optional().describe("connect_pins_batch: per-connection records"),
  },
);
