import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Vec3 } from "../schemas.js";

export const pcgTool: ToolDef = categoryTool(
  "pcg",
  "Procedural Content Generation: graphs, nodes, connections, execution, volumes.",
  {
    list_graphs:          bp("List PCG graphs. Params: directory?, recursive?", "list_pcg_graphs"),
    read_graph:           bp("Read graph structure. Params: assetPath", "read_pcg_graph"),
    read_node_settings:   bp("Read node settings. Params: assetPath, nodeName", "read_pcg_node_settings"),
    get_components:       bp("List PCG components in level", "get_pcg_components"),
    get_component_details: bp("Inspect PCG component. Params: actorLabel", "get_pcg_component_details"),
    create_graph:         bp("Create graph. Params: name, packagePath?", "create_pcg_graph"),
    add_node:             bp("Add node. Params: assetPath, nodeType, nodeName?", "add_pcg_node"),
    connect_nodes:        bp("Wire nodes. Params: assetPath, sourceNode, sourcePin, targetNode, targetPin. Returns edgeVerified=true after confirming the UPCGEdge persisted; surfaces an error if AddEdge succeeded but no edge object was instantiated (#304).", "connect_pcg_nodes"),
    disconnect_nodes:     bp("Remove a wired edge between two PCG nodes. Params: assetPath, sourceNode, targetNode, sourcePin? (default: any), targetPin? (default: any). Returns removedEdges count (#346).", "disconnect_pcg_nodes", (p) => ({ assetPath: p.assetPath, sourceNode: p.sourceNode, targetNode: p.targetNode, sourcePin: p.sourcePin, targetPin: p.targetPin, sourceNodeName: p.sourceNodeName, targetNodeName: p.targetNodeName, sourcePinLabel: p.sourcePinLabel, targetPinLabel: p.targetPinLabel })),
    set_node_settings:    bp("Set node params. Params: assetPath, nodeName, settings", "set_pcg_node_settings"),
    set_static_mesh_spawner_meshes: bp("Populate weighted MeshEntries on a PCGStaticMeshSpawner node (#145). Params: assetPath, nodeName, entries=[{mesh, weight?}], replace? (default true)", "set_static_mesh_spawner_meshes", (p) => ({ assetPath: p.assetPath, nodeName: p.nodeName, entries: p.entries, replace: p.replace })),
    remove_node:          bp("Remove node. Params: assetPath, nodeName", "remove_pcg_node"),
    execute:              bp("Regenerate PCG. Params: actorLabel", "execute_pcg_graph"),
    force_regenerate:     bp("Force a stuck PCG component to regenerate (clears graph ref, re-sets, cleanup+generate). Params: actorLabel (#146)", "force_regenerate_pcg"),
    cleanup:              bp("Cleanup a PCG component (remove spawned content). Params: actorLabel, removeComponents? (default true) (#146)", "cleanup_pcg", (p) => ({ actorLabel: p.actorLabel, removeComponents: p.removeComponents })),
    toggle_graph:         bp("Toggle a PCG component's graph assignment to force reinit (no generate). Params: actorLabel, graphPath? (#146)", "toggle_pcg_graph", (p) => ({ actorLabel: p.actorLabel, graphPath: p.graphPath })),
    add_volume:           bp("Place PCG volume. Params: graphPath, location?, extent?", "add_pcg_volume"),
    import_graph:         bp("Bulk-author a PCG graph from JSON. Params: assetPath, nodes=[{name,class,posX?,posY?,settings?}], connections=[{from,fromPin?,to,toPin?}], replace? (default false). One call replaces N add_node + M connect_nodes + K set_node_settings (#213).", "import_pcg_graph", (p) => ({ assetPath: p.assetPath, nodes: p.nodes, connections: p.connections, replace: p.replace })),
    export_graph:         bp("Export a PCG graph as JSON. Params: assetPath, includeSettings? (default true). Round-trip safe with import_graph (#213).", "export_pcg_graph", (p) => ({ assetPath: p.assetPath, includeSettings: p.includeSettings })),
  },
  undefined,
  {
    assetPath: z.string().optional(), actorLabel: z.string().optional(),
    directory: z.string().optional(), recursive: z.boolean().optional(),
    name: z.string().optional(), packagePath: z.string().optional(),
    nodeType: z.string().optional(), nodeName: z.string().optional(),
    sourceNode: z.string().optional(), sourcePin: z.string().optional(),
    targetNode: z.string().optional(), targetPin: z.string().optional(),
    settings: z.record(z.unknown()).optional(),
    entries: z.array(z.record(z.unknown())).optional().describe("Array of {mesh, weight?} entries for set_static_mesh_spawner_meshes"),
    replace: z.boolean().optional().describe("set_static_mesh_spawner_meshes: overwrite existing MeshEntries (default true). import_graph: wipe existing user nodes first (default false)."),
    graphPath: z.string().optional(),
    location: Vec3.optional(),
    extent: Vec3.optional(),
    removeComponents: z.boolean().optional().describe("cleanup: remove managed spawned components (default true)"),
    nodes: z.array(z.record(z.unknown())).optional().describe("import_graph: [{name, class, posX?, posY?, settings?}]"),
    connections: z.array(z.record(z.unknown())).optional().describe("import_graph: [{from, fromPin?, to, toPin?}]"),
    includeSettings: z.boolean().optional().describe("export_graph: include per-node editable settings in the response (default true)"),
  },
);
