model ObsAvoidController_Sysblock2 "避障控制（Sysblock）"
  extends ModelWorkspace;
  import SysplorerEmbeddedCoder.Types.*;
  import BaseWorkspace.*;
  annotation(__MWORKS(version="2025a",modelType=Control,PortArrangement(Left(front_dist, rear_dist, left_dist, right_dist), Right(speed, steer)),BlockSystem(blockKind=BlockKind.userModel,SampleTime(auto=true,group="")=0.01),SysblockVersion="1.0"),Icon(coordinateSystem(preserveAspectRatio=false)),experiment(Algorithm=Dassl,Interval=0.01,InlineIntegrator=false,InlineStepSize=false,StartTime=0,StopTime=1,Tolerance=0.0001),Diagram(coordinateSystem(extent={{-100,-100},{100,100}}, 
grid={2,2}),graphics = {Text(origin={-171,58}, 
lineColor={0,0,0}, 
extent={{-19,10},{19,-10}}, 
textString="前方传感器距离", 
textStyle={TextStyle.None}, 
textColor={0,0,0}, 
horizontalAlignment=LinePattern.None), Text(origin={-171,16}, 
lineColor={0,0,0}, 
extent={{-19,10},{19,-10}}, 
textString="后方传感器距离", 
textStyle={TextStyle.None}, 
textColor={0,0,0}, 
horizontalAlignment=LinePattern.None), Text(origin={-171,-26}, 
lineColor={0,0,0}, 
extent={{-19,10},{19,-10}}, 
textString="左方传感器距离", 
textStyle={TextStyle.None}, 
textColor={0,0,0}, 
horizontalAlignment=LinePattern.None), Text(origin={-171,-68}, 
lineColor={0,0,0}, 
extent={{-19,10},{19,-10}}, 
textString="右方传感器距离", 
textStyle={TextStyle.None}, 
textColor={0,0,0}, 
horizontalAlignment=LinePattern.None), Text(origin={221,58}, 
lineColor={0,0,0}, 
extent={{-19,10},{19,-10}}, 
textString="预期车速", 
textStyle={TextStyle.None}, 
textColor={0,0,0}, 
horizontalAlignment=LinePattern.None), Text(origin={221,-58}, 
lineColor={0,0,0}, 
extent={{-19,10},{19,-10}}, 
textString="前轮转角", 
textStyle={TextStyle.None}, 
textColor={0,0,0}, 
horizontalAlignment=LinePattern.None)}),Protection(access=Access.diagram));
  SysplorerEmbeddedCoder.Port.Inport front_dist 
    annotation (Placement(transformation(origin={-136,58}, 
extent={{-10,-10},{10,10}}), 
iconTransformation(origin={-101.8,75}, 
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.Port.Inport rear_dist 
    annotation (Placement(transformation(origin={-136,16}, 
extent={{-10,-10},{10,10}}), 
iconTransformation(origin={-101.8,25}, 
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.Port.Inport left_dist 
    annotation (Placement(transformation(origin={-136,-26}, 
extent={{-10,-10},{10,10}}), 
iconTransformation(origin={-101.8,-25}, 
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.Port.Inport right_dist 
    annotation (Placement(transformation(origin={-136,-68}, 
extent={{-10,-10},{10,10}}), 
iconTransformation(origin={-101.8,-75}, 
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.Port.Outport speed 
    annotation (Placement(transformation(origin={178,58}, 
extent={{-10,-10},{10,10}}), 
iconTransformation(origin={101.8,50}, 
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.Port.Outport steer 
    annotation (Placement(transformation(origin={178,-58}, 
extent={{-10,-10},{10,10}}), 
iconTransformation(origin={101.8,-50}, 
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.01)));
  Chart chart 
    annotation (Placement(transformation(origin={-18,-7}, 
extent={{-29,-29},{29,29}})),__MWORKS(ComponentNamePlacement(BOTTOM),BlockSystem(SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.MathOperation.Sum sum1(isSaturate=false,inputs="+-") 
    annotation (Placement(transformation(origin={140,28}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(u1(Type(ref="double") ,Dimension=1) ,u2(Type(ref="double") ,Dimension=1)) ,y(Type(ref="double") ,Dimension=1)),Type(overflowKind=SysplorerEmbeddedCoder.Types.OverflowKind.wrap) ,SampleTime(group="D1")=0.01),PortLabels(labelType="CustomType",labels(label(text="+",instance="u1"),label(text="-",instance="u2")))));
  SysplorerEmbeddedCoder.MathOperation.Sum sum2(isSaturate=false,inputs="++") 
    annotation (Placement(transformation(origin={52,-26.5}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(u1(Type(ref="double") ,Dimension=1) ,u2(Type(ref="double") ,Dimension=1)) ,y(Type(ref="double") ,Dimension=1)),Type(overflowKind=SysplorerEmbeddedCoder.Types.OverflowKind.wrap) ,SampleTime(group="D1")=0.01),PortLabels(labelType="CustomType",labels(label(text="+",instance="u1"),label(text="+",instance="u2")))));
  SysplorerEmbeddedCoder.Sources.Constant constant1(k=pi) 
    annotation (Placement(transformation(origin={1,-58}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(SampleTime(auto=true,group="D1")=0.01,Instance(y(Type(ref="double") ,Dimension=1) ,k(Type(ref="double") ,Dimension=1)))));
  SysplorerEmbeddedCoder.MathOperation.RoundingFunction roundingFunction 
    annotation (Placement(transformation(origin={62,16}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.MathOperation.Product product1(isSaturate=false,inputs="*/") 
    annotation (Placement(transformation(origin={94,-31.5}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(u1(Type(ref="double") ,Dimension=1) ,u2(Type(ref="double") ,Dimension=1)) ,y(Type(ref="double") ,Dimension=1)),Type(overflowKind=SysplorerEmbeddedCoder.Types.OverflowKind.wrap) ,SampleTime(group="D1")=0.01),PortLabels(labelType="CustomType",labels(label(text="*",instance="u1"),label(text="/",instance="u2")))));
  SysplorerEmbeddedCoder.Sources.Constant constant2(k=2*pi) 
    annotation (Placement(transformation(origin={52,-58}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(SampleTime(auto=true,group="D1")=0.01,Instance(y(Type(ref="double") ,Dimension=1) ,k(Type(ref="double") ,Dimension=1)))));
  SysplorerEmbeddedCoder.MathOperation.Gain gain(k=2*pi) 
    annotation (Placement(transformation(origin={94,16}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1) ,k(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.MathOperation.Abs abs1 
    annotation (Placement(transformation(origin={-98,58}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.MathOperation.Abs abs2 
    annotation (Placement(transformation(origin={-98,16}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.MathOperation.Abs abs3 
    annotation (Placement(transformation(origin={-98,-26}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.01)));
  SysplorerEmbeddedCoder.MathOperation.Abs abs4 
    annotation (Placement(transformation(origin={-98,-68}, 
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.01)));
  block Chart "状态机"
    annotation (__MWORKS(BlockSystem(blockKind = BlockKind.stateMachine,SampleTime(auto = true),independent = true,StateMachine(virtual = false,functionPack = FunctionPack.auto,functionName = "",sourceFile = "",parallel=true)),PortArrangement(Left(df, db, dl, dr), Right(speed, steer)),sourceModel=SysplorerEmbeddedCoder.StateMachine.Chart,independentInstance=true,hide=true), 
      defaultComponentName = "chart", 
      Icon(coordinateSystem(extent = {{-100.0, -100.0}, {100.0, 100.0}}, 
        grid = {2.0, 2.0}), graphics = {Rectangle(origin = {0.0, 0.0}, 
        lineColor = {74, 84, 154}, 
        fillColor = {255, 255, 255}, 
        lineThickness = 1.0, 
        extent = {{-100.0, 100.0}, {100.0, -100.0}}, 
        radius = 11.0), Rectangle(origin = {0.0, 27.0}, 
        lineColor = {74, 84, 154}, 
        fillColor = {255, 255, 255}, 
        lineThickness = 1.0, 
        extent = {{-25.0, 20.0}, {25.0, -20.0}}, 
        radius = 10.0), Rectangle(origin = {-40.0, -27.0}, 
        lineColor = {74, 84, 154}, 
        fillColor = {255, 255, 255}, 
        lineThickness = 1.0, 
        extent = {{-25.0, 20.0}, {25.0, -20.0}}, 
        radius = 10.0), Rectangle(origin = {40.0, -27.0}, 
        lineColor = {74, 84, 154}, 
        fillColor = {255, 255, 255}, 
        lineThickness = 1.0, 
        extent = {{-25.0, 20.0}, {25.0, -20.0}}, 
        radius = 10.0), Line(origin = {-40.0, 13.0}, 
        points = {{-10.0, -13.0}, {-10.0, 7.0}, {10.0, 13.0}}, 
        color = {74, 84, 154}, 
        thickness = 1.0, 
        arrow = {Arrow.None, Arrow.Filled}, 
        arrowSize = 8.0, 
        smooth = Smooth.Bezier), Line(origin = {41.0, 13.0}, 
        points = {{-9.0, 13.0}, {9.0, 11.0}, {9.0, -13.0}}, 
        color = {74, 84, 154}, 
        thickness = 1.0, 
        arrow = {Arrow.None, Arrow.Filled}, 
        arrowSize = 8.0, 
        smooth = Smooth.Bezier), Line(origin = {0.0, -28.0}, 
        points = {{10.0, 0.0}, {-10.0, 0.0}}, 
        color = {74, 84, 154}, 
        thickness = 1.0, 
        arrow = {Arrow.None, Arrow.Filled}, 
        arrowSize = 8.0, 
        smooth = Smooth.Bezier), Text(origin = {0.0, -120.0}, 
        lineColor = {74, 84, 154}, 
        extent = {{0, 20.0}, {0, -20.0}}, 
        textString = "%name", 
        fontSize = 14, 
        textStyle = {TextStyle.None}, 
        textColor = {74, 84, 154}, 
        verticalAlignment = TextAlignment.Top)}),Diagram(coordinateSystem(extent={{-100,-100},{100,100}}, 
  grid={2,2})),Protection(access=Access.diagram));
    SysplorerEmbeddedCoder.Port.Inport df annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Port.Inport db annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Port.Inport dl annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Port.Inport dr annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Port.Outport speed(start=0) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Port.Outport steer(start=0) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Types.Auto mindis(start=1) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)));
    SysplorerEmbeddedCoder.Types.Auto safeF(start=1.5) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)));
    State longitudinal 
      annotation (Placement(transformation(origin={-202,-7.5}, 
extent={{-116,-101.5},{116,101.5}})),__MWORKS(BlockSystem(StateMachine(priority=1))));
    SysplorerEmbeddedCoder.Types.Auto flag(start=false) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="boolean"),Dimension(dimensionType=DimensionType.none)=1)));
    State2 lateral 
      annotation (Placement(transformation(origin={-202,-276}, 
  extent={{-380,-160},{380,160}})),__MWORKS(BlockSystem(StateMachine(priority=2))));
    block State "状态"
      annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
       Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
         grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
         lineColor = {74, 84, 154}, 
         fillColor = {255, 255, 255}, 
         lineThickness = 1, 
         extent = {{-100, 100}, {100, -100}}, 
         radius = 11), Line(origin = {0, 80}, 
         points = {{-100, 0}, {100, 0}}, 
         color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
         lineColor = {0, 0, 128}, 
         extent = {{-100, 10}, {100, -10}}, 
         textString = "%name", 
         textStyle = {TextStyle.None}, 
         textColor = {0, 0, 128}), Text(origin = {0, -10}, 
         lineColor = {0, 0, 128}, 
         extent = {{-100, 90}, {100, -90}}, 
         textString = "algorithm", 
         fontSize = 16, 
         textStyle = {TextStyle.None}, 
         textColor = {0, 0, 128}, 
         horizontalAlignment = TextAlignment.Left, 
         verticalAlignment = TextAlignment.Top)}), 
       Diagram(coordinateSystem(extent={{-116,-101.5},{116,101.5}}, 
  initialScale=1, 
  grid={2,2}),graphics = {State(origin={0,0}, 
  stateTitle=Text(origin={0,0}, 
  lineColor={74,84,154}, 
  extent={{-114,93.5},{114,101.5}}, 
  textString="%name", 
  fontSize=16, 
  textStyle={TextStyle.Bold}, 
  textColor={74,84,154}, 
  horizontalAlignment=TextAlignment.Left), 
  stateText=Text(origin={0,0}, 
  lineColor={74,84,154}, 
  extent={{-114,-101.5},{114,93.5}}, 
  textString="%algorithm", 
  fontSize=16, 
  textColor={74,84,154}, 
  horizontalAlignment=TextAlignment.Left, 
  verticalAlignment=TextAlignment.Top))}),Protection(access=Access.diagram));
      block State2 "状态"
        annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
         Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
           grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
           lineColor = {74, 84, 154}, 
           fillColor = {255, 255, 255}, 
           lineThickness = 1, 
           extent = {{-100, 100}, {100, -100}}, 
           radius = 11), Line(origin = {0, 80}, 
           points = {{-100, 0}, {100, 0}}, 
           color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
           lineColor = {0, 0, 128}, 
           extent = {{-100, 10}, {100, -10}}, 
           textString = "%name", 
           textStyle = {TextStyle.None}, 
           textColor = {0, 0, 128}), Text(origin = {0, -10}, 
           lineColor = {0, 0, 128}, 
           extent = {{-100, 90}, {100, -90}}, 
           textString = "algorithm", 
           fontSize = 16, 
           textStyle = {TextStyle.None}, 
           textColor = {0, 0, 128}, 
           horizontalAlignment = TextAlignment.Left, 
           verticalAlignment = TextAlignment.Top)}), 
         Diagram(coordinateSystem(extent={{-40, -30}, {40, 30}}, initialScale=1, grid={2, 2}), graphics = {State(origin = {0.0, 0.0}, 
              stateTitle = Text(origin = {0, 0}, 
              lineColor = {74, 84, 154}, 
              extent = {{-38, 22}, {38, 30}}, 
              textString = "%name", 
              fontSize = 16, 
              horizontalAlignment = TextAlignment.Left, 
              textStyle = {TextStyle.Bold}, 
              textColor = {74, 84, 154}, 
              verticalAlignment = TextAlignment.Center), 
              stateLine = Line(origin={0,0}, 
              color = {74, 84, 154}, 
              points={{-40,22},{40,22}}), 
              stateText = Text(origin = {0.0, 0.0}, 
              lineColor = {74, 84, 154}, 
              extent = {{-38, -30}, {38, 22}}, 
              textString = "%algorithm", 
              fontSize = 16, 
              textColor = {74, 84, 154}, 
              horizontalAlignment = TextAlignment.Left, 
              verticalAlignment = TextAlignment.Top))}),Protection(access=Access.diagram));
      algorithm
      annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  speed := 1;
        flag := false;
      end State2;
      State2 cruise 
      annotation(Placement(transformation(origin={-66,27.5}, 
  extent={{-40,-30},{40,30}})),__MWORKS(BlockSystem(StateMachine)));
      State avoid 
        annotation (Placement(transformation(origin={66,27.5}, 
  extent={{-40,-30},{40,30}})),__MWORKS(BlockSystem(StateMachine)));
      block State "状态"
        annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
         Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
           grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
           lineColor = {74, 84, 154}, 
           fillColor = {255, 255, 255}, 
           lineThickness = 1, 
           extent = {{-100, 100}, {100, -100}}, 
           radius = 11), Line(origin = {0, 80}, 
           points = {{-100, 0}, {100, 0}}, 
           color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
           lineColor = {0, 0, 128}, 
           extent = {{-100, 10}, {100, -10}}, 
           textString = "%name", 
           textStyle = {TextStyle.None}, 
           textColor = {0, 0, 128}), Text(origin = {0, -10}, 
           lineColor = {0, 0, 128}, 
           extent = {{-100, 90}, {100, -90}}, 
           textString = "algorithm", 
           fontSize = 16, 
           textStyle = {TextStyle.None}, 
           textColor = {0, 0, 128}, 
           horizontalAlignment = TextAlignment.Left, 
           verticalAlignment = TextAlignment.Top)}), 
         Diagram(coordinateSystem(extent={{-40, -30}, {40, 30}}, initialScale=1, grid={2, 2}), graphics = {State(origin = {0.0, 0.0}, 
              stateTitle = Text(origin = {0, 0}, 
              lineColor = {74, 84, 154}, 
              extent = {{-38, 22}, {38, 30}}, 
              textString = "%name", 
              fontSize = 16, 
              horizontalAlignment = TextAlignment.Left, 
              textStyle = {TextStyle.Bold}, 
              textColor = {74, 84, 154}, 
              verticalAlignment = TextAlignment.Center), 
              stateLine = Line(origin={0,0}, 
              color = {74, 84, 154}, 
              points={{-40,22},{40,22}}), 
              stateText = Text(origin = {0.0, 0.0}, 
              lineColor = {74, 84, 154}, 
              extent = {{-38, -30}, {38, 22}}, 
              textString = "%algorithm", 
              fontSize = 16, 
              textColor = {74, 84, 154}, 
              horizontalAlignment = TextAlignment.Left, 
              verticalAlignment = TextAlignment.Top))}),Protection(access=Access.diagram));
      algorithm
      annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  speed := -1;
        flag := true;
      end State;
      equation
      initialState(cruise, true, 1) 
      annotation(Line(origin={-284,60}, 
      points={{0,10},{0,-10}}, 
      color={113,119,170}, 
      smooth=Smooth.Bezier),Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{0,-3},{0,3}}, 
      textString="%condition", 
      fontSize=10, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}), displayText = "[true]");
      transition(cruise, avoid, df <= mindis, reset = false) 
      annotation(Line(origin={-202,33.8644}, 
      points={{-26,0},{26,0}}, 
      color={113,119,170}, 
      smooth=Smooth.Bezier),Text(origin={-10.6675,4.37639}, 
      lineColor={74,84,154}, 
      extent={{0,-3},{0,3}}, 
      textString="%condition", 
      fontSize=10, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[df <= mindis]");
      transition(avoid, cruise, after(1,sec), reset = false) 
      annotation(Line(origin={-202,13.07656}, 
      points={{26,0},{-26,0}}, 
      color={113,119,170}, 
      smooth=Smooth.Bezier),Text(origin={-7.38516,-4.37639}, 
      lineColor={74,84,154}, 
      extent={{0,-3},{0,3}}, 
      textString="%condition", 
      fontSize=10, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[after(1,sec)]");
    algorithm
    annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));
    end State;
    block State2 "状态"
      annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),StateMachine),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
       Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
         grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
         lineColor = {74, 84, 154}, 
         fillColor = {255, 255, 255}, 
         lineThickness = 1, 
         extent = {{-100, 100}, {100, -100}}, 
         radius = 11), Line(origin = {0, 80}, 
         points = {{-100, 0}, {100, 0}}, 
         color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
         lineColor = {0, 0, 128}, 
         extent = {{-100, 10}, {100, -10}}, 
         textString = "%name", 
         textStyle = {TextStyle.None}, 
         textColor = {0, 0, 128}), Text(origin = {0, -10}, 
         lineColor = {0, 0, 128}, 
         extent = {{-100, 90}, {100, -90}}, 
         textString = "algorithm", 
         fontSize = 16, 
         textStyle = {TextStyle.None}, 
         textColor = {0, 0, 128}, 
         horizontalAlignment = TextAlignment.Left, 
         verticalAlignment = TextAlignment.Top)}), 
       Diagram(coordinateSystem(extent={{-380,-160},{380,160}}, 
  initialScale=1, 
  grid={2,2}),graphics = {State(origin={0,0}, 
  stateTitle=Text(origin={0,0}, 
  lineColor={74,84,154}, 
  extent={{-378,152},{378,160}}, 
  textString="%name", 
  fontSize=16, 
  textStyle={TextStyle.Bold}, 
  textColor={74,84,154}, 
  horizontalAlignment=TextAlignment.Left), 
  stateText=Text(origin={0,0}, 
  lineColor={74,84,154}, 
  extent={{-378,-160},{378,152}}, 
  textString="%algorithm", 
  fontSize=16, 
  textColor={74,84,154}, 
  horizontalAlignment=TextAlignment.Left, 
  verticalAlignment=TextAlignment.Top), 
  stateLine = Line(origin={0,0}, 
  color = {74, 84, 154}, 
  points={{-40,22},{40,22}}))}),Protection(access=Access.diagram));
      block State1 "状态"
        annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
         Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
           grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
           lineColor = {74, 84, 154}, 
           fillColor = {255, 255, 255}, 
           lineThickness = 1, 
           extent = {{-100, 100}, {100, -100}}, 
           radius = 11), Line(origin = {0, 80}, 
           points = {{-100, 0}, {100, 0}}, 
           color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
           lineColor = {0, 0, 128}, 
           extent = {{-100, 10}, {100, -10}}, 
           textString = "%name", 
           textStyle = {TextStyle.None}, 
           textColor = {0, 0, 128}), Text(origin = {0, -10}, 
           lineColor = {0, 0, 128}, 
           extent = {{-100, 90}, {100, -90}}, 
           textString = "algorithm", 
           fontSize = 16, 
           textStyle = {TextStyle.None}, 
           textColor = {0, 0, 128}, 
           horizontalAlignment = TextAlignment.Left, 
           verticalAlignment = TextAlignment.Top)}), 
         Diagram(coordinateSystem(extent={{-166,-92},{166,92}}, 
      initialScale=1, 
      grid={2,2}),graphics = {State(origin={0,0}, 
      stateTitle=Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{-164,84},{164,92}}, 
      textString="%name", 
      fontSize=16, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left), 
      stateText=Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{-164,-92},{164,84}}, 
      textString="%algorithm", 
      fontSize=16, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left, 
      verticalAlignment=TextAlignment.Top))}),Protection(access=Access.diagram));
        block State "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
             grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
             lineColor = {74, 84, 154}, 
             fillColor = {255, 255, 255}, 
             lineThickness = 1, 
             extent = {{-100, 100}, {100, -100}}, 
             radius = 11), Line(origin = {0, 80}, 
             points = {{-100, 0}, {100, 0}}, 
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 10}, {100, -10}}, 
             textString = "%name", 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}), Text(origin = {0, -10}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 90}, {100, -90}}, 
             textString = "algorithm", 
             fontSize = 16, 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}, 
             horizontalAlignment = TextAlignment.Left, 
             verticalAlignment = TextAlignment.Top)}), 
           Diagram(coordinateSystem(extent={{-24,-19.5},{24,19.5}}, 
      initialScale=1, 
      grid={2,2}),graphics = {State(origin={0,0}, 
      stateTitle=Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{-22,11.5},{22,19.5}}, 
      textString="%name", 
      fontSize=16, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left), 
      stateText=Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{-22,-19.5},{22,11.5}}, 
      textString="%algorithm", 
      fontSize=16, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left, 
      verticalAlignment=TextAlignment.Top), 
      stateLine = Line(origin={0,0}, 
      color = {74, 84, 154}, 
      points={{-40,22},{40,22}}))}),Protection(access=Access.diagram));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  steer := 0;
        end State;
        State ini_state 
          annotation (Placement(transformation(origin={-84,50}, 
      extent={{-24,-19.5},{24,19.5}})),__MWORKS(BlockSystem(StateMachine)));
        State1 turn_right 
          annotation (Placement(transformation(origin={97,-44}, 
      extent={{-53,-20},{53,20}})),__MWORKS(BlockSystem(StateMachine)));
        State2 turn_left 
          annotation (Placement(transformation(origin={-81,-46}, 
      extent={{-51,-20},{51,20}})),__MWORKS(BlockSystem(StateMachine)));
        State3 state 
          annotation (Placement(transformation(origin={90,52}, 
      extent={{-27,-20},{27,20}})),__MWORKS(BlockSystem(StateMachine)));
        block State1 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
             grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
             lineColor = {74, 84, 154}, 
             fillColor = {255, 255, 255}, 
             lineThickness = 1, 
             extent = {{-100, 100}, {100, -100}}, 
             radius = 11), Line(origin = {0, 80}, 
             points = {{-100, 0}, {100, 0}}, 
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 10}, {100, -10}}, 
             textString = "%name", 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}), Text(origin = {0, -10}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 90}, {100, -90}}, 
             textString = "algorithm", 
             fontSize = 16, 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}, 
             horizontalAlignment = TextAlignment.Left, 
             verticalAlignment = TextAlignment.Top)}), 
           Diagram(coordinateSystem(extent={{-53,-20},{53,20}}, 
      initialScale=1, 
      grid={2,2}),graphics = {State(origin={0,0}, 
      stateTitle=Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{-51,12},{51,20}}, 
      textString="%name", 
      fontSize=16, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left), 
      stateText=Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{-51,-20},{51,12}}, 
      textString="%algorithm", 
      fontSize=16, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left, 
      verticalAlignment=TextAlignment.Top), 
      stateLine = Line(origin={0,0}, 
      color = {74, 84, 154}, 
      points={{-40,22},{40,22}}))}),Protection(access=Access.diagram));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));steer := -2 * (1 / dr + 0.1) * abs(dl - dr);
        end State1;
        block State2 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
             grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
             lineColor = {74, 84, 154}, 
             fillColor = {255, 255, 255}, 
             lineThickness = 1, 
             extent = {{-100, 100}, {100, -100}}, 
             radius = 11), Line(origin = {0, 80}, 
             points = {{-100, 0}, {100, 0}}, 
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 10}, {100, -10}}, 
             textString = "%name", 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}), Text(origin = {0, -10}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 90}, {100, -90}}, 
             textString = "algorithm", 
             fontSize = 16, 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}, 
             horizontalAlignment = TextAlignment.Left, 
             verticalAlignment = TextAlignment.Top)}), 
           Diagram(coordinateSystem(extent={{-51,-20},{51,20}}, 
      initialScale=1, 
      grid={2,2}),graphics = {State(origin={0,0}, 
      stateTitle=Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{-49,12},{49,20}}, 
      textString="%name", 
      fontSize=16, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left), 
      stateText=Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{-49,-20},{49,12}}, 
      textString="%algorithm", 
      fontSize=16, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left, 
      verticalAlignment=TextAlignment.Top), 
      stateLine = Line(origin={0,0}, 
      color = {74, 84, 154}, 
      points={{-40,22},{40,22}}))}),Protection(access=Access.diagram));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));steer:=2 * (1 / dl + 0.1) * abs(dl - dr);
        end State2;
        block State3 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
             grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
             lineColor = {74, 84, 154}, 
             fillColor = {255, 255, 255}, 
             lineThickness = 1, 
             extent = {{-100, 100}, {100, -100}}, 
             radius = 11), Line(origin = {0, 80}, 
             points = {{-100, 0}, {100, 0}}, 
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 10}, {100, -10}}, 
             textString = "%name", 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}), Text(origin = {0, -10}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 90}, {100, -90}}, 
             textString = "algorithm", 
             fontSize = 16, 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}, 
             horizontalAlignment = TextAlignment.Left, 
             verticalAlignment = TextAlignment.Top)}), 
           Diagram(coordinateSystem(extent={{-27,-20},{27,20}}, 
      initialScale=1, 
      grid={2,2}),graphics = {State(origin={0,0}, 
      stateTitle=Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{-25,12},{25,20}}, 
      textString="%name", 
      fontSize=16, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left), 
      stateText=Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{-25,-20},{25,12}}, 
      textString="%algorithm", 
      fontSize=16, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left, 
      verticalAlignment=TextAlignment.Top), 
      stateLine = Line(origin={0,0}, 
      color = {74, 84, 154}, 
      points={{-40,22},{40,22}}))}),Protection(access=Access.diagram));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  steer := 0;
        end State3;
      equation
        initialState(ini_state, true, 1) 
        annotation(Line(origin={-463.974,-233.67302}, 
        points={{0,4.82698},{0,-4.82698}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={0,0}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}), displayText = "[true]");
        transition(state, turn_left, dl > dr, reset = false, priority = 2) 
        annotation(Line(origin={-381.116,-305}, 
        points={{69.2926,29},{-69.2926,-29}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={-20.8847,-6.67848}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[dl > dr]");
        transition(turn_left, state, dl == dr, reset = false) 
        annotation(Line(origin={-419.705,-278.019}, 
        points={{-49.8096,-55.981},{102.705,3.08569}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={0,0}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[dl == dr]");
        transition(turn_left, turn_right, dl < dr, reset = false, priority = 2) 
        annotation(Line(origin={-373,-344.509}, 
        points={{-37,0},{37,0}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={-7.65869,5.74401}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[dl < dr]");
        transition(state, turn_right, dr > dl, reset = false) 
        annotation(Line(origin={-302.1284,-304}, 
        points={{0,28},{0,-28}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={5.60665,3.96939}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[dr > dl]");
        transition(turn_right, state, dr == dl, reset = false, priority = 2) 
        annotation(Line(origin={-315.246,-304}, 
        points={{-8.55464,-28},{8.55464,28}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={-23.2496,-7.65869}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[dr == dl]");
        transition(turn_right, turn_left, dr < dl, reset = false) 
        annotation(Line(origin={-373,-359.194}, 
        points={{37,0},{-37,0}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={-5.74401,-4.10287}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[dr < dl]");
        transition(ini_state, state, after(1,sec), reset = false) 
        annotation(Line(origin={-378.5,-253.214}, 
        points={{-61.5,0},{61.5,0}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={-4.27732,4.56247}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[after(1,sec)]");
      end State1;
      State1 curise_lateral 
      annotation(Placement(transformation(origin={-178,-32}, 
  extent={{-166,-92},{166,92}})),__MWORKS(BlockSystem(StateMachine)));
      State2 avoid_lateral 
        annotation (Placement(transformation(origin={178,-30}, 
  extent={{-168,-92},{168,92}})),__MWORKS(BlockSystem(StateMachine)));
      block State2 "状态"
        annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state, SampleTime(auto = true)),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
         Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
           grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
           lineColor = {74, 84, 154}, 
           fillColor = {255, 255, 255}, 
           lineThickness = 1, 
           extent = {{-100, 100}, {100, -100}}, 
           radius = 11), Line(origin = {0, 80}, 
           points = {{-100, 0}, {100, 0}}, 
           color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
           lineColor = {0, 0, 128}, 
           extent = {{-100, 10}, {100, -10}}, 
           textString = "%name", 
           textStyle = {TextStyle.None}, 
           textColor = {0, 0, 128}), Text(origin = {0, -10}, 
           lineColor = {0, 0, 128}, 
           extent = {{-100, 90}, {100, -90}}, 
           textString = "algorithm", 
           fontSize = 16, 
           textStyle = {TextStyle.None}, 
           textColor = {0, 0, 128}, 
           horizontalAlignment = TextAlignment.Left, 
           verticalAlignment = TextAlignment.Top)}), 
         Diagram(coordinateSystem(extent={{-168,-92},{168,92}}, 
  initialScale=1, 
  grid={2,2}),graphics = {State(origin={0,0}, 
  stateTitle=Text(origin={0,0}, 
  lineColor={74,84,154}, 
  extent={{-166,84},{166,92}}, 
  textString="%name", 
  fontSize=16, 
  textStyle={TextStyle.Bold}, 
  textColor={74,84,154}, 
  horizontalAlignment=TextAlignment.Left), 
  stateText=Text(origin={0,0}, 
  lineColor={74,84,154}, 
  extent={{-166,-92},{166,84}}, 
  textString="%algorithm", 
  fontSize=16, 
  textColor={74,84,154}, 
  horizontalAlignment=TextAlignment.Left, 
  verticalAlignment=TextAlignment.Top), 
  stateLine = Line(origin={0,0}, 
  color = {74, 84, 154}, 
  points={{-40,22},{40,22}}))}),Protection(access=Access.diagram));
        block State "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
             grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
             lineColor = {74, 84, 154}, 
             fillColor = {255, 255, 255}, 
             lineThickness = 1, 
             extent = {{-100, 100}, {100, -100}}, 
             radius = 11), Line(origin = {0, 80}, 
             points = {{-100, 0}, {100, 0}}, 
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 10}, {100, -10}}, 
             textString = "%name", 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}), Text(origin = {0, -10}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 90}, {100, -90}}, 
             textString = "algorithm", 
             fontSize = 16, 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}, 
             horizontalAlignment = TextAlignment.Left, 
             verticalAlignment = TextAlignment.Top)}), 
           Diagram(coordinateSystem(extent={{-35,-27},{35,27}}, 
  initialScale=1, 
  grid={2,2}),graphics = {State(origin={0,0}, 
  stateTitle=Text(origin={0,0}, 
  lineColor={74,84,154}, 
  extent={{-33,19},{33,27}}, 
  textString="%name", 
  fontSize=16, 
  textStyle={TextStyle.Bold}, 
  textColor={74,84,154}, 
  horizontalAlignment=TextAlignment.Left), 
  stateText=Text(origin={0,0}, 
  lineColor={74,84,154}, 
  extent={{-33,-27},{33,19}}, 
  textString="%algorithm", 
  fontSize=16, 
  textColor={74,84,154}, 
  horizontalAlignment=TextAlignment.Left, 
  verticalAlignment=TextAlignment.Top))}),Protection(access=Access.diagram));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));    steer := 0.6;
        end State;
        State ini_state 
          annotation (Placement(transformation(origin={-117,27}, 
  extent={{-35,-27},{35,27}})),__MWORKS(BlockSystem(StateMachine)));
        State4 turn_left 
        annotation(Placement(transformation(origin={-98,-46}, 
  extent={{-51,-20},{51,20}})),__MWORKS(BlockSystem(StateMachine)));
        State1 turn_right 
        annotation(Placement(transformation(origin={69,-46}, 
  extent={{-53,-20},{53,20}})),__MWORKS(BlockSystem(StateMachine)));
        State2 state 
          annotation (Placement(transformation(origin={42,36}, 
  extent={{-30,-18},{30,18}})),__MWORKS(BlockSystem(StateMachine)));
        block State4 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
             grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
             lineColor = {74, 84, 154}, 
             fillColor = {255, 255, 255}, 
             lineThickness = 1, 
             extent = {{-100, 100}, {100, -100}}, 
             radius = 11), Line(origin = {0, 80}, 
             points = {{-100, 0}, {100, 0}}, 
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 10}, {100, -10}}, 
             textString = "%name", 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}), Text(origin = {0, -10}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 90}, {100, -90}}, 
             textString = "algorithm", 
             fontSize = 16, 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}, 
             horizontalAlignment = TextAlignment.Left, 
             verticalAlignment = TextAlignment.Top)}), 
           Diagram(coordinateSystem(extent={{-51,-20},{51,20}}, 
          initialScale=1, 
          grid={2,2}),graphics = {State(origin={0,0}, 
          stateTitle=Text(origin={0,0}, 
          lineColor={74,84,154}, 
          extent={{-49,12},{49,20}}, 
          textString="%name", 
          fontSize=16, 
          textStyle={TextStyle.Bold}, 
          textColor={74,84,154}, 
          horizontalAlignment=TextAlignment.Left), 
          stateText=Text(origin={0,0}, 
          lineColor={74,84,154}, 
          extent={{-49,-20},{49,12}}, 
          textString="%algorithm", 
          fontSize=16, 
          textColor={74,84,154}, 
          horizontalAlignment=TextAlignment.Left, 
          verticalAlignment=TextAlignment.Top), 
          stateLine = Line(origin={0,0}, 
          color = {74, 84, 154}, 
          points={{-40,22},{40,22}}))}),Protection(access=Access.diagram));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  steer := 2 * (1 / dl + 0.1) * abs(dl - dr);
        end State4;
        block State1 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
             grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
             lineColor = {74, 84, 154}, 
             fillColor = {255, 255, 255}, 
             lineThickness = 1, 
             extent = {{-100, 100}, {100, -100}}, 
             radius = 11), Line(origin = {0, 80}, 
             points = {{-100, 0}, {100, 0}}, 
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 10}, {100, -10}}, 
             textString = "%name", 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}), Text(origin = {0, -10}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 90}, {100, -90}}, 
             textString = "algorithm", 
             fontSize = 16, 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}, 
             horizontalAlignment = TextAlignment.Left, 
             verticalAlignment = TextAlignment.Top)}), 
           Diagram(coordinateSystem(extent={{-53,-20},{53,20}}, 
          initialScale=1, 
          grid={2,2}),graphics = {State(origin={0,0}, 
          stateTitle=Text(origin={0,0}, 
          lineColor={74,84,154}, 
          extent={{-51,12},{51,20}}, 
          textString="%name", 
          fontSize=16, 
          textStyle={TextStyle.Bold}, 
          textColor={74,84,154}, 
          horizontalAlignment=TextAlignment.Left), 
          stateText=Text(origin={0,0}, 
          lineColor={74,84,154}, 
          extent={{-51,-20},{51,12}}, 
          textString="%algorithm", 
          fontSize=16, 
          textColor={74,84,154}, 
          horizontalAlignment=TextAlignment.Left, 
          verticalAlignment=TextAlignment.Top), 
          stateLine = Line(origin={0,0}, 
          color = {74, 84, 154}, 
          points={{-40,22},{40,22}}))}),Protection(access=Access.diagram));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  steer := -2 * (1 / dr + 0.1) * abs(dl - dr);
        end State1;
        block State2 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state", 
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}}, 
             grid={2, 2}), graphics={Rectangle(origin = {0, 0}, 
             lineColor = {74, 84, 154}, 
             fillColor = {255, 255, 255}, 
             lineThickness = 1, 
             extent = {{-100, 100}, {100, -100}}, 
             radius = 11), Line(origin = {0, 80}, 
             points = {{-100, 0}, {100, 0}}, 
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 10}, {100, -10}}, 
             textString = "%name", 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}), Text(origin = {0, -10}, 
             lineColor = {0, 0, 128}, 
             extent = {{-100, 90}, {100, -90}}, 
             textString = "algorithm", 
             fontSize = 16, 
             textStyle = {TextStyle.None}, 
             textColor = {0, 0, 128}, 
             horizontalAlignment = TextAlignment.Left, 
             verticalAlignment = TextAlignment.Top)}), 
           Diagram(coordinateSystem(extent={{-30,-18},{30,18}}, 
  initialScale=1, 
  grid={2,2}),graphics = {State(origin={0,0}, 
  stateTitle=Text(origin={0,0}, 
  lineColor={74,84,154}, 
  extent={{-28,10},{28,18}}, 
  textString="%name", 
  fontSize=16, 
  textStyle={TextStyle.Bold}, 
  textColor={74,84,154}, 
  horizontalAlignment=TextAlignment.Left), 
  stateText=Text(origin={0,0}, 
  lineColor={74,84,154}, 
  extent={{-28,-18},{28,10}}, 
  textString="%algorithm", 
  fontSize=16, 
  textColor={74,84,154}, 
  horizontalAlignment=TextAlignment.Left, 
  verticalAlignment=TextAlignment.Top), 
  stateLine = Line(origin={0,0}, 
  color = {74, 84, 154}, 
  points={{-40,22},{40,22}}))}),Protection(access=Access.diagram));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));steer := 0;
        end State2;
      equation
        initialState(ini_state, true, 1) 
        annotation(Line(origin={-140,-242}, 
        points={{0,10},{0,-10}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={0,0}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}), displayText = "[true]");
        transition(state, turn_left, dl > dr, reset = false, priority = 2) 
        annotation(Line(origin={-55.9657,-310}, 
        points={{50.0714,22},{-50.0714,-22}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={4.33326,0.180553}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[dl > dr]");
        transition(state, turn_right, dr > dl, reset = false) 
        annotation(Line(origin={24.9,-310}, 
        points={{14.2431,22},{-14.2431,-22}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={0,0}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[dr > dl]");
        transition(turn_left, turn_right, dr > dl, reset = false) 
        annotation(Line(origin={-39.5,-346.57}, 
        points={{-31.5,0},{31.5,0}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={-6.05957,4.61682}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[dr > dl]");
        transition(turn_right, turn_left, dl > dr, reset = false) 
        annotation(Line(origin={-39.5,-361.574}, 
        points={{31.5,0},{-31.5,0}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={-5.77102,-4.61682}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[dl > dr]");
        transition(ini_state, state, after(2,sec), reset = false) 
        annotation(Line(origin={-59,-268.492}, 
        points={{-47,0},{47,0}}, 
        color={113,119,170}, 
        smooth=Smooth.Bezier),Text(origin={-5.45426,4.56636}, 
        lineColor={74,84,154}, 
        extent={{0,-3},{0,3}}, 
        textString="%condition", 
        fontSize=10, 
        textStyle={TextStyle.Bold}, 
        textColor={74,84,154}, 
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[after(2,sec)]");
      end State2;
    equation
      transition(avoid_lateral, curise_lateral, not flag, reset = false) 
      annotation(Line(origin={-204.363,-181.749}, 
      points={{69.2947,-32.251},{-1.28162,-0.021717},{-68.5683,-34.251}}, 
      color={113,119,170}, 
      smooth=Smooth.Bezier),Text(origin={-7.15991,7.15991}, 
      lineColor={74,84,154}, 
      extent={{0,-3},{0,3}}, 
      textString="%condition", 
      fontSize=10, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[not flag]");
      transition(curise_lateral, avoid_lateral, flag, reset = false) 
      annotation(Line(origin={-204,-199.0168}, 
      points={{-30.9664,-16.9832},{30.9664,-14.9832}}, 
      color={113,119,170}, 
      smooth=Smooth.Bezier),Text(origin={0,0}, 
      lineColor={74,84,154}, 
      extent={{0,-3},{0,3}}, 
      textString="%condition", 
      fontSize=10, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}, 
      horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[flag]");
      initialState(curise_lateral, true, 1) 
      annotation(Line(origin={-415.907,-204.981}, 
      points={{0.0362665,14.1629},{-7.7894e-5,1.08245},{0.0362665,-11.0189}}, 
      color={113,119,170}, 
      smooth=Smooth.Bezier),Text(origin={-12.7065,1.36141}, 
      lineColor={74,84,154}, 
      extent={{0,-3},{0,3}}, 
      textString="%condition", 
      fontSize=10, 
      textStyle={TextStyle.Bold}, 
      textColor={74,84,154}), displayText = "[true]");
    end State2;
    equation
    end Chart;
  model ModelWorkspace
    annotation(__MWORKS(hide = true,BlockSystem(blockKind=BlockKind.modelWorkspace)),Protection(access=Access.diagram));
  end ModelWorkspace;
equation
  connect(front_dist, abs1.u) 
  annotation(Line(origin={-71,36}, 
points={{-53,22},{-38.8,22}}, 
color={0,0,0}));
  connect(chart.speed, speed) 
  annotation(Line(origin={85,26}, 
points={{-72.2,-18.5},{-59,-18.5},{-59,32},{81,32}}, 
color={0,0,0}));
  connect(steer, sum1.y) 
  annotation(Line(origin={105,-58}, 
points={{61,0},{51,0},{51,86},{46.8,86}}, 
color={0,0,0}));
  connect(chart.steer, sum1.u1) 
  annotation(Line(origin={45,-37}, 
points={{-32.2,15.5},{-13,15.5},{-13,70},{83.2,70}}, 
color={0,0,0}));
  connect(constant1.y, sum2.u2) 
  annotation(Line(origin={9,-98}, 
points={{3.8,40},{21,40},{21,66.5},{31.2,66.5}}, 
color={0,0,0}));
  connect(chart.steer, sum2.u1) 
  annotation(Line(origin={16,-49}, 
points={{-3.2,27.5},{24.2,27.5}}, 
color={0,0,0}),__MWORKS(BlockSystem(NamedSignal)));
  connect(constant2.y, product1.u2) 
  annotation(Line(origin={41,-81}, 
points={{22.8,23},{33,23},{33,44.5},{41.2,44.5}}, 
color={0,0,0}));
  connect(sum2.y, product1.u1) 
  annotation(Line(origin={59,-45}, 
points={{4.8,18.5},{23.2,18.5}}, 
color={0,0,0}),__MWORKS(BlockSystem(NamedSignal)));
  connect(product1.y, roundingFunction.u) 
  annotation(Line(origin={77,-8}, 
points={{28.8,-23.5},{35,-23.5},{35,0},{-35,0},{-35,24},{-26.8,24}}, 
color={0,0,0}));
  connect(roundingFunction.y, gain.u) 
  annotation(Line(origin={78,16}, 
  points={{-4.2,0},{4.2,0}}, 
  color={0,0,0}));
  connect(gain.y, sum1.u2) 
  annotation(Line(origin={117,20}, 
points={{-11.2,-4},{-4.1,-4},{-4.1,3},{11.2,3}}, 
color={0,0,0}));
  connect(abs1.y, chart.df) 
  annotation(Line(origin={-49,42}, 
points={{-37.2,16},{-11,16},{-11,-27.25},{0.2,-27.25}}, 
color={0,0,0}));
  connect(rear_dist, abs2.u) 
  annotation(Line(origin={-117,16}, 
  points={{-7,0},{7.2,0}}, 
  color={0,0,0}));
  connect(abs2.y, chart.db) 
  annotation(Line(origin={-67,8}, 
  points={{-19.2,8},{-11,8},{-11,-7.75},{18.2,-7.75}}, 
  color={0,0,0}));
  connect(left_dist, abs3.u) 
  annotation(Line(origin={-117,-26}, 
  points={{-7,0},{7.2,0}}, 
  color={0,0,0}));
  connect(abs3.y, chart.dl) 
  annotation(Line(origin={-67,-20}, 
  points={{-19.2,-6},{-11,-6},{-11,5.75},{18.2,5.75}}, 
  color={0,0,0}));
  connect(right_dist, abs4.u) 
  annotation(Line(origin={-117,-68}, 
  points={{-7,0},{7.2,0}}, 
  color={0,0,0}));
  connect(abs4.y, chart.dr) 
  annotation(Line(origin={-67,-48}, 
  points={{-19.2,-20},{-1,-20},{-1,19.25},{18.2,19.25}}, 
  color={0,0,0}));
  end ObsAvoidController_Sysblock2;