// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/datatypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABVersionGetter creates a new instance of MockMATLABVersionGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABVersionGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABVersionGetter {
	mock := &MockMATLABVersionGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABVersionGetter is an autogenerated mock type for the MATLABVersionGetter type
type MockMATLABVersionGetter struct {
	mock.Mock
}

type MockMATLABVersionGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABVersionGetter) EXPECT() *MockMATLABVersionGetter_Expecter {
	return &MockMATLABVersionGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockMATLABVersionGetter
func (_mock *MockMATLABVersionGetter) Get(matlabRootLocation string) (datatypes.MatlabVersionInfo, error) {
	ret := _mock.Called(matlabRootLocation)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 datatypes.MatlabVersionInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (datatypes.MatlabVersionInfo, error)); ok {
		return returnFunc(matlabRootLocation)
	}
	if returnFunc, ok := ret.Get(0).(func(string) datatypes.MatlabVersionInfo); ok {
		r0 = returnFunc(matlabRootLocation)
	} else {
		r0 = ret.Get(0).(datatypes.MatlabVersionInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(matlabRootLocation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABVersionGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMATLABVersionGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - matlabRootLocation string
func (_e *MockMATLABVersionGetter_Expecter) Get(matlabRootLocation interface{}) *MockMATLABVersionGetter_Get_Call {
	return &MockMATLABVersionGetter_Get_Call{Call: _e.mock.On("Get", matlabRootLocation)}
}

func (_c *MockMATLABVersionGetter_Get_Call) Run(run func(matlabRootLocation string)) *MockMATLABVersionGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABVersionGetter_Get_Call) Return(matlabVersionInfo datatypes.MatlabVersionInfo, err error) *MockMATLABVersionGetter_Get_Call {
	_c.Call.Return(matlabVersionInfo, err)
	return _c
}

func (_c *MockMATLABVersionGetter_Get_Call) RunAndReturn(run func(matlabRootLocation string) (datatypes.MatlabVersionInfo, error)) *MockMATLABVersionGetter_Get_Call {
	_c.Call.Return(run)
	return _c
}
