// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABRootGetter creates a new instance of MockMATLABRootGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABRootGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABRootGetter {
	mock := &MockMATLABRootGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABRootGetter is an autogenerated mock type for the MATLABRootGetter type
type MockMATLABRootGetter struct {
	mock.Mock
}

type MockMATLABRootGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABRootGetter) EXPECT() *MockMATLABRootGetter_Expecter {
	return &MockMATLABRootGetter_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockMATLABRootGetter
func (_mock *MockMATLABRootGetter) GetAll(logger entities.Logger) []string {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) []string); ok {
		r0 = returnFunc(logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockMATLABRootGetter_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockMATLABRootGetter_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockMATLABRootGetter_Expecter) GetAll(logger interface{}) *MockMATLABRootGetter_GetAll_Call {
	return &MockMATLABRootGetter_GetAll_Call{Call: _e.mock.On("GetAll", logger)}
}

func (_c *MockMATLABRootGetter_GetAll_Call) Run(run func(logger entities.Logger)) *MockMATLABRootGetter_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABRootGetter_GetAll_Call) Return(strings []string) *MockMATLABRootGetter_GetAll_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockMATLABRootGetter_GetAll_Call) RunAndReturn(run func(logger entities.Logger) []string) *MockMATLABRootGetter_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
