// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/facades/registryfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistryLayer creates a new instance of MockRegistryLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryLayer {
	mock := &MockRegistryLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistryLayer is an autogenerated mock type for the RegistryLayer type
type MockRegistryLayer struct {
	mock.Mock
}

type MockRegistryLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistryLayer) EXPECT() *MockRegistryLayer_Expecter {
	return &MockRegistryLayer_Expecter{mock: &_m.Mock}
}

// OpenKey provides a mock function for the type MockRegistryLayer
func (_mock *MockRegistryLayer) OpenKey(k uintptr, path string, access uint32) (registryfacade.RegistryKey, error) {
	ret := _mock.Called(k, path, access)

	if len(ret) == 0 {
		panic("no return value specified for OpenKey")
	}

	var r0 registryfacade.RegistryKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uintptr, string, uint32) (registryfacade.RegistryKey, error)); ok {
		return returnFunc(k, path, access)
	}
	if returnFunc, ok := ret.Get(0).(func(uintptr, string, uint32) registryfacade.RegistryKey); ok {
		r0 = returnFunc(k, path, access)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(registryfacade.RegistryKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uintptr, string, uint32) error); ok {
		r1 = returnFunc(k, path, access)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistryLayer_OpenKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenKey'
type MockRegistryLayer_OpenKey_Call struct {
	*mock.Call
}

// OpenKey is a helper method to define mock.On call
//   - k uintptr
//   - path string
//   - access uint32
func (_e *MockRegistryLayer_Expecter) OpenKey(k interface{}, path interface{}, access interface{}) *MockRegistryLayer_OpenKey_Call {
	return &MockRegistryLayer_OpenKey_Call{Call: _e.mock.On("OpenKey", k, path, access)}
}

func (_c *MockRegistryLayer_OpenKey_Call) Run(run func(k uintptr, path string, access uint32)) *MockRegistryLayer_OpenKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uintptr
		if args[0] != nil {
			arg0 = args[0].(uintptr)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRegistryLayer_OpenKey_Call) Return(registryKey registryfacade.RegistryKey, err error) *MockRegistryLayer_OpenKey_Call {
	_c.Call.Return(registryKey, err)
	return _c
}

func (_c *MockRegistryLayer_OpenKey_Call) RunAndReturn(run func(k uintptr, path string, access uint32) (registryfacade.RegistryKey, error)) *MockRegistryLayer_OpenKey_Call {
	_c.Call.Return(run)
	return _c
}
