// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVersionOSLayer creates a new instance of MockVersionOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionOSLayer {
	mock := &MockVersionOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVersionOSLayer is an autogenerated mock type for the VersionOSLayer type
type MockVersionOSLayer struct {
	mock.Mock
}

type MockVersionOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionOSLayer) EXPECT() *MockVersionOSLayer_Expecter {
	return &MockVersionOSLayer_Expecter{mock: &_m.Mock}
}

// Command provides a mock function for the type MockVersionOSLayer
func (_mock *MockVersionOSLayer) Command(name string, arg ...string) osfacade.Cmd {
	var tmpRet mock.Arguments
	if len(arg) > 0 {
		tmpRet = _mock.Called(name, arg)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Command")
	}

	var r0 osfacade.Cmd
	if returnFunc, ok := ret.Get(0).(func(string, ...string) osfacade.Cmd); ok {
		r0 = returnFunc(name, arg...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.Cmd)
		}
	}
	return r0
}

// MockVersionOSLayer_Command_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Command'
type MockVersionOSLayer_Command_Call struct {
	*mock.Call
}

// Command is a helper method to define mock.On call
//   - name string
//   - arg ...string
func (_e *MockVersionOSLayer_Expecter) Command(name interface{}, arg ...interface{}) *MockVersionOSLayer_Command_Call {
	return &MockVersionOSLayer_Command_Call{Call: _e.mock.On("Command",
		append([]interface{}{name}, arg...)...)}
}

func (_c *MockVersionOSLayer_Command_Call) Run(run func(name string, arg ...string)) *MockVersionOSLayer_Command_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockVersionOSLayer_Command_Call) Return(cmd osfacade.Cmd) *MockVersionOSLayer_Command_Call {
	_c.Call.Return(cmd)
	return _c
}

func (_c *MockVersionOSLayer_Command_Call) RunAndReturn(run func(name string, arg ...string) osfacade.Cmd) *MockVersionOSLayer_Command_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockVersionOSLayer
func (_mock *MockVersionOSLayer) Open(path string) (osfacade.File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 osfacade.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (osfacade.File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) osfacade.File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionOSLayer_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockVersionOSLayer_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - path string
func (_e *MockVersionOSLayer_Expecter) Open(path interface{}) *MockVersionOSLayer_Open_Call {
	return &MockVersionOSLayer_Open_Call{Call: _e.mock.On("Open", path)}
}

func (_c *MockVersionOSLayer_Open_Call) Run(run func(path string)) *MockVersionOSLayer_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionOSLayer_Open_Call) Return(file osfacade.File, err error) *MockVersionOSLayer_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockVersionOSLayer_Open_Call) RunAndReturn(run func(path string) (osfacade.File, error)) *MockVersionOSLayer_Open_Call {
	_c.Call.Return(run)
	return _c
}
