// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"
	"syscall"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCmd creates a new instance of MockCmd. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCmd(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCmd {
	mock := &MockCmd{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCmd is an autogenerated mock type for the Cmd type
type MockCmd struct {
	mock.Mock
}

type MockCmd_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCmd) EXPECT() *MockCmd_Expecter {
	return &MockCmd_Expecter{mock: &_m.Mock}
}

// Output provides a mock function for the type MockCmd
func (_mock *MockCmd) Output() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCmd_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type MockCmd_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
func (_e *MockCmd_Expecter) Output() *MockCmd_Output_Call {
	return &MockCmd_Output_Call{Call: _e.mock.On("Output")}
}

func (_c *MockCmd_Output_Call) Run(run func()) *MockCmd_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_Output_Call) Return(bytes []byte, err error) *MockCmd_Output_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockCmd_Output_Call) RunAndReturn(run func() ([]byte, error)) *MockCmd_Output_Call {
	_c.Call.Return(run)
	return _c
}

// SetSysProcAttr provides a mock function for the type MockCmd
func (_mock *MockCmd) SetSysProcAttr(attr *syscall.SysProcAttr) {
	_mock.Called(attr)
	return
}

// MockCmd_SetSysProcAttr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSysProcAttr'
type MockCmd_SetSysProcAttr_Call struct {
	*mock.Call
}

// SetSysProcAttr is a helper method to define mock.On call
//   - attr *syscall.SysProcAttr
func (_e *MockCmd_Expecter) SetSysProcAttr(attr interface{}) *MockCmd_SetSysProcAttr_Call {
	return &MockCmd_SetSysProcAttr_Call{Call: _e.mock.On("SetSysProcAttr", attr)}
}

func (_c *MockCmd_SetSysProcAttr_Call) Run(run func(attr *syscall.SysProcAttr)) *MockCmd_SetSysProcAttr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *syscall.SysProcAttr
		if args[0] != nil {
			arg0 = args[0].(*syscall.SysProcAttr)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCmd_SetSysProcAttr_Call) Return() *MockCmd_SetSysProcAttr_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCmd_SetSysProcAttr_Call) RunAndReturn(run func(attr *syscall.SysProcAttr)) *MockCmd_SetSysProcAttr_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockCmd
func (_mock *MockCmd) Start() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCmd_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockCmd_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockCmd_Expecter) Start() *MockCmd_Start_Call {
	return &MockCmd_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockCmd_Start_Call) Run(run func()) *MockCmd_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_Start_Call) Return(err error) *MockCmd_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCmd_Start_Call) RunAndReturn(run func() error) *MockCmd_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StderrPipe provides a mock function for the type MockCmd
func (_mock *MockCmd) StderrPipe() (io.Reader, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StderrPipe")
	}

	var r0 io.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (io.Reader, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCmd_StderrPipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StderrPipe'
type MockCmd_StderrPipe_Call struct {
	*mock.Call
}

// StderrPipe is a helper method to define mock.On call
func (_e *MockCmd_Expecter) StderrPipe() *MockCmd_StderrPipe_Call {
	return &MockCmd_StderrPipe_Call{Call: _e.mock.On("StderrPipe")}
}

func (_c *MockCmd_StderrPipe_Call) Run(run func()) *MockCmd_StderrPipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_StderrPipe_Call) Return(reader io.Reader, err error) *MockCmd_StderrPipe_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *MockCmd_StderrPipe_Call) RunAndReturn(run func() (io.Reader, error)) *MockCmd_StderrPipe_Call {
	_c.Call.Return(run)
	return _c
}

// StdinPipe provides a mock function for the type MockCmd
func (_mock *MockCmd) StdinPipe() (io.Writer, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StdinPipe")
	}

	var r0 io.Writer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (io.Writer, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCmd_StdinPipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StdinPipe'
type MockCmd_StdinPipe_Call struct {
	*mock.Call
}

// StdinPipe is a helper method to define mock.On call
func (_e *MockCmd_Expecter) StdinPipe() *MockCmd_StdinPipe_Call {
	return &MockCmd_StdinPipe_Call{Call: _e.mock.On("StdinPipe")}
}

func (_c *MockCmd_StdinPipe_Call) Run(run func()) *MockCmd_StdinPipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_StdinPipe_Call) Return(writer io.Writer, err error) *MockCmd_StdinPipe_Call {
	_c.Call.Return(writer, err)
	return _c
}

func (_c *MockCmd_StdinPipe_Call) RunAndReturn(run func() (io.Writer, error)) *MockCmd_StdinPipe_Call {
	_c.Call.Return(run)
	return _c
}

// StdoutPipe provides a mock function for the type MockCmd
func (_mock *MockCmd) StdoutPipe() (io.Reader, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StdoutPipe")
	}

	var r0 io.Reader
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (io.Reader, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() io.Reader); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCmd_StdoutPipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StdoutPipe'
type MockCmd_StdoutPipe_Call struct {
	*mock.Call
}

// StdoutPipe is a helper method to define mock.On call
func (_e *MockCmd_Expecter) StdoutPipe() *MockCmd_StdoutPipe_Call {
	return &MockCmd_StdoutPipe_Call{Call: _e.mock.On("StdoutPipe")}
}

func (_c *MockCmd_StdoutPipe_Call) Run(run func()) *MockCmd_StdoutPipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCmd_StdoutPipe_Call) Return(reader io.Reader, err error) *MockCmd_StdoutPipe_Call {
	_c.Call.Return(reader, err)
	return _c
}

func (_c *MockCmd_StdoutPipe_Call) RunAndReturn(run func() (io.Reader, error)) *MockCmd_StdoutPipe_Call {
	_c.Call.Return(run)
	return _c
}
