// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileMode creates a new instance of MockFileMode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileMode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileMode {
	mock := &MockFileMode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileMode is an autogenerated mock type for the FileMode type
type MockFileMode struct {
	mock.Mock
}

type MockFileMode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileMode) EXPECT() *MockFileMode_Expecter {
	return &MockFileMode_Expecter{mock: &_m.Mock}
}

// Perm provides a mock function for the type MockFileMode
func (_mock *MockFileMode) Perm() uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Perm")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// MockFileMode_Perm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Perm'
type MockFileMode_Perm_Call struct {
	*mock.Call
}

// Perm is a helper method to define mock.On call
func (_e *MockFileMode_Expecter) Perm() *MockFileMode_Perm_Call {
	return &MockFileMode_Perm_Call{Call: _e.mock.On("Perm")}
}

func (_c *MockFileMode_Perm_Call) Run(run func()) *MockFileMode_Perm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileMode_Perm_Call) Return(v uint32) *MockFileMode_Perm_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFileMode_Perm_Call) RunAndReturn(run func() uint32) *MockFileMode_Perm_Call {
	_c.Call.Return(run)
	return _c
}
