// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProcess creates a new instance of MockProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcess {
	mock := &MockProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcess is an autogenerated mock type for the Process type
type MockProcess struct {
	mock.Mock
}

type MockProcess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcess) EXPECT() *MockProcess_Expecter {
	return &MockProcess_Expecter{mock: &_m.Mock}
}

// Kill provides a mock function for the type MockProcess
func (_mock *MockProcess) Kill() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcess_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockProcess_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
func (_e *MockProcess_Expecter) Kill() *MockProcess_Kill_Call {
	return &MockProcess_Kill_Call{Call: _e.mock.On("Kill")}
}

func (_c *MockProcess_Kill_Call) Run(run func()) *MockProcess_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_Kill_Call) Return(err error) *MockProcess_Kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcess_Kill_Call) RunAndReturn(run func() error) *MockProcess_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// Signal provides a mock function for the type MockProcess
func (_mock *MockProcess) Signal(sig os.Signal) error {
	ret := _mock.Called(sig)

	if len(ret) == 0 {
		panic("no return value specified for Signal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(os.Signal) error); ok {
		r0 = returnFunc(sig)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProcess_Signal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signal'
type MockProcess_Signal_Call struct {
	*mock.Call
}

// Signal is a helper method to define mock.On call
//   - sig os.Signal
func (_e *MockProcess_Expecter) Signal(sig interface{}) *MockProcess_Signal_Call {
	return &MockProcess_Signal_Call{Call: _e.mock.On("Signal", sig)}
}

func (_c *MockProcess_Signal_Call) Run(run func(sig os.Signal)) *MockProcess_Signal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 os.Signal
		if args[0] != nil {
			arg0 = args[0].(os.Signal)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProcess_Signal_Call) Return(err error) *MockProcess_Signal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProcess_Signal_Call) RunAndReturn(run func(sig os.Signal) error) *MockProcess_Signal_Call {
	_c.Call.Return(run)
	return _c
}

// Wait provides a mock function for the type MockProcess
func (_mock *MockProcess) Wait() (*os.ProcessState, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 *os.ProcessState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*os.ProcessState, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *os.ProcessState); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.ProcessState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcess_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockProcess_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockProcess_Expecter) Wait() *MockProcess_Wait_Call {
	return &MockProcess_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockProcess_Wait_Call) Run(run func()) *MockProcess_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcess_Wait_Call) Return(processState *os.ProcessState, err error) *MockProcess_Wait_Call {
	_c.Call.Return(processState, err)
	return _c
}

func (_c *MockProcess_Wait_Call) RunAndReturn(run func() (*os.ProcessState, error)) *MockProcess_Wait_Call {
	_c.Call.Return(run)
	return _c
}
