// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// Getppid provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Getppid() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Getppid")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockOSLayer_Getppid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getppid'
type MockOSLayer_Getppid_Call struct {
	*mock.Call
}

// Getppid is a helper method to define mock.On call
func (_e *MockOSLayer_Expecter) Getppid() *MockOSLayer_Getppid_Call {
	return &MockOSLayer_Getppid_Call{Call: _e.mock.On("Getppid")}
}

func (_c *MockOSLayer_Getppid_Call) Run(run func()) *MockOSLayer_Getppid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOSLayer_Getppid_Call) Return(n int) *MockOSLayer_Getppid_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockOSLayer_Getppid_Call) RunAndReturn(run func() int) *MockOSLayer_Getppid_Call {
	_c.Call.Return(run)
	return _c
}
