// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerFactory creates a new instance of MockServerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerFactory {
	mock := &MockServerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerFactory is an autogenerated mock type for the ServerFactory type
type MockServerFactory struct {
	mock.Mock
}

type MockServerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerFactory) EXPECT() *MockServerFactory_Expecter {
	return &MockServerFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockServerFactory
func (_mock *MockServerFactory) New() (transport.Server, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 transport.Server
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (transport.Server, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() transport.Server); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transport.Server)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServerFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockServerFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
func (_e *MockServerFactory_Expecter) New() *MockServerFactory_New_Call {
	return &MockServerFactory_New_Call{Call: _e.mock.On("New")}
}

func (_c *MockServerFactory_New_Call) Run(run func()) *MockServerFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerFactory_New_Call) Return(server transport.Server, err error) *MockServerFactory_New_Call {
	_c.Call.Return(server, err)
	return _c
}

func (_c *MockServerFactory_New_Call) RunAndReturn(run func() (transport.Server, error)) *MockServerFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
