// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFile creates a new instance of MockFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFile {
	mock := &MockFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFile is an autogenerated mock type for the File type
type MockFile struct {
	mock.Mock
}

type MockFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFile) EXPECT() *MockFile_Expecter {
	return &MockFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockFile
func (_mock *MockFile) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFile_Expecter) Close() *MockFile_Close_Call {
	return &MockFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFile_Close_Call) Run(run func()) *MockFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Close_Call) Return(err error) *MockFile_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFile_Close_Call) RunAndReturn(run func() error) *MockFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Fd provides a mock function for the type MockFile
func (_mock *MockFile) Fd() uintptr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fd")
	}

	var r0 uintptr
	if returnFunc, ok := ret.Get(0).(func() uintptr); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uintptr)
	}
	return r0
}

// MockFile_Fd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fd'
type MockFile_Fd_Call struct {
	*mock.Call
}

// Fd is a helper method to define mock.On call
func (_e *MockFile_Expecter) Fd() *MockFile_Fd_Call {
	return &MockFile_Fd_Call{Call: _e.mock.On("Fd")}
}

func (_c *MockFile_Fd_Call) Run(run func()) *MockFile_Fd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Fd_Call) Return(v uintptr) *MockFile_Fd_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFile_Fd_Call) RunAndReturn(run func() uintptr) *MockFile_Fd_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockFile
func (_mock *MockFile) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFile_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockFile_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockFile_Expecter) Name() *MockFile_Name_Call {
	return &MockFile_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockFile_Name_Call) Run(run func()) *MockFile_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Name_Call) Return(s string) *MockFile_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFile_Name_Call) RunAndReturn(run func() string) *MockFile_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockFile
func (_mock *MockFile) Read(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockFile_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - b []byte
func (_e *MockFile_Expecter) Read(b interface{}) *MockFile_Read_Call {
	return &MockFile_Read_Call{Call: _e.mock.On("Read", b)}
}

func (_c *MockFile_Read_Call) Run(run func(b []byte)) *MockFile_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFile_Read_Call) Return(n int, err error) *MockFile_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFile_Read_Call) RunAndReturn(run func(b []byte) (int, error)) *MockFile_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Unwrap provides a mock function for the type MockFile
func (_mock *MockFile) Unwrap() *os.File {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unwrap")
	}

	var r0 *os.File
	if returnFunc, ok := ret.Get(0).(func() *os.File); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}
	return r0
}

// MockFile_Unwrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unwrap'
type MockFile_Unwrap_Call struct {
	*mock.Call
}

// Unwrap is a helper method to define mock.On call
func (_e *MockFile_Expecter) Unwrap() *MockFile_Unwrap_Call {
	return &MockFile_Unwrap_Call{Call: _e.mock.On("Unwrap")}
}

func (_c *MockFile_Unwrap_Call) Run(run func()) *MockFile_Unwrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Unwrap_Call) Return(file *os.File) *MockFile_Unwrap_Call {
	_c.Call.Return(file)
	return _c
}

func (_c *MockFile_Unwrap_Call) RunAndReturn(run func() *os.File) *MockFile_Unwrap_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockFile
func (_mock *MockFile) Write(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockFile_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - b []byte
func (_e *MockFile_Expecter) Write(b interface{}) *MockFile_Write_Call {
	return &MockFile_Write_Call{Call: _e.mock.On("Write", b)}
}

func (_c *MockFile_Write_Call) Run(run func(b []byte)) *MockFile_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFile_Write_Call) Return(n int, err error) *MockFile_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFile_Write_Call) RunAndReturn(run func(b []byte) (int, error)) *MockFile_Write_Call {
	_c.Call.Return(run)
	return _c
}
