// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileInfo creates a new instance of MockFileInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileInfo {
	mock := &MockFileInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileInfo is an autogenerated mock type for the FileInfo type
type MockFileInfo struct {
	mock.Mock
}

type MockFileInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileInfo) EXPECT() *MockFileInfo_Expecter {
	return &MockFileInfo_Expecter{mock: &_m.Mock}
}

// IsDir provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) IsDir() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDir")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileInfo_IsDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDir'
type MockFileInfo_IsDir_Call struct {
	*mock.Call
}

// IsDir is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) IsDir() *MockFileInfo_IsDir_Call {
	return &MockFileInfo_IsDir_Call{Call: _e.mock.On("IsDir")}
}

func (_c *MockFileInfo_IsDir_Call) Run(run func()) *MockFileInfo_IsDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_IsDir_Call) Return(b bool) *MockFileInfo_IsDir_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileInfo_IsDir_Call) RunAndReturn(run func() bool) *MockFileInfo_IsDir_Call {
	_c.Call.Return(run)
	return _c
}

// ModTime provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) ModTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockFileInfo_ModTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModTime'
type MockFileInfo_ModTime_Call struct {
	*mock.Call
}

// ModTime is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) ModTime() *MockFileInfo_ModTime_Call {
	return &MockFileInfo_ModTime_Call{Call: _e.mock.On("ModTime")}
}

func (_c *MockFileInfo_ModTime_Call) Run(run func()) *MockFileInfo_ModTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_ModTime_Call) Return(time1 time.Time) *MockFileInfo_ModTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockFileInfo_ModTime_Call) RunAndReturn(run func() time.Time) *MockFileInfo_ModTime_Call {
	_c.Call.Return(run)
	return _c
}

// Mode provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) Mode() osfacade.FileMode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mode")
	}

	var r0 osfacade.FileMode
	if returnFunc, ok := ret.Get(0).(func() osfacade.FileMode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.FileMode)
		}
	}
	return r0
}

// MockFileInfo_Mode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mode'
type MockFileInfo_Mode_Call struct {
	*mock.Call
}

// Mode is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Mode() *MockFileInfo_Mode_Call {
	return &MockFileInfo_Mode_Call{Call: _e.mock.On("Mode")}
}

func (_c *MockFileInfo_Mode_Call) Run(run func()) *MockFileInfo_Mode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Mode_Call) Return(fileMode osfacade.FileMode) *MockFileInfo_Mode_Call {
	_c.Call.Return(fileMode)
	return _c
}

func (_c *MockFileInfo_Mode_Call) RunAndReturn(run func() osfacade.FileMode) *MockFileInfo_Mode_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFileInfo_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockFileInfo_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Name() *MockFileInfo_Name_Call {
	return &MockFileInfo_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockFileInfo_Name_Call) Run(run func()) *MockFileInfo_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Name_Call) Return(s string) *MockFileInfo_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFileInfo_Name_Call) RunAndReturn(run func() string) *MockFileInfo_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) Size() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockFileInfo_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockFileInfo_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Size() *MockFileInfo_Size_Call {
	return &MockFileInfo_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockFileInfo_Size_Call) Run(run func()) *MockFileInfo_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Size_Call) Return(n int64) *MockFileInfo_Size_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFileInfo_Size_Call) RunAndReturn(run func() int64) *MockFileInfo_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Sys provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) Sys() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sys")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockFileInfo_Sys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sys'
type MockFileInfo_Sys_Call struct {
	*mock.Call
}

// Sys is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Sys() *MockFileInfo_Sys_Call {
	return &MockFileInfo_Sys_Call{Call: _e.mock.On("Sys")}
}

func (_c *MockFileInfo_Sys_Call) Run(run func()) *MockFileInfo_Sys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Sys_Call) Return(v any) *MockFileInfo_Sys_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFileInfo_Sys_Call) RunAndReturn(run func() any) *MockFileInfo_Sys_Call {
	_c.Call.Return(run)
	return _c
}
