// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabservices/datatypes"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABLocator creates a new instance of MockMATLABLocator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABLocator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABLocator {
	mock := &MockMATLABLocator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABLocator is an autogenerated mock type for the MATLABLocator type
type MockMATLABLocator struct {
	mock.Mock
}

type MockMATLABLocator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABLocator) EXPECT() *MockMATLABLocator_Expecter {
	return &MockMATLABLocator_Expecter{mock: &_m.Mock}
}

// ListDiscoveredMatlabInfo provides a mock function for the type MockMATLABLocator
func (_mock *MockMATLABLocator) ListDiscoveredMatlabInfo(logger entities.Logger) datatypes.ListMatlabInfo {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for ListDiscoveredMatlabInfo")
	}

	var r0 datatypes.ListMatlabInfo
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) datatypes.ListMatlabInfo); ok {
		r0 = returnFunc(logger)
	} else {
		r0 = ret.Get(0).(datatypes.ListMatlabInfo)
	}
	return r0
}

// MockMATLABLocator_ListDiscoveredMatlabInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDiscoveredMatlabInfo'
type MockMATLABLocator_ListDiscoveredMatlabInfo_Call struct {
	*mock.Call
}

// ListDiscoveredMatlabInfo is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockMATLABLocator_Expecter) ListDiscoveredMatlabInfo(logger interface{}) *MockMATLABLocator_ListDiscoveredMatlabInfo_Call {
	return &MockMATLABLocator_ListDiscoveredMatlabInfo_Call{Call: _e.mock.On("ListDiscoveredMatlabInfo", logger)}
}

func (_c *MockMATLABLocator_ListDiscoveredMatlabInfo_Call) Run(run func(logger entities.Logger)) *MockMATLABLocator_ListDiscoveredMatlabInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABLocator_ListDiscoveredMatlabInfo_Call) Return(listMatlabInfo datatypes.ListMatlabInfo) *MockMATLABLocator_ListDiscoveredMatlabInfo_Call {
	_c.Call.Return(listMatlabInfo)
	return _c
}

func (_c *MockMATLABLocator_ListDiscoveredMatlabInfo_Call) RunAndReturn(run func(logger entities.Logger) datatypes.ListMatlabInfo) *MockMATLABLocator_ListDiscoveredMatlabInfo_Call {
	_c.Call.Return(run)
	return _c
}
