within QuadrotorExperiments.RobustFaultScenarios;
model Example1WindGustAntiWindupFeedforwardPID
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.Example1WindGustAntiWindupFeedforwardPID"
  extends MoSimQuadrotorModel.Robustness.Scenarios.Example1WindGustAntiWindupFeedforwardPID;
  annotation(__MWORKS(hide=true));
end Example1WindGustAntiWindupFeedforwardPID;
