within QuadrotorExperiments.RobustFaultScenarios;
model Example1Mass20LinearMPCSysblockClosedLoop
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.Example1Mass20LinearMPCSysblockClosedLoop"
  extends MoSimQuadrotorModel.Robustness.Scenarios.Example1Mass20LinearMPCSysblockClosedLoop;
  annotation(__MWORKS(hide=true));
end Example1Mass20LinearMPCSysblockClosedLoop;
