within QuadrotorExperiments.RobustFaultScenarios;
model Example1QPNMPCSafetyReturnLandSysblockClosedLoop
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.Example1QPNMPCSafetyReturnLandSysblockClosedLoop"
  extends MoSimQuadrotorModel.Robustness.Scenarios.Example1QPNMPCSafetyReturnLandSysblockClosedLoop;
  annotation(__MWORKS(hide=true));
end Example1QPNMPCSafetyReturnLandSysblockClosedLoop;
