within QuadrotorExperiments.RobustFaultScenarios;
model Example1Mass20AntiWindupFeedforwardPID
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.Example1Mass20AntiWindupFeedforwardPID"
  extends MoSimQuadrotorModel.Robustness.Scenarios.Example1Mass20AntiWindupFeedforwardPID;
  annotation(__MWORKS(hide=true));
end Example1Mass20AntiWindupFeedforwardPID;
