// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessagesFactory creates a new instance of MockMessagesFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessagesFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessagesFactory {
	mock := &MockMessagesFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessagesFactory is an autogenerated mock type for the MessagesFactory type
type MockMessagesFactory struct {
	mock.Mock
}

type MockMessagesFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessagesFactory) EXPECT() *MockMessagesFactory_Expecter {
	return &MockMessagesFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockMessagesFactory
func (_mock *MockMessagesFactory) New(messageCatalog messages.MessageCatalog) messages.I18nErrorFactory {
	ret := _mock.Called(messageCatalog)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 messages.I18nErrorFactory
	if returnFunc, ok := ret.Get(0).(func(messages.MessageCatalog) messages.I18nErrorFactory); ok {
		r0 = returnFunc(messageCatalog)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messages.I18nErrorFactory)
		}
	}
	return r0
}

// MockMessagesFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockMessagesFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - messageCatalog messages.MessageCatalog
func (_e *MockMessagesFactory_Expecter) New(messageCatalog interface{}) *MockMessagesFactory_New_Call {
	return &MockMessagesFactory_New_Call{Call: _e.mock.On("New", messageCatalog)}
}

func (_c *MockMessagesFactory_New_Call) Run(run func(messageCatalog messages.MessageCatalog)) *MockMessagesFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 messages.MessageCatalog
		if args[0] != nil {
			arg0 = args[0].(messages.MessageCatalog)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessagesFactory_New_Call) Return(i18nErrorFactory messages.I18nErrorFactory) *MockMessagesFactory_New_Call {
	_c.Call.Return(i18nErrorFactory)
	return _c
}

func (_c *MockMessagesFactory_New_Call) RunAndReturn(run func(messageCatalog messages.MessageCatalog) messages.I18nErrorFactory) *MockMessagesFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
