// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSupportedParameterValueType creates a new instance of MockSupportedParameterValueType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupportedParameterValueType(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupportedParameterValueType {
	mock := &MockSupportedParameterValueType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSupportedParameterValueType is an autogenerated mock type for the SupportedParameterValueType type
type MockSupportedParameterValueType struct {
	mock.Mock
}

type MockSupportedParameterValueType_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupportedParameterValueType) EXPECT() *MockSupportedParameterValueType_Expecter {
	return &MockSupportedParameterValueType_Expecter{mock: &_m.Mock}
}
