// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

const (
	fallbackLocale = "en_US"
)

// GetSystemLocale automatically detects the system locale and returns
// as a string to support locales to be looked to support 1p use.
// If no locale can be detected it will return "en_US".
func GetSystemLocale() string {
	checker := newSystemChecker()

	locale, err := checker.getSystemLocale()
	if err != nil {
		return fallbackLocale
	}

	normalizedLocale := normalizeLocale(locale)
	if normalizedLocale == "" {
		return fallbackLocale
	}

	return normalizedLocale
}
