// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

import (
	"os"
	"strings"
)

// normalizeLocale converts locale strings to the standard language_territory format
func normalizeLocale(locale string) string {
	// Remove encoding suffix - don't care if we don't find a match so ignore the other args
	locale, _, _ = strings.Cut(locale, ".")

	// Remove any @ modifier - don't care if we don't find a match so ignore the other args
	locale, _, _ = strings.Cut(locale, "@")

	// Convert hyphens to underscores
	locale = strings.ReplaceAll(locale, "-", "_")

	// Trim whitespace
	locale = strings.TrimSpace(locale)

	// Normalize capitalization: language_TERRITORY format
	parts := strings.Split(locale, "_")
	switch len(parts) {
	case 1:
		// Just language or territory - convert to lowercase by convention
		return strings.ToLower(locale)
	case 2:
		// language code lowercase, territory code uppercase
		return strings.ToLower(parts[0]) + "_" + strings.ToUpper(parts[1])
	default:
		// Locale isn't of a standard format, so return empty string
		return ""
	}
}

func getFromEnvironment(
	envVars []string,
) string {
	for _, envVar := range envVars {
		if value := os.Getenv(envVar); value != "" {
			return value
		}
	}
	return ""
}

// processMacOSDefaultsOutput extracts the first valid language code from macOS defaults output
func processMacOSDefaultsOutput(output string) string {
	lines := strings.Split(output, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "(" || line == ")" || line == "" {
			continue
		}

		line = strings.Trim(line, `",`)
		if line != "" {
			return line
		}
	}

	return ""
}
