// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

import (
	"errors"
	"os"
	"syscall"
	"unsafe"
)

const (
	// https://nsis.sourceforge.io/Language_Detection_From_Windows_UI_Language
	LOCALE_NAME_MAX_LENGTH = 85 // includes terminating NUL

	// https://doc.geodigital.com/index.htm?Windows.LCIDToLocaleName.htm
	SORT_DEFAULT = 0 // used with MAKELCID
)

func newSystemChecker() *systemChecker {
	return &systemChecker{
		systemCheck: getWindowsUILanguage,
	}
}

type systemChecker struct {
	systemCheck func() string
}

func (sc *systemChecker) getSystemLocale() (string, error) {
	// Check for MW override
	if locale := os.Getenv("MW_SET_WIN_LC_MESSAGE"); locale != "" {
		return locale, nil
	}

	// Use Windows API to get UI language
	locale := sc.systemCheck()
	if locale != "" {
		return locale, nil
	}

	return "", errors.New("unable to determine system locale")
}

func getWindowsUILanguage() string {
	getUserDefaultUILanguage, lcidToLocaleName, err := lazyLoadKernelDLL()
	if err != nil {
		return ""
	}

	langID, _, _ := getUserDefaultUILanguage.Call()
	if langID == 0 {
		return ""
	}

	lcid := makeLCID(uint16(langID))

	var buf [LOCALE_NAME_MAX_LENGTH]uint16
	ret, _, _ := lcidToLocaleName.Call(
		uintptr(lcid),                    // LCID
		uintptr(unsafe.Pointer(&buf[0])), // output buffer
		uintptr(len(buf)),                // cchName; max is LOCALE_NAME_MAX_LENGTH
		uintptr(0),                       // flags (0 is fine; ignoring neutral name flag as want a specific locale)
	)
	if ret == 0 {
		return ""
	}

	return syscall.UTF16ToString(buf[:])
}

// lazyLoadKernelDLL loads the kernal32 DLL and then returns
// GetUserDefaultUILanguage and LCIDToLocaleName to the caller
func lazyLoadKernelDLL() (*syscall.LazyProc, *syscall.LazyProc, error) {
	kernel32 := syscall.NewLazyDLL("kernel32.dll")
	if kernel32 == nil {
		return nil, nil, errors.New("kernel32.dll failed to load")
	}

	getUserDefaultUILanguage := kernel32.NewProc("GetUserDefaultUILanguage")
	lcidToLocaleName := kernel32.NewProc("LCIDToLocaleName")
	return getUserDefaultUILanguage, lcidToLocaleName, nil
}

func makeLCID(langID uint16) uint32 {
	// Equivalent to MAKELCID(langID, SORT_DEFAULT)
	// Type casting is to handle the bitwise operation correctly while mimicking
	// the MAKELCID macro behaviour
	return (uint32(SORT_DEFAULT) << 16) | uint32(langID)
}
