// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessDetails creates a new instance of MockProcessDetails. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessDetails(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessDetails {
	mock := &MockProcessDetails{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessDetails is an autogenerated mock type for the ProcessDetails type
type MockProcessDetails struct {
	mock.Mock
}

type MockProcessDetails_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessDetails) EXPECT() *MockProcessDetails_Expecter {
	return &MockProcessDetails_Expecter{mock: &_m.Mock}
}

// EnvironmentVariables provides a mock function for the type MockProcessDetails
func (_mock *MockProcessDetails) EnvironmentVariables(sessionDirPath string, apiKey string, certificateFile string, certificateKey string) []string {
	ret := _mock.Called(sessionDirPath, apiKey, certificateFile, certificateKey)

	if len(ret) == 0 {
		panic("no return value specified for EnvironmentVariables")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string) []string); ok {
		r0 = returnFunc(sessionDirPath, apiKey, certificateFile, certificateKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockProcessDetails_EnvironmentVariables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnvironmentVariables'
type MockProcessDetails_EnvironmentVariables_Call struct {
	*mock.Call
}

// EnvironmentVariables is a helper method to define mock.On call
//   - sessionDirPath string
//   - apiKey string
//   - certificateFile string
//   - certificateKey string
func (_e *MockProcessDetails_Expecter) EnvironmentVariables(sessionDirPath interface{}, apiKey interface{}, certificateFile interface{}, certificateKey interface{}) *MockProcessDetails_EnvironmentVariables_Call {
	return &MockProcessDetails_EnvironmentVariables_Call{Call: _e.mock.On("EnvironmentVariables", sessionDirPath, apiKey, certificateFile, certificateKey)}
}

func (_c *MockProcessDetails_EnvironmentVariables_Call) Run(run func(sessionDirPath string, apiKey string, certificateFile string, certificateKey string)) *MockProcessDetails_EnvironmentVariables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProcessDetails_EnvironmentVariables_Call) Return(strings []string) *MockProcessDetails_EnvironmentVariables_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockProcessDetails_EnvironmentVariables_Call) RunAndReturn(run func(sessionDirPath string, apiKey string, certificateFile string, certificateKey string) []string) *MockProcessDetails_EnvironmentVariables_Call {
	_c.Call.Return(run)
	return _c
}

// NewAPIKey provides a mock function for the type MockProcessDetails
func (_mock *MockProcessDetails) NewAPIKey() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewAPIKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProcessDetails_NewAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewAPIKey'
type MockProcessDetails_NewAPIKey_Call struct {
	*mock.Call
}

// NewAPIKey is a helper method to define mock.On call
func (_e *MockProcessDetails_Expecter) NewAPIKey() *MockProcessDetails_NewAPIKey_Call {
	return &MockProcessDetails_NewAPIKey_Call{Call: _e.mock.On("NewAPIKey")}
}

func (_c *MockProcessDetails_NewAPIKey_Call) Run(run func()) *MockProcessDetails_NewAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessDetails_NewAPIKey_Call) Return(s string) *MockProcessDetails_NewAPIKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProcessDetails_NewAPIKey_Call) RunAndReturn(run func() string) *MockProcessDetails_NewAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// StartupFlag provides a mock function for the type MockProcessDetails
func (_mock *MockProcessDetails) StartupFlag(os string, showMATLAB bool, startupCode string) []string {
	ret := _mock.Called(os, showMATLAB, startupCode)

	if len(ret) == 0 {
		panic("no return value specified for StartupFlag")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(string, bool, string) []string); ok {
		r0 = returnFunc(os, showMATLAB, startupCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockProcessDetails_StartupFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartupFlag'
type MockProcessDetails_StartupFlag_Call struct {
	*mock.Call
}

// StartupFlag is a helper method to define mock.On call
//   - os string
//   - showMATLAB bool
//   - startupCode string
func (_e *MockProcessDetails_Expecter) StartupFlag(os interface{}, showMATLAB interface{}, startupCode interface{}) *MockProcessDetails_StartupFlag_Call {
	return &MockProcessDetails_StartupFlag_Call{Call: _e.mock.On("StartupFlag", os, showMATLAB, startupCode)}
}

func (_c *MockProcessDetails_StartupFlag_Call) Run(run func(os string, showMATLAB bool, startupCode string)) *MockProcessDetails_StartupFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProcessDetails_StartupFlag_Call) Return(strings []string) *MockProcessDetails_StartupFlag_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockProcessDetails_StartupFlag_Call) RunAndReturn(run func(os string, showMATLAB bool, startupCode string) []string) *MockProcessDetails_StartupFlag_Call {
	_c.Call.Return(run)
	return _c
}
