// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLifecycleSignaler creates a new instance of MockLifecycleSignaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLifecycleSignaler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLifecycleSignaler {
	mock := &MockLifecycleSignaler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLifecycleSignaler is an autogenerated mock type for the LifecycleSignaler type
type MockLifecycleSignaler struct {
	mock.Mock
}

type MockLifecycleSignaler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLifecycleSignaler) EXPECT() *MockLifecycleSignaler_Expecter {
	return &MockLifecycleSignaler_Expecter{mock: &_m.Mock}
}

// RequestShutdown provides a mock function for the type MockLifecycleSignaler
func (_mock *MockLifecycleSignaler) RequestShutdown() {
	_mock.Called()
	return
}

// MockLifecycleSignaler_RequestShutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestShutdown'
type MockLifecycleSignaler_RequestShutdown_Call struct {
	*mock.Call
}

// RequestShutdown is a helper method to define mock.On call
func (_e *MockLifecycleSignaler_Expecter) RequestShutdown() *MockLifecycleSignaler_RequestShutdown_Call {
	return &MockLifecycleSignaler_RequestShutdown_Call{Call: _e.mock.On("RequestShutdown")}
}

func (_c *MockLifecycleSignaler_RequestShutdown_Call) Run(run func()) *MockLifecycleSignaler_RequestShutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLifecycleSignaler_RequestShutdown_Call) Return() *MockLifecycleSignaler_RequestShutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLifecycleSignaler_RequestShutdown_Call) RunAndReturn(run func()) *MockLifecycleSignaler_RequestShutdown_Call {
	_c.Run(run)
	return _c
}

// WaitForShutdownToComplete provides a mock function for the type MockLifecycleSignaler
func (_mock *MockLifecycleSignaler) WaitForShutdownToComplete() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for WaitForShutdownToComplete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLifecycleSignaler_WaitForShutdownToComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForShutdownToComplete'
type MockLifecycleSignaler_WaitForShutdownToComplete_Call struct {
	*mock.Call
}

// WaitForShutdownToComplete is a helper method to define mock.On call
func (_e *MockLifecycleSignaler_Expecter) WaitForShutdownToComplete() *MockLifecycleSignaler_WaitForShutdownToComplete_Call {
	return &MockLifecycleSignaler_WaitForShutdownToComplete_Call{Call: _e.mock.On("WaitForShutdownToComplete")}
}

func (_c *MockLifecycleSignaler_WaitForShutdownToComplete_Call) Run(run func()) *MockLifecycleSignaler_WaitForShutdownToComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLifecycleSignaler_WaitForShutdownToComplete_Call) Return(err error) *MockLifecycleSignaler_WaitForShutdownToComplete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLifecycleSignaler_WaitForShutdownToComplete_Call) RunAndReturn(run func() error) *MockLifecycleSignaler_WaitForShutdownToComplete_Call {
	_c.Call.Return(run)
	return _c
}
