// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/telemetry/otel"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExporterFactory creates a new instance of MockExporterFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExporterFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExporterFactory {
	mock := &MockExporterFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExporterFactory is an autogenerated mock type for the ExporterFactory type
type MockExporterFactory struct {
	mock.Mock
}

type MockExporterFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExporterFactory) EXPECT() *MockExporterFactory_Expecter {
	return &MockExporterFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockExporterFactory
func (_mock *MockExporterFactory) New() (otel.MetricExporter, messages.Error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 otel.MetricExporter
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func() (otel.MetricExporter, messages.Error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() otel.MetricExporter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(otel.MetricExporter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() messages.Error); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockExporterFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockExporterFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
func (_e *MockExporterFactory_Expecter) New() *MockExporterFactory_New_Call {
	return &MockExporterFactory_New_Call{Call: _e.mock.On("New")}
}

func (_c *MockExporterFactory_New_Call) Run(run func()) *MockExporterFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExporterFactory_New_Call) Return(metricExporter otel.MetricExporter, error messages.Error) *MockExporterFactory_New_Call {
	_c.Call.Return(metricExporter, error)
	return _c
}

func (_c *MockExporterFactory_New_Call) RunAndReturn(run func() (otel.MetricExporter, messages.Error)) *MockExporterFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
