// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/telemetry/otel/instruments"
	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/metric"
)

// NewMockInstrumentFactory creates a new instance of MockInstrumentFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInstrumentFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInstrumentFactory {
	mock := &MockInstrumentFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInstrumentFactory is an autogenerated mock type for the InstrumentFactory type
type MockInstrumentFactory struct {
	mock.Mock
}

type MockInstrumentFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInstrumentFactory) EXPECT() *MockInstrumentFactory_Expecter {
	return &MockInstrumentFactory_Expecter{mock: &_m.Mock}
}

// NewInt64Counter provides a mock function for the type MockInstrumentFactory
func (_mock *MockInstrumentFactory) NewInt64Counter(meter metric.Meter, name string, description string, unit string) (instruments.Int64Counter, error) {
	ret := _mock.Called(meter, name, description, unit)

	if len(ret) == 0 {
		panic("no return value specified for NewInt64Counter")
	}

	var r0 instruments.Int64Counter
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(metric.Meter, string, string, string) (instruments.Int64Counter, error)); ok {
		return returnFunc(meter, name, description, unit)
	}
	if returnFunc, ok := ret.Get(0).(func(metric.Meter, string, string, string) instruments.Int64Counter); ok {
		r0 = returnFunc(meter, name, description, unit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(instruments.Int64Counter)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(metric.Meter, string, string, string) error); ok {
		r1 = returnFunc(meter, name, description, unit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInstrumentFactory_NewInt64Counter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewInt64Counter'
type MockInstrumentFactory_NewInt64Counter_Call struct {
	*mock.Call
}

// NewInt64Counter is a helper method to define mock.On call
//   - meter metric.Meter
//   - name string
//   - description string
//   - unit string
func (_e *MockInstrumentFactory_Expecter) NewInt64Counter(meter interface{}, name interface{}, description interface{}, unit interface{}) *MockInstrumentFactory_NewInt64Counter_Call {
	return &MockInstrumentFactory_NewInt64Counter_Call{Call: _e.mock.On("NewInt64Counter", meter, name, description, unit)}
}

func (_c *MockInstrumentFactory_NewInt64Counter_Call) Run(run func(meter metric.Meter, name string, description string, unit string)) *MockInstrumentFactory_NewInt64Counter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.Meter
		if args[0] != nil {
			arg0 = args[0].(metric.Meter)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInstrumentFactory_NewInt64Counter_Call) Return(int64Counter instruments.Int64Counter, err error) *MockInstrumentFactory_NewInt64Counter_Call {
	_c.Call.Return(int64Counter, err)
	return _c
}

func (_c *MockInstrumentFactory_NewInt64Counter_Call) RunAndReturn(run func(meter metric.Meter, name string, description string, unit string) (instruments.Int64Counter, error)) *MockInstrumentFactory_NewInt64Counter_Call {
	_c.Call.Return(run)
	return _c
}
