// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTelemetry creates a new instance of MockTelemetry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelemetry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelemetry {
	mock := &MockTelemetry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelemetry is an autogenerated mock type for the Telemetry type
type MockTelemetry struct {
	mock.Mock
}

type MockTelemetry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelemetry) EXPECT() *MockTelemetry_Expecter {
	return &MockTelemetry_Expecter{mock: &_m.Mock}
}

// RecordServerStart provides a mock function for the type MockTelemetry
func (_mock *MockTelemetry) RecordServerStart(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockTelemetry_RecordServerStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordServerStart'
type MockTelemetry_RecordServerStart_Call struct {
	*mock.Call
}

// RecordServerStart is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTelemetry_Expecter) RecordServerStart(ctx interface{}) *MockTelemetry_RecordServerStart_Call {
	return &MockTelemetry_RecordServerStart_Call{Call: _e.mock.On("RecordServerStart", ctx)}
}

func (_c *MockTelemetry_RecordServerStart_Call) Run(run func(ctx context.Context)) *MockTelemetry_RecordServerStart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTelemetry_RecordServerStart_Call) Return() *MockTelemetry_RecordServerStart_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelemetry_RecordServerStart_Call) RunAndReturn(run func(ctx context.Context)) *MockTelemetry_RecordServerStart_Call {
	_c.Run(run)
	return _c
}
