import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Vec3, Quat } from "../schemas.js";

export const animationTool: ToolDef = categoryTool(
  "animation",
  "Animation assets, skeletons, montages, blendspaces, anim blueprints, physics assets.",
  {
    read_anim_blueprint:  bp("Read AnimBP structure. Params: assetPath", "read_anim_blueprint"),
    read_montage:         bp("Read montage. Params: assetPath", "read_anim_montage", (p) => ({ assetPath: p.assetPath })),
    read_sequence:        bp("Read anim sequence. Params: assetPath", "read_anim_sequence", (p) => ({ assetPath: p.assetPath })),
    read_blendspace:      bp("Read blendspace. Params: assetPath", "read_blendspace", (p) => ({ assetPath: p.assetPath })),
    add_blend_sample:     bp("Append a sample to a BlendSpace. Params: assetPath, animation (AnimSequence path), position {x,y} (or flat x,y) (#248)", "add_blend_sample", (p) => ({ assetPath: p.assetPath, animation: p.animation, position: p.position, x: p.x, y: p.y })),
    set_blend_sample:     bp("Move an existing BlendSpace sample or swap its animation. Params: assetPath, sampleIndex, position? {x,y} (or flat x,y), animation? (#272)", "set_blend_sample", (p) => ({ assetPath: p.assetPath, sampleIndex: p.sampleIndex, position: p.position, x: p.x, y: p.y, animation: p.animation })),
    list:                 bp("List anim assets. Params: directory?, recursive?", "list_anim_assets"),
    create_montage:       bp("Create montage. Params: animSequencePath, name?, packagePath?", "create_anim_montage"),
    create_anim_blueprint: bp("Create AnimBP. Params: skeletonPath, name?, packagePath?, parentClass?", "create_anim_blueprint"),
    create_blendspace:    bp("Create blendspace. Params: skeletonPath, name?, packagePath?, axisHorizontal?, axisVertical?", "create_blendspace"),
    add_notify:           bp("Add notify. Params: assetPath, notifyName, triggerTime, notifyClass?", "add_anim_notify"),
    get_skeleton_info:    bp("Read skeleton. Params: assetPath", "get_skeleton_info"),
    list_sockets:         bp("List sockets. Params: assetPath", "list_sockets"),
    list_skeletal_meshes: bp("List skeletal meshes. Params: directory?, recursive?", "list_skeletal_meshes"),
    get_physics_asset:    bp("Read physics asset. Params: assetPath", "get_physics_asset_info"),
    create_sequence:      bp("Create blank AnimSequence. Params: name, skeletonPath, packagePath?, numFrames?, frameRate?", "create_sequence"),
    set_bone_keyframes:   bp("Set bone transform keyframes. Params: assetPath, boneName, keyframes", "set_bone_keyframes"),
    get_bone_transforms:  bp("Read reference pose transforms. Params: skeletonPath, boneNames?, space? ('local' default, or 'component' for composed parent-chain transforms - retarget-chain / anatomical-scale work) (#245)", "get_bone_transforms"),
    set_montage_sequence: bp("Replace animation sequence in a montage. Params: assetPath, animSequencePath, slotIndex?", "set_montage_sequence"),
    set_montage_properties: bp("Set montage properties. Params: assetPath, sequenceLength?, rateScale?, blendIn?, blendOut?", "set_montage_properties"),
    create_state_machine: bp("Create state machine in AnimBP. Params: assetPath, name?, graphName?", "create_state_machine"),
    add_state:            bp("Add state to a state machine. Params: assetPath, stateMachineName, stateName", "add_state"),
    add_transition:       bp("Add directed transition between states. Params: assetPath, stateMachineName, fromState, toState", "add_transition"),
    set_state_animation:  bp("Assign anim asset to state. Params: assetPath, stateMachineName, stateName, animAssetPath", "set_state_animation"),
    set_transition_blend: bp("Set blend type/duration on transition. Params: assetPath, stateMachineName, fromState, toState, blendDuration?, blendLogic?", "set_transition_blend"),
    read_state_machine:   bp("Read state machine topology. Params: assetPath, stateMachineName", "read_state_machine"),
    read_anim_graph:      bp("Read AnimBP AnimGraph nodes with properties & pins. Params: assetPath, graphName?", "read_anim_graph"),
    add_curve:            bp("Add float curve to AnimSequence. Params: assetPath, curveName, curveType?", "add_curve"),
    set_montage_slot:     bp("Set slot name on a montage track. Params: assetPath, slotName, trackIndex?", "set_montage_slot"),
    add_montage_section:  bp("Add composite section to montage. Params: assetPath, sectionName, startTime?, linkedSection?", "add_montage_section"),
    create_ik_rig:        bp("Create IKRigDefinition asset, optionally with retargetRoot + chains[]. Params: name, skeletalMeshPath, packagePath?, retargetRoot?, chains?: [{name, startBone, endBone, goal?}]", "create_ik_rig"),
    read_ik_rig:          bp("Read IK Rig chains, solvers, skeleton. Params: assetPath", "read_ik_rig"),
    list_control_rig_variables: bp("List ControlRig variables and hierarchy. Params: assetPath", "list_control_rig_variables"),
    set_root_motion:    bp("Set root motion settings on AnimSequence. Params: assetPath, enableRootMotion?, forceRootLock?, useNormalizedRootMotionScale?, rootMotionRootLock?", "set_root_motion_settings", (p) => ({ path: p.assetPath, enableRootMotion: p.enableRootMotion, forceRootLock: p.forceRootLock, useNormalizedRootMotionScale: p.useNormalizedRootMotionScale, rootMotionRootLock: p.rootMotionRootLock })),
    add_virtual_bone:   bp("Add virtual bone. Params: skeletonPath, sourceBone, targetBone", "add_virtual_bone"),
    remove_virtual_bone: bp("Remove virtual bone. Params: skeletonPath, virtualBoneName", "remove_virtual_bone"),
    create_composite:   bp("Create AnimComposite. Params: name, skeletonPath, packagePath?", "create_anim_composite"),
    list_modifiers:     bp("List applied animation modifiers. Params: assetPath", "list_anim_modifiers", (p) => ({ path: p.assetPath })),
    create_ik_retargeter: bp("Create IKRetargeter asset and (default) initialize the UE 5.7 ops stack: assigns sourceRig+targetRig to all ops, runs AutoMapChains. Returns chainsMapped count. Params: name, packagePath?, sourceRig?, targetRig?, autoMapChains? (default true) (#246)", "create_ik_retargeter", (p) => ({ name: p.name, packagePath: p.packagePath, sourceRig: p.sourceRig, targetRig: p.targetRig, autoMapChains: p.autoMapChains, onConflict: p.onConflict })),
    read_ik_retargeter: bp("Read IKRetargeter: source/target rigs and chain mappings. Params: assetPath (#246)", "read_ik_retargeter", (p) => ({ assetPath: p.assetPath })),
    set_anim_blueprint_skeleton: bp("Set target skeleton on AnimBP. Params: assetPath, skeletonPath", "set_anim_blueprint_skeleton"),
    read_bone_track:    bp("Read bone transform samples from AnimSequence. Params: assetPath, boneName, frames?: [int]", "read_bone_track"),
    create_pose_search_database: bp("Create a PoseSearchDatabase asset (motion matching). Params: name, packagePath?, schemaPath?", "create_pose_search_database"),
    set_pose_search_schema:      bp("Set the Schema on an existing PoseSearchDatabase. Params: assetPath, schemaPath", "set_pose_search_schema", (p) => ({ assetPath: p.assetPath, schemaPath: p.schemaPath })),
    add_pose_search_sequence:    bp("Append an AnimSequence/AnimComposite/AnimMontage/BlendSpace to a PoseSearchDatabase. Params: assetPath, sequencePath", "add_pose_search_sequence", (p) => ({ assetPath: p.assetPath, sequencePath: p.sequencePath })),
    build_pose_search_index:     bp("Build (or rebuild) the search index. Params: assetPath, wait? (default true)", "build_pose_search_index", (p) => ({ assetPath: p.assetPath, wait: p.wait })),
    read_pose_search_database:   bp("Inspect a PoseSearchDatabase: schema, animation entries, cost biases, tags. Params: assetPath", "read_pose_search_database", (p) => ({ assetPath: p.assetPath })),
    // v1.0.0-rc.2 — #153, #154 (animation authoring gaps)
    set_sequence_properties: bp("Batch-set properties on AnimSequence assets. If a path is a Montage and resolveFromMontages is true (default), resolves to its first AnimSequence. Params: assetPaths[], properties{enableRootMotion?, forceRootLock?, useNormalizedRootMotionScale?, rootMotionRootLock?}, resolveFromMontages?", "set_sequence_properties"),
    bake_root_motion_from_bone: bp("Bake delta translation from a source bone (e.g. pelvis) onto the root bone across the whole sequence; compensates the source bone so world-space position is unchanged. Params: assetPath, sourceBone, rootBone? (default 'root'), axes? (default ['x','y']), interpolation? ('linear'|'per_frame', default 'linear')", "bake_root_motion_from_bone"),
    // #419/#420 — live-actor skeletal operations (moved from level for proper domain alignment)
    get_bone_transform: bp("Read a bone or socket transform on a live actor's SkeletalMeshComponent. Wraps GetBoneTransform / GetSocketTransform. Params: actorLabel, boneName (or socket name), componentName? (default: CharacterMesh0 / Mesh / first SK component), space? (world|component|local, default world). Returns location, rotation, scale (#420)", "get_bone_transform", (p) => ({ actorLabel: p.actorLabel, boneName: p.boneName, componentName: p.componentName, space: p.space })),
    list_bones: bp("List bones in a live actor's SkeletalMeshComponent ref skeleton (name, index, parent). Params: actorLabel, componentName? (#420)", "list_bones", (p) => ({ actorLabel: p.actorLabel, componentName: p.componentName })),
    rebind_leader_pose: bp("Re-bind every secondary SkeletalMeshComponent on an actor to a body component (default CharacterMesh0 / Mesh). One-call fix for the 'character explodes after rotating the actor' failure mode. Params: actorLabel, bodyComponent? (#419)", "rebind_leader_pose", (p) => ({ actorLabel: p.actorLabel, bodyComponent: p.bodyComponent })),
    preview_animation: bp("Toggle bUpdateAnimationInEditor + VisibilityBasedAnimTickOption=AlwaysTickPoseAndRefreshBones on every SkeletalMeshComponent of an actor. Bypasses the 'cannot be edited on templates' guard for level instances. Params: actorLabel, enabled (#419/#420)", "preview_animation", (p) => ({ actorLabel: p.actorLabel, enabled: p.enabled })),
  },
  undefined,
  {
    assetPath: z.string().optional(),
    directory: z.string().optional(),
    recursive: z.boolean().optional(),
    animSequencePath: z.string().optional(),
    skeletonPath: z.string().optional(),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    axisHorizontal: z.string().optional(),
    axisVertical: z.string().optional(),
    notifyName: z.string().optional(),
    triggerTime: z.number().optional(),
    notifyClass: z.string().optional(),
    slotIndex: z.number().optional(),
    sequenceLength: z.number().optional(),
    rateScale: z.number().optional(),
    blendIn: z.number().optional(),
    blendOut: z.number().optional(),
    numFrames: z.number().optional(),
    frameRate: z.number().optional(),
    boneName: z.string().optional(),
    boneNames: z.array(z.string()).optional(),
    parentClass: z.string().optional().describe("Parent AnimInstance class name for create_anim_blueprint"),
    // State machine params
    stateMachineName: z.string().optional(),
    stateName: z.string().optional(),
    fromState: z.string().optional(),
    toState: z.string().optional(),
    animAssetPath: z.string().optional().describe("Path to animation sequence or blendspace"),
    blendDuration: z.number().optional(),
    blendLogic: z.string().optional().describe("Standard or Inertialization"),
    graphName: z.string().optional().describe("Target graph name (default: AnimGraph)"),
    // Curve params (#79 / #24)
    curveName: z.string().optional().describe("Curve name for add_curve"),
    curveType: z.string().optional().describe("Curve type (default: float)"),
    // Montage slot & section params (#78, #27)
    slotName: z.string().optional().describe("Slot name for set_montage_slot"),
    trackIndex: z.number().optional().describe("Slot track index (default: 0)"),
    sectionName: z.string().optional().describe("Section name for add_montage_section"),
    startTime: z.number().optional().describe("Start time for montage section"),
    linkedSection: z.string().optional().describe("Next section name to link to"),
    // IK Rig params (#93)
    skeletalMeshPath: z.string().optional().describe("Path to skeletal mesh for create_ik_rig"),
    enableRootMotion: z.boolean().optional(),
    forceRootLock: z.boolean().optional(),
    useNormalizedRootMotionScale: z.boolean().optional(),
    rootMotionRootLock: z.string().optional().describe("RefPose|AnimFirstFrame|Zero"),
    sourceBone: z.string().optional(),
    targetBone: z.string().optional(),
    virtualBoneName: z.string().optional(),
    retargetRoot: z.string().optional().describe("Retarget root bone name for IK Rig"),
    sourceRig: z.string().optional().describe("Source IKRig path for create_ik_retargeter"),
    targetRig: z.string().optional().describe("Target IKRig path for create_ik_retargeter"),
    autoMapChains: z.boolean().optional().describe("create_ik_retargeter: assign rigs to ops + AutoMapChains after creation (default true)"),
    onConflict: z.string().optional().describe("Asset-creation conflict policy: skip (default) | error | overwrite"),
    frames: z.array(z.number()).optional().describe("Specific frames to sample for read_bone_track"),
    chains: z.array(z.object({
      name: z.string(),
      startBone: z.string(),
      endBone: z.string(),
      goal: z.string().optional(),
    })).optional().describe("IK retarget chains for create_ik_rig"),
    keyframes: z.array(z.object({
      frame: z.number(),
      location: Vec3.optional(),
      rotation: Quat.optional(),
      scale: Vec3.optional(),
    })).optional(),
    // PoseSearch (v0.7.15)
    schemaPath: z.string().optional().describe("Path to a UPoseSearchSchema asset"),
    sequencePath: z.string().optional().describe("Animation asset path to add to a PoseSearchDatabase"),
    wait: z.boolean().optional().describe("build_pose_search_index: block until the async build resolves (default true)"),
    // #153 / #154
    assetPaths: z.array(z.string()).optional().describe("Asset paths (batch) for set_sequence_properties"),
    properties: z.record(z.any()).optional().describe("Property dict for set_sequence_properties"),
    resolveFromMontages: z.boolean().optional().describe("Resolve AnimMontage inputs to first anim reference (default true)"),
    rootBone: z.string().optional().describe("Root bone name for bake_root_motion_from_bone (default 'root')"),
    axes: z.array(z.string()).optional().describe("Axes to bake ('x','y','z') for bake_root_motion_from_bone"),
    interpolation: z.string().optional().describe("bake_root_motion_from_bone: 'linear' (default) or 'per_frame'"),
    space: z.string().optional().describe("Bone-space frame. get_bone_transforms (ref skeleton): 'local' (default) | 'component'. get_bone_transform (live actor): 'world' (default) | 'component' | 'local'"),
    animation: z.string().optional().describe("AnimSequence path for add_blend_sample / set_blend_sample"),
    sampleIndex: z.number().optional().describe("BlendSpace sample index for set_blend_sample"),
    position: z.object({ x: z.number().optional(), y: z.number().optional() }).optional().describe("BlendSpace sample position {x,y}"),
    x: z.number().optional(),
    y: z.number().optional(),
    // Live-actor skeletal operations (moved from level)
    actorLabel: z.string().optional().describe("Actor label for live skeletal queries"),
    componentName: z.string().optional().describe("SkeletalMeshComponent name (default: CharacterMesh0 / Mesh)"),
    bodyComponent: z.string().optional().describe("rebind_leader_pose: explicit body component name"),
    enabled: z.boolean().optional().describe("preview_animation: toggle on/off"),
  },
);
