import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Vec3, Rotator } from "../schemas.js";

export const gameplayTool: ToolDef = categoryTool(
  "gameplay",
  "Gameplay systems: physics, collision, navigation, input, behavior trees, AI (EQS, perception, State Trees, Smart Objects), game framework.",
  {
    set_collision_profile:  bp("Set collision preset. Params: actorLabel, profileName", "set_collision_profile"),
    set_simulate_physics:   bp("Toggle physics. Params: actorLabel, simulate", "set_simulate_physics"),
    set_collision_enabled:  bp("Set collision mode. Params: actorLabel, collisionEnabled", "set_collision_enabled"),
    set_physics_properties: bp("Set mass/damping/gravity. Params: actorLabel, mass?, linearDamping?, angularDamping?, enableGravity?", "set_physics_properties"),
    rebuild_navigation:     bp("Rebuild navmesh", "rebuild_navigation"),
    find_nav_path:          bp("Synchronous nav-path query between two world points. Returns valid/partial/length plus the polyline. The standard 'why doesn't my AI move?' diagnostic. Params: start (Vec3), end (Vec3), pathfindingContext? (actorLabel - uses its agent + filter) (#424)", "find_nav_path", (p) => ({ start: p.start, end: p.end, pathfindingContext: p.pathfindingContext })),
    list_nav_invokers:      bp("Enumerate actors carrying a NavigationInvokerComponent + their tile generation/removal radii. Diagnoses 'no navmesh in this region' caused by missing or mis-sized invokers (#424)", "list_nav_invokers"),
    get_navmesh_info:       bp("Query nav system", "get_navmesh_info"),
    project_to_nav:         bp("Project point to navmesh. Params: location, extent?", "project_point_to_navigation"),
    spawn_nav_modifier:     bp("Place nav modifier. Params: location, extent?, areaClass?", "spawn_nav_modifier_volume"),
    create_input_action:    bp("Create InputAction. Params: name, packagePath?, valueType?", "create_input_action"),
    create_input_mapping:   bp("Create InputMappingContext. Params: name, packagePath?", "create_input_mapping_context"),
    list_input_assets:      bp("List input assets. Params: directory?, recursive?", "list_input_assets"),
    read_imc:               bp("Read InputMappingContext mappings. Params: imcPath. Returns {key, inputAction, triggers[], modifiers[]}.", "read_imc"),
    list_input_mappings:    bp("Alias for read_imc. List key→action bindings with triggers/modifiers. Params: imcPath", "list_imc_mappings"),
    add_imc_mapping:        bp("Add key mapping to IMC. Params: imcPath, inputActionPath, key", "add_imc_mapping"),
    set_mapping_modifiers:  bp("Set modifiers/triggers on an IMC mapping. Params: imcPath, mappingIndex?, modifiers?, triggers?", "set_mapping_modifiers"),
    remove_imc_mapping:     bp("(#158) Remove an IMC mapping. Params: imcPath, mappingIndex? | (inputActionPath? + key?)", "remove_imc_mapping"),
    set_imc_mapping_key:    bp("(#158) Rebind an IMC mapping to a new key. Params: imcPath, newKey, mappingIndex? | key? | inputActionPath?", "set_imc_mapping_key"),
    set_imc_mapping_action: bp("(#158) Retarget an IMC mapping to a different InputAction. Params: imcPath, newInputActionPath, mappingIndex? | key? | inputActionPath?", "set_imc_mapping_action"),
    list_behavior_trees:    bp("List behavior trees. Params: directory?, recursive?", "list_behavior_trees"),
    get_behavior_tree_info: bp("Inspect behavior tree (top-level + blackboard). Params: assetPath", "get_behavior_tree_info"),
    read_behavior_tree_graph: bp("Walk BT tree: composites, tasks, decorators, services with blackboard keys. Params: assetPath", "read_behavior_tree_graph"),
    create_blackboard:      bp("Create Blackboard. Params: name, packagePath?", "create_blackboard"),
    add_blackboard_key:     bp("Add a typed key to a Blackboard asset. Params: blackboardPath, keyName, keyType (Bool|Int|Float|String|Name|Vector|Rotator|Object|Class|Enum), baseClass? (for Object/Class types; e.g. /Script/Engine.Actor) (#250)", "add_blackboard_key", (p) => ({ blackboardPath: p.blackboardPath, keyName: p.keyName, keyType: p.keyType, baseClass: p.baseClass })),
    set_behavior_tree_blackboard: bp("Rebind a BehaviorTree asset's BlackboardAsset reference. Params: behaviorTreePath, blackboardPath. The C++ field is protected so reflection is the only writable path (#250)", "set_behavior_tree_blackboard", (p) => ({ behaviorTreePath: p.behaviorTreePath, blackboardPath: p.blackboardPath })),
    create_behavior_tree:   bp("Create behavior tree. Params: name, packagePath?, blackboardPath?", "create_behavior_tree"),
    create_eqs_query:       bp("Create EQS query. Params: name, packagePath?", "create_eqs_query"),
    list_eqs_queries:       bp("List EQS queries. Params: directory?", "list_eqs_queries"),
    add_perception:         bp("Add AIPerceptionComponent. Params: blueprintPath, senses?", "add_perception_component"),
    configure_sense:        bp("Configure perception sense. Params: blueprintPath, senseType, settings?", "configure_ai_perception_sense"),
    create_state_tree:      bp("Create StateTree. Params: name, packagePath?", "create_state_tree"),
    list_state_trees:       bp("List StateTrees. Params: directory?", "list_state_trees"),
    add_state_tree_component: bp("Add StateTreeComponent. Params: blueprintPath", "add_state_tree_component"),
    create_smart_object_def: bp("Create SmartObjectDefinition. Params: name, packagePath?", "create_smart_object_definition"),
    add_smart_object_component: bp("Add SmartObjectComponent. Params: blueprintPath", "add_smart_object_component"),
    add_smart_object_slot: bp("Append a FSmartObjectSlotDefinition to a SmartObjectDefinition's Slots array. Params: assetPath, name?, offset? ({x,y,z}), rotation? ({pitch,yaw,roll}), tags? (array). Returns the new slotIndex. Rollback removes the slot (#416)", "add_smart_object_slot", (p) => ({ assetPath: p.assetPath, name: p.name, offset: p.offset, rotation: p.rotation, tags: p.tags })),
    set_smart_object_slot: bp("Mutate an existing slot's offset/rotation/tags. Params: assetPath, slotIndex, offset? ({x,y,z}), rotation? ({pitch,yaw,roll}), tags? (array). Omitted fields keep their current values (#416)", "set_smart_object_slot", (p) => ({ assetPath: p.assetPath, slotIndex: p.slotIndex, name: p.name, offset: p.offset, rotation: p.rotation, tags: p.tags })),
    remove_smart_object_slot: bp("Remove a slot by index. Idempotent: out-of-range returns alreadyDeleted=true. Params: assetPath, slotIndex (#416)", "remove_smart_object_slot", (p) => ({ assetPath: p.assetPath, slotIndex: p.slotIndex })),
    list_smart_object_slots: bp("List slots on a SmartObjectDefinition with index, offset, rotation, and raw text. Params: assetPath (#416)", "list_smart_object_slots", (p) => ({ assetPath: p.assetPath })),
    add_smart_object_slot_behavior: bp("Attach a behavior definition (UBehaviorDefinition asset or class) to a slot's BehaviorDefinitions array. Pass instanceProperties to seed UPROPERTYs on a freshly-spawned class-instance. Params: assetPath, slotIndex, behaviorClass (asset path or class path), instanceProperties? (#416)", "add_smart_object_slot_behavior", (p) => ({ assetPath: p.assetPath, slotIndex: p.slotIndex, behaviorClass: p.behaviorClass, instanceProperties: p.instanceProperties })),
    inspect_pie:            bp("Inspect PIE runtime. Params: actorLabel?", "inspect_pie"),
    get_pie_anim_state:     bp("Get PIE anim instance state. Params: actorLabel", "get_pie_anim_state"),
    get_pie_anim_properties: bp("Read arbitrary UPROPERTY values on a PIE actor's AnimInstance (#139). Params: actorLabel, propertyNames? (omit = dump all)", "get_pie_anim_properties", (p) => ({ actorLabel: p.actorLabel, propertyNames: p.propertyNames })),
    get_pie_subsystem_state: bp("Read UPROPERTY values on a running subsystem in PIE (#139). Params: subsystemClass, scope? (game|world|engine|localplayer), propertyNames?", "get_pie_subsystem_state", (p) => ({ subsystemClass: p.subsystemClass, scope: p.scope, propertyNames: p.propertyNames })),
    create_game_mode:       bp("Create GameMode BP. Params: name, packagePath?, parentClass?, defaults?", "create_game_mode"),
    create_game_state:      bp("Create GameState BP. Params: name, packagePath?, parentClass?", "create_game_state"),
    create_player_controller: bp("Create PlayerController BP. Params: name, packagePath?, parentClass?", "create_player_controller"),
    create_player_state:    bp("Create PlayerState BP. Params: name, packagePath?", "create_player_state"),
    create_hud:             bp("Create HUD BP. Params: name, packagePath?", "create_hud"),
    set_world_game_mode:    bp("Set level GameMode override. Params: gameModePath", "set_world_game_mode"),
    get_framework_info:     bp("Get level framework classes", "get_game_framework_info"),
    get_navmesh_details:    bp("Read RecastNavMesh generation params (cellSize, agentHeight, maxStepHeight, etc.) (#163)", "get_navmesh_details"),
    apply_damage_in_pie:    bp("Apply damage to PIE actor. Params: actorLabel, baseDamage?, damageTypeClass? (#186)", "apply_damage_in_pie"),
    inject_input:           bp("Single-frame Enhanced Input inject via UEnhancedInputLocalPlayerSubsystem::InjectInputForAction. Routes through the same pipeline as a real keypress (triggers, modifiers, IMC). Params: action (UInputAction path), value_x? (default 1.0), value_y?, value_z?. Requires PIE running with a local player.", "inject_input", (p) => ({ action: p.action, value_x: p.value_x, value_y: p.value_y, value_z: p.value_z })),
    inject_input_start:     bp("Begin holding an Enhanced Input action. Re-injects the value every end-of-frame until inject_input_stop. Returns injection_id (also rollback-bound to inject_input_stop). Params: action, value_x?, value_y?, value_z?, injection_id? (override the auto-generated id).", "inject_input_start", (p) => ({ action: p.action, value_x: p.value_x, value_y: p.value_y, value_z: p.value_z, injection_id: p.injection_id })),
    inject_input_update:    bp("Change the value of a running hold without releasing it. Params: injection_id, value_x?, value_y?, value_z?.", "inject_input_update", (p) => ({ injection_id: p.injection_id, value_x: p.value_x, value_y: p.value_y, value_z: p.value_z })),
    inject_input_stop:      bp("Stop a running hold or tape by id. Idempotent: returns stopped=false if no injection existed for that id. Params: injection_id.", "inject_input_stop", (p) => ({ injection_id: p.injection_id })),
    inject_input_tape:      bp("Play a per-frame value array through Enhanced Input at the given Hz. One value = one frame. Scalars or [x,y] / [x,y,z] tuples accepted per element to match the action's value type. Auto-stops at the end of the array (or inject_input_stop with the returned id). Params: action, values (array of numbers or 2/3-tuples), hz? (default 60), injection_id?.", "inject_input_tape", (p) => ({ action: p.action, values: p.values, hz: p.hz, injection_id: p.injection_id })),
    pie_record_arm:         bp("Arm a PIE input recording for the next BeginPIE (or immediately if PIE is already running). Writes manifest.json / sequence.json / recording.csv into Saved/MCPRecordings/<id>/ on EndPIE, plus tracked.jsonl when track_actors is set. Params: actions? (whitelist of UInputAction paths; empty = record all bound), track_values? (dotted reflection paths sampled to doubles per frame), track_actors? (world actor ids sampled per frame; pos/rot/vel written to tracked.jsonl), axis_threshold? (default 0.15), sample_hz? (default 60), pin_fps? (default = sample_hz; 0 to skip the t.MaxFPS pin), capture_pawn_state? (default true), capture_montage? (default true), rng_seed? (default auto), run_gap_frames? (default 6), recording_dir? (override of Saved/MCPRecordings/), id? (override the auto-generated id). Determinism note: pins FMath::RandInit and t.MaxFPS but does not affect FRandomStream or Niagara/AI RNG.", "pie_record_arm", (p) => ({ actions: p.actions, track_values: p.track_values, track_actors: p.track_actors, axis_threshold: p.axis_threshold, sample_hz: p.sample_hz, pin_fps: p.pin_fps, capture_pawn_state: p.capture_pawn_state, capture_montage: p.capture_montage, rng_seed: p.rng_seed, run_gap_frames: p.run_gap_frames, recording_dir: p.recording_dir, id: p.id })),
    pie_record_disarm:      bp("Cancel an armed (but not yet started) recording. No-op if no recording is armed. Errors if a recording is already in flight (use pie_record_stop).", "pie_record_disarm"),
    pie_record_stop:        bp("Finalize the in-flight recording immediately even if PIE has not ended. Writes manifest/sequence/csv and clears state. Returns the same shape that EndPIE finalization would produce.", "pie_record_stop"),
    pie_record_status:      bp("Recorder state: { state: idle|armed|waiting_for_pawn|recording, id, current_frame, elapsed_seconds, tracked_action_count }.", "pie_record_status"),
    pie_record_list:        bp("Enumerate recordings under Saved/MCPRecordings/ (newest first). Params: recording_dir? (override root), record_limit? (default 200), record_offset?.", "pie_record_list", (p) => ({ recording_dir: p.recording_dir, limit: p.record_limit, offset: p.record_offset })),
    pie_record_read:        bp("Read a recording artifact. Params: id, file? (manifest|sequence|csv|drift|tracked, default manifest), recording_dir?, record_limit? (CSV rows; default 1000), record_offset?. 'tracked' reads tracked.jsonl when track_actors was set on arm.", "pie_record_read", (p) => ({ id: p.id, file: p.file, recording_dir: p.recording_dir, limit: p.record_limit, offset: p.record_offset })),
    pie_record_delete:      bp("Delete a recording directory. Idempotent: returns alreadyDeleted=true if the dir is absent. Requires confirm=true to actually remove. Params: id, confirm, recording_dir?.", "pie_record_delete", (p) => ({ id: p.id, confirm: p.confirm, recording_dir: p.recording_dir })),
    pie_mark:               bp("Insert a labelled marker into the in-flight recording (or replay) timeline. No-op (active=false) when no recording/replay is running. Params: label, metadata?.", "pie_mark", (p) => ({ label: p.label, metadata: p.metadata })),
    pie_replay_arm:         bp("Arm a PIE replay for the next BeginPIE (or current PIE). Drives the recorded sequence through UEnhancedInputLocalPlayerSubsystem::InjectInputForAction (input/hold/input_tape) plus console/mark/capture steps. Writes drift.json (per-frame pawn delta vs source) when replaying a known recording_id. mode='monitor' skips step execution but keeps drift sampling running so a human can play manually against a reference recording. Params: recording_id? (loads sequence.json + recording.csv for drift), sequence_path? (explicit), steps? (inline array; same schema as sequence.json), settle_ms?, sample_hz?, pin_fps? (default = sample_hz; 0 to skip), apply_rng_seed? (default true), record_drift? (default true), auto_stop_pie? (default false), mode? ('replay' default | 'monitor'), drift_thresholds? ({ position_cm?, rotation_deg?, velocity_cms?, tracked_default?, tracked? }), rng_seed? (inline-only).", "pie_replay_arm", (p) => ({ recording_id: p.recording_id, sequence_path: p.sequence_path, steps: p.steps, recording_dir: p.recording_dir, settle_ms: p.settle_ms, sample_hz: p.sample_hz, pin_fps: p.pin_fps, apply_rng_seed: p.apply_rng_seed, record_drift: p.record_drift, auto_stop_pie: p.auto_stop_pie, mode: p.mode, drift_thresholds: p.drift_thresholds, rng_seed: p.rng_seed })),
    pie_replay_disarm:      bp("Cancel an armed (but not yet started) replay. Errors if a replay is already in flight (use pie_replay_stop).", "pie_replay_disarm"),
    pie_replay_stop:        bp("Stop the in-flight replay immediately. Releases all held injections and writes drift.json when applicable. Returns { stopped, executed_steps, drift_report_path?, max_position_drift_cm?, max_velocity_drift_cms?, frames_compared? }.", "pie_replay_stop"),
    pie_replay_status:      bp("Replay state: { state, source_recording_id, current_step, total_steps, elapsed_seconds, max_position_drift_cm, max_velocity_drift_cms }.", "pie_replay_status"),
    pie_snapshot:           bp("One-shot dump of a live PIE actor's full UProperty state to JSON. Resolves target by name, class name, or full path (first match wins). Writes <recording_dir>/<recording_id>/snapshots/<snapshot_name>.json when recording_id is supplied; Saved/MCPSnapshots/<snapshot_name>.json otherwise. Complements track_actors (which only samples pos/rot/vel per frame). Params: target, recording_id?, recording_dir?, snapshot_name? (default snapshot-<timestamp>), include_components? (default true).", "pie_snapshot", (p) => ({ target: p.target, recording_id: p.recording_id, recording_dir: p.recording_dir, name: p.snapshot_name, include_components: p.include_components })),
    pie_record_diff:        bp("Offline diff of two PIE recordings. Walks both recording.csv files in lockstep by frame index and emits position / rotation / velocity deltas, per-path tracked_value_max_deltas for reflection paths sampled in both recordings, plus the list of frames over the configurable thresholds. Pure file read; no PIE required. Params: a_id, b_id, recording_dir? (override root), position_cm? (default 5), rotation_deg? (default 2), velocity_cms? (default 25), tracked_default? (default 0 = tracked drift never trips frames_over_threshold), tracked_thresholds? (per-path map).", "pie_record_diff", (p) => ({ a_id: p.a_id, b_id: p.b_id, recording_dir: p.recording_dir, position_cm: p.position_cm, rotation_deg: p.rotation_deg, velocity_cms: p.velocity_cms, tracked_default: p.tracked_default, tracked_thresholds: p.tracked_thresholds })),
  },
  undefined,
  {
    actorLabel: z.string().optional(),
    profileName: z.string().optional(),
    simulate: z.boolean().optional(),
    collisionEnabled: z.string().optional(),
    mass: z.number().optional(),
    linearDamping: z.number().optional(),
    angularDamping: z.number().optional(),
    enableGravity: z.boolean().optional(),
    location: Vec3.optional(),
    extent: Vec3.optional(),
    start: Vec3.optional().describe("find_nav_path: query start"),
    end: Vec3.optional().describe("find_nav_path: query end"),
    pathfindingContext: z.string().optional().describe("find_nav_path: actor label whose agent/filter the query uses"),
    areaClass: z.string().optional(),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    valueType: z.string().optional(),
    directory: z.string().optional(),
    recursive: z.boolean().optional(),
    assetPath: z.string().optional(),
    blackboardPath: z.string().optional(),
    behaviorTreePath: z.string().optional().describe("BehaviorTree asset path for set_behavior_tree_blackboard"),
    keyName: z.string().optional().describe("Blackboard key name for add_blackboard_key"),
    keyType: z.string().optional().describe("Blackboard key type: Bool, Int, Float, String, Name, Vector, Rotator, Object, Class, Enum"),
    baseClass: z.string().optional().describe("Base class path for Object/Class blackboard keys (e.g. /Script/Engine.Actor)"),
    blueprintPath: z.string().optional(),
    slotIndex: z.number().optional().describe("SmartObject slot index"),
    offset: Vec3.optional().describe("SmartObject slot offset"),
    rotation: Rotator.optional().describe("SmartObject slot rotation"),
    tags: z.array(z.unknown()).optional().describe("SmartObject slot tags (gameplay tag strings or struct shapes)"),
    behaviorClass: z.string().optional().describe("SmartObject behavior class or asset path for add_smart_object_slot_behavior"),
    instanceProperties: z.record(z.unknown()).optional().describe("Property writes to apply to a freshly-spawned behavior instance"),
    senses: z.array(z.string()).optional(),
    senseType: z.string().optional(),
    settings: z.record(z.unknown()).optional(),
    parentClass: z.string().optional(),
    defaults: z.record(z.string()).optional(),
    gameModePath: z.string().optional(),
    imcPath: z.string().optional(),
    inputActionPath: z.string().optional(),
    key: z.string().optional(),
    newKey: z.string().optional().describe("New FKey name for set_imc_mapping_key"),
    newInputActionPath: z.string().optional().describe("New InputAction path for set_imc_mapping_action"),
    mappingIndex: z.number().optional().describe("Index of mapping in IMC (default 0)"),
    modifiers: z.array(z.record(z.unknown())).optional().describe("Array of modifier objects: {type, ...props}"),
    triggers: z.array(z.record(z.unknown())).optional().describe("Array of trigger objects: {type, ...props}"),
    propertyNames: z.array(z.string()).optional().describe("Property names to read for get_pie_anim_properties/get_pie_subsystem_state"),
    subsystemClass: z.string().optional().describe("Subsystem class path or short name for get_pie_subsystem_state"),
    scope: z.enum(["game", "world", "engine", "localplayer"]).optional().describe("Subsystem scope for get_pie_subsystem_state (default: game)"),
    baseDamage: z.number().optional().describe("Damage amount for apply_damage_in_pie (default 10)"),
    damageTypeClass: z.string().optional().describe("Damage type class for apply_damage_in_pie"),
    action: z.string().optional().describe("inject_input/_start/_tape: UInputAction asset path (e.g. /Game/Input/IA_Move)"),
    value_x: z.number().optional().describe("inject_input/_start/_update: X axis value (default 1.0 for Boolean)"),
    value_y: z.number().optional().describe("inject_input/_start/_update: Y axis value"),
    value_z: z.number().optional().describe("inject_input/_start/_update: Z axis value"),
    injection_id: z.string().optional().describe("Injection id returned by inject_input_start/_tape. Pass into _update/_stop."),
    values: z.array(z.unknown()).optional().describe("inject_input_tape: per-frame values array. Scalar, [x,y], or [x,y,z] per element."),
    hz: z.number().optional().describe("inject_input_tape: tape rate in Hz (default 60)"),
    actions: z.array(z.string()).optional().describe("pie_record_arm: whitelist of UInputAction asset paths to record. Empty = record all bound."),
    track_values: z.array(z.string()).optional().describe("pie_record_arm: dotted reflection paths sampled per frame (e.g. 'Hero.AbilitySystem.Health')."),
    track_actors: z.array(z.string()).optional().describe("pie_record_arm: world actors to sample per frame (matched by name, class name, or full path; first match wins). Writes tracked.jsonl with per-frame pos/rot/vel for each id."),
    axis_threshold: z.number().optional().describe("pie_record_arm: dead zone for axis edge detection (default 0.15)"),
    sample_hz: z.number().optional().describe("pie_record_arm: sample rate in Hz (default 60). Also the default for pin_fps."),
    pin_fps: z.number().optional().describe("pie_record_arm: t.MaxFPS pin during recording (default = sample_hz; 0 to skip)"),
    capture_pawn_state: z.boolean().optional().describe("pie_record_arm: include pawn location/rotation/velocity/Speed2D per row (default true)"),
    capture_montage: z.boolean().optional().describe("pie_record_arm: include 'Montage:Section' per row (default true)"),
    take_record: z.boolean().optional().describe("pie_record_arm: also drive Take Recorder Start/Stop in lockstep with BeginPIE / EndPIE. Requires the Take Recorder plugin enabled and an open Take Recorder panel with sources configured. pie_record_stop returns take_recorder_status with the outcome (started / skipped / stopped, plus the reason)."),
    client_id: z.number().optional().describe("pie_record_arm / pie_replay_arm / inject_input*: which local player to sample, replay, or inject into. 0 (default) = first local player; 1+ selects subsequent local players in multi-client PIE sessions. To record multiple clients in one PIE session, call pie_record_arm once per client_id with different ids."),
    rng_seed: z.number().optional().describe("pie_record_arm: explicit RNG seed (default auto). Reapplied via FMath::RandInit on attach."),
    run_gap_frames: z.number().optional().describe("pie_record_arm: gap-tolerance frames for axis run extraction in sequence.json (default 6)"),
    recording_dir: z.string().optional().describe("pie_record_arm/list/read/delete: override of Saved/MCPRecordings/"),
    id: z.string().optional().describe("pie_record_arm: override the auto-generated recording id. pie_record_read/delete: the id to operate on."),
    file: z.string().optional().describe("pie_record_read: which artifact to return (manifest|sequence|csv|drift, default manifest)"),
    record_limit: z.number().optional().describe("pie_record_list/read: max rows/entries"),
    record_offset: z.number().optional().describe("pie_record_list/read: rows/entries to skip"),
    confirm: z.boolean().optional().describe("pie_record_delete: must be true to actually delete"),
    label: z.string().optional().describe("pie_mark: marker label"),
    metadata: z.record(z.unknown()).optional().describe("pie_mark: optional structured metadata"),
    recording_id: z.string().optional().describe("pie_replay_arm: id of recording to replay (loads sequence.json + recording.csv)"),
    sequence_path: z.string().optional().describe("pie_replay_arm: explicit path to a sequence.json (alternative to recording_id)"),
    steps: z.array(z.unknown()).optional().describe("pie_replay_arm: inline step array (same schema as sequence.json)"),
    settle_ms: z.number().optional().describe("pie_replay_arm: delay after pawn attach before the first step fires (default = sequence's setting, 500ms)"),
    apply_rng_seed: z.boolean().optional().describe("pie_replay_arm: reapply sequence.rng_seed via FMath::RandInit (default true)"),
    record_drift: z.boolean().optional().describe("pie_replay_arm: sample replay state and emit drift.json (default true when recording_id is set)"),
    auto_stop_pie: z.boolean().optional().describe("pie_replay_arm: stop PIE on sequence completion (default false)"),
    mode: z.string().optional().describe("pie_replay_arm: 'replay' (default) injects inputs and drives the sequence; 'monitor' skips step execution but keeps drift sampling running so a human can play manually against a reference recording."),
    capture_frame_every: z.number().optional().describe("pie_replay_arm: when > 0, write a viewport screenshot every Nth sampled frame to <recording_dir>/frames/. pie_replay_stop returns ffmpeg hints for assembling the PNG sequence into a GIF or MP4."),
    drift_thresholds: z.record(z.unknown()).optional().describe("pie_replay_arm: { position_cm?, rotation_deg?, velocity_cms?, tracked_default?, tracked? } cutoffs for over-threshold frame list. tracked is a per-path map (path -> threshold); tracked_default applies to paths without an explicit entry. 0 disables tracked-value triggering."),
    a_id: z.string().optional().describe("pie_record_diff: id of recording A"),
    b_id: z.string().optional().describe("pie_record_diff: id of recording B"),
    position_cm: z.number().optional().describe("pie_record_diff: position delta threshold in cm (default 5)"),
    rotation_deg: z.number().optional().describe("pie_record_diff: rotation delta threshold in degrees (default 2)"),
    velocity_cms: z.number().optional().describe("pie_record_diff: velocity delta threshold in cm/s (default 25)"),
    tracked_default: z.number().optional().describe("pie_record_diff: default per-path delta threshold applied to tracked-value columns that are not in tracked_thresholds (default 0 = don't trigger)"),
    tracked_thresholds: z.record(z.number()).optional().describe("pie_record_diff: per-path delta thresholds keyed by reflection path. A frame is over-threshold if any path's |delta| exceeds its entry (or tracked_default when absent)."),
    target: z.string().optional().describe("pie_snapshot: actor identifier (name, class name, or full path)"),
    snapshot_name: z.string().optional().describe("pie_snapshot: filename basename (default snapshot-<timestamp>)"),
    include_components: z.boolean().optional().describe("pie_snapshot: also dump UActorComponents (default true)"),
  },
);
