// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/definition"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResourcesFactory creates a new instance of MockResourcesFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourcesFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourcesFactory {
	mock := &MockResourcesFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourcesFactory is an autogenerated mock type for the ResourcesFactory type
type MockResourcesFactory struct {
	mock.Mock
}

type MockResourcesFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourcesFactory) EXPECT() *MockResourcesFactory_Expecter {
	return &MockResourcesFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockResourcesFactory
func (_mock *MockResourcesFactory) New(internal definition.DependenciesProviderResources) publictypes.DependenciesProviderResources {
	ret := _mock.Called(internal)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 publictypes.DependenciesProviderResources
	if returnFunc, ok := ret.Get(0).(func(definition.DependenciesProviderResources) publictypes.DependenciesProviderResources); ok {
		r0 = returnFunc(internal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.DependenciesProviderResources)
		}
	}
	return r0
}

// MockResourcesFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockResourcesFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - internal definition.DependenciesProviderResources
func (_e *MockResourcesFactory_Expecter) New(internal interface{}) *MockResourcesFactory_New_Call {
	return &MockResourcesFactory_New_Call{Call: _e.mock.On("New", internal)}
}

func (_c *MockResourcesFactory_New_Call) Run(run func(internal definition.DependenciesProviderResources)) *MockResourcesFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 definition.DependenciesProviderResources
		if args[0] != nil {
			arg0 = args[0].(definition.DependenciesProviderResources)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResourcesFactory_New_Call) Return(dependenciesProviderResources publictypes.DependenciesProviderResources) *MockResourcesFactory_New_Call {
	_c.Call.Return(dependenciesProviderResources)
	return _c
}

func (_c *MockResourcesFactory_New_Call) RunAndReturn(run func(internal definition.DependenciesProviderResources) publictypes.DependenciesProviderResources) *MockResourcesFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
