// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIOLayer creates a new instance of MockIOLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOLayer {
	mock := &MockIOLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIOLayer is an autogenerated mock type for the IOLayer type
type MockIOLayer struct {
	mock.Mock
}

type MockIOLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOLayer) EXPECT() *MockIOLayer_Expecter {
	return &MockIOLayer_Expecter{mock: &_m.Mock}
}

// ReadAll provides a mock function for the type MockIOLayer
func (_mock *MockIOLayer) ReadAll(r io.Reader) ([]byte, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ReadAll")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader) ([]byte, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(io.Reader) []byte); ok {
		r0 = returnFunc(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(io.Reader) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIOLayer_ReadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAll'
type MockIOLayer_ReadAll_Call struct {
	*mock.Call
}

// ReadAll is a helper method to define mock.On call
//   - r io.Reader
func (_e *MockIOLayer_Expecter) ReadAll(r interface{}) *MockIOLayer_ReadAll_Call {
	return &MockIOLayer_ReadAll_Call{Call: _e.mock.On("ReadAll", r)}
}

func (_c *MockIOLayer_ReadAll_Call) Run(run func(r io.Reader)) *MockIOLayer_ReadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIOLayer_ReadAll_Call) Return(bytes []byte, err error) *MockIOLayer_ReadAll_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockIOLayer_ReadAll_Call) RunAndReturn(run func(r io.Reader) ([]byte, error)) *MockIOLayer_ReadAll_Call {
	_c.Call.Return(run)
	return _c
}
