// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Open(path string) (osfacade.File, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 osfacade.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (osfacade.File, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) osfacade.File); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOSLayer_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockOSLayer_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - path string
func (_e *MockOSLayer_Expecter) Open(path interface{}) *MockOSLayer_Open_Call {
	return &MockOSLayer_Open_Call{Call: _e.mock.On("Open", path)}
}

func (_c *MockOSLayer_Open_Call) Run(run func(path string)) *MockOSLayer_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_Open_Call) Return(file osfacade.File, err error) *MockOSLayer_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockOSLayer_Open_Call) RunAndReturn(run func(path string) (osfacade.File, error)) *MockOSLayer_Open_Call {
	_c.Call.Return(run)
	return _c
}
