// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/matlabmanager/matlabsessionclient/embeddedconnector"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABSessionClientFactory creates a new instance of MockMATLABSessionClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABSessionClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABSessionClientFactory {
	mock := &MockMATLABSessionClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABSessionClientFactory is an autogenerated mock type for the MATLABSessionClientFactory type
type MockMATLABSessionClientFactory struct {
	mock.Mock
}

type MockMATLABSessionClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABSessionClientFactory) EXPECT() *MockMATLABSessionClientFactory_Expecter {
	return &MockMATLABSessionClientFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockMATLABSessionClientFactory
func (_mock *MockMATLABSessionClientFactory) New(endpoint embeddedconnector.ConnectionDetails) (entities.MATLABSessionClient, error) {
	ret := _mock.Called(endpoint)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 entities.MATLABSessionClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(embeddedconnector.ConnectionDetails) (entities.MATLABSessionClient, error)); ok {
		return returnFunc(endpoint)
	}
	if returnFunc, ok := ret.Get(0).(func(embeddedconnector.ConnectionDetails) entities.MATLABSessionClient); ok {
		r0 = returnFunc(endpoint)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.MATLABSessionClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(embeddedconnector.ConnectionDetails) error); ok {
		r1 = returnFunc(endpoint)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABSessionClientFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockMATLABSessionClientFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - endpoint embeddedconnector.ConnectionDetails
func (_e *MockMATLABSessionClientFactory_Expecter) New(endpoint interface{}) *MockMATLABSessionClientFactory_New_Call {
	return &MockMATLABSessionClientFactory_New_Call{Call: _e.mock.On("New", endpoint)}
}

func (_c *MockMATLABSessionClientFactory_New_Call) Run(run func(endpoint embeddedconnector.ConnectionDetails)) *MockMATLABSessionClientFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 embeddedconnector.ConnectionDetails
		if args[0] != nil {
			arg0 = args[0].(embeddedconnector.ConnectionDetails)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMATLABSessionClientFactory_New_Call) Return(mATLABSessionClient entities.MATLABSessionClient, err error) *MockMATLABSessionClientFactory_New_Call {
	_c.Call.Return(mATLABSessionClient, err)
	return _c
}

func (_c *MockMATLABSessionClientFactory_New_Call) RunAndReturn(run func(endpoint embeddedconnector.ConnectionDetails) (entities.MATLABSessionClient, error)) *MockMATLABSessionClientFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
