cmake_minimum_required(VERSION 3.0.2)
project(sunray_ugv_control)

## Compile as C++11, supported in ROS Kinetic and newer
# add_compile_options(-std=c++11)

## Find catkin macros and libraries
## if COMPONENTS list like find_package(catkin REQUIRED COMPONENTS xyz)
## is used, also find other catkin packages

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(octomap_msgs_DIR /home/yundrone/app/octomap_msgs/build/devel/share/octomap_msgs/cmake/octomap_msgsConfig.cmake)
find_package(octomap_msgs REQUIRED)
find_package(octomap REQUIRED)
find_package(PCL REQUIRED)
find_package(catkin REQUIRED COMPONENTS
  roscpp
  rospy
  std_msgs
  pcl_msgs
  laser_geometry
  nav_msgs
  pcl_ros
  sunray_msgs
  nav_msgs
  geometry_msgs
	pcl_conversions
	sensor_msgs
	tf2
  tf2_ros
  tf2_sensor_msgs
  sensor_msgs
)

catkin_package(
#  INCLUDE_DIRS include
#  LIBRARIES ugv_planning
#  CATKIN_DEPENDS octomap roscpp rospy std_msgs
#  DEPENDS system_lib
CATKIN_DEPENDS rospy nav_msgs geometry_msgs tf2 tf2_ros tf2_sensor_msgs sensor_msgs
)

include_directories(
  include
  ${catkin_INCLUDE_DIRS}
  ${PCL_INCLUDE_DIRS}
  ${OCTOMAP_INCLUDE_DIRS}
  ${PROJECT_SOURCE_DIR}/../sunray_common/common_lib
)

link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})


add_library(UGVControl ugv_control/UGVControl.cpp)

add_executable(AstarMap ugv_control/AstarMap.cpp)
target_link_libraries(AstarMap 
                        ${catkin_LIBRARIES}
                        ${OCTOMAP_LIBRARIES}
                        ${PCL_LIBRARIES}
                        # astar_lib
                        )

add_executable(astar ugv_control/Astar.cpp)
target_link_libraries(astar ${catkin_LIBRARIES})    


add_executable(mocap2odom ugv_control/mocap2odom.cpp)
target_link_libraries(mocap2odom ${catkin_LIBRARIES})



add_executable(ugv_terminal_control ugv_control/ugv_terminal_control.cpp)
target_link_libraries(ugv_terminal_control
    ${catkin_LIBRARIES}
    octomap
    octomath
)

add_executable(ugv_control_node ugv_control/ugv_control_node.cpp)
target_link_libraries(ugv_control_node 
                        ${catkin_LIBRARIES}
                        ${OCTOMAP_LIBRARIES}
                        ${PCL_LIBRARIES}
                        UGVControl
                        # astar_lib
                        # map_generator_lib
                        )

## 安装Python脚本
catkin_install_python(PROGRAMS
  scripts/OccupancyGrid_pgm.py  # 脚本路径
  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
)


include_directories(SYSTEM ${PCL_INCLUDE_DIRS})

add_executable(pointcloud_aligner_node ugv_control/pointcloud_aligner_node.cpp)
target_link_libraries(pointcloud_aligner_node ${catkin_LIBRARIES} ${PCL_LIBRARIES})

add_executable(bridge_node ugv_control/bridge.cpp)
target_link_libraries(bridge_node ${catkin_LIBRARIES})

