exploration:
  global_frame: "world"
  base_link_frame: "base_link"
  depth: 14
  radius: 5.5
  bbx_minX: -98.40496
  bbx_maxX: 77.25491
  bbx_minY: -51.36291
  bbx_maxY: 12.63665
  bbx_minZ: 0.9
  bbx_maxZ: 1.6
  box_length: 8.0
  k_gain: 100.0
  lambda: 0.1386
  volume: 16864
sensor_model:
  horizontalFOV: 360
  verticalFOV: 30
  max_range: 10
  pitch_angle: 10.0
  probability_hit: 0.7
  probability_miss: 0.4
  clamping_thres_min: 0.12
  clamping_thres_max: 0.97
octomap:
  resolution: 0.5
  octree_depth: 16
  filename: "factory_l2_indoor_uav_frontier.bt"
  file_path: "/tmp/"
clustering:
  kernel_bandwidth: 2
