// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// AddResource provides a mock function for the type MockServer
func (_mock *MockServer) AddResource(resource *mcp.Resource, handler mcp.ResourceHandler) {
	_mock.Called(resource, handler)
	return
}

// MockServer_AddResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddResource'
type MockServer_AddResource_Call struct {
	*mock.Call
}

// AddResource is a helper method to define mock.On call
//   - resource *mcp.Resource
//   - handler mcp.ResourceHandler
func (_e *MockServer_Expecter) AddResource(resource interface{}, handler interface{}) *MockServer_AddResource_Call {
	return &MockServer_AddResource_Call{Call: _e.mock.On("AddResource", resource, handler)}
}

func (_c *MockServer_AddResource_Call) Run(run func(resource *mcp.Resource, handler mcp.ResourceHandler)) *MockServer_AddResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *mcp.Resource
		if args[0] != nil {
			arg0 = args[0].(*mcp.Resource)
		}
		var arg1 mcp.ResourceHandler
		if args[1] != nil {
			arg1 = args[1].(mcp.ResourceHandler)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServer_AddResource_Call) Return() *MockServer_AddResource_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_AddResource_Call) RunAndReturn(run func(resource *mcp.Resource, handler mcp.ResourceHandler)) *MockServer_AddResource_Call {
	_c.Run(run)
	return _c
}
