// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockI18nErrorFactory creates a new instance of MockI18nErrorFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockI18nErrorFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockI18nErrorFactory {
	mock := &MockI18nErrorFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockI18nErrorFactory is an autogenerated mock type for the I18nErrorFactory type
type MockI18nErrorFactory struct {
	mock.Mock
}

type MockI18nErrorFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockI18nErrorFactory) EXPECT() *MockI18nErrorFactory_Expecter {
	return &MockI18nErrorFactory_Expecter{mock: &_m.Mock}
}

// FromInternalError provides a mock function for the type MockI18nErrorFactory
func (_mock *MockI18nErrorFactory) FromInternalError(internalError messages.Error) publictypes.Error {
	ret := _mock.Called(internalError)

	if len(ret) == 0 {
		panic("no return value specified for FromInternalError")
	}

	var r0 publictypes.Error
	if returnFunc, ok := ret.Get(0).(func(messages.Error) publictypes.Error); ok {
		r0 = returnFunc(internalError)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.Error)
		}
	}
	return r0
}

// MockI18nErrorFactory_FromInternalError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromInternalError'
type MockI18nErrorFactory_FromInternalError_Call struct {
	*mock.Call
}

// FromInternalError is a helper method to define mock.On call
//   - internalError messages.Error
func (_e *MockI18nErrorFactory_Expecter) FromInternalError(internalError interface{}) *MockI18nErrorFactory_FromInternalError_Call {
	return &MockI18nErrorFactory_FromInternalError_Call{Call: _e.mock.On("FromInternalError", internalError)}
}

func (_c *MockI18nErrorFactory_FromInternalError_Call) Run(run func(internalError messages.Error)) *MockI18nErrorFactory_FromInternalError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 messages.Error
		if args[0] != nil {
			arg0 = args[0].(messages.Error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockI18nErrorFactory_FromInternalError_Call) Return(error publictypes.Error) *MockI18nErrorFactory_FromInternalError_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *MockI18nErrorFactory_FromInternalError_Call) RunAndReturn(run func(internalError messages.Error) publictypes.Error) *MockI18nErrorFactory_FromInternalError_Call {
	_c.Call.Return(run)
	return _c
}
