// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLifecycleSignaler creates a new instance of MockLifecycleSignaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLifecycleSignaler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLifecycleSignaler {
	mock := &MockLifecycleSignaler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLifecycleSignaler is an autogenerated mock type for the LifecycleSignaler type
type MockLifecycleSignaler struct {
	mock.Mock
}

type MockLifecycleSignaler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLifecycleSignaler) EXPECT() *MockLifecycleSignaler_Expecter {
	return &MockLifecycleSignaler_Expecter{mock: &_m.Mock}
}

// AddShutdownFunction provides a mock function for the type MockLifecycleSignaler
func (_mock *MockLifecycleSignaler) AddShutdownFunction(shutdownFcn func() error) {
	_mock.Called(shutdownFcn)
	return
}

// MockLifecycleSignaler_AddShutdownFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddShutdownFunction'
type MockLifecycleSignaler_AddShutdownFunction_Call struct {
	*mock.Call
}

// AddShutdownFunction is a helper method to define mock.On call
//   - shutdownFcn func() error
func (_e *MockLifecycleSignaler_Expecter) AddShutdownFunction(shutdownFcn interface{}) *MockLifecycleSignaler_AddShutdownFunction_Call {
	return &MockLifecycleSignaler_AddShutdownFunction_Call{Call: _e.mock.On("AddShutdownFunction", shutdownFcn)}
}

func (_c *MockLifecycleSignaler_AddShutdownFunction_Call) Run(run func(shutdownFcn func() error)) *MockLifecycleSignaler_AddShutdownFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() error
		if args[0] != nil {
			arg0 = args[0].(func() error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLifecycleSignaler_AddShutdownFunction_Call) Return() *MockLifecycleSignaler_AddShutdownFunction_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLifecycleSignaler_AddShutdownFunction_Call) RunAndReturn(run func(shutdownFcn func() error)) *MockLifecycleSignaler_AddShutdownFunction_Call {
	_c.Run(run)
	return _c
}
