// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistryKey creates a new instance of MockRegistryKey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryKey(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryKey {
	mock := &MockRegistryKey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistryKey is an autogenerated mock type for the RegistryKey type
type MockRegistryKey struct {
	mock.Mock
}

type MockRegistryKey_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistryKey) EXPECT() *MockRegistryKey_Expecter {
	return &MockRegistryKey_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockRegistryKey
func (_mock *MockRegistryKey) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistryKey_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRegistryKey_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRegistryKey_Expecter) Close() *MockRegistryKey_Close_Call {
	return &MockRegistryKey_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRegistryKey_Close_Call) Run(run func()) *MockRegistryKey_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistryKey_Close_Call) Return(err error) *MockRegistryKey_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistryKey_Close_Call) RunAndReturn(run func() error) *MockRegistryKey_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetStringValue provides a mock function for the type MockRegistryKey
func (_mock *MockRegistryKey) GetStringValue(name string) (string, uint32, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetStringValue")
	}

	var r0 string
	var r1 uint32
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, uint32, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) uint32); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(uint32)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRegistryKey_GetStringValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStringValue'
type MockRegistryKey_GetStringValue_Call struct {
	*mock.Call
}

// GetStringValue is a helper method to define mock.On call
//   - name string
func (_e *MockRegistryKey_Expecter) GetStringValue(name interface{}) *MockRegistryKey_GetStringValue_Call {
	return &MockRegistryKey_GetStringValue_Call{Call: _e.mock.On("GetStringValue", name)}
}

func (_c *MockRegistryKey_GetStringValue_Call) Run(run func(name string)) *MockRegistryKey_GetStringValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRegistryKey_GetStringValue_Call) Return(s string, v uint32, err error) *MockRegistryKey_GetStringValue_Call {
	_c.Call.Return(s, v, err)
	return _c
}

func (_c *MockRegistryKey_GetStringValue_Call) RunAndReturn(run func(name string) (string, uint32, error)) *MockRegistryKey_GetStringValue_Call {
	_c.Call.Return(run)
	return _c
}
