// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInternalConfig creates a new instance of MockInternalConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInternalConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInternalConfig {
	mock := &MockInternalConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInternalConfig is an autogenerated mock type for the InternalConfig type
type MockInternalConfig struct {
	mock.Mock
}

type MockInternalConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInternalConfig) EXPECT() *MockInternalConfig_Expecter {
	return &MockInternalConfig_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockInternalConfig
func (_mock *MockInternalConfig) Get(key string) (any, messages.Error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 messages.Error
	if returnFunc, ok := ret.Get(0).(func(string) (any, messages.Error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) messages.Error); ok {
		r1 = returnFunc(key)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(messages.Error)
		}
	}
	return r0, r1
}

// MockInternalConfig_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockInternalConfig_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockInternalConfig_Expecter) Get(key interface{}) *MockInternalConfig_Get_Call {
	return &MockInternalConfig_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockInternalConfig_Get_Call) Run(run func(key string)) *MockInternalConfig_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInternalConfig_Get_Call) Return(v any, error messages.Error) *MockInternalConfig_Get_Call {
	_c.Call.Return(v, error)
	return _c
}

func (_c *MockInternalConfig_Get_Call) RunAndReturn(run func(key string) (any, messages.Error)) *MockInternalConfig_Get_Call {
	_c.Call.Return(run)
	return _c
}
