// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/config"
	mock "github.com/stretchr/testify/mock"
)

// newMockparameter creates a new instance of mockparameter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockparameter[ParameterType config.SupportedParameterValueType](t interface {
	mock.TestingT
	Cleanup(func())
}) *mockparameter[ParameterType] {
	mock := &mockparameter[ParameterType]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockparameter is an autogenerated mock type for the parameter type
type mockparameter[ParameterType config.SupportedParameterValueType] struct {
	mock.Mock
}

type mockparameter_Expecter[ParameterType config.SupportedParameterValueType] struct {
	mock *mock.Mock
}

func (_m *mockparameter[ParameterType]) EXPECT() *mockparameter_Expecter[ParameterType] {
	return &mockparameter_Expecter[ParameterType]{mock: &_m.Mock}
}

// GetID provides a mock function for the type mockparameter
func (_mock *mockparameter[ParameterType]) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockparameter_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type mockparameter_GetID_Call[ParameterType config.SupportedParameterValueType] struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *mockparameter_Expecter[ParameterType]) GetID() *mockparameter_GetID_Call[ParameterType] {
	return &mockparameter_GetID_Call[ParameterType]{Call: _e.mock.On("GetID")}
}

func (_c *mockparameter_GetID_Call[ParameterType]) Run(run func()) *mockparameter_GetID_Call[ParameterType] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockparameter_GetID_Call[ParameterType]) Return(s string) *mockparameter_GetID_Call[ParameterType] {
	_c.Call.Return(s)
	return _c
}

func (_c *mockparameter_GetID_Call[ParameterType]) RunAndReturn(run func() string) *mockparameter_GetID_Call[ParameterType] {
	_c.Call.Return(run)
	return _c
}
