name = "Example"
uuid = "11d21e96-2442-41e9-9bdc-dfd03454ecfc"
authors = [" <>"]
version = "0.0.1"
description = ""

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
    