// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfig creates a new instance of MockConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfig {
	mock := &MockConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

type MockConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfig) EXPECT() *MockConfig_Expecter {
	return &MockConfig_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockConfig
func (_mock *MockConfig) Get(key string, expectedType any) (any, publictypes.Error) {
	ret := _mock.Called(key, expectedType)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	var r1 publictypes.Error
	if returnFunc, ok := ret.Get(0).(func(string, any) (any, publictypes.Error)); ok {
		return returnFunc(key, expectedType)
	}
	if returnFunc, ok := ret.Get(0).(func(string, any) any); ok {
		r0 = returnFunc(key, expectedType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, any) publictypes.Error); ok {
		r1 = returnFunc(key, expectedType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(publictypes.Error)
		}
	}
	return r0, r1
}

// MockConfig_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockConfig_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
//   - expectedType any
func (_e *MockConfig_Expecter) Get(key interface{}, expectedType interface{}) *MockConfig_Get_Call {
	return &MockConfig_Get_Call{Call: _e.mock.On("Get", key, expectedType)}
}

func (_c *MockConfig_Get_Call) Run(run func(key string, expectedType any)) *MockConfig_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfig_Get_Call) Return(v any, error publictypes.Error) *MockConfig_Get_Call {
	_c.Call.Return(v, error)
	return _c
}

func (_c *MockConfig_Get_Call) RunAndReturn(run func(key string, expectedType any) (any, publictypes.Error)) *MockConfig_Get_Call {
	_c.Call.Return(run)
	return _c
}
