// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolCallRequest creates a new instance of MockToolCallRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolCallRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolCallRequest {
	mock := &MockToolCallRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolCallRequest is an autogenerated mock type for the ToolCallRequest type
type MockToolCallRequest struct {
	mock.Mock
}

type MockToolCallRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolCallRequest) EXPECT() *MockToolCallRequest_Expecter {
	return &MockToolCallRequest_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockToolCallRequest
func (_mock *MockToolCallRequest) Config() publictypes.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 publictypes.Config
	if returnFunc, ok := ret.Get(0).(func() publictypes.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.Config)
		}
	}
	return r0
}

// MockToolCallRequest_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockToolCallRequest_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockToolCallRequest_Expecter) Config() *MockToolCallRequest_Config_Call {
	return &MockToolCallRequest_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockToolCallRequest_Config_Call) Run(run func()) *MockToolCallRequest_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolCallRequest_Config_Call) Return(config publictypes.Config) *MockToolCallRequest_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockToolCallRequest_Config_Call) RunAndReturn(run func() publictypes.Config) *MockToolCallRequest_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockToolCallRequest
func (_mock *MockToolCallRequest) Logger() publictypes.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 publictypes.Logger
	if returnFunc, ok := ret.Get(0).(func() publictypes.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.Logger)
		}
	}
	return r0
}

// MockToolCallRequest_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockToolCallRequest_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockToolCallRequest_Expecter) Logger() *MockToolCallRequest_Logger_Call {
	return &MockToolCallRequest_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockToolCallRequest_Logger_Call) Run(run func()) *MockToolCallRequest_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolCallRequest_Logger_Call) Return(logger publictypes.Logger) *MockToolCallRequest_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockToolCallRequest_Logger_Call) RunAndReturn(run func() publictypes.Logger) *MockToolCallRequest_Logger_Call {
	_c.Call.Return(run)
	return _c
}
