// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolsProviderResources creates a new instance of MockToolsProviderResources. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolsProviderResources[Dependencies any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolsProviderResources[Dependencies] {
	mock := &MockToolsProviderResources[Dependencies]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolsProviderResources is an autogenerated mock type for the ToolsProviderResources type
type MockToolsProviderResources[Dependencies any] struct {
	mock.Mock
}

type MockToolsProviderResources_Expecter[Dependencies any] struct {
	mock *mock.Mock
}

func (_m *MockToolsProviderResources[Dependencies]) EXPECT() *MockToolsProviderResources_Expecter[Dependencies] {
	return &MockToolsProviderResources_Expecter[Dependencies]{mock: &_m.Mock}
}

// Dependencies provides a mock function for the type MockToolsProviderResources
func (_mock *MockToolsProviderResources[Dependencies]) Dependencies() Dependencies {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dependencies")
	}

	var r0 Dependencies
	if returnFunc, ok := ret.Get(0).(func() Dependencies); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Dependencies)
		}
	}
	return r0
}

// MockToolsProviderResources_Dependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dependencies'
type MockToolsProviderResources_Dependencies_Call[Dependencies any] struct {
	*mock.Call
}

// Dependencies is a helper method to define mock.On call
func (_e *MockToolsProviderResources_Expecter[Dependencies]) Dependencies() *MockToolsProviderResources_Dependencies_Call[Dependencies] {
	return &MockToolsProviderResources_Dependencies_Call[Dependencies]{Call: _e.mock.On("Dependencies")}
}

func (_c *MockToolsProviderResources_Dependencies_Call[Dependencies]) Run(run func()) *MockToolsProviderResources_Dependencies_Call[Dependencies] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolsProviderResources_Dependencies_Call[Dependencies]) Return(v Dependencies) *MockToolsProviderResources_Dependencies_Call[Dependencies] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockToolsProviderResources_Dependencies_Call[Dependencies]) RunAndReturn(run func() Dependencies) *MockToolsProviderResources_Dependencies_Call[Dependencies] {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockToolsProviderResources
func (_mock *MockToolsProviderResources[Dependencies]) Logger() publictypes.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 publictypes.Logger
	if returnFunc, ok := ret.Get(0).(func() publictypes.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.Logger)
		}
	}
	return r0
}

// MockToolsProviderResources_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockToolsProviderResources_Logger_Call[Dependencies any] struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockToolsProviderResources_Expecter[Dependencies]) Logger() *MockToolsProviderResources_Logger_Call[Dependencies] {
	return &MockToolsProviderResources_Logger_Call[Dependencies]{Call: _e.mock.On("Logger")}
}

func (_c *MockToolsProviderResources_Logger_Call[Dependencies]) Run(run func()) *MockToolsProviderResources_Logger_Call[Dependencies] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockToolsProviderResources_Logger_Call[Dependencies]) Return(logger publictypes.Logger) *MockToolsProviderResources_Logger_Call[Dependencies] {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockToolsProviderResources_Logger_Call[Dependencies]) RunAndReturn(run func() publictypes.Logger) *MockToolsProviderResources_Logger_Call[Dependencies] {
	_c.Call.Return(run)
	return _c
}
