// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockWatchdog creates a new instance of MockWatchdog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchdog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchdog {
	mock := &MockWatchdog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatchdog is an autogenerated mock type for the Watchdog type
type MockWatchdog struct {
	mock.Mock
}

type MockWatchdog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchdog) EXPECT() *MockWatchdog_Expecter {
	return &MockWatchdog_Expecter{mock: &_m.Mock}
}

// WatchProcess provides a mock function for the type MockWatchdog
func (_mock *MockWatchdog) WatchProcess(pid int) {
	_mock.Called(pid)
	return
}

// MockWatchdog_WatchProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchProcess'
type MockWatchdog_WatchProcess_Call struct {
	*mock.Call
}

// WatchProcess is a helper method to define mock.On call
//   - pid int
func (_e *MockWatchdog_Expecter) WatchProcess(pid interface{}) *MockWatchdog_WatchProcess_Call {
	return &MockWatchdog_WatchProcess_Call{Call: _e.mock.On("WatchProcess", pid)}
}

func (_c *MockWatchdog_WatchProcess_Call) Run(run func(pid int)) *MockWatchdog_WatchProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWatchdog_WatchProcess_Call) Return() *MockWatchdog_WatchProcess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWatchdog_WatchProcess_Call) RunAndReturn(run func(pid int)) *MockWatchdog_WatchProcess_Call {
	_c.Run(run)
	return _c
}
