// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSLayer creates a new instance of MockOSLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSLayer {
	mock := &MockOSLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSLayer is an autogenerated mock type for the OSLayer type
type MockOSLayer struct {
	mock.Mock
}

type MockOSLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSLayer) EXPECT() *MockOSLayer_Expecter {
	return &MockOSLayer_Expecter{mock: &_m.Mock}
}

// Stat provides a mock function for the type MockOSLayer
func (_mock *MockOSLayer) Stat(filePath string) (osfacade.FileInfo, error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 osfacade.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (osfacade.FileInfo, error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) osfacade.FileInfo); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOSLayer_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockOSLayer_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - filePath string
func (_e *MockOSLayer_Expecter) Stat(filePath interface{}) *MockOSLayer_Stat_Call {
	return &MockOSLayer_Stat_Call{Call: _e.mock.On("Stat", filePath)}
}

func (_c *MockOSLayer_Stat_Call) Run(run func(filePath string)) *MockOSLayer_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSLayer_Stat_Call) Return(fileInfo osfacade.FileInfo, err error) *MockOSLayer_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockOSLayer_Stat_Call) RunAndReturn(run func(filePath string) (osfacade.FileInfo, error)) *MockOSLayer_Stat_Call {
	_c.Call.Return(run)
	return _c
}
