/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: d33755722e998d7e325bd5768c52cf72)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Assistant";
  }
  interface Env {
    AI: Ai;
    Assistant: DurableObjectNamespace<import("./src/server").Assistant>;
  }
}
interface Env extends Cloudflare.Env {}
