// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// Start provides a mock function for the type MockServer
func (_mock *MockServer) Start(socketPath string) error {
	ret := _mock.Called(socketPath)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(socketPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockServer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - socketPath string
func (_e *MockServer_Expecter) Start(socketPath interface{}) *MockServer_Start_Call {
	return &MockServer_Start_Call{Call: _e.mock.On("Start", socketPath)}
}

func (_c *MockServer_Start_Call) Run(run func(socketPath string)) *MockServer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServer_Start_Call) Return(err error) *MockServer_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServer_Start_Call) RunAndReturn(run func(socketPath string) error) *MockServer_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockServer
func (_mock *MockServer) Stop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockServer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockServer_Expecter) Stop() *MockServer_Stop_Call {
	return &MockServer_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockServer_Stop_Call) Run(run func()) *MockServer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServer_Stop_Call) Return(err error) *MockServer_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServer_Stop_Call) RunAndReturn(run func() error) *MockServer_Stop_Call {
	_c.Call.Return(run)
	return _c
}
