/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 947710528bf88df36c6f0d9a4b38636c)
interface __BaseEnv_Env {
  AI: Ai;
  DeployChurnAgent: DurableObjectNamespace<
    import("./src/server").DeployChurnAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "DeployChurnAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
