// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMCPSession creates a new instance of MockMCPSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMCPSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMCPSession {
	mock := &MockMCPSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMCPSession is an autogenerated mock type for the MCPSession type
type MockMCPSession struct {
	mock.Mock
}

type MockMCPSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMCPSession) EXPECT() *MockMCPSession_Expecter {
	return &MockMCPSession_Expecter{mock: &_m.Mock}
}

// InitializeParams provides a mock function for the type MockMCPSession
func (_mock *MockMCPSession) InitializeParams() *mcp.InitializeParams {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitializeParams")
	}

	var r0 *mcp.InitializeParams
	if returnFunc, ok := ret.Get(0).(func() *mcp.InitializeParams); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.InitializeParams)
		}
	}
	return r0
}

// MockMCPSession_InitializeParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeParams'
type MockMCPSession_InitializeParams_Call struct {
	*mock.Call
}

// InitializeParams is a helper method to define mock.On call
func (_e *MockMCPSession_Expecter) InitializeParams() *MockMCPSession_InitializeParams_Call {
	return &MockMCPSession_InitializeParams_Call{Call: _e.mock.On("InitializeParams")}
}

func (_c *MockMCPSession_InitializeParams_Call) Run(run func()) *MockMCPSession_InitializeParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMCPSession_InitializeParams_Call) Return(initializeParams *mcp.InitializeParams) *MockMCPSession_InitializeParams_Call {
	_c.Call.Return(initializeParams)
	return _c
}

func (_c *MockMCPSession_InitializeParams_Call) RunAndReturn(run func() *mcp.InitializeParams) *MockMCPSession_InitializeParams_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoots provides a mock function for the type MockMCPSession
func (_mock *MockMCPSession) ListRoots(ctx context.Context, params *mcp.ListRootsParams) (*mcp.ListRootsResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListRoots")
	}

	var r0 *mcp.ListRootsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *mcp.ListRootsParams) (*mcp.ListRootsResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *mcp.ListRootsParams) *mcp.ListRootsResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.ListRootsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *mcp.ListRootsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPSession_ListRoots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoots'
type MockMCPSession_ListRoots_Call struct {
	*mock.Call
}

// ListRoots is a helper method to define mock.On call
//   - ctx context.Context
//   - params *mcp.ListRootsParams
func (_e *MockMCPSession_Expecter) ListRoots(ctx interface{}, params interface{}) *MockMCPSession_ListRoots_Call {
	return &MockMCPSession_ListRoots_Call{Call: _e.mock.On("ListRoots", ctx, params)}
}

func (_c *MockMCPSession_ListRoots_Call) Run(run func(ctx context.Context, params *mcp.ListRootsParams)) *MockMCPSession_ListRoots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *mcp.ListRootsParams
		if args[1] != nil {
			arg1 = args[1].(*mcp.ListRootsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMCPSession_ListRoots_Call) Return(listRootsResult *mcp.ListRootsResult, err error) *MockMCPSession_ListRoots_Call {
	_c.Call.Return(listRootsResult, err)
	return _c
}

func (_c *MockMCPSession_ListRoots_Call) RunAndReturn(run func(ctx context.Context, params *mcp.ListRootsParams) (*mcp.ListRootsResult, error)) *MockMCPSession_ListRoots_Call {
	_c.Call.Return(run)
	return _c
}
