// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRootStore creates a new instance of MockRootStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRootStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRootStore {
	mock := &MockRootStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRootStore is an autogenerated mock type for the RootStore type
type MockRootStore struct {
	mock.Mock
}

type MockRootStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRootStore) EXPECT() *MockRootStore_Expecter {
	return &MockRootStore_Expecter{mock: &_m.Mock}
}

// UpdateRoots provides a mock function for the type MockRootStore
func (_mock *MockRootStore) UpdateRoots(roots []*mcp.Root) {
	_mock.Called(roots)
	return
}

// MockRootStore_UpdateRoots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoots'
type MockRootStore_UpdateRoots_Call struct {
	*mock.Call
}

// UpdateRoots is a helper method to define mock.On call
//   - roots []*mcp.Root
func (_e *MockRootStore_Expecter) UpdateRoots(roots interface{}) *MockRootStore_UpdateRoots_Call {
	return &MockRootStore_UpdateRoots_Call{Call: _e.mock.On("UpdateRoots", roots)}
}

func (_c *MockRootStore_UpdateRoots_Call) Run(run func(roots []*mcp.Root)) *MockRootStore_UpdateRoots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*mcp.Root
		if args[0] != nil {
			arg0 = args[0].([]*mcp.Root)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRootStore_UpdateRoots_Call) Return() *MockRootStore_UpdateRoots_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRootStore_UpdateRoots_Call) RunAndReturn(run func(roots []*mcp.Root)) *MockRootStore_UpdateRoots_Call {
	_c.Run(run)
	return _c
}
