// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type MockClient
func (_mock *MockClient) Connect(socketPath string) error {
	ret := _mock.Called(socketPath)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(socketPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - socketPath string
func (_e *MockClient_Expecter) Connect(socketPath interface{}) *MockClient_Connect_Call {
	return &MockClient_Connect_Call{Call: _e.mock.On("Connect", socketPath)}
}

func (_c *MockClient_Connect_Call) Run(run func(socketPath string)) *MockClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Connect_Call) Return(err error) *MockClient_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Connect_Call) RunAndReturn(run func(socketPath string) error) *MockClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// SendProcessPID provides a mock function for the type MockClient
func (_mock *MockClient) SendProcessPID(pid int) (messages.ProcessToKillResponse, error) {
	ret := _mock.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for SendProcessPID")
	}

	var r0 messages.ProcessToKillResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (messages.ProcessToKillResponse, error)); ok {
		return returnFunc(pid)
	}
	if returnFunc, ok := ret.Get(0).(func(int) messages.ProcessToKillResponse); ok {
		r0 = returnFunc(pid)
	} else {
		r0 = ret.Get(0).(messages.ProcessToKillResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(pid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_SendProcessPID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendProcessPID'
type MockClient_SendProcessPID_Call struct {
	*mock.Call
}

// SendProcessPID is a helper method to define mock.On call
//   - pid int
func (_e *MockClient_Expecter) SendProcessPID(pid interface{}) *MockClient_SendProcessPID_Call {
	return &MockClient_SendProcessPID_Call{Call: _e.mock.On("SendProcessPID", pid)}
}

func (_c *MockClient_SendProcessPID_Call) Run(run func(pid int)) *MockClient_SendProcessPID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_SendProcessPID_Call) Return(processToKillResponse messages.ProcessToKillResponse, err error) *MockClient_SendProcessPID_Call {
	_c.Call.Return(processToKillResponse, err)
	return _c
}

func (_c *MockClient_SendProcessPID_Call) RunAndReturn(run func(pid int) (messages.ProcessToKillResponse, error)) *MockClient_SendProcessPID_Call {
	_c.Call.Return(run)
	return _c
}

// SendStop provides a mock function for the type MockClient
func (_mock *MockClient) SendStop() (messages.ShutdownResponse, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendStop")
	}

	var r0 messages.ShutdownResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (messages.ShutdownResponse, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() messages.ShutdownResponse); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(messages.ShutdownResponse)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_SendStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStop'
type MockClient_SendStop_Call struct {
	*mock.Call
}

// SendStop is a helper method to define mock.On call
func (_e *MockClient_Expecter) SendStop() *MockClient_SendStop_Call {
	return &MockClient_SendStop_Call{Call: _e.mock.On("SendStop")}
}

func (_c *MockClient_SendStop_Call) Run(run func()) *MockClient_SendStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_SendStop_Call) Return(shutdownResponse messages.ShutdownResponse, err error) *MockClient_SendStop_Call {
	_c.Call.Return(shutdownResponse, err)
	return _c
}

func (_c *MockClient_SendStop_Call) RunAndReturn(run func() (messages.ShutdownResponse, error)) *MockClient_SendStop_Call {
	_c.Call.Return(run)
	return _c
}
