// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/facades/osfacade"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOSWrapper creates a new instance of MockOSWrapper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOSWrapper(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOSWrapper {
	mock := &MockOSWrapper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOSWrapper is an autogenerated mock type for the OSWrapper type
type MockOSWrapper struct {
	mock.Mock
}

type MockOSWrapper_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOSWrapper) EXPECT() *MockOSWrapper_Expecter {
	return &MockOSWrapper_Expecter{mock: &_m.Mock}
}

// FindProcess provides a mock function for the type MockOSWrapper
func (_mock *MockOSWrapper) FindProcess(processPid int) osfacade.Process {
	ret := _mock.Called(processPid)

	if len(ret) == 0 {
		panic("no return value specified for FindProcess")
	}

	var r0 osfacade.Process
	if returnFunc, ok := ret.Get(0).(func(int) osfacade.Process); ok {
		r0 = returnFunc(processPid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(osfacade.Process)
		}
	}
	return r0
}

// MockOSWrapper_FindProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindProcess'
type MockOSWrapper_FindProcess_Call struct {
	*mock.Call
}

// FindProcess is a helper method to define mock.On call
//   - processPid int
func (_e *MockOSWrapper_Expecter) FindProcess(processPid interface{}) *MockOSWrapper_FindProcess_Call {
	return &MockOSWrapper_FindProcess_Call{Call: _e.mock.On("FindProcess", processPid)}
}

func (_c *MockOSWrapper_FindProcess_Call) Run(run func(processPid int)) *MockOSWrapper_FindProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSWrapper_FindProcess_Call) Return(process osfacade.Process) *MockOSWrapper_FindProcess_Call {
	_c.Call.Return(process)
	return _c
}

func (_c *MockOSWrapper_FindProcess_Call) RunAndReturn(run func(processPid int) osfacade.Process) *MockOSWrapper_FindProcess_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForProcessToComplete provides a mock function for the type MockOSWrapper
func (_mock *MockOSWrapper) WaitForProcessToComplete(processPid int) {
	_mock.Called(processPid)
	return
}

// MockOSWrapper_WaitForProcessToComplete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForProcessToComplete'
type MockOSWrapper_WaitForProcessToComplete_Call struct {
	*mock.Call
}

// WaitForProcessToComplete is a helper method to define mock.On call
//   - processPid int
func (_e *MockOSWrapper_Expecter) WaitForProcessToComplete(processPid interface{}) *MockOSWrapper_WaitForProcessToComplete_Call {
	return &MockOSWrapper_WaitForProcessToComplete_Call{Call: _e.mock.On("WaitForProcessToComplete", processPid)}
}

func (_c *MockOSWrapper_WaitForProcessToComplete_Call) Run(run func(processPid int)) *MockOSWrapper_WaitForProcessToComplete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOSWrapper_WaitForProcessToComplete_Call) Return() *MockOSWrapper_WaitForProcessToComplete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOSWrapper_WaitForProcessToComplete_Call) RunAndReturn(run func(processPid int)) *MockOSWrapper_WaitForProcessToComplete_Call {
	_c.Run(run)
	return _c
}
