// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/definition"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResourcesFactory creates a new instance of MockResourcesFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourcesFactory[Dependencies any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourcesFactory[Dependencies] {
	mock := &MockResourcesFactory[Dependencies]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourcesFactory is an autogenerated mock type for the ResourcesFactory type
type MockResourcesFactory[Dependencies any] struct {
	mock.Mock
}

type MockResourcesFactory_Expecter[Dependencies any] struct {
	mock *mock.Mock
}

func (_m *MockResourcesFactory[Dependencies]) EXPECT() *MockResourcesFactory_Expecter[Dependencies] {
	return &MockResourcesFactory_Expecter[Dependencies]{mock: &_m.Mock}
}

// New provides a mock function for the type MockResourcesFactory
func (_mock *MockResourcesFactory[Dependencies]) New(internal definition.ToolsProviderResources) publictypes.ToolsProviderResources[Dependencies] {
	ret := _mock.Called(internal)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 publictypes.ToolsProviderResources[Dependencies]
	if returnFunc, ok := ret.Get(0).(func(definition.ToolsProviderResources) publictypes.ToolsProviderResources[Dependencies]); ok {
		r0 = returnFunc(internal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.ToolsProviderResources[Dependencies])
		}
	}
	return r0
}

// MockResourcesFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockResourcesFactory_New_Call[Dependencies any] struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - internal definition.ToolsProviderResources
func (_e *MockResourcesFactory_Expecter[Dependencies]) New(internal interface{}) *MockResourcesFactory_New_Call[Dependencies] {
	return &MockResourcesFactory_New_Call[Dependencies]{Call: _e.mock.On("New", internal)}
}

func (_c *MockResourcesFactory_New_Call[Dependencies]) Run(run func(internal definition.ToolsProviderResources)) *MockResourcesFactory_New_Call[Dependencies] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 definition.ToolsProviderResources
		if args[0] != nil {
			arg0 = args[0].(definition.ToolsProviderResources)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockResourcesFactory_New_Call[Dependencies]) Return(toolsProviderResources publictypes.ToolsProviderResources[Dependencies]) *MockResourcesFactory_New_Call[Dependencies] {
	_c.Call.Return(toolsProviderResources)
	return _c
}

func (_c *MockResourcesFactory_New_Call[Dependencies]) RunAndReturn(run func(internal definition.ToolsProviderResources) publictypes.ToolsProviderResources[Dependencies]) *MockResourcesFactory_New_Call[Dependencies] {
	_c.Call.Return(run)
	return _c
}
