// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientFactory creates a new instance of MockClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientFactory {
	mock := &MockClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientFactory is an autogenerated mock type for the ClientFactory type
type MockClientFactory struct {
	mock.Mock
}

type MockClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientFactory) EXPECT() *MockClientFactory_Expecter {
	return &MockClientFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockClientFactory
func (_mock *MockClientFactory) New() transport.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 transport.Client
	if returnFunc, ok := ret.Get(0).(func() transport.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(transport.Client)
		}
	}
	return r0
}

// MockClientFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockClientFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
func (_e *MockClientFactory_Expecter) New() *MockClientFactory_New_Call {
	return &MockClientFactory_New_Call{Call: _e.mock.On("New")}
}

func (_c *MockClientFactory_New_Call) Run(run func()) *MockClientFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientFactory_New_Call) Return(client transport.Client) *MockClientFactory_New_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockClientFactory_New_Call) RunAndReturn(run func() transport.Client) *MockClientFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
