// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/resources"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/mcp/tools"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMCPServerConfigurator creates a new instance of MockMCPServerConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMCPServerConfigurator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMCPServerConfigurator {
	mock := &MockMCPServerConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMCPServerConfigurator is an autogenerated mock type for the MCPServerConfigurator type
type MockMCPServerConfigurator struct {
	mock.Mock
}

type MockMCPServerConfigurator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMCPServerConfigurator) EXPECT() *MockMCPServerConfigurator_Expecter {
	return &MockMCPServerConfigurator_Expecter{mock: &_m.Mock}
}

// GetResourcesToAdd provides a mock function for the type MockMCPServerConfigurator
func (_mock *MockMCPServerConfigurator) GetResourcesToAdd() []resources.Resource {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResourcesToAdd")
	}

	var r0 []resources.Resource
	if returnFunc, ok := ret.Get(0).(func() []resources.Resource); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]resources.Resource)
		}
	}
	return r0
}

// MockMCPServerConfigurator_GetResourcesToAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourcesToAdd'
type MockMCPServerConfigurator_GetResourcesToAdd_Call struct {
	*mock.Call
}

// GetResourcesToAdd is a helper method to define mock.On call
func (_e *MockMCPServerConfigurator_Expecter) GetResourcesToAdd() *MockMCPServerConfigurator_GetResourcesToAdd_Call {
	return &MockMCPServerConfigurator_GetResourcesToAdd_Call{Call: _e.mock.On("GetResourcesToAdd")}
}

func (_c *MockMCPServerConfigurator_GetResourcesToAdd_Call) Run(run func()) *MockMCPServerConfigurator_GetResourcesToAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMCPServerConfigurator_GetResourcesToAdd_Call) Return(resources1 []resources.Resource) *MockMCPServerConfigurator_GetResourcesToAdd_Call {
	_c.Call.Return(resources1)
	return _c
}

func (_c *MockMCPServerConfigurator_GetResourcesToAdd_Call) RunAndReturn(run func() []resources.Resource) *MockMCPServerConfigurator_GetResourcesToAdd_Call {
	_c.Call.Return(run)
	return _c
}

// GetToolsToAdd provides a mock function for the type MockMCPServerConfigurator
func (_mock *MockMCPServerConfigurator) GetToolsToAdd() ([]tools.Tool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetToolsToAdd")
	}

	var r0 []tools.Tool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]tools.Tool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []tools.Tool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tools.Tool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMCPServerConfigurator_GetToolsToAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToolsToAdd'
type MockMCPServerConfigurator_GetToolsToAdd_Call struct {
	*mock.Call
}

// GetToolsToAdd is a helper method to define mock.On call
func (_e *MockMCPServerConfigurator_Expecter) GetToolsToAdd() *MockMCPServerConfigurator_GetToolsToAdd_Call {
	return &MockMCPServerConfigurator_GetToolsToAdd_Call{Call: _e.mock.On("GetToolsToAdd")}
}

func (_c *MockMCPServerConfigurator_GetToolsToAdd_Call) Run(run func()) *MockMCPServerConfigurator_GetToolsToAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMCPServerConfigurator_GetToolsToAdd_Call) Return(tools1 []tools.Tool, err error) *MockMCPServerConfigurator_GetToolsToAdd_Call {
	_c.Call.Return(tools1, err)
	return _c
}

func (_c *MockMCPServerConfigurator_GetToolsToAdd_Call) RunAndReturn(run func() ([]tools.Tool, error)) *MockMCPServerConfigurator_GetToolsToAdd_Call {
	_c.Call.Return(run)
	return _c
}
