model AWFF_L1OnlineFaultAllocationControllerEquation_Sysblock
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Controllers.Sysblocks.AWFF_L1OnlineFaultAllocationControllerEquation_Sysblock"
  extends MoSimQuadrotorModel.Controllers.Sysblocks.AWFF_L1OnlineFaultAllocationControllerEquation_Sysblock;
  annotation(__MWORKS(hide=true));
end AWFF_L1OnlineFaultAllocationControllerEquation_Sysblock;
