model AWFF_FullControllerFlatGraphical_Sysblock
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Controllers.Sysblocks.AWFF_FullControllerFlatGraphical_Sysblock"
  extends MoSimQuadrotorModel.Controllers.Sysblocks.AWFF_FullControllerFlatGraphical_Sysblock;
  annotation(__MWORKS(hide=true));
end AWFF_FullControllerFlatGraphical_Sysblock;
