model AWFF_LinearMPCOuterLoopControllerEquation_Sysblock
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Controllers.Sysblocks.AWFF_LinearMPCOuterLoopControllerEquation_Sysblock"
  extends MoSimQuadrotorModel.Controllers.Sysblocks.AWFF_LinearMPCOuterLoopControllerEquation_Sysblock;
  annotation(__MWORKS(hide=true));
end AWFF_LinearMPCOuterLoopControllerEquation_Sysblock;
