model AWFF_LinearMPCOnlineFaultAllocationController_Sysblock
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Controllers.Sysblocks.AWFF_LinearMPCOnlineFaultAllocationController_Sysblock"
  extends MoSimQuadrotorModel.Controllers.Sysblocks.AWFF_LinearMPCOnlineFaultAllocationController_Sysblock;
  annotation(__MWORKS(hide=true));
end AWFF_LinearMPCOnlineFaultAllocationController_Sysblock;
