// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
)

// NewMockMetricExporter creates a new instance of MockMetricExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricExporter {
	mock := &MockMetricExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricExporter is an autogenerated mock type for the MetricExporter type
type MockMetricExporter struct {
	mock.Mock
}

type MockMetricExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricExporter) EXPECT() *MockMetricExporter_Expecter {
	return &MockMetricExporter_Expecter{mock: &_m.Mock}
}

// Aggregation provides a mock function for the type MockMetricExporter
func (_mock *MockMetricExporter) Aggregation(instrumentKind metric.InstrumentKind) metric.Aggregation {
	ret := _mock.Called(instrumentKind)

	if len(ret) == 0 {
		panic("no return value specified for Aggregation")
	}

	var r0 metric.Aggregation
	if returnFunc, ok := ret.Get(0).(func(metric.InstrumentKind) metric.Aggregation); ok {
		r0 = returnFunc(instrumentKind)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metric.Aggregation)
		}
	}
	return r0
}

// MockMetricExporter_Aggregation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregation'
type MockMetricExporter_Aggregation_Call struct {
	*mock.Call
}

// Aggregation is a helper method to define mock.On call
//   - instrumentKind metric.InstrumentKind
func (_e *MockMetricExporter_Expecter) Aggregation(instrumentKind interface{}) *MockMetricExporter_Aggregation_Call {
	return &MockMetricExporter_Aggregation_Call{Call: _e.mock.On("Aggregation", instrumentKind)}
}

func (_c *MockMetricExporter_Aggregation_Call) Run(run func(instrumentKind metric.InstrumentKind)) *MockMetricExporter_Aggregation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.InstrumentKind
		if args[0] != nil {
			arg0 = args[0].(metric.InstrumentKind)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricExporter_Aggregation_Call) Return(aggregation metric.Aggregation) *MockMetricExporter_Aggregation_Call {
	_c.Call.Return(aggregation)
	return _c
}

func (_c *MockMetricExporter_Aggregation_Call) RunAndReturn(run func(instrumentKind metric.InstrumentKind) metric.Aggregation) *MockMetricExporter_Aggregation_Call {
	_c.Call.Return(run)
	return _c
}

// Export provides a mock function for the type MockMetricExporter
func (_mock *MockMetricExporter) Export(context1 context.Context, resourceMetrics *metricdata.ResourceMetrics) error {
	ret := _mock.Called(context1, resourceMetrics)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metricdata.ResourceMetrics) error); ok {
		r0 = returnFunc(context1, resourceMetrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricExporter_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type MockMetricExporter_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - context1 context.Context
//   - resourceMetrics *metricdata.ResourceMetrics
func (_e *MockMetricExporter_Expecter) Export(context1 interface{}, resourceMetrics interface{}) *MockMetricExporter_Export_Call {
	return &MockMetricExporter_Export_Call{Call: _e.mock.On("Export", context1, resourceMetrics)}
}

func (_c *MockMetricExporter_Export_Call) Run(run func(context1 context.Context, resourceMetrics *metricdata.ResourceMetrics)) *MockMetricExporter_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *metricdata.ResourceMetrics
		if args[1] != nil {
			arg1 = args[1].(*metricdata.ResourceMetrics)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricExporter_Export_Call) Return(err error) *MockMetricExporter_Export_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricExporter_Export_Call) RunAndReturn(run func(context1 context.Context, resourceMetrics *metricdata.ResourceMetrics) error) *MockMetricExporter_Export_Call {
	_c.Call.Return(run)
	return _c
}

// ForceFlush provides a mock function for the type MockMetricExporter
func (_mock *MockMetricExporter) ForceFlush(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ForceFlush")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricExporter_ForceFlush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForceFlush'
type MockMetricExporter_ForceFlush_Call struct {
	*mock.Call
}

// ForceFlush is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockMetricExporter_Expecter) ForceFlush(context1 interface{}) *MockMetricExporter_ForceFlush_Call {
	return &MockMetricExporter_ForceFlush_Call{Call: _e.mock.On("ForceFlush", context1)}
}

func (_c *MockMetricExporter_ForceFlush_Call) Run(run func(context1 context.Context)) *MockMetricExporter_ForceFlush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricExporter_ForceFlush_Call) Return(err error) *MockMetricExporter_ForceFlush_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricExporter_ForceFlush_Call) RunAndReturn(run func(context1 context.Context) error) *MockMetricExporter_ForceFlush_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockMetricExporter
func (_mock *MockMetricExporter) Shutdown(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricExporter_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockMetricExporter_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockMetricExporter_Expecter) Shutdown(context1 interface{}) *MockMetricExporter_Shutdown_Call {
	return &MockMetricExporter_Shutdown_Call{Call: _e.mock.On("Shutdown", context1)}
}

func (_c *MockMetricExporter_Shutdown_Call) Run(run func(context1 context.Context)) *MockMetricExporter_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricExporter_Shutdown_Call) Return(err error) *MockMetricExporter_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricExporter_Shutdown_Call) RunAndReturn(run func(context1 context.Context) error) *MockMetricExporter_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Temporality provides a mock function for the type MockMetricExporter
func (_mock *MockMetricExporter) Temporality(instrumentKind metric.InstrumentKind) metricdata.Temporality {
	ret := _mock.Called(instrumentKind)

	if len(ret) == 0 {
		panic("no return value specified for Temporality")
	}

	var r0 metricdata.Temporality
	if returnFunc, ok := ret.Get(0).(func(metric.InstrumentKind) metricdata.Temporality); ok {
		r0 = returnFunc(instrumentKind)
	} else {
		r0 = ret.Get(0).(metricdata.Temporality)
	}
	return r0
}

// MockMetricExporter_Temporality_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Temporality'
type MockMetricExporter_Temporality_Call struct {
	*mock.Call
}

// Temporality is a helper method to define mock.On call
//   - instrumentKind metric.InstrumentKind
func (_e *MockMetricExporter_Expecter) Temporality(instrumentKind interface{}) *MockMetricExporter_Temporality_Call {
	return &MockMetricExporter_Temporality_Call{Call: _e.mock.On("Temporality", instrumentKind)}
}

func (_c *MockMetricExporter_Temporality_Call) Run(run func(instrumentKind metric.InstrumentKind)) *MockMetricExporter_Temporality_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metric.InstrumentKind
		if args[0] != nil {
			arg0 = args[0].(metric.InstrumentKind)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricExporter_Temporality_Call) Return(temporality metricdata.Temporality) *MockMetricExporter_Temporality_Call {
	_c.Call.Return(temporality)
	return _c
}

func (_c *MockMetricExporter_Temporality_Call) RunAndReturn(run func(instrumentKind metric.InstrumentKind) metricdata.Temporality) *MockMetricExporter_Temporality_Call {
	_c.Call.Return(run)
	return _c
}
