/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 55e4ce52fc087c1e748b18ae35f2bddd)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "AssistantDirectory" | "MyAssistant";
  }
  interface Env {
    LOADER: WorkerLoader;
    AI: Ai;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    AssistantDirectory: DurableObjectNamespace<
      import("./src/server").AssistantDirectory
    >;
    MyAssistant: DurableObjectNamespace<import("./src/server").MyAssistant>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET">
  > {}
}
