// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	"github.com/matlab/matlab-mcp-core-server/internal/usecases/listavailablematlabs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockUsecase
func (_mock *MockUsecase) Execute(ctx context.Context, sessionLogger entities.Logger) listavailablematlabs.ReturnArgs {
	ret := _mock.Called(ctx, sessionLogger)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 listavailablematlabs.ReturnArgs
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger) listavailablematlabs.ReturnArgs); ok {
		r0 = returnFunc(ctx, sessionLogger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(listavailablematlabs.ReturnArgs)
		}
	}
	return r0
}

// MockUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
func (_e *MockUsecase_Expecter) Execute(ctx interface{}, sessionLogger interface{}) *MockUsecase_Execute_Call {
	return &MockUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, sessionLogger)}
}

func (_c *MockUsecase_Execute_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger)) *MockUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_Execute_Call) Return(returnArgs listavailablematlabs.ReturnArgs) *MockUsecase_Execute_Call {
	_c.Call.Return(returnArgs)
	return _c
}

func (_c *MockUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger) listavailablematlabs.ReturnArgs) *MockUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
