/* Config.hh. Generated by CMake for gz-smoke. */

/* Version number */
#define MAJOR_VERSION 0
#define MINOR_VERSION 0
#define PATCH_VERSION 1

#define VERSION "0.0"
#define VERSION_FULL "0.0.1"
#define VERSION_NAMESPACE v0
