// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoggerFactory creates a new instance of MockLoggerFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoggerFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoggerFactory {
	mock := &MockLoggerFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoggerFactory is an autogenerated mock type for the LoggerFactory type
type MockLoggerFactory struct {
	mock.Mock
}

type MockLoggerFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoggerFactory) EXPECT() *MockLoggerFactory_Expecter {
	return &MockLoggerFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockLoggerFactory
func (_mock *MockLoggerFactory) New(logger entities.Logger) publictypes.Logger {
	ret := _mock.Called(logger)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 publictypes.Logger
	if returnFunc, ok := ret.Get(0).(func(entities.Logger) publictypes.Logger); ok {
		r0 = returnFunc(logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.Logger)
		}
	}
	return r0
}

// MockLoggerFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockLoggerFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - logger entities.Logger
func (_e *MockLoggerFactory_Expecter) New(logger interface{}) *MockLoggerFactory_New_Call {
	return &MockLoggerFactory_New_Call{Call: _e.mock.On("New", logger)}
}

func (_c *MockLoggerFactory_New_Call) Run(run func(logger entities.Logger)) *MockLoggerFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLoggerFactory_New_Call) Return(logger1 publictypes.Logger) *MockLoggerFactory_New_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockLoggerFactory_New_Call) RunAndReturn(run func(logger entities.Logger) publictypes.Logger) *MockLoggerFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
