// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockWatchdog creates a new instance of MockWatchdog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchdog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchdog {
	mock := &MockWatchdog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatchdog is an autogenerated mock type for the Watchdog type
type MockWatchdog struct {
	mock.Mock
}

type MockWatchdog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchdog) EXPECT() *MockWatchdog_Expecter {
	return &MockWatchdog_Expecter{mock: &_m.Mock}
}

// RegisterProcessPIDWithWatchdog provides a mock function for the type MockWatchdog
func (_mock *MockWatchdog) RegisterProcessPIDWithWatchdog(processPID int) error {
	ret := _mock.Called(processPID)

	if len(ret) == 0 {
		panic("no return value specified for RegisterProcessPIDWithWatchdog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(processPID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWatchdog_RegisterProcessPIDWithWatchdog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterProcessPIDWithWatchdog'
type MockWatchdog_RegisterProcessPIDWithWatchdog_Call struct {
	*mock.Call
}

// RegisterProcessPIDWithWatchdog is a helper method to define mock.On call
//   - processPID int
func (_e *MockWatchdog_Expecter) RegisterProcessPIDWithWatchdog(processPID interface{}) *MockWatchdog_RegisterProcessPIDWithWatchdog_Call {
	return &MockWatchdog_RegisterProcessPIDWithWatchdog_Call{Call: _e.mock.On("RegisterProcessPIDWithWatchdog", processPID)}
}

func (_c *MockWatchdog_RegisterProcessPIDWithWatchdog_Call) Run(run func(processPID int)) *MockWatchdog_RegisterProcessPIDWithWatchdog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWatchdog_RegisterProcessPIDWithWatchdog_Call) Return(err error) *MockWatchdog_RegisterProcessPIDWithWatchdog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWatchdog_RegisterProcessPIDWithWatchdog_Call) RunAndReturn(run func(processPID int) error) *MockWatchdog_RegisterProcessPIDWithWatchdog_Call {
	_c.Call.Return(run)
	return _c
}
