import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Vec3, Rotator, Color } from "../schemas.js";

export const levelTool: ToolDef = categoryTool(
  "level",
  "Level actors, selection, components, level management, volumes, lights, and splines.",
  {
    get_outliner:       bp("List actors. Params: classFilter?, nameFilter?, world? (editor|pie|auto), limit?", "get_world_outliner"),
    place_actor:        bp("Spawn actor. Params: actorClass, label?, location?, rotation?, scale?, staticMesh?, material?", "place_actor"),
    delete_actor:       bp("Remove actor. Params: actorLabel", "delete_actor"),
    get_actor_details:  bp("Inspect actor. Params: actorLabel OR actorPath, includeProperties?, propertyName?, world? (editor|pie)", "get_actor_details"),
    move_actor:         bp("Transform actor. Params: actorLabel, location?, rotation?, scale?", "move_actor"),
    select:             bp("Select actors. Params: actorLabels[]", "select_actors"),
    get_selected:       bp("Get selection", "get_selected_actors"),
    add_component:      bp("Add component to actor. Params: actorLabel, componentClass, componentName?", "add_component_to_actor"),
    remove_component:   bp("Remove instance component from a level actor by name. Idempotent: returns alreadyDeleted=true if no matching component exists. Params: actorLabel, componentName (#426)", "remove_component_from_actor", (p) => ({ actorLabel: p.actorLabel, componentName: p.componentName })),
    set_component_property: bp("Set component prop. Pass value=null to clear a TObjectPtr/SoftObject/WeakObject/UClass/Interface reference (#420). Params: actorLabel, componentName, propertyName, value", "set_component_property"),
    get_current:        bp("Get current level name and path", "get_current_level"),
    load:               bp("Load level. Params: levelPath", "load_level"),
    save:               bp("Save current level", "save_current_level"),
    list:               bp("List levels. Params: directory?, recursive?", "list_levels"),
    create:             bp("Create new level. Params: levelPath?, templateLevel?", "create_new_level"),
    spawn_volume:       bp("Place volume. Params: volumeType, location?, extent?, label?", "spawn_volume"),
    list_volumes:       bp("List volumes. Params: volumeType?", "list_volumes"),
    set_volume_properties: bp("Edit volume. Params: actorLabel, properties", "set_volume_properties"),
    spawn_light:        bp("Place light. Params: lightType (point|spot|directional|rect|sky), location?, rotation?, intensity?, color? ({r,g,b} 0-255), mobility? (static|stationary|movable; default movable so the light renders without a build), label? (#331/#310)", "spawn_light"),
    set_light_properties: bp("Edit light. Params: actorLabel, intensity?, color?, rotation? (DirectionalLight sun angle), mobility? (static|stationary|movable), recaptureSky?, temperature?, castShadows?, attenuationRadius?", "set_light_properties"),
    set_fog_properties: bp("Edit ExponentialHeightFog. Params: actorLabel?, fogDensity?, fogHeightFalloff?, startDistance?, fogInscatteringColor?", "set_fog_properties"),
    get_actors_by_class: bp("List actors by class name. Params: className, world? (editor|pie)", "get_actors_by_class"),
    count_actors_by_class: bp("Histogram of actor classes in the level (sorted desc). Params: world? (editor|pie), topN? (#146)", "count_actors_by_class", (p) => ({ world: p.world, topN: p.topN })),
    get_runtime_virtual_texture_summary: bp("List RuntimeVirtualTextureVolume actors + their bound VirtualTexture assets (#150)", "get_runtime_virtual_texture_summary"),
    set_water_body_property: bp("Set a property on an actor's WaterBodyComponent (ShapeDilation, WaterLevel, etc.). Params: actorLabel, propertyName, value. Requires Water plugin. For spline edits use level(set_spline_points) (#151)", "set_water_body_property", (p) => ({ actorLabel: p.actorLabel, propertyName: p.propertyName, value: p.value })),
    build_lighting:     bp("Build lights. Params: quality?", "build_lighting"),
    get_spline_info:    bp("Read spline. Params: actorLabel", "get_spline_info"),
    set_spline_points:  bp("Set spline points. Params: actorLabel, points[], closedLoop?", "set_spline_points"),
    set_actor_material: bp("Set material on actor. Params: actorLabel, materialPath, slotIndex?", "set_actor_material"),
    get_world_settings: bp("Read world settings (GameMode, KillZ, gravity, etc.)", "get_world_settings"),
    set_world_settings: bp("Set world settings. Params: defaultGameMode?, killZ?, globalGravityZ?, enableWorldBoundsChecks?", "set_world_settings"),
    get_actor_bounds:   bp("Get actor AABB. Params: actorLabel. Returns origin + extent (#188)", "get_actor_bounds"),
    get_component_tree: bp("Deep component-tree dump for an actor. Returns per-component: name, class, attachParent, attachSocket, mobility, visibility, relative+world transforms, tags. For PrimitiveComponents adds collisionProfile/collisionEnabled/bounds/castShadow. For StaticMeshComponent adds staticMesh + materials[]. For SkeletalMeshComponent adds skeletalMesh + skeleton + materials[]. Params: actorLabel | actorPath, world? (editor|pie), componentClass? (substring filter), includeProperties? (dump UPROPERTY name/type/value per component) (#240/#241/#302/#320/#370/#353)", "get_component_tree", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, world: p.world, componentClass: p.componentClass, includeProperties: p.includeProperties })),
    get_relative_transform: bp("Compute target's transform in reference's local space (location/rotation/scale). Common dungeon/calibration workflow. Params: target (actor label), reference (actor label), world? (#386/#387)", "get_relative_transform", (p) => ({ targetLabel: p.target ?? p.targetLabel, referenceLabel: p.reference ?? p.referenceLabel, target: p.target, reference: p.reference, world: p.world })),
    resolve_actor:      bp("Resolve internal/runtime actor name to editor label. Params: internalName (e.g. StaticMeshActor_141). Returns actorLabel, actorPath, className, location (#178)", "resolve_actor"),
    set_actor_property: bp("Set per-instance UPROPERTY on a level actor. Params: actorLabel ('WorldSettings' targets the world settings actor), propertyName (dotted paths like 'Foo.Bar' supported), value (string/number/bool/object/array; an actor label resolves to AActor* refs), force? (bypass EditDefaultsOnly), world? (editor|pie) (#202/#230)", "set_actor_property", (p) => ({ actorLabel: p.actorLabel, propertyName: p.propertyName, value: p.value, force: p.force, world: p.world })),
    delete_actors: bp("Bulk-delete actors. Params: at least one of labelPrefix, className, tag; dryRun? to preview. Returns matched/deleted/labels (#220)", "delete_actors", (p) => ({ labelPrefix: p.labelPrefix, className: p.className, tag: p.tag, dryRun: p.dryRun })),
    add_actor_tag: bp("Append a tag to an actor's Tags array. Params: actorLabel, tag (#219)", "add_actor_tag", (p) => ({ actorLabel: p.actorLabel, tag: p.tag })),
    remove_actor_tag: bp("Remove a tag from an actor's Tags array. Params: actorLabel, tag (#219)", "remove_actor_tag", (p) => ({ actorLabel: p.actorLabel, tag: p.tag })),
    set_actor_tags: bp("Replace an actor's Tags array. Params: actorLabel, tags[] (#219)", "set_actor_tags", (p) => ({ actorLabel: p.actorLabel, tags: p.tags })),
    list_actor_tags: bp("List an actor's Tags. Params: actorLabel (#219)", "list_actor_tags", (p) => ({ actorLabel: p.actorLabel })),
    attach_actor: bp("Attach actor as child. Params: childLabel, parentLabel, attachRule? (KeepWorld|KeepRelative|SnapToTarget; default KeepWorld), socketName? (#205)", "attach_actor", (p) => ({ childLabel: p.childLabel, parentLabel: p.parentLabel, attachRule: p.attachRule, socketName: p.socketName })),
    detach_actor: bp("Detach actor from parent. Params: childLabel (#205)", "detach_actor", (p) => ({ childLabel: p.childLabel })),
    set_actor_mobility: bp("Set actor root component Mobility. Params: actorLabel, mobility (static|stationary|movable) (#205)", "set_actor_mobility", (p) => ({ actorLabel: p.actorLabel, mobility: p.mobility })),
    get_current_edit_level: bp("Read the active edit-target sub-level (#204)", "get_current_edit_level"),
    set_current_edit_level: bp("Set the active edit-target sub-level so subsequent spawns land in it. Params: levelName (e.g. SubLevel_A) (#204)", "set_current_edit_level", (p) => ({ levelName: p.levelName, levelPath: p.levelPath })),
    list_streaming_sublevels: bp("List streaming sub-levels with transform + initially-loaded/visible flags (#206)", "list_streaming_sublevels"),
    add_streaming_sublevel: bp("Add a streaming sub-level. Params: levelPath, streamingClass? (LevelStreamingDynamic|LevelStreamingAlwaysLoaded), location?, initiallyLoaded?, initiallyVisible? (#206)", "add_streaming_sublevel", (p) => ({ levelPath: p.levelPath, streamingClass: p.streamingClass, location: p.location, initiallyLoaded: p.initiallyLoaded, initiallyVisible: p.initiallyVisible })),
    remove_streaming_sublevel: bp("Remove a streaming sub-level. Params: levelName | levelPath (#206)", "remove_streaming_sublevel", (p) => ({ levelName: p.levelName, levelPath: p.levelPath })),
    set_streaming_sublevel_properties: bp("Update sub-level transform/visibility flags. Params: levelName | levelPath, location?, initiallyLoaded?, initiallyVisible?, editorVisible? (#206)", "set_streaming_sublevel_properties", (p) => ({ levelName: p.levelName, levelPath: p.levelPath, location: p.location, initiallyLoaded: p.initiallyLoaded, initiallyVisible: p.initiallyVisible, editorVisible: p.editorVisible })),
    spawn_grid: bp("Batch-spawn StaticMeshActors on a grid. Params: staticMesh, min, max (Vec3 bounds), countX?, countY?, countZ?, jitter?, labelPrefix? (#203)", "spawn_grid", (p) => ({ staticMesh: p.staticMesh, min: p.min, max: p.max, countX: p.countX, countY: p.countY, countZ: p.countZ, jitter: p.jitter, labelPrefix: p.labelPrefix })),
    batch_translate: bp("Translate a set of actors by an offset. Params: offset (Vec3), actorLabels[] OR tag (#203)", "batch_translate", (p) => ({ offset: p.offset, actorLabels: p.actorLabels, tag: p.tag })),
    place_actors_batch: bp("Bulk-spawn StaticMeshActors with per-instance mesh + transform. Params: actors[]: [{staticMesh, location?, rotation?, scale?, label?}]. Mesh loads cached per path. Returns spawned/failedMesh/failedSpawn counts + labels (#264)", "place_actors_batch", (p) => ({ actors: p.actors })),
    line_trace: bp("Line trace in the editor world. Returns hit + actorLabel/actorClass/componentName/componentClass/location/impactPoint/normal/distance/faceIndex/boneName/physicalMaterial. Params: start (Vec3), end? (Vec3) OR direction? (Vec3) + distance? (default 200000), ignoreActors? (array of labels) (#420)", "line_trace", (p) => ({ start: p.start, end: p.end, direction: p.direction, distance: p.distance, ignoreActors: p.ignoreActors })),
    snap_actor_to_floor: bp("Snap an actor's bounds-bottom to the first downward line-trace hit. Equivalent of the End-key shortcut, works on arbitrary geometry (not just Landscape). Params: actorLabel, floorOffset? (added to impact Z, default 0), maxDistance? (default 100000) (#419)", "snap_actor_to_floor", (p) => ({ actorLabel: p.actorLabel, floorOffset: p.floorOffset, maxDistance: p.maxDistance })),
  },
  undefined,  // actionDocs auto-generated from descriptions
  {
    actorLabel: z.string().optional(), actorLabels: z.array(z.string()).optional(),
    actorClass: z.string().optional(), label: z.string().optional(),
    location: Vec3.optional(),
    rotation: Rotator.optional(),
    scale: Vec3.optional(),
    properties: z.record(z.unknown()).optional(),
    classFilter: z.string().optional(), nameFilter: z.string().optional(),
    componentClass: z.string().optional(), componentName: z.string().optional(),
    propertyName: z.string().optional(), value: z.unknown().optional(),
    levelPath: z.string().optional(), templateLevel: z.string().optional(),
    directory: z.string().optional(), recursive: z.boolean().optional(),
    volumeType: z.string().optional(),
    extent: Vec3.optional(),
    lightType: z.string().optional(), intensity: z.number().optional(),
    color: Color.optional(),
    temperature: z.number().optional(), castShadows: z.boolean().optional(),
    attenuationRadius: z.number().optional(),
    innerConeAngle: z.number().optional(), outerConeAngle: z.number().optional(),
    quality: z.string().optional(),
    points: z.array(Vec3).optional(),
    closedLoop: z.boolean().optional(),
    staticMesh: z.string().optional().describe("Asset path for static mesh (e.g. /Engine/BasicShapes/Cube.Cube)"),
    material: z.string().optional().describe("Asset path for material to apply at slot 0"),
    materialPath: z.string().optional().describe("Material asset path for set_actor_material"),
    slotIndex: z.number().optional().describe("Material slot index (default 0)"),
    actorPath: z.string().optional().describe("Full actor object path; alternative to actorLabel"),
    includeProperties: z.boolean().optional().describe("Include reflected UPROPERTY values in get_actor_details"),
    world: z.string().optional().describe("World scope: editor (default) or pie"),
    className: z.string().optional().describe("Class name filter for get_actors_by_class"),
    topN: z.number().optional().describe("Limit for count_actors_by_class result"),
    fogDensity: z.number().optional(),
    fogHeightFalloff: z.number().optional(),
    startDistance: z.number().optional(),
    fogInscatteringColor: Color.optional(),
    recaptureSky: z.boolean().optional(),
    defaultGameMode: z.string().optional(),
    killZ: z.number().optional(),
    globalGravityZ: z.number().optional(),
    enableWorldBoundsChecks: z.boolean().optional(),
    internalName: z.string().optional().describe("Internal/runtime UObject name for resolve_actor (e.g. StaticMeshActor_141)"),
    target: z.string().optional().describe("Target actor label for get_relative_transform"),
    reference: z.string().optional().describe("Reference actor label for get_relative_transform"),
    start: Vec3.optional().describe("line_trace: ray start"),
    end: Vec3.optional().describe("line_trace: ray end (use this OR direction+distance)"),
    direction: Vec3.optional().describe("line_trace: ray direction (unit-normalized internally)"),
    distance: z.number().optional().describe("line_trace: ray length when direction is supplied (default 200000)"),
    ignoreActors: z.array(z.string()).optional().describe("line_trace: actor labels to skip"),
    floorOffset: z.number().optional().describe("snap_actor_to_floor: vertical offset added to impact Z"),
    maxDistance: z.number().optional().describe("snap_actor_to_floor: line-trace length downward (default 100000)"),
    force: z.boolean().optional().describe("set_actor_property: bypass EditDefaultsOnly to write per-instance overrides"),
    labelPrefix: z.string().optional().describe("delete_actors: actor label prefix filter"),
    tag: z.string().optional(),
    tags: z.array(z.string()).optional(),
    dryRun: z.boolean().optional().describe("delete_actors: report matches without deleting"),
    childLabel: z.string().optional(),
    parentLabel: z.string().optional(),
    attachRule: z.string().optional().describe("attach_actor: KeepWorld | KeepRelative | SnapToTarget"),
    socketName: z.string().optional(),
    mobility: z.string().optional().describe("set_actor_mobility: static | stationary | movable"),
    levelName: z.string().optional(),
    streamingClass: z.string().optional().describe("add_streaming_sublevel: LevelStreamingDynamic (default) | LevelStreamingAlwaysLoaded"),
    initiallyLoaded: z.boolean().optional(),
    initiallyVisible: z.boolean().optional(),
    editorVisible: z.boolean().optional().describe("set_streaming_sublevel_properties: editor viewport visibility"),
    min: Vec3.optional().describe("spawn_grid lower bound"),
    max: Vec3.optional().describe("spawn_grid upper bound"),
    countX: z.number().optional(),
    countY: z.number().optional(),
    countZ: z.number().optional(),
    jitter: z.number().optional().describe("spawn_grid: per-axis location jitter"),
    offset: Vec3.optional(),
    actors: z.array(z.object({
      staticMesh: z.string(),
      location: Vec3.optional(),
      rotation: Rotator.optional(),
      scale: Vec3.optional(),
      label: z.string().optional(),
    })).optional().describe("place_actors_batch: per-instance mesh+transform records"),
  },
);
