import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Color } from "../schemas.js";

export const materialTool: ToolDef = categoryTool(
  "material",
  "Materials: create, read, parameters, shading, textures, and graph authoring (expression nodes, connections).",
  {
    read:              bp("Read material structure. Params: assetPath", "read_material", (p) => ({ assetPath: p.assetPath })),
    list_parameters:   bp("List overridable parameters. Params: assetPath", "list_material_parameters", (p) => ({ assetPath: p.assetPath })),
    set_parameter:     bp("Set parameter on MaterialInstance. Params: assetPath, parameterName, parameterType, value", "set_material_parameter"),
    set_expression_value: bp("Set value on expression node. Params: materialPath, expressionIndex, value", "set_expression_value"),
    disconnect_property: bp("Disconnect a material property input. Params: materialPath, property", "disconnect_material_property"),
    create_instance:   bp("Create material instance. Params: parentPath, name?, packagePath?", "create_material_instance"),
    create:            bp("Create material. Params: name, packagePath?", "create_material"),
    create_simple:     bp("Single-call simple material. Params: name, packagePath?, baseColor? ({r,g,b}), metallic?, specular?, roughness?, emissive?, usages?[] (e.g. InstancedStaticMeshes, Nanite, NiagaraSprites). Recompiles + saves in one shot (#225)", "create_material_simple", (p) => ({ name: p.name, packagePath: p.packagePath, baseColor: p.baseColor, metallic: p.metallic, specular: p.specular, roughness: p.roughness, emissive: p.emissive, usages: p.usages, onConflict: p.onConflict })),
    set_usage:         bp("Set EMaterialUsage flag(s) on a material. Params: assetPath, usage OR usages[], enabled? (default true). Recompiles + saves (#225)", "set_material_usage", (p) => ({ assetPath: p.assetPath ?? p.materialPath, usage: p.usage, usages: p.usages, enabled: p.enabled })),
    set_shading_model: bp("Set shading model. Params: assetPath, shadingModel", "set_material_shading_model"),
    set_blend_mode:    bp("Set blend mode. Params: assetPath, blendMode", "set_material_blend_mode"),
    set_domain:        bp("Set material domain. Params: assetPath, materialDomain (Surface | DeferredDecal | LightFunction | Volume | PostProcess | UI | RuntimeVirtualTexture). Required for post-process / decal / UI authoring (#299/#356).", "set_material_domain", (p) => ({ assetPath: p.assetPath, materialDomain: p.materialDomain, domain: p.domain })),
    set_base_color:    bp("Set base color. Params: assetPath, color", "set_material_base_color"),
    connect_texture:   bp("Connect texture to property. Params: materialPath, texturePath, property", "connect_texture_to_material"),
    add_expression:    bp("Add expression node. Params: materialPath, expressionType, name?, parameterName?, group?, sortPriority?, defaultValue? (scalar number or {r,g,b,a} for vector params), value? (number for Constant, {r,g,b} for Constant3Vector, {x,y} for Constant2Vector), channels? ({r,g,b,a} bools for ComponentMask), positionX?, positionY? (#318)", "add_material_expression"),
    connect_expressions: bp("Wire two expressions. Params: materialPath, sourceExpression, sourceOutput?, targetExpression, targetInput?", "connect_material_expressions"),
    connect_to_property: bp("Wire expression to material output. Params: materialPath, expressionName, outputName?, property", "connect_to_material_property"),
    list_expressions:  bp("List expression nodes. Params: materialPath", "list_material_expressions"),
    delete_expression: bp("Remove expression. Params: materialPath, expressionName", "delete_material_expression"),
    list_expression_types: bp("List available expression types", "list_expression_types"),
    recompile:         bp("Recompile material. Pass recompileChildren=true to cascade to every MaterialInstanceConstant whose parent chain reaches this material (#421). Params: materialPath, recompileChildren?", "recompile_material", (p) => ({ materialPath: p.materialPath, recompileChildren: p.recompileChildren })),
    duplicate:         bp("Duplicate material asset. Params: sourcePath, destinationPath", "duplicate_material"),
    validate:          bp("Validate material graph — find orphans, broken refs. Params: assetPath", "validate_material", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    get_shader_stats:  bp("Shader compile stats, sampler+param counts. Params: assetPath", "get_material_shader_stats", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    export_graph:      bp("Export material graph as JSON. Params: assetPath", "export_material_graph", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    import_graph:      bp("Rebuild graph from JSON. Params: assetPath, nodes, propertyConnections?", "import_material_graph"),
    build_graph:       bp("Build graph from spec. Params: assetPath, nodes, propertyConnections?", "build_material_graph"),
    render_preview:    bp("Render preview PNG. Params: assetPath, outputPath, width?, height?", "render_material_preview", (p) => ({ assetPath: p.assetPath ?? p.materialPath, outputPath: p.outputPath, width: p.width, height: p.height })),
    begin_transaction: bp("Begin undo transaction. Params: label?", "begin_material_transaction"),
    end_transaction:   bp("End undo transaction", "end_material_transaction"),
  },
  undefined,
  {
    assetPath: z.string().optional(),
    parameterName: z.string().optional(),
    parameterType: z.string().optional().describe("Parameter type for set_parameter: scalar, vector, texture"),
    expressionIndex: z.number().optional(),
    value: z.unknown().optional(),
    parentPath: z.string().optional(),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    shadingModel: z.string().optional(),
    blendMode: z.string().optional().describe("Blend mode: Opaque, Masked, Translucent, Additive, Modulate, AlphaComposite, AlphaHoldout"),
    materialDomain: z.string().optional().describe("Material domain for set_domain: Surface, DeferredDecal, LightFunction, Volume, PostProcess, UI, RuntimeVirtualTexture"),
    domain: z.string().optional().describe("Alias for materialDomain"),
    group: z.string().optional().describe("Parameter Group on add_expression for parameter nodes (#318)"),
    sortPriority: z.number().optional().describe("SortPriority within a parameter Group"),
    defaultValue: z.union([z.number(), z.record(z.unknown())]).optional().describe("ScalarParameter default (number) or VectorParameter default ({r,g,b,a})"),
    channels: z.record(z.unknown()).optional().describe("ComponentMask channels {r,g,b,a} bools"),
    positionX: z.number().optional(),
    positionY: z.number().optional(),
    color: Color.optional(),
    materialPath: z.string().optional(),
    recompileChildren: z.boolean().optional().describe("recompile_material: cascade to MaterialInstances whose parent chain reaches this material"),
    texturePath: z.string().optional(),
    property: z.string().optional().describe("Material property: BaseColor, Normal, Roughness, Metallic, EmissiveColor, etc."),
    expressionType: z.string().optional().describe("Expression type: Constant, TextureSample, Multiply, Lerp, ScalarParameter, etc."),
    x: z.number().optional(), y: z.number().optional(),
    properties: z.record(z.unknown()).optional(),
    sourceExpression: z.string().optional(),
    sourceOutput: z.string().optional(),
    targetExpression: z.string().optional(),
    targetInput: z.string().optional(),
    expressionName: z.string().optional(),
    outputName: z.string().optional(),
    sourcePath: z.string().optional(), destinationPath: z.string().optional(),
    outputPath: z.string().optional().describe("Absolute file path for render_preview PNG output"),
    width: z.number().optional(), height: z.number().optional(),
    nodes: z.array(z.record(z.unknown())).optional().describe("Graph spec: [{name,class,posX,posY,...}]"),
    propertyConnections: z.array(z.record(z.unknown())).optional().describe("[{property,from,outputIndex}]"),
    label: z.string().optional().describe("Transaction label"),
    baseColor: Color.optional().describe("create_simple base color"),
    metallic: z.number().optional(),
    specular: z.number().optional(),
    roughness: z.number().optional(),
    emissive: z.number().optional(),
    usage: z.string().optional().describe("set_usage: single MATUSAGE flag name"),
    usages: z.array(z.string()).optional().describe("MATUSAGE flag names for create_simple/set_usage (InstancedStaticMeshes, Nanite, NiagaraSprites, ...)"),
    enabled: z.boolean().optional().describe("set_usage: enable (default true) or disable"),
    onConflict: z.string().optional().describe("create_simple: skip (default) | error"),
  },
);
