import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";

export const statetreeTool: ToolDef = categoryTool(
  "statetree",
  "StateTree asset editing: read, modify states/tasks/conditions/transitions/bindings/evaluators/global tasks/colors/state parameters/root parameters, compile and validate.",
  {
    read:                   bp("Full dump of a StateTree asset: state hierarchy (with description, tag, customTickRate, color), tasks, conditions, transitions, evaluators, global tasks, root params, bindings. Params: assetPath", "read_state_tree"),
    list_states:            bp("List all states with IDs and paths. Params: assetPath", "list_state_tree_states"),
    add_state:              bp("Add child state. Params: assetPath, stateId? (parent GUID, omit for root), name, stateType? (State|Group|LinkedAsset|Subtree), selectionBehavior?, insertIndex?", "add_state_tree_state"),
    remove_state:           bp("Remove a state by ID. Params: assetPath, stateId", "remove_state_tree_state"),
    set_state_property:     bp("Set a property on a state. Params: assetPath, stateId, propertyName (name|type|selectionBehavior|bEnabled|weight|linkedAsset|description|tag|customTickRate|color), value. For tag: gameplay tag string or empty to clear. For customTickRate: number in seconds or empty to disable. For color: palette color display name, GUID, or empty to clear.", "set_state_tree_state_property"),
    clear_state_nodes:      bp("Remove all tasks/conditions/transitions from a state. Params: assetPath, stateId", "clear_state_tree_state_nodes"),
    add_task:               bp("Add a task to a state. Params: assetPath, stateId, structType (C++ struct name e.g. FMyStateTreeTask or an engine-shipped task like FStateTreeRunParallelStateTreesTask), instanceProperties?", "add_state_tree_task"),
    add_enter_condition:    bp("Add an enter condition to a state. Params: assetPath, stateId, structType (C++ struct name), instanceProperties?, operand? (And|Or)", "add_state_tree_enter_condition"),
    remove_enter_condition: bp("Remove an enter condition by index. Params: assetPath, stateId, conditionIndex", "remove_state_tree_enter_condition"),
    remove_task:            bp("Remove a task by index. Params: assetPath, stateId, taskIndex", "remove_state_tree_task"),
    set_task_instance_property: bp("Set a property on a task's instance data. Params: assetPath, stateId, taskIndex, propertyName, value", "set_state_tree_task_instance_property"),
    set_task_property:      bp("Set a property on the task's node struct (FStateTreeTaskBase-level: bConsideredForCompletion, bTaskEnabled, bShouldStateChangeOnReselect). Distinct from set_task_instance_property which targets instance data. Params: assetPath, stateId, taskIndex, propertyName, value (string-encoded e.g. 'true'/'false')", "set_state_tree_task_property"),
    add_transition:         bp("Add a transition to a state. Params: assetPath, stateId, trigger (OnStateCompleted|OnStateSucceeded|OnStateFailed|OnTick|OnEvent; combine with | e.g. OnStateSucceeded|OnStateFailed), transitionType (GotoState|NextState|Succeeded|Failed), eventTag?, targetStateId?, targetStatePath?, priority? (Low|Normal|Medium|High|Critical), delayDuration?, bDelayTransition?", "add_state_tree_transition"),
    add_transition_condition: bp("Add a condition to an existing transition. Params: assetPath, stateId, transitionIndex, structType, instanceProperties?, operand?", "add_state_tree_transition_condition"),
    remove_transition:      bp("Remove a transition by index. Params: assetPath, stateId, transitionIndex", "remove_state_tree_transition"),
    add_binding:            bp("Add a property binding. Params: assetPath, sourceStructId, sourcePath, targetStructId, targetPath", "add_state_tree_binding"),
    remove_binding:         bp("Remove a property binding. Params: assetPath, targetStructId, targetPath", "remove_state_tree_binding"),
    list_bindings:          bp("List all property bindings. Params: assetPath, structId? (filter)", "list_state_tree_bindings"),
    add_evaluator:          bp("Add an evaluator to the StateTree (tree-level). Params: assetPath, structType (must derive from FStateTreeEvaluatorBase), instanceProperties?", "add_state_tree_evaluator"),
    remove_evaluator:       bp("Remove an evaluator by node ID. Params: assetPath, nodeId", "remove_state_tree_evaluator"),
    set_evaluator_instance_property: bp("Set a property on an evaluator's instance data. Params: assetPath, nodeId, propertyName, value", "set_state_tree_evaluator_instance_property"),
    set_evaluator_property: bp("Set a property on the evaluator's node struct (FStateTreeEvaluatorBase-level). Params: assetPath, nodeId, propertyName, value", "set_state_tree_evaluator_property"),
    add_global_task:        bp("Add a global task to the StateTree (tree-level). Params: assetPath, structType (must derive from FStateTreeTaskBase), instanceProperties?", "add_state_tree_global_task"),
    remove_global_task:     bp("Remove a global task by node ID. Params: assetPath, nodeId", "remove_state_tree_global_task"),
    set_global_task_instance_property: bp("Set a property on a global task's instance data. Params: assetPath, nodeId, propertyName, value", "set_state_tree_global_task_instance_property"),
    set_global_task_property: bp("Set a property on a global task's node struct (FStateTreeTaskBase-level). Params: assetPath, nodeId, propertyName, value", "set_state_tree_global_task_property"),
    list_colors:            bp("List all color palette entries for a StateTree. Params: assetPath. Returns: colors[] with id, displayName, color.", "list_state_tree_colors"),
    add_color:              bp("Add a new color to the StateTree palette. Params: assetPath, displayName, color? (FLinearColor string e.g. '(R=1.0,G=0.0,B=0.0,A=1.0)')", "add_state_tree_color"),
    list_state_parameters:  bp("List parameters defined on a state. Params: assetPath, stateId. Returns: parameters[] with name, id, type, value; also bFixedLayout.", "list_state_tree_state_parameters"),
    add_state_parameter:    bp("Add a parameter to a state's property bag. Rejects fixed-layout (linked) states. Params: assetPath, stateId, paramName, paramType (Bool|Int32|Int64|Float|Double|Name|String|Text)", "add_state_tree_state_parameter"),
    remove_state_parameter: bp("Remove a parameter from a state's property bag by name. Rejects fixed-layout (linked) states. Params: assetPath, stateId, paramName", "remove_state_tree_state_parameter"),
    set_state_parameter:    bp("Set the value of an existing state parameter. On fixed-layout states, also marks the parameter as overridden. Params: assetPath, stateId, paramName, value", "set_state_tree_state_parameter"),
    set_root_parameters:    bp("Define root parameters (property bag). Params: assetPath, parameters[] ({name, type}) where type is float|int32|bool|string|name|double", "set_state_tree_root_parameters"),
    compile:                bp("Compile a StateTree asset. Returns success, errors[], warnings[]. Params: assetPath", "compile_state_tree"),
    validate:               bp("Validate a StateTree asset without compiling. Params: assetPath", "validate_state_tree"),
  },
  undefined,
  {
    assetPath: z.string().describe("StateTree asset path, e.g. /Game/Path/To/ST_Asset"),
    stateId: z.string().optional().describe("GUID of the target state (or parent state for add_state)"),
    statePath: z.string().optional().describe("Dot-path to state as alternative to stateId"),
    name: z.string().optional().describe("Name for a new state"),
    stateType: z.string().optional().describe("State type: State, Group, LinkedAsset, Subtree"),
    selectionBehavior: z.string().optional().describe("Selection behavior: TryEnterState, TrySelectChildrenInOrder, TrySelectChildrenAtRandom, etc."),
    insertIndex: z.number().optional().describe("Insert position for add_state"),
    propertyName: z.string().optional().describe("Property name for set_state_property / set_task_instance_property / set_evaluator_instance_property / set_global_task_instance_property"),
    value: z.string().optional().describe("Property value to set (as string)"),
    structType: z.string().optional().describe("C++ struct name for tasks/conditions/evaluators, e.g. FMyStateTreeTask"),
    instanceProperties: z.record(z.unknown()).optional().describe("Key-value map of instance data properties to set on new tasks/conditions/evaluators/global tasks"),
    operand: z.string().optional().describe("Expression operand for conditions: And or Or"),
    taskIndex: z.number().optional().describe("Task index within the state for remove/set operations"),
    conditionIndex: z.number().optional().describe("Enter condition index for remove_enter_condition"),
    trigger: z.string().optional().describe("Transition trigger: OnStateCompleted, OnStateSucceeded, OnStateFailed, OnTick, OnEvent"),
    transitionType: z.string().optional().describe("Transition type: GotoState, NextState, Succeeded, Failed, NextSelectableState"),
    eventTag: z.string().optional().describe("Gameplay tag for OnEvent transitions, e.g. MyGame.SomeEvent"),
    targetStateId: z.string().optional().describe("Target state GUID for GotoState transitions"),
    targetStatePath: z.string().optional().describe("Target state dot-path for GotoState transitions"),
    priority: z.string().optional().describe("Transition priority: Low, Normal, Medium, High, Critical"),
    delayDuration: z.number().optional().describe("Transition delay in seconds"),
    bDelayTransition: z.boolean().optional().describe("Enable transition delay"),
    transitionIndex: z.number().optional().describe("Transition index for remove/condition operations"),
    sourceStructId: z.string().optional().describe("Source struct GUID for bindings"),
    sourcePath: z.string().optional().describe("Source property path for bindings"),
    targetStructId: z.string().optional().describe("Target struct GUID for bindings"),
    targetPath: z.string().optional().describe("Target property path for bindings"),
    structId: z.string().optional().describe("Filter bindings by struct GUID"),
    nodeId: z.string().optional().describe("GUID of an evaluator or global task node (for remove/set_*_property operations)"),
    displayName: z.string().optional().describe("Display name for a new color palette entry"),
    color: z.string().optional().describe("FLinearColor string e.g. '(R=1.0,G=0.0,B=0.0,A=1.0)' for add_color"),
    paramName: z.string().optional().describe("Parameter name for state parameter operations"),
    paramType: z.string().optional().describe("Parameter type for add_state_parameter: Bool, Int32, Int64, Float, Double, Name, String, Text"),
    parameters: z.array(z.object({
      name: z.string(),
      type: z.string(),
    })).optional().describe("Root parameter definitions: [{name, type}] where type is float, int32, bool, string, name, double"),
    linkedSubtree: z.string().optional().describe("Asset path for LinkedAsset/Subtree states"),
  },
);
