import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";

export const widgetTool: ToolDef = categoryTool(
  "widget",
  "UMG Widget Blueprints, Editor Utility Widgets, and Editor Utility Blueprints.",
  {
    read_tree:         bp("Read widget hierarchy. Params: assetPath", "read_widget_tree"),
    get_details:       bp("Inspect widget. Params: assetPath, widgetName", "get_widget_details"),
    set_property:      bp("Set widget property. Params: assetPath, widgetName, propertyName, value", "set_widget_property"),
    list:              bp("List Widget BPs. Params: directory?, recursive?", "list_widget_blueprints"),
    read_animations:   bp("Read UMG animations. Params: assetPath", "read_widget_animations"),
    create:            bp("Create Widget BP. Params: name, packagePath?, parentClass?", "create_widget_blueprint"),
    create_utility_widget:    bp("Create editor utility widget. Params: name, packagePath?", "create_editor_utility_widget"),
    run_utility_widget:       bp("Open editor utility widget. Params: assetPath", "run_editor_utility_widget"),
    create_utility_blueprint: bp("Create editor utility blueprint. Params: name, packagePath?", "create_editor_utility_blueprint"),
    run_utility_blueprint:    bp("Run editor utility blueprint. Params: assetPath", "run_editor_utility_blueprint"),
    add_widget:               bp("Add widget to widget tree. Params: assetPath, widgetClass, widgetName?, parentWidgetName?", "add_widget"),
    remove_widget:            bp("Remove widget from tree. Params: assetPath, widgetName", "remove_widget"),
    move_widget:              bp("Reparent widget. Params: assetPath, widgetName, newParentWidgetName", "move_widget"),
    set_root:                 bp("Replace WBP root with an existing widget by name (#365). Params: assetPath, widgetName", "set_root_widget", (p) => ({ assetPath: p.assetPath, path: p.path, widgetName: p.widgetName })),
    wrap_root:                bp("Wrap the current root in a new panel widget (UMG 'Wrap With'). Params: assetPath, wrapperClass (must be a UPanelWidget subclass), wrapperName? (#365)", "wrap_root_widget", (p) => ({ assetPath: p.assetPath, path: p.path, wrapperClass: p.wrapperClass, widgetClass: p.widgetClass, wrapperName: p.wrapperName })),
    list_classes:             bp("List available widget classes", "list_widget_classes"),
    list_runtime:             bp("(#160) List live UUserWidget instances in the PIE world. Params: classFilter?, namePrefix?, viewportOnly?", "list_runtime_widgets"),
    get_runtime:              bp("(#160) Inspect a live PIE widget tree with text/visibility/brush/percent values. Params: widgetName? | className?, childName?, maxDepth?", "get_runtime_widget"),
    get_runtime_delegates:    bp("(#161) Read delegate binding state on a live PIE widget. Params: widgetName, className?. Returns array of {delegateName, isBound, numBindings}", "get_runtime_delegates"),
  },
  undefined,
  {
    assetPath: z.string().optional(),
    widgetName: z.string().optional(),
    widgetClass: z.string().optional(),
    parentWidgetName: z.string().optional(),
    newParentWidgetName: z.string().optional(),
    propertyName: z.string().optional(),
    value: z.unknown().optional(),
    directory: z.string().optional(),
    recursive: z.boolean().optional(),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    parentClass: z.string().optional(),
    classFilter: z.string().optional().describe("Class name substring filter for list_runtime"),
    className: z.string().optional().describe("Widget class name for get_runtime (first match wins)"),
    namePrefix: z.string().optional().describe("Instance name prefix filter for list_runtime"),
    viewportOnly: z.boolean().optional().describe("list_runtime: only return widgets currently added to the viewport"),
    childName: z.string().optional().describe("get_runtime: restrict the tree walk to the named child inside the UserWidget"),
    maxDepth: z.number().optional().describe("get_runtime: max widget-tree depth to walk (default 6)"),
    wrapperClass: z.string().optional().describe("wrap_root: panel widget class (CanvasPanel, VerticalBox, Overlay, etc.)"),
    wrapperName: z.string().optional().describe("wrap_root: optional name for the new wrapper widget"),
    path: z.string().optional().describe("Alias for assetPath"),
  },
);
