/**
 * SDK Conversion / Round-Trip Tests
 *
 * Proves the critical migration path: a standard markdown-based squad
 * (.squad/ with team.md, routing.md, agent charters) can be "converted"
 * to SDK mode (squad.config.ts using builder functions), and `squad build`
 * regenerates functionally-equivalent .squad/ markdown from the typed config.
 *
 * Test coverage:
 *   1. Original markdown squad structure is valid and complete
 *   2. SDK config (via builders) models the same team
 *   3. Build output preserves team members, routing rules, agent identities
 *   4. Protected files (decisions.md, history.md, orchestration-log/) survive build
 *   5. Edge cases: custom content, extra agents, minimal squads
 *
 * ⚠️ Uses local stubs matching build-command.test.ts patterns.
 * When Fenster's build command lands, replace stubs with real imports.
 *
 * @see packages/squad-cli/src/cli/commands/build.ts
 * @see packages/squad-sdk/src/builders/index.ts
 * @module test/sdk-conversion
 */

import { describe, it, expect, afterEach } from 'vitest';
import {
  mkdtempSync,
  writeFileSync,
  readFileSync,
  mkdirSync,
  rmSync,
  existsSync,
} from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import type {
  TeamDefinition,
  AgentDefinition,
  RoutingDefinition,
  CeremonyDefinition,
  SquadSDKConfig,
} from '../packages/squad-sdk/src/builders/types.js';

// ============================================================================
// Constants
// ============================================================================

const GENERATED_HEADER = '<!-- generated by squad build -->';

// ============================================================================
// Helpers — temp dir management
// ============================================================================

const tmpDirs: string[] = [];

function makeTmpDir(): string {
  const dir = mkdtempSync(join(tmpdir(), 'squad-conversion-test-'));
  tmpDirs.push(dir);
  return dir;
}

// ============================================================================
// Local builder stubs (same contract as builders.test.ts)
//
// ⚠️ When the real builders land, replace with:
//   import { defineTeam, defineAgent, defineRouting, defineCeremony }
//     from '../packages/squad-sdk/src/builders/index.js';
// ============================================================================

function defineTeam(config: TeamDefinition): TeamDefinition {
  if (!config.name || config.name.trim() === '') throw new Error('defineTeam: name required');
  if (!Array.isArray(config.members) || config.members.length === 0) throw new Error('defineTeam: members required');
  return config;
}

function defineAgent(config: AgentDefinition): AgentDefinition {
  if (!config.name || config.name.trim() === '') throw new Error('defineAgent: name required');
  if (!config.role || config.role.trim() === '') throw new Error('defineAgent: role required');
  return config;
}

function defineRouting(config: RoutingDefinition): RoutingDefinition {
  if (!Array.isArray(config.rules)) throw new Error('defineRouting: rules must be an array');
  return config;
}

function defineCeremony(config: CeremonyDefinition): CeremonyDefinition {
  if (!config.name || config.name.trim() === '') throw new Error('defineCeremony: name required');
  return config;
}

// ============================================================================
// Local build stubs (same contract as build-command.test.ts)
//
// ⚠️ When Fenster's build command lands, replace with:
//   import { runBuild } from
//     '../packages/squad-cli/src/cli/commands/build.js';
// ============================================================================

function generateTeamMd(config: SquadSDKConfig): string {
  const lines: string[] = [GENERATED_HEADER, '', `# ${config.team.name}`];
  if (config.team.description) lines.push('', config.team.description);
  lines.push('', '## Members', '');
  for (const m of config.team.members) {
    const agent = config.agents.find((a) => a.name === m);
    lines.push(`- **${m}** — ${agent?.role ?? 'Unknown'}`);
  }
  return lines.join('\n') + '\n';
}

function generateRoutingMd(config: SquadSDKConfig): string {
  if (!config.routing) return '';
  const lines: string[] = [GENERATED_HEADER, '', '# Routing'];
  if (config.routing.defaultAgent) {
    lines.push('', `**Default agent:** ${config.routing.defaultAgent}`);
  }
  lines.push('', '## Rules', '');
  for (const rule of config.routing.rules) {
    lines.push(`- \`${rule.pattern}\` → ${rule.agents.join(', ')}`);
  }
  return lines.join('\n') + '\n';
}

function generateCharterMd(agent: AgentDefinition): string {
  const lines: string[] = [
    GENERATED_HEADER,
    '',
    `# ${agent.name} — ${agent.role}`,
  ];
  if (agent.charter) lines.push('', agent.charter);
  if (agent.model) lines.push('', `**Model:** ${agent.model}`);
  if (agent.tools && agent.tools.length > 0) {
    lines.push('', '## Tools', '');
    for (const t of agent.tools) lines.push(`- ${t}`);
  }
  return lines.join('\n') + '\n';
}

function generateCeremoniesMd(config: SquadSDKConfig): string {
  if (!config.ceremonies || config.ceremonies.length === 0) return '';
  const lines: string[] = [GENERATED_HEADER, '', '# Ceremonies'];
  for (const c of config.ceremonies) {
    lines.push('', `## ${c.name}`);
    if (c.schedule) lines.push(`**Schedule:** ${c.schedule}`);
    if (c.participants && c.participants.length > 0) {
      lines.push(`**Participants:** ${c.participants.join(', ')}`);
    }
    if (c.agenda) lines.push('', c.agenda);
  }
  return lines.join('\n') + '\n';
}

function runBuild(config: SquadSDKConfig, squadDir: string): { filesWritten: string[] } {
  const written: string[] = [];

  writeFileSync(join(squadDir, 'team.md'), generateTeamMd(config));
  written.push('team.md');

  if (config.routing) {
    writeFileSync(join(squadDir, 'routing.md'), generateRoutingMd(config));
    written.push('routing.md');
  }

  for (const agent of config.agents) {
    const charterDir = join(squadDir, 'agents', agent.name);
    mkdirSync(charterDir, { recursive: true });
    writeFileSync(join(charterDir, 'charter.md'), generateCharterMd(agent));
    written.push(`agents/${agent.name}/charter.md`);
  }

  if (config.ceremonies && config.ceremonies.length > 0) {
    writeFileSync(join(squadDir, 'ceremonies.md'), generateCeremoniesMd(config));
    written.push('ceremonies.md');
  }

  return { filesWritten: written };
}

// ============================================================================
// Fixture: hand-written markdown squad (the "original" before conversion)
// ============================================================================

/**
 * Creates a complete, hand-written .squad/ directory that represents
 * a "normal" markdown-based squad — the starting point before SDK conversion.
 */
function createOriginalMarkdownSquad(root: string): string {
  const squadDir = join(root, '.squad');
  mkdirSync(join(squadDir, 'agents', 'edie'), { recursive: true });
  mkdirSync(join(squadDir, 'agents', 'hockney'), { recursive: true });
  mkdirSync(join(squadDir, 'orchestration-log'), { recursive: true });
  mkdirSync(join(squadDir, 'decisions', 'inbox'), { recursive: true });

  // team.md — hand-written, no generated header
  writeFileSync(
    join(squadDir, 'team.md'),
    `# Alpha Squad

> The core engineering team for the replatform.

## Coordinator

| Name | Role |
|------|------|
| Squad | Coordinator |

## Members

| Name | Role | Charter |
|------|------|---------|
| Edie | TypeScript Engineer | \`.squad/agents/edie/charter.md\` |
| Hockney | Tester | \`.squad/agents/hockney/charter.md\` |
`,
  );

  // routing.md — hand-written
  writeFileSync(
    join(squadDir, 'routing.md'),
    `# Routing Rules

**Default agent:** edie

## Rules

- \`feature-*\` → edie
- \`test-*\` → hockney
- \`bug-*\` → edie, hockney
`,
  );

  // Agent charters — hand-written
  writeFileSync(
    join(squadDir, 'agents', 'edie', 'charter.md'),
    `# Edie — TypeScript Engineer

> Precise, opinionated. Types are contracts.

## What I Own
- All TypeScript implementation code
- Type system design and strict mode compliance

## How I Work
- strict: true, noUncheckedIndexedAccess: true
- No @ts-ignore allowed
`,
  );

  writeFileSync(
    join(squadDir, 'agents', 'hockney', 'charter.md'),
    `# Hockney — Tester

> Skeptical, relentless. If it can break, he'll find how.

## What I Own
- Test coverage and quality gates
- Edge case discovery

## How I Work
- 80% coverage is the floor, not the ceiling
- 100% on critical paths
`,
  );

  // Protected files — custom content that MUST survive conversion
  writeFileSync(
    join(squadDir, 'decisions.md'),
    `# Decisions

> Team decisions that all agents must respect.

### 2026-02-21: Type safety — strict mode non-negotiable
**By:** Edie
**What:** strict: true everywhere.

### 2026-02-21: No temp files in repo root
**By:** Brady
**What:** All squad state in .squad/ only.
`,
  );

  writeFileSync(
    join(squadDir, 'agents', 'edie', 'history.md'),
    `# Edie — Project History

## Learnings

### Phase 1 builder functions (2026-03-05)
Built 8 builder functions with runtime validation. Zero dependencies.
`,
  );

  writeFileSync(
    join(squadDir, 'agents', 'hockney', 'history.md'),
    `# Hockney — Project History

## Learnings

### Phase 1 SDK tests (2026-03-05)
60 contract-first tests: 36 builders, 24 build command. All passing.
`,
  );

  writeFileSync(
    join(squadDir, 'orchestration-log', '2026-03-01.md'),
    `# Session — 2026-03-01

## Summary
Brady kicked off Phase 1 SDK-first mode.
Edie designed builder types, Hockney wrote tests.
`,
  );

  writeFileSync(
    join(squadDir, 'decisions', 'inbox', 'edie-builder-naming.md'),
    `### Builder naming: defineXxx pattern
**By:** Edie
**What:** All builder functions use defineXxx() naming.
`,
  );

  return squadDir;
}

/**
 * Build the SDK config that models the same team as the hand-written
 * markdown squad above. This is what a user would write in squad.config.ts
 * when converting from markdown to SDK mode.
 */
function buildEquivalentSDKConfig(): SquadSDKConfig {
  return {
    version: '1.0.0',
    team: defineTeam({
      name: 'Alpha Squad',
      description: 'The core engineering team for the replatform.',
      members: ['edie', 'hockney'],
    }),
    agents: [
      defineAgent({
        name: 'edie',
        role: 'TypeScript Engineer',
        charter: 'Precise, opinionated. Types are contracts.',
        model: 'claude-sonnet-4',
      }),
      defineAgent({
        name: 'hockney',
        role: 'Tester',
        charter: 'Skeptical, relentless. If it can break, he\'ll find how.',
      }),
    ],
    routing: defineRouting({
      rules: [
        { pattern: 'feature-*', agents: ['edie'] },
        { pattern: 'test-*', agents: ['hockney'] },
        { pattern: 'bug-*', agents: ['edie', 'hockney'] },
      ],
      defaultAgent: 'edie',
    }),
    ceremonies: [
      defineCeremony({
        name: 'standup',
        schedule: '0 9 * * 1-5',
        participants: ['edie', 'hockney'],
      }),
    ],
  };
}

// ============================================================================
// Cleanup
// ============================================================================

afterEach(() => {
  for (const dir of tmpDirs) {
    try {
      rmSync(dir, { recursive: true, force: true });
    } catch {
      // best-effort cleanup
    }
  }
  tmpDirs.length = 0;
});

// ============================================================================
// 1. Original markdown squad is valid and complete
// ============================================================================

describe('original markdown squad — fixture validation', () => {
  it('has all expected files in the .squad/ directory', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);

    expect(existsSync(join(squadDir, 'team.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'routing.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'agents', 'edie', 'charter.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'agents', 'hockney', 'charter.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'decisions.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'agents', 'edie', 'history.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'agents', 'hockney', 'history.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'orchestration-log', '2026-03-01.md'))).toBe(true);
  });

  it('team.md contains team name and both members', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const content = readFileSync(join(squadDir, 'team.md'), 'utf-8');

    expect(content).toContain('Alpha Squad');
    expect(content).toContain('Edie');
    expect(content).toContain('Hockney');
    expect(content).toContain('TypeScript Engineer');
    expect(content).toContain('Tester');
  });

  it('routing.md contains routing rules and default agent', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const content = readFileSync(join(squadDir, 'routing.md'), 'utf-8');

    expect(content).toContain('feature-*');
    expect(content).toContain('test-*');
    expect(content).toContain('bug-*');
    expect(content).toContain('edie');
    expect(content).toContain('hockney');
  });

  it('original markdown has NO generated-by header', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);

    const teamMd = readFileSync(join(squadDir, 'team.md'), 'utf-8');
    const routingMd = readFileSync(join(squadDir, 'routing.md'), 'utf-8');
    const edieCharter = readFileSync(join(squadDir, 'agents', 'edie', 'charter.md'), 'utf-8');

    expect(teamMd).not.toContain(GENERATED_HEADER);
    expect(routingMd).not.toContain(GENERATED_HEADER);
    expect(edieCharter).not.toContain(GENERATED_HEADER);
  });
});

// ============================================================================
// 2. SDK config models the same team
// ============================================================================

describe('SDK config equivalence', () => {
  it('SDK config has the same team name', () => {
    const config = buildEquivalentSDKConfig();
    expect(config.team.name).toBe('Alpha Squad');
  });

  it('SDK config has the same member list', () => {
    const config = buildEquivalentSDKConfig();
    expect(config.team.members).toEqual(['edie', 'hockney']);
  });

  it('SDK config agents match original charter roles', () => {
    const config = buildEquivalentSDKConfig();
    const edie = config.agents.find((a) => a.name === 'edie');
    const hockney = config.agents.find((a) => a.name === 'hockney');

    expect(edie).toBeDefined();
    expect(edie!.role).toBe('TypeScript Engineer');
    expect(hockney).toBeDefined();
    expect(hockney!.role).toBe('Tester');
  });

  it('SDK config has same routing rules', () => {
    const config = buildEquivalentSDKConfig();
    expect(config.routing!.rules).toHaveLength(3);
    expect(config.routing!.rules[0]!.pattern).toBe('feature-*');
    expect(config.routing!.rules[1]!.pattern).toBe('test-*');
    expect(config.routing!.rules[2]!.pattern).toBe('bug-*');
    expect(config.routing!.defaultAgent).toBe('edie');
  });
});

// ============================================================================
// 3. Build output preserves team semantics (the round-trip)
// ============================================================================

describe('SDK conversion round-trip — build output', () => {
  it('generated team.md contains the same team name and members', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    runBuild(config, squadDir);

    const generated = readFileSync(join(squadDir, 'team.md'), 'utf-8');
    expect(generated).toContain('Alpha Squad');
    expect(generated).toContain('edie');
    expect(generated).toContain('hockney');
    expect(generated).toContain('TypeScript Engineer');
    expect(generated).toContain('Tester');
  });

  it('generated team.md has the generated-by header (marks it as SDK-managed)', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    runBuild(config, squadDir);

    const generated = readFileSync(join(squadDir, 'team.md'), 'utf-8');
    expect(generated).toContain(GENERATED_HEADER);
    expect(generated.indexOf(GENERATED_HEADER)).toBe(0);
  });

  it('generated routing.md contains the same rules', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    runBuild(config, squadDir);

    const generated = readFileSync(join(squadDir, 'routing.md'), 'utf-8');
    expect(generated).toContain('`feature-*`');
    expect(generated).toContain('`test-*`');
    expect(generated).toContain('`bug-*`');
    expect(generated).toContain('edie');
    expect(generated).toContain('hockney');
    expect(generated).toContain('edie, hockney');
    expect(generated).toContain('**Default agent:** edie');
  });

  it('generated charter files contain agent name and role', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    runBuild(config, squadDir);

    const edieCharter = readFileSync(join(squadDir, 'agents', 'edie', 'charter.md'), 'utf-8');
    expect(edieCharter).toContain('edie');
    expect(edieCharter).toContain('TypeScript Engineer');
    expect(edieCharter).toContain('Precise, opinionated');

    const hockneyCharter = readFileSync(join(squadDir, 'agents', 'hockney', 'charter.md'), 'utf-8');
    expect(hockneyCharter).toContain('hockney');
    expect(hockneyCharter).toContain('Tester');
    expect(hockneyCharter).toContain('Skeptical, relentless');
  });

  it('generated ceremonies.md contains ceremony details', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    runBuild(config, squadDir);

    const generated = readFileSync(join(squadDir, 'ceremonies.md'), 'utf-8');
    expect(generated).toContain('standup');
    expect(generated).toContain('0 9 * * 1-5');
    expect(generated).toContain('edie');
    expect(generated).toContain('hockney');
  });

  it('build overwrites original hand-written files with generated versions', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    const originalTeam = readFileSync(join(squadDir, 'team.md'), 'utf-8');
    expect(originalTeam).not.toContain(GENERATED_HEADER);

    runBuild(config, squadDir);

    const afterBuild = readFileSync(join(squadDir, 'team.md'), 'utf-8');
    expect(afterBuild).toContain(GENERATED_HEADER);
    expect(afterBuild).not.toBe(originalTeam);
  });
});

// ============================================================================
// 4. Protected files survive conversion (CRITICAL)
// ============================================================================

describe('SDK conversion — protected files preserved', () => {
  it('decisions.md is NOT overwritten during build', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    const originalDecisions = readFileSync(join(squadDir, 'decisions.md'), 'utf-8');
    expect(originalDecisions).toContain('strict mode non-negotiable');
    expect(originalDecisions).toContain('No temp files in repo root');

    runBuild(config, squadDir);

    const afterBuild = readFileSync(join(squadDir, 'decisions.md'), 'utf-8');
    expect(afterBuild).toBe(originalDecisions);
    expect(afterBuild).not.toContain(GENERATED_HEADER);
  });

  it('agent history.md files are NOT overwritten during build', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    const edieHistory = readFileSync(join(squadDir, 'agents', 'edie', 'history.md'), 'utf-8');
    const hockneyHistory = readFileSync(join(squadDir, 'agents', 'hockney', 'history.md'), 'utf-8');

    expect(edieHistory).toContain('Phase 1 builder functions');
    expect(hockneyHistory).toContain('Phase 1 SDK tests');

    runBuild(config, squadDir);

    expect(readFileSync(join(squadDir, 'agents', 'edie', 'history.md'), 'utf-8')).toBe(edieHistory);
    expect(readFileSync(join(squadDir, 'agents', 'hockney', 'history.md'), 'utf-8')).toBe(hockneyHistory);
  });

  it('orchestration-log/ entries are NOT touched during build', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    const logContent = readFileSync(join(squadDir, 'orchestration-log', '2026-03-01.md'), 'utf-8');
    expect(logContent).toContain('Brady kicked off Phase 1');

    runBuild(config, squadDir);

    const afterBuild = readFileSync(join(squadDir, 'orchestration-log', '2026-03-01.md'), 'utf-8');
    expect(afterBuild).toBe(logContent);
  });

  it('decisions/inbox/ files are NOT touched during build', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    const inboxContent = readFileSync(
      join(squadDir, 'decisions', 'inbox', 'edie-builder-naming.md'),
      'utf-8',
    );

    runBuild(config, squadDir);

    const afterBuild = readFileSync(
      join(squadDir, 'decisions', 'inbox', 'edie-builder-naming.md'),
      'utf-8',
    );
    expect(afterBuild).toBe(inboxContent);
  });

  it('custom decisions content with many entries survives build', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);

    // Add lots of custom decisions
    const heavyDecisions = `# Decisions

### 2026-01-01: Decision one
Content one.

### 2026-01-15: Decision two
Content two.

### 2026-02-01: Decision three
Content three with **bold** and \`code\`.

### 2026-02-15: Decision four
Content four with a [link](https://example.com).

### 2026-03-01: Decision five
Content five — most recent.
`;
    writeFileSync(join(squadDir, 'decisions.md'), heavyDecisions);

    const config = buildEquivalentSDKConfig();
    runBuild(config, squadDir);

    const afterBuild = readFileSync(join(squadDir, 'decisions.md'), 'utf-8');
    expect(afterBuild).toBe(heavyDecisions);
    expect(afterBuild).toContain('Decision one');
    expect(afterBuild).toContain('Decision five');
  });

  it('custom history with detailed learnings survives build', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);

    const detailedHistory = `# Edie — Project History

## Learnings

### Docker fix (2026-03-03)
Root cause: SDK package.json has prepare script that runs tsc.
Fix: strip prepare from package.json inside Dockerfile.

### Import resolution (2026-03-02)
Barrel exports must re-export all public types.
subpath exports require explicit entries in package.json exports map.

### Builder naming convention (2026-03-01)
All builders use defineXxx() pattern — mirrors Vite/Vitest conventions.
`;
    writeFileSync(join(squadDir, 'agents', 'edie', 'history.md'), detailedHistory);

    const config = buildEquivalentSDKConfig();
    runBuild(config, squadDir);

    const afterBuild = readFileSync(join(squadDir, 'agents', 'edie', 'history.md'), 'utf-8');
    expect(afterBuild).toBe(detailedHistory);
    expect(afterBuild).toContain('Docker fix');
    expect(afterBuild).toContain('Import resolution');
    expect(afterBuild).toContain('Builder naming convention');
  });
});

// ============================================================================
// 5. Edge cases
// ============================================================================

describe('SDK conversion — edge cases', () => {
  it('adding a new agent via SDK does not destroy existing protected files', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);

    // SDK config adds a third agent not in the original markdown
    const config: SquadSDKConfig = {
      ...buildEquivalentSDKConfig(),
      team: defineTeam({
        name: 'Alpha Squad',
        description: 'The core engineering team for the replatform.',
        members: ['edie', 'hockney', 'fenster'],
      }),
      agents: [
        defineAgent({ name: 'edie', role: 'TypeScript Engineer', charter: 'Types are contracts.' }),
        defineAgent({ name: 'hockney', role: 'Tester', charter: 'Breaks things.' }),
        defineAgent({ name: 'fenster', role: 'Core Developer', charter: 'Builds the engine.' }),
      ],
    };

    const edieHistory = readFileSync(join(squadDir, 'agents', 'edie', 'history.md'), 'utf-8');

    runBuild(config, squadDir);

    // New agent charter is created
    expect(existsSync(join(squadDir, 'agents', 'fenster', 'charter.md'))).toBe(true);
    const fensterCharter = readFileSync(join(squadDir, 'agents', 'fenster', 'charter.md'), 'utf-8');
    expect(fensterCharter).toContain('fenster');
    expect(fensterCharter).toContain('Core Developer');

    // Existing protected files untouched
    expect(readFileSync(join(squadDir, 'agents', 'edie', 'history.md'), 'utf-8')).toBe(edieHistory);
    expect(readFileSync(join(squadDir, 'decisions.md'), 'utf-8')).toContain('strict mode non-negotiable');
  });

  it('minimal squad — single agent, no routing, no ceremonies', () => {
    const root = makeTmpDir();
    const squadDir = join(root, '.squad');
    mkdirSync(squadDir, { recursive: true });

    const config: SquadSDKConfig = {
      team: defineTeam({ name: 'Solo Squad', members: ['solo'] }),
      agents: [defineAgent({ name: 'solo', role: 'Generalist' })],
    };

    runBuild(config, squadDir);

    expect(existsSync(join(squadDir, 'team.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'agents', 'solo', 'charter.md'))).toBe(true);
    expect(existsSync(join(squadDir, 'routing.md'))).toBe(false);
    expect(existsSync(join(squadDir, 'ceremonies.md'))).toBe(false);

    const teamMd = readFileSync(join(squadDir, 'team.md'), 'utf-8');
    expect(teamMd).toContain('Solo Squad');
    expect(teamMd).toContain('solo');
    expect(teamMd).toContain('Generalist');
  });

  it('re-running build is idempotent — same config produces same output', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    // First build
    runBuild(config, squadDir);
    const firstTeam = readFileSync(join(squadDir, 'team.md'), 'utf-8');
    const firstRouting = readFileSync(join(squadDir, 'routing.md'), 'utf-8');
    const firstEdie = readFileSync(join(squadDir, 'agents', 'edie', 'charter.md'), 'utf-8');

    // Second build — should produce identical output
    runBuild(config, squadDir);
    expect(readFileSync(join(squadDir, 'team.md'), 'utf-8')).toBe(firstTeam);
    expect(readFileSync(join(squadDir, 'routing.md'), 'utf-8')).toBe(firstRouting);
    expect(readFileSync(join(squadDir, 'agents', 'edie', 'charter.md'), 'utf-8')).toBe(firstEdie);
  });

  it('SDK config with agent model preference generates model line in charter', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    runBuild(config, squadDir);

    const edieCharter = readFileSync(join(squadDir, 'agents', 'edie', 'charter.md'), 'utf-8');
    expect(edieCharter).toContain('**Model:** claude-sonnet-4');
  });

  it('agent without model preference does NOT have model line in charter', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    runBuild(config, squadDir);

    const hockneyCharter = readFileSync(join(squadDir, 'agents', 'hockney', 'charter.md'), 'utf-8');
    expect(hockneyCharter).not.toContain('**Model:**');
  });

  it('SDK config with tools generates tools section in charter', () => {
    const root = makeTmpDir();
    const squadDir = join(root, '.squad');
    mkdirSync(squadDir, { recursive: true });

    const config: SquadSDKConfig = {
      team: defineTeam({ name: 'Tooled', members: ['tooler'] }),
      agents: [
        defineAgent({
          name: 'tooler',
          role: 'Toolsmith',
          tools: ['grep', 'edit', 'powershell'],
        }),
      ],
    };

    runBuild(config, squadDir);

    const charter = readFileSync(join(squadDir, 'agents', 'tooler', 'charter.md'), 'utf-8');
    expect(charter).toContain('## Tools');
    expect(charter).toContain('- grep');
    expect(charter).toContain('- edit');
    expect(charter).toContain('- powershell');
  });

  it('multi-agent routing rule serializes all agents', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    runBuild(config, squadDir);

    const routing = readFileSync(join(squadDir, 'routing.md'), 'utf-8');
    // The bug-* rule routes to both edie and hockney
    expect(routing).toContain('`bug-*` → edie, hockney');
  });

  it('build reports correct number of files written', () => {
    const root = makeTmpDir();
    const squadDir = createOriginalMarkdownSquad(root);
    const config = buildEquivalentSDKConfig();

    const result = runBuild(config, squadDir);

    // team.md + routing.md + 2 charters + ceremonies.md = 5
    expect(result.filesWritten).toHaveLength(5);
    expect(result.filesWritten).toContain('team.md');
    expect(result.filesWritten).toContain('routing.md');
    expect(result.filesWritten).toContain('agents/edie/charter.md');
    expect(result.filesWritten).toContain('agents/hockney/charter.md');
    expect(result.filesWritten).toContain('ceremonies.md');
  });

  it('empty orchestration-log directory is preserved during build', () => {
    const root = makeTmpDir();
    const squadDir = join(root, '.squad');
    mkdirSync(join(squadDir, 'orchestration-log'), { recursive: true });

    const config: SquadSDKConfig = {
      team: defineTeam({ name: 'Fresh', members: ['newbie'] }),
      agents: [defineAgent({ name: 'newbie', role: 'Learner' })],
    };

    runBuild(config, squadDir);

    expect(existsSync(join(squadDir, 'orchestration-log'))).toBe(true);
  });
});
