// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConvertibleAnnotation creates a new instance of MockConvertibleAnnotation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConvertibleAnnotation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConvertibleAnnotation {
	mock := &MockConvertibleAnnotation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConvertibleAnnotation is an autogenerated mock type for the ConvertibleAnnotation type
type MockConvertibleAnnotation struct {
	mock.Mock
}

type MockConvertibleAnnotation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConvertibleAnnotation) EXPECT() *MockConvertibleAnnotation_Expecter {
	return &MockConvertibleAnnotation_Expecter{mock: &_m.Mock}
}

// ToToolAnnotations provides a mock function for the type MockConvertibleAnnotation
func (_mock *MockConvertibleAnnotation) ToToolAnnotations() *mcp.ToolAnnotations {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToToolAnnotations")
	}

	var r0 *mcp.ToolAnnotations
	if returnFunc, ok := ret.Get(0).(func() *mcp.ToolAnnotations); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mcp.ToolAnnotations)
		}
	}
	return r0
}

// MockConvertibleAnnotation_ToToolAnnotations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToToolAnnotations'
type MockConvertibleAnnotation_ToToolAnnotations_Call struct {
	*mock.Call
}

// ToToolAnnotations is a helper method to define mock.On call
func (_e *MockConvertibleAnnotation_Expecter) ToToolAnnotations() *MockConvertibleAnnotation_ToToolAnnotations_Call {
	return &MockConvertibleAnnotation_ToToolAnnotations_Call{Call: _e.mock.On("ToToolAnnotations")}
}

func (_c *MockConvertibleAnnotation_ToToolAnnotations_Call) Run(run func()) *MockConvertibleAnnotation_ToToolAnnotations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConvertibleAnnotation_ToToolAnnotations_Call) Return(toolAnnotations *mcp.ToolAnnotations) *MockConvertibleAnnotation_ToToolAnnotations_Call {
	_c.Call.Return(toolAnnotations)
	return _c
}

func (_c *MockConvertibleAnnotation_ToToolAnnotations_Call) RunAndReturn(run func() *mcp.ToolAnnotations) *MockConvertibleAnnotation_ToToolAnnotations_Call {
	_c.Call.Return(run)
	return _c
}

// mwAnnotationSeal provides a mock function for the type MockConvertibleAnnotation
func (_mock *MockConvertibleAnnotation) mwAnnotationSeal() {
	_mock.Called()
	return
}

// MockConvertibleAnnotation_mwAnnotationSeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mwAnnotationSeal'
type MockConvertibleAnnotation_mwAnnotationSeal_Call struct {
	*mock.Call
}

// mwAnnotationSeal is a helper method to define mock.On call
func (_e *MockConvertibleAnnotation_Expecter) mwAnnotationSeal() *MockConvertibleAnnotation_mwAnnotationSeal_Call {
	return &MockConvertibleAnnotation_mwAnnotationSeal_Call{Call: _e.mock.On("mwAnnotationSeal")}
}

func (_c *MockConvertibleAnnotation_mwAnnotationSeal_Call) Run(run func()) *MockConvertibleAnnotation_mwAnnotationSeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConvertibleAnnotation_mwAnnotationSeal_Call) Return() *MockConvertibleAnnotation_mwAnnotationSeal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConvertibleAnnotation_mwAnnotationSeal_Call) RunAndReturn(run func()) *MockConvertibleAnnotation_mwAnnotationSeal_Call {
	_c.Run(run)
	return _c
}
