// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/config"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/definition"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolCallRequestFactory creates a new instance of MockToolCallRequestFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolCallRequestFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolCallRequestFactory {
	mock := &MockToolCallRequestFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolCallRequestFactory is an autogenerated mock type for the ToolCallRequestFactory type
type MockToolCallRequestFactory struct {
	mock.Mock
}

type MockToolCallRequestFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolCallRequestFactory) EXPECT() *MockToolCallRequestFactory_Expecter {
	return &MockToolCallRequestFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockToolCallRequestFactory
func (_mock *MockToolCallRequestFactory) New(internalLogger entities.Logger, internalConfig config.GenericConfig, internalMessageCatalog definition.MessageCatalog) publictypes.ToolCallRequest {
	ret := _mock.Called(internalLogger, internalConfig, internalMessageCatalog)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 publictypes.ToolCallRequest
	if returnFunc, ok := ret.Get(0).(func(entities.Logger, config.GenericConfig, definition.MessageCatalog) publictypes.ToolCallRequest); ok {
		r0 = returnFunc(internalLogger, internalConfig, internalMessageCatalog)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.ToolCallRequest)
		}
	}
	return r0
}

// MockToolCallRequestFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockToolCallRequestFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - internalLogger entities.Logger
//   - internalConfig config.GenericConfig
//   - internalMessageCatalog definition.MessageCatalog
func (_e *MockToolCallRequestFactory_Expecter) New(internalLogger interface{}, internalConfig interface{}, internalMessageCatalog interface{}) *MockToolCallRequestFactory_New_Call {
	return &MockToolCallRequestFactory_New_Call{Call: _e.mock.On("New", internalLogger, internalConfig, internalMessageCatalog)}
}

func (_c *MockToolCallRequestFactory_New_Call) Run(run func(internalLogger entities.Logger, internalConfig config.GenericConfig, internalMessageCatalog definition.MessageCatalog)) *MockToolCallRequestFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		var arg1 config.GenericConfig
		if args[1] != nil {
			arg1 = args[1].(config.GenericConfig)
		}
		var arg2 definition.MessageCatalog
		if args[2] != nil {
			arg2 = args[2].(definition.MessageCatalog)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockToolCallRequestFactory_New_Call) Return(toolCallRequest publictypes.ToolCallRequest) *MockToolCallRequestFactory_New_Call {
	_c.Call.Return(toolCallRequest)
	return _c
}

func (_c *MockToolCallRequestFactory_New_Call) RunAndReturn(run func(internalLogger entities.Logger, internalConfig config.GenericConfig, internalMessageCatalog definition.MessageCatalog) publictypes.ToolCallRequest) *MockToolCallRequestFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
