// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/definition"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFeaturesFactory creates a new instance of MockFeaturesFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeaturesFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeaturesFactory {
	mock := &MockFeaturesFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFeaturesFactory is an autogenerated mock type for the FeaturesFactory type
type MockFeaturesFactory struct {
	mock.Mock
}

type MockFeaturesFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeaturesFactory) EXPECT() *MockFeaturesFactory_Expecter {
	return &MockFeaturesFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockFeaturesFactory
func (_mock *MockFeaturesFactory) New(features publictypes.Features) definition.Features {
	ret := _mock.Called(features)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 definition.Features
	if returnFunc, ok := ret.Get(0).(func(publictypes.Features) definition.Features); ok {
		r0 = returnFunc(features)
	} else {
		r0 = ret.Get(0).(definition.Features)
	}
	return r0
}

// MockFeaturesFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockFeaturesFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - features publictypes.Features
func (_e *MockFeaturesFactory_Expecter) New(features interface{}) *MockFeaturesFactory_New_Call {
	return &MockFeaturesFactory_New_Call{Call: _e.mock.On("New", features)}
}

func (_c *MockFeaturesFactory_New_Call) Run(run func(features publictypes.Features)) *MockFeaturesFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 publictypes.Features
		if args[0] != nil {
			arg0 = args[0].(publictypes.Features)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFeaturesFactory_New_Call) Return(features1 definition.Features) *MockFeaturesFactory_New_Call {
	_c.Call.Return(features1)
	return _c
}

func (_c *MockFeaturesFactory_New_Call) RunAndReturn(run func(features publictypes.Features) definition.Features) *MockFeaturesFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
