// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/messages"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParameterWithDescriptionFromMessageCatalog creates a new instance of MockParameterWithDescriptionFromMessageCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParameterWithDescriptionFromMessageCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParameterWithDescriptionFromMessageCatalog {
	mock := &MockParameterWithDescriptionFromMessageCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParameterWithDescriptionFromMessageCatalog is an autogenerated mock type for the ParameterWithDescriptionFromMessageCatalog type
type MockParameterWithDescriptionFromMessageCatalog struct {
	mock.Mock
}

type MockParameterWithDescriptionFromMessageCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParameterWithDescriptionFromMessageCatalog) EXPECT() *MockParameterWithDescriptionFromMessageCatalog_Expecter {
	return &MockParameterWithDescriptionFromMessageCatalog_Expecter{mock: &_m.Mock}
}

// GetActive provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) GetActive() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockParameterWithDescriptionFromMessageCatalog_GetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActive'
type MockParameterWithDescriptionFromMessageCatalog_GetActive_Call struct {
	*mock.Call
}

// GetActive is a helper method to define mock.On call
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) GetActive() *MockParameterWithDescriptionFromMessageCatalog_GetActive_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_GetActive_Call{Call: _e.mock.On("GetActive")}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetActive_Call) Run(run func()) *MockParameterWithDescriptionFromMessageCatalog_GetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetActive_Call) Return(b bool) *MockParameterWithDescriptionFromMessageCatalog_GetActive_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetActive_Call) RunAndReturn(run func() bool) *MockParameterWithDescriptionFromMessageCatalog_GetActive_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultValue provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) GetDefaultValue() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultValue")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockParameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultValue'
type MockParameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call struct {
	*mock.Call
}

// GetDefaultValue is a helper method to define mock.On call
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) GetDefaultValue() *MockParameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call{Call: _e.mock.On("GetDefaultValue")}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call) Run(run func()) *MockParameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call) Return(v any) *MockParameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call) RunAndReturn(run func() any) *MockParameterWithDescriptionFromMessageCatalog_GetDefaultValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetDescription provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) GetDescription() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDescription")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParameterWithDescriptionFromMessageCatalog_GetDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDescription'
type MockParameterWithDescriptionFromMessageCatalog_GetDescription_Call struct {
	*mock.Call
}

// GetDescription is a helper method to define mock.On call
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) GetDescription() *MockParameterWithDescriptionFromMessageCatalog_GetDescription_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_GetDescription_Call{Call: _e.mock.On("GetDescription")}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetDescription_Call) Run(run func()) *MockParameterWithDescriptionFromMessageCatalog_GetDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetDescription_Call) Return(s string) *MockParameterWithDescriptionFromMessageCatalog_GetDescription_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetDescription_Call) RunAndReturn(run func() string) *MockParameterWithDescriptionFromMessageCatalog_GetDescription_Call {
	_c.Call.Return(run)
	return _c
}

// GetDescriptionKey provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) GetDescriptionKey() messages.MessageKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDescriptionKey")
	}

	var r0 messages.MessageKey
	if returnFunc, ok := ret.Get(0).(func() messages.MessageKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messages.MessageKey)
		}
	}
	return r0
}

// MockParameterWithDescriptionFromMessageCatalog_GetDescriptionKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDescriptionKey'
type MockParameterWithDescriptionFromMessageCatalog_GetDescriptionKey_Call struct {
	*mock.Call
}

// GetDescriptionKey is a helper method to define mock.On call
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) GetDescriptionKey() *MockParameterWithDescriptionFromMessageCatalog_GetDescriptionKey_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_GetDescriptionKey_Call{Call: _e.mock.On("GetDescriptionKey")}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetDescriptionKey_Call) Run(run func()) *MockParameterWithDescriptionFromMessageCatalog_GetDescriptionKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetDescriptionKey_Call) Return(messageKey messages.MessageKey) *MockParameterWithDescriptionFromMessageCatalog_GetDescriptionKey_Call {
	_c.Call.Return(messageKey)
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetDescriptionKey_Call) RunAndReturn(run func() messages.MessageKey) *MockParameterWithDescriptionFromMessageCatalog_GetDescriptionKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvVarName provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) GetEnvVarName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEnvVarName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvVarName'
type MockParameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call struct {
	*mock.Call
}

// GetEnvVarName is a helper method to define mock.On call
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) GetEnvVarName() *MockParameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call{Call: _e.mock.On("GetEnvVarName")}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call) Run(run func()) *MockParameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call) Return(s string) *MockParameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call) RunAndReturn(run func() string) *MockParameterWithDescriptionFromMessageCatalog_GetEnvVarName_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlagName provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) GetFlagName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFlagName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParameterWithDescriptionFromMessageCatalog_GetFlagName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlagName'
type MockParameterWithDescriptionFromMessageCatalog_GetFlagName_Call struct {
	*mock.Call
}

// GetFlagName is a helper method to define mock.On call
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) GetFlagName() *MockParameterWithDescriptionFromMessageCatalog_GetFlagName_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_GetFlagName_Call{Call: _e.mock.On("GetFlagName")}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetFlagName_Call) Run(run func()) *MockParameterWithDescriptionFromMessageCatalog_GetFlagName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetFlagName_Call) Return(s string) *MockParameterWithDescriptionFromMessageCatalog_GetFlagName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetFlagName_Call) RunAndReturn(run func() string) *MockParameterWithDescriptionFromMessageCatalog_GetFlagName_Call {
	_c.Call.Return(run)
	return _c
}

// GetHiddenFlag provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) GetHiddenFlag() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHiddenFlag")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockParameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHiddenFlag'
type MockParameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call struct {
	*mock.Call
}

// GetHiddenFlag is a helper method to define mock.On call
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) GetHiddenFlag() *MockParameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call{Call: _e.mock.On("GetHiddenFlag")}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call) Run(run func()) *MockParameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call) Return(b bool) *MockParameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call) RunAndReturn(run func() bool) *MockParameterWithDescriptionFromMessageCatalog_GetHiddenFlag_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParameterWithDescriptionFromMessageCatalog_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockParameterWithDescriptionFromMessageCatalog_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) GetID() *MockParameterWithDescriptionFromMessageCatalog_GetID_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetID_Call) Run(run func()) *MockParameterWithDescriptionFromMessageCatalog_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetID_Call) Return(s string) *MockParameterWithDescriptionFromMessageCatalog_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetID_Call) RunAndReturn(run func() string) *MockParameterWithDescriptionFromMessageCatalog_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPIISafe provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) GetPIISafe() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPIISafe")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockParameterWithDescriptionFromMessageCatalog_GetPIISafe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPIISafe'
type MockParameterWithDescriptionFromMessageCatalog_GetPIISafe_Call struct {
	*mock.Call
}

// GetPIISafe is a helper method to define mock.On call
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) GetPIISafe() *MockParameterWithDescriptionFromMessageCatalog_GetPIISafe_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_GetPIISafe_Call{Call: _e.mock.On("GetPIISafe")}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetPIISafe_Call) Run(run func()) *MockParameterWithDescriptionFromMessageCatalog_GetPIISafe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetPIISafe_Call) Return(b bool) *MockParameterWithDescriptionFromMessageCatalog_GetPIISafe_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetPIISafe_Call) RunAndReturn(run func() bool) *MockParameterWithDescriptionFromMessageCatalog_GetPIISafe_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecordToLog provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) GetRecordToLog() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRecordToLog")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockParameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecordToLog'
type MockParameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call struct {
	*mock.Call
}

// GetRecordToLog is a helper method to define mock.On call
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) GetRecordToLog() *MockParameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call{Call: _e.mock.On("GetRecordToLog")}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call) Run(run func()) *MockParameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call) Return(b bool) *MockParameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call) RunAndReturn(run func() bool) *MockParameterWithDescriptionFromMessageCatalog_GetRecordToLog_Call {
	_c.Call.Return(run)
	return _c
}

// SetActive provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) SetActive(active bool) {
	_mock.Called(active)
	return
}

// MockParameterWithDescriptionFromMessageCatalog_SetActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActive'
type MockParameterWithDescriptionFromMessageCatalog_SetActive_Call struct {
	*mock.Call
}

// SetActive is a helper method to define mock.On call
//   - active bool
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) SetActive(active interface{}) *MockParameterWithDescriptionFromMessageCatalog_SetActive_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_SetActive_Call{Call: _e.mock.On("SetActive", active)}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_SetActive_Call) Run(run func(active bool)) *MockParameterWithDescriptionFromMessageCatalog_SetActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_SetActive_Call) Return() *MockParameterWithDescriptionFromMessageCatalog_SetActive_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_SetActive_Call) RunAndReturn(run func(active bool)) *MockParameterWithDescriptionFromMessageCatalog_SetActive_Call {
	_c.Run(run)
	return _c
}

// SetDescription provides a mock function for the type MockParameterWithDescriptionFromMessageCatalog
func (_mock *MockParameterWithDescriptionFromMessageCatalog) SetDescription(description string) {
	_mock.Called(description)
	return
}

// MockParameterWithDescriptionFromMessageCatalog_SetDescription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDescription'
type MockParameterWithDescriptionFromMessageCatalog_SetDescription_Call struct {
	*mock.Call
}

// SetDescription is a helper method to define mock.On call
//   - description string
func (_e *MockParameterWithDescriptionFromMessageCatalog_Expecter) SetDescription(description interface{}) *MockParameterWithDescriptionFromMessageCatalog_SetDescription_Call {
	return &MockParameterWithDescriptionFromMessageCatalog_SetDescription_Call{Call: _e.mock.On("SetDescription", description)}
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_SetDescription_Call) Run(run func(description string)) *MockParameterWithDescriptionFromMessageCatalog_SetDescription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_SetDescription_Call) Return() *MockParameterWithDescriptionFromMessageCatalog_SetDescription_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockParameterWithDescriptionFromMessageCatalog_SetDescription_Call) RunAndReturn(run func(description string)) *MockParameterWithDescriptionFromMessageCatalog_SetDescription_Call {
	_c.Run(run)
	return _c
}
