// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/watchdog/transport/socket"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSocketFactory creates a new instance of MockSocketFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSocketFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSocketFactory {
	mock := &MockSocketFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSocketFactory is an autogenerated mock type for the SocketFactory type
type MockSocketFactory struct {
	mock.Mock
}

type MockSocketFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSocketFactory) EXPECT() *MockSocketFactory_Expecter {
	return &MockSocketFactory_Expecter{mock: &_m.Mock}
}

// Socket provides a mock function for the type MockSocketFactory
func (_mock *MockSocketFactory) Socket() (socket.Socket, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Socket")
	}

	var r0 socket.Socket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (socket.Socket, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() socket.Socket); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(socket.Socket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSocketFactory_Socket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Socket'
type MockSocketFactory_Socket_Call struct {
	*mock.Call
}

// Socket is a helper method to define mock.On call
func (_e *MockSocketFactory_Expecter) Socket() *MockSocketFactory_Socket_Call {
	return &MockSocketFactory_Socket_Call{Call: _e.mock.On("Socket")}
}

func (_c *MockSocketFactory_Socket_Call) Run(run func()) *MockSocketFactory_Socket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSocketFactory_Socket_Call) Return(socket1 socket.Socket, err error) *MockSocketFactory_Socket_Call {
	_c.Call.Return(socket1, err)
	return _c
}

func (_c *MockSocketFactory_Socket_Call) RunAndReturn(run func() (socket.Socket, error)) *MockSocketFactory_Socket_Call {
	_c.Call.Return(run)
	return _c
}
