// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/definition"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDependenciesProviderFactory creates a new instance of MockDependenciesProviderFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDependenciesProviderFactory[Dependencies any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDependenciesProviderFactory[Dependencies] {
	mock := &MockDependenciesProviderFactory[Dependencies]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDependenciesProviderFactory is an autogenerated mock type for the DependenciesProviderFactory type
type MockDependenciesProviderFactory[Dependencies any] struct {
	mock.Mock
}

type MockDependenciesProviderFactory_Expecter[Dependencies any] struct {
	mock *mock.Mock
}

func (_m *MockDependenciesProviderFactory[Dependencies]) EXPECT() *MockDependenciesProviderFactory_Expecter[Dependencies] {
	return &MockDependenciesProviderFactory_Expecter[Dependencies]{mock: &_m.Mock}
}

// New provides a mock function for the type MockDependenciesProviderFactory
func (_mock *MockDependenciesProviderFactory[Dependencies]) New(provider publictypes.DependenciesProvider[Dependencies]) definition.DependenciesProvider {
	ret := _mock.Called(provider)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 definition.DependenciesProvider
	if returnFunc, ok := ret.Get(0).(func(publictypes.DependenciesProvider[Dependencies]) definition.DependenciesProvider); ok {
		r0 = returnFunc(provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(definition.DependenciesProvider)
		}
	}
	return r0
}

// MockDependenciesProviderFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockDependenciesProviderFactory_New_Call[Dependencies any] struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - provider publictypes.DependenciesProvider[Dependencies]
func (_e *MockDependenciesProviderFactory_Expecter[Dependencies]) New(provider interface{}) *MockDependenciesProviderFactory_New_Call[Dependencies] {
	return &MockDependenciesProviderFactory_New_Call[Dependencies]{Call: _e.mock.On("New", provider)}
}

func (_c *MockDependenciesProviderFactory_New_Call[Dependencies]) Run(run func(provider publictypes.DependenciesProvider[Dependencies])) *MockDependenciesProviderFactory_New_Call[Dependencies] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 publictypes.DependenciesProvider[Dependencies]
		if args[0] != nil {
			arg0 = args[0].(publictypes.DependenciesProvider[Dependencies])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDependenciesProviderFactory_New_Call[Dependencies]) Return(dependenciesProvider definition.DependenciesProvider) *MockDependenciesProviderFactory_New_Call[Dependencies] {
	_c.Call.Return(dependenciesProvider)
	return _c
}

func (_c *MockDependenciesProviderFactory_New_Call[Dependencies]) RunAndReturn(run func(provider publictypes.DependenciesProvider[Dependencies]) definition.DependenciesProvider) *MockDependenciesProviderFactory_New_Call[Dependencies] {
	_c.Call.Return(run)
	return _c
}
