// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParametersFactory creates a new instance of MockParametersFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParametersFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParametersFactory {
	mock := &MockParametersFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParametersFactory is an autogenerated mock type for the ParametersFactory type
type MockParametersFactory struct {
	mock.Mock
}

type MockParametersFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParametersFactory) EXPECT() *MockParametersFactory_Expecter {
	return &MockParametersFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockParametersFactory
func (_mock *MockParametersFactory) New(parameters []publictypes.Parameter) []entities.Parameter {
	ret := _mock.Called(parameters)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 []entities.Parameter
	if returnFunc, ok := ret.Get(0).(func([]publictypes.Parameter) []entities.Parameter); ok {
		r0 = returnFunc(parameters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Parameter)
		}
	}
	return r0
}

// MockParametersFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockParametersFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - parameters []publictypes.Parameter
func (_e *MockParametersFactory_Expecter) New(parameters interface{}) *MockParametersFactory_New_Call {
	return &MockParametersFactory_New_Call{Call: _e.mock.On("New", parameters)}
}

func (_c *MockParametersFactory_New_Call) Run(run func(parameters []publictypes.Parameter)) *MockParametersFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []publictypes.Parameter
		if args[0] != nil {
			arg0 = args[0].([]publictypes.Parameter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParametersFactory_New_Call) Return(parameters1 []entities.Parameter) *MockParametersFactory_New_Call {
	_c.Call.Return(parameters1)
	return _c
}

func (_c *MockParametersFactory_New_Call) RunAndReturn(run func(parameters []publictypes.Parameter) []entities.Parameter) *MockParametersFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
