// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/application/definition"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/toolsprovider"
	mock "github.com/stretchr/testify/mock"
)

// NewMockToolsProviderFactory creates a new instance of MockToolsProviderFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolsProviderFactory[Dependencies any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolsProviderFactory[Dependencies] {
	mock := &MockToolsProviderFactory[Dependencies]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockToolsProviderFactory is an autogenerated mock type for the ToolsProviderFactory type
type MockToolsProviderFactory[Dependencies any] struct {
	mock.Mock
}

type MockToolsProviderFactory_Expecter[Dependencies any] struct {
	mock *mock.Mock
}

func (_m *MockToolsProviderFactory[Dependencies]) EXPECT() *MockToolsProviderFactory_Expecter[Dependencies] {
	return &MockToolsProviderFactory_Expecter[Dependencies]{mock: &_m.Mock}
}

// New provides a mock function for the type MockToolsProviderFactory
func (_mock *MockToolsProviderFactory[Dependencies]) New(provider toolsprovider.ToolsProvider[Dependencies]) definition.ToolsProvider {
	ret := _mock.Called(provider)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 definition.ToolsProvider
	if returnFunc, ok := ret.Get(0).(func(toolsprovider.ToolsProvider[Dependencies]) definition.ToolsProvider); ok {
		r0 = returnFunc(provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(definition.ToolsProvider)
		}
	}
	return r0
}

// MockToolsProviderFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockToolsProviderFactory_New_Call[Dependencies any] struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - provider toolsprovider.ToolsProvider[Dependencies]
func (_e *MockToolsProviderFactory_Expecter[Dependencies]) New(provider interface{}) *MockToolsProviderFactory_New_Call[Dependencies] {
	return &MockToolsProviderFactory_New_Call[Dependencies]{Call: _e.mock.On("New", provider)}
}

func (_c *MockToolsProviderFactory_New_Call[Dependencies]) Run(run func(provider toolsprovider.ToolsProvider[Dependencies])) *MockToolsProviderFactory_New_Call[Dependencies] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 toolsprovider.ToolsProvider[Dependencies]
		if args[0] != nil {
			arg0 = args[0].(toolsprovider.ToolsProvider[Dependencies])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockToolsProviderFactory_New_Call[Dependencies]) Return(toolsProvider definition.ToolsProvider) *MockToolsProviderFactory_New_Call[Dependencies] {
	_c.Call.Return(toolsProvider)
	return _c
}

func (_c *MockToolsProviderFactory_New_Call[Dependencies]) RunAndReturn(run func(provider toolsprovider.ToolsProvider[Dependencies]) definition.ToolsProvider) *MockToolsProviderFactory_New_Call[Dependencies] {
	_c.Call.Return(run)
	return _c
}
