// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.opentelemetry.io/otel/attribute"
)

// NewMockInt64Counter creates a new instance of MockInt64Counter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInt64Counter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInt64Counter {
	mock := &MockInt64Counter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInt64Counter is an autogenerated mock type for the Int64Counter type
type MockInt64Counter struct {
	mock.Mock
}

type MockInt64Counter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInt64Counter) EXPECT() *MockInt64Counter_Expecter {
	return &MockInt64Counter_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockInt64Counter
func (_mock *MockInt64Counter) Add(ctx context.Context, value int64, attrs []attribute.KeyValue) {
	_mock.Called(ctx, value, attrs)
	return
}

// MockInt64Counter_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockInt64Counter_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - value int64
//   - attrs []attribute.KeyValue
func (_e *MockInt64Counter_Expecter) Add(ctx interface{}, value interface{}, attrs interface{}) *MockInt64Counter_Add_Call {
	return &MockInt64Counter_Add_Call{Call: _e.mock.On("Add", ctx, value, attrs)}
}

func (_c *MockInt64Counter_Add_Call) Run(run func(ctx context.Context, value int64, attrs []attribute.KeyValue)) *MockInt64Counter_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 []attribute.KeyValue
		if args[2] != nil {
			arg2 = args[2].([]attribute.KeyValue)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInt64Counter_Add_Call) Return() *MockInt64Counter_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInt64Counter_Add_Call) RunAndReturn(run func(ctx context.Context, value int64, attrs []attribute.KeyValue)) *MockInt64Counter_Add_Call {
	_c.Run(run)
	return _c
}
