// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/config"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfigFactory creates a new instance of MockConfigFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigFactory {
	mock := &MockConfigFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfigFactory is an autogenerated mock type for the ConfigFactory type
type MockConfigFactory struct {
	mock.Mock
}

type MockConfigFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigFactory) EXPECT() *MockConfigFactory_Expecter {
	return &MockConfigFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockConfigFactory
func (_mock *MockConfigFactory) New(internalConfig config.InternalConfig, internalMessageCatalog config.InternalMessageCatalog) publictypes.Config {
	ret := _mock.Called(internalConfig, internalMessageCatalog)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 publictypes.Config
	if returnFunc, ok := ret.Get(0).(func(config.InternalConfig, config.InternalMessageCatalog) publictypes.Config); ok {
		r0 = returnFunc(internalConfig, internalMessageCatalog)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.Config)
		}
	}
	return r0
}

// MockConfigFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockConfigFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - internalConfig config.InternalConfig
//   - internalMessageCatalog config.InternalMessageCatalog
func (_e *MockConfigFactory_Expecter) New(internalConfig interface{}, internalMessageCatalog interface{}) *MockConfigFactory_New_Call {
	return &MockConfigFactory_New_Call{Call: _e.mock.On("New", internalConfig, internalMessageCatalog)}
}

func (_c *MockConfigFactory_New_Call) Run(run func(internalConfig config.InternalConfig, internalMessageCatalog config.InternalMessageCatalog)) *MockConfigFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.InternalConfig
		if args[0] != nil {
			arg0 = args[0].(config.InternalConfig)
		}
		var arg1 config.InternalMessageCatalog
		if args[1] != nil {
			arg1 = args[1].(config.InternalMessageCatalog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfigFactory_New_Call) Return(config1 publictypes.Config) *MockConfigFactory_New_Call {
	_c.Call.Return(config1)
	return _c
}

func (_c *MockConfigFactory_New_Call) RunAndReturn(run func(internalConfig config.InternalConfig, internalMessageCatalog config.InternalMessageCatalog) publictypes.Config) *MockConfigFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
