// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/watchdog"
	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWatchdogFactory creates a new instance of MockWatchdogFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWatchdogFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWatchdogFactory {
	mock := &MockWatchdogFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWatchdogFactory is an autogenerated mock type for the WatchdogFactory type
type MockWatchdogFactory struct {
	mock.Mock
}

type MockWatchdogFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWatchdogFactory) EXPECT() *MockWatchdogFactory_Expecter {
	return &MockWatchdogFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockWatchdogFactory
func (_mock *MockWatchdogFactory) New(logger entities.Logger, internalWatchdog watchdog.InternalWatchdog) publictypes.Watchdog {
	ret := _mock.Called(logger, internalWatchdog)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 publictypes.Watchdog
	if returnFunc, ok := ret.Get(0).(func(entities.Logger, watchdog.InternalWatchdog) publictypes.Watchdog); ok {
		r0 = returnFunc(logger, internalWatchdog)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.Watchdog)
		}
	}
	return r0
}

// MockWatchdogFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockWatchdogFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - logger entities.Logger
//   - internalWatchdog watchdog.InternalWatchdog
func (_e *MockWatchdogFactory_Expecter) New(logger interface{}, internalWatchdog interface{}) *MockWatchdogFactory_New_Call {
	return &MockWatchdogFactory_New_Call{Call: _e.mock.On("New", logger, internalWatchdog)}
}

func (_c *MockWatchdogFactory_New_Call) Run(run func(logger entities.Logger, internalWatchdog watchdog.InternalWatchdog)) *MockWatchdogFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Logger
		if args[0] != nil {
			arg0 = args[0].(entities.Logger)
		}
		var arg1 watchdog.InternalWatchdog
		if args[1] != nil {
			arg1 = args[1].(watchdog.InternalWatchdog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWatchdogFactory_New_Call) Return(watchdog1 publictypes.Watchdog) *MockWatchdogFactory_New_Call {
	_c.Call.Return(watchdog1)
	return _c
}

func (_c *MockWatchdogFactory_New_Call) RunAndReturn(run func(logger entities.Logger, internalWatchdog watchdog.InternalWatchdog) publictypes.Watchdog) *MockWatchdogFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
