#!/usr/bin/env python3
"""Run a small Sysplorer MCP parameter search for project improved PID models."""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
EXTRA_MODEL_FILE_WIN = r"C:\Users\HP\Desktop\Quadrotor\results\tmp\pid_tuning\package.mo"


CANDIDATES = [
    {
        "id": "att_kd_145",
        "pid3_kp": 1.5,
        "pid3_kd": 1.0,
        "pid4_kp": 1.5,
        "pid4_kd": 1.0,
        "pid5_kd": 1.45,
        "pid6_kd": 1.45,
        "pid7_kp": 8.0,
        "pid7_ki": 6.0,
        "pid7_kd": 4.0,
    },
    {
        "id": "att_kd_170",
        "pid3_kp": 1.5,
        "pid3_kd": 1.0,
        "pid4_kp": 1.5,
        "pid4_kd": 1.0,
        "pid5_kd": 1.70,
        "pid6_kd": 1.70,
        "pid7_kp": 8.0,
        "pid7_ki": 6.0,
        "pid7_kd": 4.0,
    },
    {
        "id": "att_kd_190",
        "pid3_kp": 1.5,
        "pid3_kd": 1.0,
        "pid4_kp": 1.5,
        "pid4_kd": 1.0,
        "pid5_kd": 1.90,
        "pid6_kd": 1.90,
        "pid7_kp": 8.0,
        "pid7_ki": 6.0,
        "pid7_kd": 4.0,
    },
    {
        "id": "pos_kd_115_att_170",
        "pid3_kp": 1.5,
        "pid3_kd": 1.15,
        "pid4_kp": 1.5,
        "pid4_kd": 1.15,
        "pid5_kd": 1.70,
        "pid6_kd": 1.70,
        "pid7_kp": 8.0,
        "pid7_ki": 6.0,
        "pid7_kd": 4.0,
    },
    {
        "id": "pos_kp_165_att_170",
        "pid3_kp": 1.65,
        "pid3_kd": 1.0,
        "pid4_kp": 1.65,
        "pid4_kd": 1.0,
        "pid5_kd": 1.70,
        "pid6_kd": 1.70,
        "pid7_kp": 8.0,
        "pid7_ki": 6.0,
        "pid7_kd": 4.0,
    },
    {
        "id": "z_soft_att_170",
        "pid3_kp": 1.5,
        "pid3_kd": 1.0,
        "pid4_kp": 1.5,
        "pid4_kd": 1.0,
        "pid5_kd": 1.70,
        "pid6_kd": 1.70,
        "pid7_kp": 7.5,
        "pid7_ki": 5.5,
        "pid7_kd": 4.2,
    },
]


def model_name(candidate_id: str, example: int) -> str:
    return f"QuadrotorPIDTuning.Example{example}_{candidate_id}"


def class_name(candidate_id: str, example: int) -> str:
    return f"Example{example}_{candidate_id}"


def render_modelica_package(path: Path, examples: list[int], candidates: list[dict[str, float | str]]) -> None:
    lines = [
        "within;",
        "package QuadrotorPIDTuning",
        '  "Temporary PID parameter search models generated by scripts/mworks/tune_improved_pid_mcp.py"',
        "",
        "  extends Modelica.Icons.Package;",
        "  annotation(uses(",
        '    Modelica(version = "4.0.0.TY.1"),',
        "    QuadrotorModel));",
        "",
    ]
    for candidate in candidates:
        cid = str(candidate["id"])
        for example in examples:
            stop_time = 50 if example == 1 else 120
            base = f"QuadrotorModel.Examples.Example{example}"
            cls = class_name(cid, example)
            lines.extend(
                [
                    f"  model {cls}",
                    f'    "Example{example} PID tuning candidate {cid}"',
                    f"    extends {base}(",
                    f"      controller3_2.PID3(KP = {candidate['pid3_kp']}, KI = 0, KD = {candidate['pid3_kd']}),",
                    f"      controller3_2.PID4(KP = {candidate['pid4_kp']}, KI = 0, KD = {candidate['pid4_kd']}),",
                    f"      controller3_2.PID5(KP = 14.142, KI = 0, KD = {candidate['pid5_kd']}),",
                    f"      controller3_2.PID6(KP = 14.142, KI = 0, KD = {candidate['pid6_kd']}),",
                    f"      controller3_2.PID7(KP = {candidate['pid7_kp']}, KI = {candidate['pid7_ki']}, KD = {candidate['pid7_kd']}));",
                    f"    annotation(experiment(Algorithm = Dassl, StartTime = 0, StopTime = {stop_time}, Tolerance = 0.0001, Interval = 0.01));",
                    f"  end {cls};",
                    "",
                ]
            )
    lines.append("end QuadrotorPIDTuning;")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_candidate(example: int, candidate: dict[str, float | str], target_time: str, timeout_s: int) -> dict[str, object]:
    cid = str(candidate["id"])
    stem = f"pid_tuning_example{example}_{cid}"
    result_base = Path("results/tuning/pid_search") / f"example{example}" / cid
    command = [
        sys.executable,
        "scripts/mworks/run_sysplorer_mcp_smoke.py",
        "--extra-model-file",
        EXTRA_MODEL_FILE_WIN,
        "--model-name",
        model_name(cid, example),
        "--target-time",
        target_time,
        "--raw-output",
        str(result_base / "raw" / f"{stem}.csv"),
        "--metrics-json",
        str(result_base / "metrics" / f"{stem}.json"),
        "--metrics-csv",
        str(result_base / "metrics" / f"{stem}.csv"),
        "--log-output",
        str(result_base / "logs" / f"sysplorer_{stem}_20260509.jsonl"),
        "--scene-id",
        f"pid_tuning_example{example}",
        "--controller-id",
        f"improved_pid_{cid}",
        "--evidence-level",
        "real_sysplorer_mcp_pid_tuning",
    ]
    proc = subprocess.run(command, cwd=ROOT, text=True, capture_output=True, timeout=timeout_s)
    metrics_path = ROOT / result_base / "metrics" / f"{stem}.json"
    row: dict[str, object] = {
        "example": example,
        "candidate_id": cid,
        "returncode": proc.returncode,
        "stdout_tail": proc.stdout[-500:],
        "stderr_tail": proc.stderr[-500:],
        **candidate,
    }
    if proc.returncode == 0 and metrics_path.exists():
        metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
        for key in [
            "row_count",
            "duration_s",
            "position_rmse_m",
            "max_position_error_m",
            "steady_state_error_m",
            "max_tilt_rad",
            "control_energy",
            "control_smoothness",
            "total_health_score",
        ]:
            row[key] = metrics.get(key)
    return row


def write_summary(rows: list[dict[str, object]], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames and not key.endswith("_tail"):
                fieldnames.append(key)
    with output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})

    markdown = output.with_suffix(".md")
    sorted_rows = sorted(rows, key=lambda row: (int(row.get("example", 0)), float(row.get("position_rmse_m", 1e9))))
    lines = [
        "# PID Tuning Summary",
        "",
        "| example | candidate | position_rmse_m | steady_state_error_m | max_tilt_rad | control_energy | total_health_score |",
        "|---:|---|---:|---:|---:|---:|---:|",
    ]
    for row in sorted_rows:
        lines.append(
            "| {example} | {candidate_id} | {position_rmse_m:.6f} | {steady_state_error_m:.6f} | {max_tilt_rad:.6f} | {control_energy:.6f} | {total_health_score:.6f} |".format(
                example=row.get("example", ""),
                candidate_id=row.get("candidate_id", ""),
                position_rmse_m=float(row.get("position_rmse_m", float("nan"))),
                steady_state_error_m=float(row.get("steady_state_error_m", float("nan"))),
                max_tilt_rad=float(row.get("max_tilt_rad", float("nan"))),
                control_energy=float(row.get("control_energy", float("nan"))),
                total_health_score=float(row.get("total_health_score", float("nan"))),
            )
        )
    markdown.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--examples", nargs="+", type=int, default=[1], choices=[1, 3])
    parser.add_argument("--target-time", default=None, help="Override target time, e.g. 0,20")
    parser.add_argument("--limit", type=int, default=None, help="Run only the first N candidates.")
    parser.add_argument("--timeout-s", type=int, default=600)
    parser.add_argument("--summary-output", type=Path, default=Path("results/tuning/pid_search/summary/pid_tuning_summary.csv"))
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    candidates = CANDIDATES[: args.limit] if args.limit else CANDIDATES
    package_path = ROOT / "results/tmp/pid_tuning/package.mo"
    render_modelica_package(package_path, args.examples, candidates)
    print(f"Tuning package: {package_path}")

    rows = []
    for example in args.examples:
        target_time = args.target_time or ("0,50" if example == 1 else "0,120")
        for candidate in candidates:
            print(f"Running Example{example} {candidate['id']} target_time={target_time}", flush=True)
            rows.append(run_candidate(example, candidate, target_time, args.timeout_s))
            write_summary(rows, ROOT / args.summary_output)
    print(f"Summary CSV: {args.summary_output}")
    print(f"Summary Markdown: {args.summary_output.with_suffix('.md')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
