// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileLayer creates a new instance of MockFileLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileLayer {
	mock := &MockFileLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileLayer is an autogenerated mock type for the FileLayer type
type MockFileLayer struct {
	mock.Mock
}

type MockFileLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileLayer) EXPECT() *MockFileLayer_Expecter {
	return &MockFileLayer_Expecter{mock: &_m.Mock}
}

// EvalSymlinks provides a mock function for the type MockFileLayer
func (_mock *MockFileLayer) EvalSymlinks(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for EvalSymlinks")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileLayer_EvalSymlinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalSymlinks'
type MockFileLayer_EvalSymlinks_Call struct {
	*mock.Call
}

// EvalSymlinks is a helper method to define mock.On call
//   - path string
func (_e *MockFileLayer_Expecter) EvalSymlinks(path interface{}) *MockFileLayer_EvalSymlinks_Call {
	return &MockFileLayer_EvalSymlinks_Call{Call: _e.mock.On("EvalSymlinks", path)}
}

func (_c *MockFileLayer_EvalSymlinks_Call) Run(run func(path string)) *MockFileLayer_EvalSymlinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileLayer_EvalSymlinks_Call) Return(s string, err error) *MockFileLayer_EvalSymlinks_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockFileLayer_EvalSymlinks_Call) RunAndReturn(run func(path string) (string, error)) *MockFileLayer_EvalSymlinks_Call {
	_c.Call.Return(run)
	return _c
}
