within QuadrotorExperiments.RobustFaultScenarios.RotorLoss;
model Example1Rotor1Loss15L1FaultAllocationSysblockClosedLoop
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor1Loss15L1FaultAllocationSysblockClosedLoop"
  extends MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor1Loss15L1FaultAllocationSysblockClosedLoop;
  annotation(__MWORKS(hide=true));
end Example1Rotor1Loss15L1FaultAllocationSysblockClosedLoop;
