within QuadrotorExperiments.RobustFaultScenarios.RotorLoss;
model Example1Rotor1Loss15WindGustAWFFFaultCompensationSysblockClosedLoop
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor1Loss15WindGustAWFFFaultCompensationSysblockClosedLoop"
  extends MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor1Loss15WindGustAWFFFaultCompensationSysblockClosedLoop;
  annotation(__MWORKS(hide=true));
end Example1Rotor1Loss15WindGustAWFFFaultCompensationSysblockClosedLoop;
