within QuadrotorExperiments.RobustFaultScenarios.RotorLoss;
model Example1Rotor4Loss15WindGustLinearMPCOnlineFaultAllocationSysblockClosedLoop
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor4Loss15WindGustLinearMPCOnlineFaultAllocationSysblockClosedLoop"
  extends MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor4Loss15WindGustLinearMPCOnlineFaultAllocationSysblockClosedLoop;
  annotation(__MWORKS(hide=true));
end Example1Rotor4Loss15WindGustLinearMPCOnlineFaultAllocationSysblockClosedLoop;
