within QuadrotorExperiments.RobustFaultScenarios.RotorLoss;
model Example1Rotor3Loss15WindGustL1MultiFaultIsolationSysblockClosedLoop
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor3Loss15WindGustL1MultiFaultIsolationSysblockClosedLoop"
  extends MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor3Loss15WindGustL1MultiFaultIsolationSysblockClosedLoop;
  annotation(__MWORKS(hide=true));
end Example1Rotor3Loss15WindGustL1MultiFaultIsolationSysblockClosedLoop;
