within QuadrotorExperiments.RobustFaultScenarios.RotorLoss;
model Example1Rotor1Loss15AWFFSysblockClosedLoop
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor1Loss15AWFFSysblockClosedLoop"
  extends MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor1Loss15AWFFSysblockClosedLoop;
  annotation(__MWORKS(hide=true));
end Example1Rotor1Loss15AWFFSysblockClosedLoop;
