within QuadrotorExperiments.RobustFaultScenarios.RotorLoss;
model Example1Rotor1Loss15L1SysblockClosedLoop
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor1Loss15L1SysblockClosedLoop"
  extends MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor1Loss15L1SysblockClosedLoop;
  annotation(__MWORKS(hide=true));
end Example1Rotor1Loss15L1SysblockClosedLoop;
