within QuadrotorExperiments.RobustFaultScenarios.RotorLoss;
model Example1Rotor2Loss15L1MultiFaultIsolationSysblockClosedLoop
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor2Loss15L1MultiFaultIsolationSysblockClosedLoop"
  extends MoSimQuadrotorModel.Robustness.Scenarios.RotorLoss.Example1Rotor2Loss15L1MultiFaultIsolationSysblockClosedLoop;
  annotation(__MWORKS(hide=true));
end Example1Rotor2Loss15L1MultiFaultIsolationSysblockClosedLoop;
