within QuadrotorExperiments.SystemArchitecture;
model Sunray150CompleteSystemMissionFailureSysblock
  "Deprecated compatibility alias; canonical implementation is MoSimQuadrotorModel.System.Architecture.Sunray150CompleteSystemMissionFailureSysblock"
  extends MoSimQuadrotorModel.System.Architecture.Sunray150CompleteSystemMissionFailureSysblock;
  annotation(__MWORKS(hide=true));
end Sunray150CompleteSystemMissionFailureSysblock;
