/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 438bb083c9d2c7b943ee2cb52e16449d)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "BrowserCodemode";
  }
  interface Env {
    AI: Ai;
    BrowserCodemode: DurableObjectNamespace<
      import("./src/server").BrowserCodemode
    >;
  }
}
interface Env extends Cloudflare.Env {}
