// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-core-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABSessionClient creates a new instance of MockMATLABSessionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABSessionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABSessionClient {
	mock := &MockMATLABSessionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABSessionClient is an autogenerated mock type for the MATLABSessionClient type
type MockMATLABSessionClient struct {
	mock.Mock
}

type MockMATLABSessionClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABSessionClient) EXPECT() *MockMATLABSessionClient_Expecter {
	return &MockMATLABSessionClient_Expecter{mock: &_m.Mock}
}

// Eval provides a mock function for the type MockMATLABSessionClient
func (_mock *MockMATLABSessionClient) Eval(ctx context.Context, sessionLogger entities.Logger, request entities.EvalRequest) (entities.EvalResponse, error) {
	ret := _mock.Called(ctx, sessionLogger, request)

	if len(ret) == 0 {
		panic("no return value specified for Eval")
	}

	var r0 entities.EvalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.EvalRequest) (entities.EvalResponse, error)); ok {
		return returnFunc(ctx, sessionLogger, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.EvalRequest) entities.EvalResponse); ok {
		r0 = returnFunc(ctx, sessionLogger, request)
	} else {
		r0 = ret.Get(0).(entities.EvalResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, entities.EvalRequest) error); ok {
		r1 = returnFunc(ctx, sessionLogger, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABSessionClient_Eval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Eval'
type MockMATLABSessionClient_Eval_Call struct {
	*mock.Call
}

// Eval is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - request entities.EvalRequest
func (_e *MockMATLABSessionClient_Expecter) Eval(ctx interface{}, sessionLogger interface{}, request interface{}) *MockMATLABSessionClient_Eval_Call {
	return &MockMATLABSessionClient_Eval_Call{Call: _e.mock.On("Eval", ctx, sessionLogger, request)}
}

func (_c *MockMATLABSessionClient_Eval_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, request entities.EvalRequest)) *MockMATLABSessionClient_Eval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.EvalRequest
		if args[2] != nil {
			arg2 = args[2].(entities.EvalRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMATLABSessionClient_Eval_Call) Return(evalResponse entities.EvalResponse, err error) *MockMATLABSessionClient_Eval_Call {
	_c.Call.Return(evalResponse, err)
	return _c
}

func (_c *MockMATLABSessionClient_Eval_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, request entities.EvalRequest) (entities.EvalResponse, error)) *MockMATLABSessionClient_Eval_Call {
	_c.Call.Return(run)
	return _c
}

// EvalWithCapture provides a mock function for the type MockMATLABSessionClient
func (_mock *MockMATLABSessionClient) EvalWithCapture(ctx context.Context, logger entities.Logger, input entities.EvalRequest) (entities.EvalResponse, error) {
	ret := _mock.Called(ctx, logger, input)

	if len(ret) == 0 {
		panic("no return value specified for EvalWithCapture")
	}

	var r0 entities.EvalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.EvalRequest) (entities.EvalResponse, error)); ok {
		return returnFunc(ctx, logger, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.EvalRequest) entities.EvalResponse); ok {
		r0 = returnFunc(ctx, logger, input)
	} else {
		r0 = ret.Get(0).(entities.EvalResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, entities.EvalRequest) error); ok {
		r1 = returnFunc(ctx, logger, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABSessionClient_EvalWithCapture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalWithCapture'
type MockMATLABSessionClient_EvalWithCapture_Call struct {
	*mock.Call
}

// EvalWithCapture is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
//   - input entities.EvalRequest
func (_e *MockMATLABSessionClient_Expecter) EvalWithCapture(ctx interface{}, logger interface{}, input interface{}) *MockMATLABSessionClient_EvalWithCapture_Call {
	return &MockMATLABSessionClient_EvalWithCapture_Call{Call: _e.mock.On("EvalWithCapture", ctx, logger, input)}
}

func (_c *MockMATLABSessionClient_EvalWithCapture_Call) Run(run func(ctx context.Context, logger entities.Logger, input entities.EvalRequest)) *MockMATLABSessionClient_EvalWithCapture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.EvalRequest
		if args[2] != nil {
			arg2 = args[2].(entities.EvalRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMATLABSessionClient_EvalWithCapture_Call) Return(evalResponse entities.EvalResponse, err error) *MockMATLABSessionClient_EvalWithCapture_Call {
	_c.Call.Return(evalResponse, err)
	return _c
}

func (_c *MockMATLABSessionClient_EvalWithCapture_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger, input entities.EvalRequest) (entities.EvalResponse, error)) *MockMATLABSessionClient_EvalWithCapture_Call {
	_c.Call.Return(run)
	return _c
}

// FEval provides a mock function for the type MockMATLABSessionClient
func (_mock *MockMATLABSessionClient) FEval(ctx context.Context, sessionLogger entities.Logger, request entities.FEvalRequest) (entities.FEvalResponse, error) {
	ret := _mock.Called(ctx, sessionLogger, request)

	if len(ret) == 0 {
		panic("no return value specified for FEval")
	}

	var r0 entities.FEvalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.FEvalRequest) (entities.FEvalResponse, error)); ok {
		return returnFunc(ctx, sessionLogger, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.FEvalRequest) entities.FEvalResponse); ok {
		r0 = returnFunc(ctx, sessionLogger, request)
	} else {
		r0 = ret.Get(0).(entities.FEvalResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, entities.FEvalRequest) error); ok {
		r1 = returnFunc(ctx, sessionLogger, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABSessionClient_FEval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FEval'
type MockMATLABSessionClient_FEval_Call struct {
	*mock.Call
}

// FEval is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - request entities.FEvalRequest
func (_e *MockMATLABSessionClient_Expecter) FEval(ctx interface{}, sessionLogger interface{}, request interface{}) *MockMATLABSessionClient_FEval_Call {
	return &MockMATLABSessionClient_FEval_Call{Call: _e.mock.On("FEval", ctx, sessionLogger, request)}
}

func (_c *MockMATLABSessionClient_FEval_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, request entities.FEvalRequest)) *MockMATLABSessionClient_FEval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.FEvalRequest
		if args[2] != nil {
			arg2 = args[2].(entities.FEvalRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMATLABSessionClient_FEval_Call) Return(fEvalResponse entities.FEvalResponse, err error) *MockMATLABSessionClient_FEval_Call {
	_c.Call.Return(fEvalResponse, err)
	return _c
}

func (_c *MockMATLABSessionClient_FEval_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, request entities.FEvalRequest) (entities.FEvalResponse, error)) *MockMATLABSessionClient_FEval_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockMATLABSessionClient
func (_mock *MockMATLABSessionClient) Ping(ctx context.Context, sessionLogger entities.Logger) entities.PingResponse {
	ret := _mock.Called(ctx, sessionLogger)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 entities.PingResponse
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger) entities.PingResponse); ok {
		r0 = returnFunc(ctx, sessionLogger)
	} else {
		r0 = ret.Get(0).(entities.PingResponse)
	}
	return r0
}

// MockMATLABSessionClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockMATLABSessionClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
func (_e *MockMATLABSessionClient_Expecter) Ping(ctx interface{}, sessionLogger interface{}) *MockMATLABSessionClient_Ping_Call {
	return &MockMATLABSessionClient_Ping_Call{Call: _e.mock.On("Ping", ctx, sessionLogger)}
}

func (_c *MockMATLABSessionClient_Ping_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger)) *MockMATLABSessionClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMATLABSessionClient_Ping_Call) Return(pingResponse entities.PingResponse) *MockMATLABSessionClient_Ping_Call {
	_c.Call.Return(pingResponse)
	return _c
}

func (_c *MockMATLABSessionClient_Ping_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger) entities.PingResponse) *MockMATLABSessionClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}
