// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSocket creates a new instance of MockSocket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSocket(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSocket {
	mock := &MockSocket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSocket is an autogenerated mock type for the Socket type
type MockSocket struct {
	mock.Mock
}

type MockSocket_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSocket) EXPECT() *MockSocket_Expecter {
	return &MockSocket_Expecter{mock: &_m.Mock}
}

// Path provides a mock function for the type MockSocket
func (_mock *MockSocket) Path() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSocket_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockSocket_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *MockSocket_Expecter) Path() *MockSocket_Path_Call {
	return &MockSocket_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *MockSocket_Path_Call) Run(run func()) *MockSocket_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSocket_Path_Call) Return(s string) *MockSocket_Path_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSocket_Path_Call) RunAndReturn(run func() string) *MockSocket_Path_Call {
	_c.Call.Return(run)
	return _c
}
