// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionDetails creates a new instance of MockSessionDetails. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionDetails(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionDetails {
	mock := &MockSessionDetails{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionDetails is an autogenerated mock type for the SessionDetails type
type MockSessionDetails struct {
	mock.Mock
}

type MockSessionDetails_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionDetails) EXPECT() *MockSessionDetails_Expecter {
	return &MockSessionDetails_Expecter{mock: &_m.Mock}
}

// interfacelock provides a mock function for the type MockSessionDetails
func (_mock *MockSessionDetails) interfacelock() {
	_mock.Called()
	return
}

// MockSessionDetails_interfacelock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'interfacelock'
type MockSessionDetails_interfacelock_Call struct {
	*mock.Call
}

// interfacelock is a helper method to define mock.On call
func (_e *MockSessionDetails_Expecter) interfacelock() *MockSessionDetails_interfacelock_Call {
	return &MockSessionDetails_interfacelock_Call{Call: _e.mock.On("interfacelock")}
}

func (_c *MockSessionDetails_interfacelock_Call) Run(run func()) *MockSessionDetails_interfacelock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionDetails_interfacelock_Call) Return() *MockSessionDetails_interfacelock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionDetails_interfacelock_Call) RunAndReturn(run func()) *MockSessionDetails_interfacelock_Call {
	_c.Run(run)
	return _c
}
