// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

import (
	"errors"
)

func newSystemChecker() *systemChecker {
	return &systemChecker{}
}

type systemChecker struct{}

func (sc *systemChecker) getSystemLocale() (string, error) {
	if locale := getFromEnvironment(
		[]string{
			"LC_MESSAGES",
			"LC_ALL",
			"LANG",
		},
	); locale != "" {
		return locale, nil
	}

	return "", errors.New("unable to determine system locale")
}
