// Code generated by cpi-go-message-catalog/v2. DO NOT EDIT.

package messages

import (
	"errors"
	"os/exec"
)

func newSystemChecker() *systemChecker {
	return &systemChecker{
		systemCheck: getAppleLanguage,
	}
}

type systemChecker struct {
	systemCheck func() string
}

func (sc *systemChecker) getSystemLocale() (string, error) {
	if locale := sc.systemCheck(); locale != "" {
		return locale, nil
	}

	if locale := getFromEnvironment(
		[]string{
			"LC_MESSAGES",
			"LANG",
		},
	); locale != "" {
		return locale, nil
	}

	return "", errors.New("unable to determine system locale")
}

func getAppleLanguage() string {
	cmd := exec.Command("defaults", "read", "-g", "AppleLanguages")
	output, err := cmd.Output()
	if err != nil {
		return ""
	}

	return processMacOSDefaultsOutput(string(output))
}
