// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnnotations creates a new instance of MockAnnotations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnnotations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnnotations {
	mock := &MockAnnotations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnnotations is an autogenerated mock type for the Annotations type
type MockAnnotations struct {
	mock.Mock
}

type MockAnnotations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnnotations) EXPECT() *MockAnnotations_Expecter {
	return &MockAnnotations_Expecter{mock: &_m.Mock}
}

// mwAnnotationSeal provides a mock function for the type MockAnnotations
func (_mock *MockAnnotations) mwAnnotationSeal() {
	_mock.Called()
	return
}

// MockAnnotations_mwAnnotationSeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mwAnnotationSeal'
type MockAnnotations_mwAnnotationSeal_Call struct {
	*mock.Call
}

// mwAnnotationSeal is a helper method to define mock.On call
func (_e *MockAnnotations_Expecter) mwAnnotationSeal() *MockAnnotations_mwAnnotationSeal_Call {
	return &MockAnnotations_mwAnnotationSeal_Call{Call: _e.mock.On("mwAnnotationSeal")}
}

func (_c *MockAnnotations_mwAnnotationSeal_Call) Run(run func()) *MockAnnotations_mwAnnotationSeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnnotations_mwAnnotationSeal_Call) Return() *MockAnnotations_mwAnnotationSeal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAnnotations_mwAnnotationSeal_Call) RunAndReturn(run func()) *MockAnnotations_mwAnnotationSeal_Call {
	_c.Run(run)
	return _c
}
