// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-core-server/internal/adaptors/sdk/publictypes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDependenciesProviderResources creates a new instance of MockDependenciesProviderResources. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDependenciesProviderResources(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDependenciesProviderResources {
	mock := &MockDependenciesProviderResources{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDependenciesProviderResources is an autogenerated mock type for the DependenciesProviderResources type
type MockDependenciesProviderResources struct {
	mock.Mock
}

type MockDependenciesProviderResources_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDependenciesProviderResources) EXPECT() *MockDependenciesProviderResources_Expecter {
	return &MockDependenciesProviderResources_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockDependenciesProviderResources
func (_mock *MockDependenciesProviderResources) Config() publictypes.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 publictypes.Config
	if returnFunc, ok := ret.Get(0).(func() publictypes.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.Config)
		}
	}
	return r0
}

// MockDependenciesProviderResources_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockDependenciesProviderResources_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockDependenciesProviderResources_Expecter) Config() *MockDependenciesProviderResources_Config_Call {
	return &MockDependenciesProviderResources_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockDependenciesProviderResources_Config_Call) Run(run func()) *MockDependenciesProviderResources_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDependenciesProviderResources_Config_Call) Return(config publictypes.Config) *MockDependenciesProviderResources_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *MockDependenciesProviderResources_Config_Call) RunAndReturn(run func() publictypes.Config) *MockDependenciesProviderResources_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockDependenciesProviderResources
func (_mock *MockDependenciesProviderResources) Logger() publictypes.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 publictypes.Logger
	if returnFunc, ok := ret.Get(0).(func() publictypes.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.Logger)
		}
	}
	return r0
}

// MockDependenciesProviderResources_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockDependenciesProviderResources_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockDependenciesProviderResources_Expecter) Logger() *MockDependenciesProviderResources_Logger_Call {
	return &MockDependenciesProviderResources_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockDependenciesProviderResources_Logger_Call) Run(run func()) *MockDependenciesProviderResources_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDependenciesProviderResources_Logger_Call) Return(logger publictypes.Logger) *MockDependenciesProviderResources_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockDependenciesProviderResources_Logger_Call) RunAndReturn(run func() publictypes.Logger) *MockDependenciesProviderResources_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Watchdog provides a mock function for the type MockDependenciesProviderResources
func (_mock *MockDependenciesProviderResources) Watchdog() publictypes.Watchdog {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Watchdog")
	}

	var r0 publictypes.Watchdog
	if returnFunc, ok := ret.Get(0).(func() publictypes.Watchdog); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(publictypes.Watchdog)
		}
	}
	return r0
}

// MockDependenciesProviderResources_Watchdog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watchdog'
type MockDependenciesProviderResources_Watchdog_Call struct {
	*mock.Call
}

// Watchdog is a helper method to define mock.On call
func (_e *MockDependenciesProviderResources_Expecter) Watchdog() *MockDependenciesProviderResources_Watchdog_Call {
	return &MockDependenciesProviderResources_Watchdog_Call{Call: _e.mock.On("Watchdog")}
}

func (_c *MockDependenciesProviderResources_Watchdog_Call) Run(run func()) *MockDependenciesProviderResources_Watchdog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDependenciesProviderResources_Watchdog_Call) Return(watchdog publictypes.Watchdog) *MockDependenciesProviderResources_Watchdog_Call {
	_c.Call.Return(watchdog)
	return _c
}

func (_c *MockDependenciesProviderResources_Watchdog_Call) RunAndReturn(run func() publictypes.Watchdog) *MockDependenciesProviderResources_Watchdog_Call {
	_c.Call.Return(run)
	return _c
}
