// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// StartAndWaitForCompletion provides a mock function for the type MockServer
func (_mock *MockServer) StartAndWaitForCompletion(ctx context.Context) int {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartAndWaitForCompletion")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockServer_StartAndWaitForCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartAndWaitForCompletion'
type MockServer_StartAndWaitForCompletion_Call struct {
	*mock.Call
}

// StartAndWaitForCompletion is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServer_Expecter) StartAndWaitForCompletion(ctx interface{}) *MockServer_StartAndWaitForCompletion_Call {
	return &MockServer_StartAndWaitForCompletion_Call{Call: _e.mock.On("StartAndWaitForCompletion", ctx)}
}

func (_c *MockServer_StartAndWaitForCompletion_Call) Run(run func(ctx context.Context)) *MockServer_StartAndWaitForCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServer_StartAndWaitForCompletion_Call) Return(n int) *MockServer_StartAndWaitForCompletion_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockServer_StartAndWaitForCompletion_Call) RunAndReturn(run func(ctx context.Context) int) *MockServer_StartAndWaitForCompletion_Call {
	_c.Call.Return(run)
	return _c
}
