// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTool creates a new instance of MockTool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTool {
	mock := &MockTool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTool is an autogenerated mock type for the Tool type
type MockTool struct {
	mock.Mock
}

type MockTool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTool) EXPECT() *MockTool_Expecter {
	return &MockTool_Expecter{mock: &_m.Mock}
}

// mwToolSeal provides a mock function for the type MockTool
func (_mock *MockTool) mwToolSeal() {
	_mock.Called()
	return
}

// MockTool_mwToolSeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mwToolSeal'
type MockTool_mwToolSeal_Call struct {
	*mock.Call
}

// mwToolSeal is a helper method to define mock.On call
func (_e *MockTool_Expecter) mwToolSeal() *MockTool_mwToolSeal_Call {
	return &MockTool_mwToolSeal_Call{Call: _e.mock.On("mwToolSeal")}
}

func (_c *MockTool_mwToolSeal_Call) Run(run func()) *MockTool_mwToolSeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTool_mwToolSeal_Call) Return() *MockTool_mwToolSeal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTool_mwToolSeal_Call) RunAndReturn(run func()) *MockTool_mwToolSeal_Call {
	_c.Run(run)
	return _c
}
